### ISSUE TITLE
[BUG] dev版更新后节点列表出错DataTables warning: table id=table_1 - Ajax error.

### ISSUE THREAD

**Issue by lowprofileusername** [Anankke/SSPanel-Uim#1001]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [X ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ X] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [X ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP 7.2 MYSQL 5.7.52
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
22C5726
**Bug**
The bug information. 请描述你遇到的 Bug。
管理面板-节点列表
DataTables warning: table id=table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
用户中心，节点列表为空
所有节点正常运行。只是显示不出来
在这之前还报错找不到appprofile.example.php。我把appprofile.example.php改名后可以进面板了。
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
debug 开了发 log

**Comment by lowprofileusername** [comment]
debug开了。没有什么报错
F12 用户中心-节点列表

node:2344 (index)01(index)010"数据库查询""执行时间"1"5 次""51.32794380188 ms"Array(2)
project.min.js:172 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at UIswitch.setDefault (project.min.js:172)
    at node:2400
    at node:2411
setDefault @ project.min.js:172
(anonymous) @ node:2400
(anonymous) @ node:2411
F12 管理中心-节点列表
jquery@3.2.1:4 POST https://qzu.in/admin/node/ajax 500

另外我执行了sql里面的gconfig.sql、telegram_tasks.sql以及user_subscribe_log.sql

**Comment by Anankke** [comment]
自己点开那个 500 看返回都不会吗

**Comment by lowprofileusername** [comment]
`

  | send | @ | jquery@3.2.1:4
-- | -- | -- | --
  | ajax | @ | jquery@3.2.1:4
  | sa | @ | datatables.net@1.10.19:37
  | mb | @ | datatables.net@1.10.19:37
  | P | @ | datatables.net@1.10.19:29
  | T | @ | datatables.net@1.10.19:31
  | ha | @ | datatables.net@1.10.19:48
  | e | @ | datatables.net@1.10.19:93
  | b | @ | datatables.net@1.10.19:73
  | Kb | @ | datatables.net@1.10.19:74
  | (anonymous) | @ | datatables.net@1.10.19:93
  | each | @ | jquery@3.2.1:2
  | each | @ | jquery@3.2.1:2
  | n | @ | datatables.net@1.10.19:83
  | h.fn.DataTable | @ | datatables.net@1.10.19:165
  | (anonymous) | @ | node:473
  | load (async) |   |  
  | (anonymous) | @ | node:472

`
不好意思。这是点开后的结果

**Comment by NimaQu** [comment]
@lowprofileusername ¿

**Comment by lowprofileusername** [comment]
不好意思哈，刚刚没理解你的意思。这个500我后面找到是这个问题
message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'op' in 'order clause' (SQL: select * from `ss_node` order by op desc limit 10 offset 0)"
数据库里面ss_node这个表中没有op这一栏。我找了SQL目录里面的数据库文件都枚看到这一栏是怎么出现的。
谢谢

**Comment by 40huo** [comment]
复现成功，这是ajax那个请求后端把排序字段取错了吧。  @Anankke

**Comment by Indexyz** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/be1ad53b9e218fa1d51f3dfdb61fa1d833fa7e04

**Comment by lowprofileusername** [comment]
还有用户面板的节点列表那在有的浏览器中刷不出节点。就是显示空白。F12出错信息是
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at UIswitch.setDefault (project.min.js:172)
好像是theme/material/js/project.min.js 文件里的172行
			if (window.getComputedStyle(this.nodeToShow).display === 'none' && (window.getComputedStyle(this.nodeToHide).display === 'none')) {
有问题。 
这个问题不知道是不是什么原因。我在有的机器就可以显示节点有的就不行。

**Comment by laurieryayoi** [comment]
@lowprofileusername ctrl f5
