### ISSUE TITLE
[BUG]全局流量重置和套餐流量重置逻辑

### ISSUE THREAD

**Issue by befantasy** [Anankke/SSPanel-Uim#1005]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

master

**Bug**
The bug information. 请描述你遇到的 Bug。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

用的master版，config.php中设置了注册用户于每月1号重置流量1G。
套餐设置30天20G流量，无重置。
这样购买套餐的用户在每个月1号，流量已用流量也会清零，而可用流量被重置到1G。
不知道是我设置问题，还是就是这样的？如果是就是这样的话，那这个逻辑很不合理啊，这样这个全局每月清零的功能形同虚设，会和套餐冲突。买了套餐的用户，已用流量会跟着清零不说，可用流量也会被从20G重置到1G。

我期望的正确逻辑应该是:
未购买套餐的用户，每个月1号已用流量清零，可用流量1G。
而购买了套餐的用户，每个月1号已用流量保持不变，可用流量也保持套餐中限定的流量不变。也就是说，每月流量清零时，排除已购买套餐的用户。
不知道该如何设置？

按照

**Comment by DANVEZ** [comment]
你可以设置每月流量不清零，然后签到获取1G-3G流量

**Comment by befantasy** [comment]
> 你可以设置每月流量不清零，然后签到获取1G-3G流量

谢谢您回复~这个变通方案我也想了，但毕竟给用户增添麻烦。。。

我有点不确定，到底是我设置的问题，还是原本设计时候的逻辑问题。
如果不是设置问题，那在我看来设计逻辑很有问题啊，那个全局流量重置形同虚设，只要卖套餐，就没法打开。

**Comment by Anankke** [comment]
那就不开就行了

**Comment by befantasy** [comment]
我想了一下，其实这个问题很好解决，全局重置的时候，只重置等级为0的用户就可以了。
购买套餐的肯定都是0以上。

**Comment by Anankke** [comment]
可以自行更改重置 job 逻辑

**Comment by befantasy** [comment]
> 可以自行更改重置 job 逻辑

请教Anankke，我是一点也不懂代码。。。研究了半天，感觉是在job.php中的这一段落来进行的“全局流量重置”。不知道怎样修改，可以让这个dailyjob排除已购买套餐的用户？
我只看懂了这个
 if (date('d') == $user->auto_reset_day) { 是当今天日期为用户的auto_reset_day的时候，执行重置。

if (in_array($user->id, $boughted_users)) {
                continue; 
这一句是啥意思啊？是不是应该修改这里，判断如果这个用户是套餐付费用户，则不往下执行？


        $users = User::all();
        foreach ($users as $user) {
            $user->last_day_t = ($user->u + $user->d);
            $user->save();
            if (in_array($user->id, $boughted_users)) {
                continue;
            }
            if (date('d') == $user->auto_reset_day) {
                $user->u = 0;
                $user->d = 0;
                $user->last_day_t = 0;
                $user->transfer_enable = $user->auto_reset_bandwidth * 1024 * 1024 * 1024;
                $user->save();

                $subject = Config::get('appName') . '-您的流量被重置了';
                $to = $user->email;
                $text = '您好，根据管理员的设置，流量已经被重置为' . $user->auto_reset_bandwidth . 'GB';
                try {
                    Mail::send($to, $subject, 'news/warn.tpl', [
                        'user' => $user,
                        'text' => $text
                    ], [
                    ]);
                } catch (Exception $e) {
                    echo $e->getMessage();
                }
            }
        }

        $adminUser = User::where('is_admin', '=', '1')->get();

**Comment by du5** [comment]
class <= 0 continue

**Comment by befantasy** [comment]
> class <= 0 continue

感谢老兄回复，我这个应该写在哪里？

完整的话是不是应该这样？？

    $users = User::all();
    foreach ($users as $user) {
        $user->last_day_t = ($user->u + $user->d);
        $user->save();
        if (in_array($user->id, $boughted_users)) {
            continue;

        }
        if ($user->class <= 0){
           continue;
        }

        if (date('d') == $user->auto_reset_day) {
            $user->u = 0;
            $user->d = 0;
            $user->last_day_t = 0;
            $user->transfer_enable = $user->auto_reset_bandwidth * 1024 * 1024 * 1024;
            $user->save();

**Comment by du5** [comment]
please do yourself

**Comment by befantasy** [comment]
搜索学习了一天PHP。。。
好像当前代码的重置逻辑就是排除了已购买套餐的用户。最后那三行应该就是跳过购买套餐的用户的代码把？？但实际运行的时候好像无效。所以我觉得这还是一个bug。各位专家能不能再帮忙看看？

    $users = User::all();
    foreach ($users as $user) {
        $user->last_day_t = ($user->u + $user->d);
        $user->save();
        if (in_array($user->id, $boughted_users)) {
            continue;
        }

有人提过PR，也被Anankke合并进dev了。
https://github.com/Anankke/SSPanel-Uim/pull/600/commits/2f9cbdc47ea2f6323f4152af4df4a2597fdf6f6c

https://github.com/Anankke/SSPanel-Uim/pull/600/commits/19d2d617bac6fef29871b261a981976b1a097483

https://github.com/Anankke/SSPanel-Uim/pull/601/commits/96fe200f130b5521d0f8f2a5bef1206bda8e50ee
