### ISSUE TITLE
[BUG]v2缺少uuid，clash订阅出错

### ISSUE THREAD

**Issue by aipeach** [Anankke/SSPanel-Uim#1006]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
https://github.com/Anankke/SSPanel-Uim/commit/4ec9c2d69c47277d35947d6f5124edeffa26dd13
**Bug**
The bug information. 请描述你遇到的 Bug。

1、v2缺少uuid
![QQ截图20200406133900](https://user-images.githubusercontent.com/44671411/78526816-c8faa980-780d-11ea-95b2-2f2b1cf53b65.png)

2、clash订阅出错
![QQ截图20200406134113](https://user-images.githubusercontent.com/44671411/78526900-095a2780-780e-11ea-8b56-9136658aded5.png)

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
@du5

**Comment by du5** [comment]
@aipeach 手动 php xcat checkjob 看看报错信息

**Comment by aipeach** [comment]
> @aipeach手动php xcat checkjob看看报错信息

节点掉线检测开始
节点掉线检测结束
异常登录检测开始
异常登录检测结束
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'field list' in /www/wwwroot/test/vendor/illuminate/database/Connection.php:478
Stack trace:
#0 /www/wwwroot/test/vendor/illuminate/database/Connection.php(478): PDO->prepare('update `user` s...')
#1 /www/wwwroot/test/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `user` s...', Array)
#2 /www/wwwroot/test/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update `user` s...', Array, Object(Closure))
#3 /www/wwwroot/test/vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update `user` s...', Array, Object(Closure))
#4 /www/wwwroot/test/vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connection->affectingStatement('update `user` s...', Array)
#5 /www/wwwroot/test/vendor/illuminate/database/Query/Builder.php(2123 in /www/wwwroot/test/vendor/illuminate/database/Connection.php on line 729

**Comment by du5** [comment]
@aipeach 看懂了吗？自己解决吧

**Comment by aipeach** [comment]
> @aipeach看懂了吗？自己解决吧

已解决

**Comment by du5** [comment]
@aipeach 好

**Comment by qsyssr** [comment]
请问这是怎么解决，我要遇到了！

**Comment by shitizen-x** [comment]
增加uuid列后还是为空

**Comment by du5** [comment]
xcat 升级配置文件自动新增 uuid

**Comment by regendsoh** [comment]
可以把user表export后，再import入新格式解决该问题。
