### ISSUE TITLE
[BUG]F12管理面板发现加载很多500b-bench.jpg

### ISSUE THREAD

**Issue by JusufUs** [Anankke/SSPanel-Uim#1010]
是最新版的master分支
之前没发现，后来发现很多这个。
问了其他人也有类似情况，不知道是什么？

如下图
https://i.loli.net/2020/04/11/voV7h3YOC5diaNx.jpg

**Comment by Anankke** [comment]
请自行查看 config 说明

**Comment by JusufUs** [comment]
在套了CDN之后获取用户真实ip?为什么只有后台有这些，F12前台没有发现这些东西

**Comment by Anankke** [comment]
jfgi

**Comment by JusufUs** [comment]
原谅我的无知，我在config里真没找到相关这个情况的设置。
谷歌也找了，管理页面加载很多500b-bench.jpg真的不知道是干嘛的

**Comment by woodyxiong** [comment]
看代码初步看是用来统计用户数据的，在config.php可以将sspanelAnalysis改成false，就不会发送请求了
