### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chunqiu033** [Anankke/SSPanel-Uim#1012]
Writing /root/.cache/composer/repo/https---repo.packagist.org/provider-khanamiryan$qrcode-detector-decoder.json into cache
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #6)
Dependency resolution completed in 2.299 seconds
Reading /root/.cache/composer/repo/https---repo.packagist.org/provider-charlottedunois$yasmin.json from cache
Reading /root/.cache/composer/repo/https---repo.packagist.org/provider-charlottedunois$yasmin.json from cache
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package charlottedunois/yasmin could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
每次安装composer到拉取这个刘报错是咋回事呢

**Comment by Anankke** [comment]
dev 版
