### ISSUE TITLE
站点和订阅地址分离

### ISSUE THREAD

**Issue by hombo125** [Anankke/SSPanel-Uim#1015]
站点和订阅地址分离，站点和订阅网站目录都要有sspanel源码才可以，这样能分离订阅地址，可是打开订阅域名还是站点，觉得不安全。如果订阅网站目录下只放个别的首页，没有别的文件，只用这个站点来订阅，这样如何才能实现订阅功能，我这样做用订阅地址更新订阅时显示（远程服务器错误404示找到）。求大佬指教一下，感谢

**Comment by NimaQu** [comment]
https://www.digitalocean.com/community/tools/nginx

**Comment by aipeach** [comment]
@hombo125 https://github.com/GeekQuerxy/SSPanelSubcribe

**Comment by hombo125** [comment]
谢谢2位大佬，非常感谢，2种方法都可以

**Comment by morying** [comment]
> 谢谢2位大佬，非常感谢，2种方法都可以

哥们，你是怎么做的
