### ISSUE TITLE
自助更换UUID

### ISSUE THREAD

**Issue by IngressPrime** [Anankke/SSPanel-Uim#1023]
- [✓] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
对于v2Ray这类，能加个自助更换UUID吗？

**Comment by Indexyz** [comment]
修改链接密码即为修改 UUID
单独修改 UUID 由于实现的原因无法做到

**Comment by clqs** [comment]
请问，如何修改链接密码，链接您指的是哪个？
