### ISSUE TITLE
[BUG] charlottedunois/yasmin 依赖无法安装，建议更换为别的

### ISSUE THREAD

**Issue by vxray** [Anankke/SSPanel-Uim#1024]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
Debian OS 9.5
PHP 7.3
MYSQL 8.0
SSPanel-UIM 最新commit

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
1a48707eb2140427c815b4c11bc7c803846d2c6b
**Bug**
The bug information. 请描述你遇到的 Bug。
无法部署，LNMP环境下，
执行``php composer.phar install`` 命令，提示
``Your requirements could not be resolved to an installable set of packages.``
package charlottedunois/yasmin 找不到
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
https://blog.anank.ke/w/SSPanel_with_LNMP#menu_index_18 
按照以上步骤正常安装，执行``php composer.phar install`` 命令 时会提示报错
**Expected behavior**
What you expected to happen. 请描述你预期的行为。
期望可以正确运行
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
````shell
Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package charlottedunois/yasmin could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

````
**Addition**
Additional context here. 如有可能，请提供更多相关资料。
将composer.json 中 ``charlottedunois/yasmin``改为``laravel-discord/yasmin``即可正确安装

**Comment by vxray** [comment]
Sorry，关键词检索错误
刚开始没找到那个issue

**Comment by siemenstutorials** [comment]
laravel-discord/yasmin
有效

**Comment by jooyyy** [comment]
更换掉这个库，找到项目根目录下的 composer.json 文件，找到 charlottedunois/yasmin 改成 laravel-discord/yasmin 即可。

**Comment by Anankke** [comment]
为什么不用 dev 呢？ master 早已停止支持。
