### ISSUE TITLE
请问老版的 单端口偏移 怎么对多个单端口偏移？

### ISSUE THREAD

**Issue by shaoyingrui** [Anankke/SSPanel-Uim#1025]
https://github.com/Anankke/SSPanel-Uim/compare/%E5%89%8D%E7%AB%AF%E7%AB%AF%E5%8F%A3%E5%81%8F%E7%A7%BB

这个似乎只能在 1个节点 1个承载端口情况下。
如果有2个端口例如 有433 和80.
#描述设置后，只能对一个偏移正确。
另外一个错误。。我看到新版貌似可以设置。
老版 怎么实现？

**Comment by shaoyingrui** [comment]
怎么关闭了？55555555555

**Comment by narakuzi** [comment]
@shaoyingrui 300

**Comment by AidenOfficial** [comment]
@narakuzi 更新。

**Comment by yuntuvu** [comment]
@shaoyingrui 不会是饺子的端口偏移吧

**Comment by shaoyingrui** [comment]
> @shaoyingrui 不会是饺子的端口偏移吧
前端偏移分支 #+- 偏移量  只对一个端口有效。。。
没升级新版。。。所以。。。新版可偏移多个的方法。。没法用。
