### ISSUE TITLE
[BUG]Unable to load class: \App\Command\createAdmin

### ISSUE THREAD

**Issue by git02hub** [Anankke/SSPanel-Uim#1028]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
CentOS 7.6 x64
Mysql 5.5.60
PHP 7.1.18

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**

根据[WIKI](https://wiki.sspanel.host/?__cf_chl_captcha_tk__=c0c16e3f0ac73de68af93a36707f2a501b6a1c5e-1588171475-0-AYB4r_OKqOqYgchDVvufk1AvP76wM3ff74vyV5QJdSiVReIwnGb0P5ap7Jwy2OgUIr6fYZa6OhgCc6nr5suZfaVTUJel0SKKd8-609QilDMGjqwLKo3HqG3G0fS4IocK_Z0dHwO9qYE4yAYVRNzdUpouSLlEP8IN6yOxtl9WN4oho4CbKrhs6J4wDNphSHFx4RPfYaJ9AewYH7rceM1eG8U_c-Y1dZqot3mmyexYyRfx1w9Q1_bs1z74uR7BGlptvR0bIdsKVRR_XqsI6aE-hQPoG_GvWUaedRrNE8ilcBnhJJHnBVsal7ty8XPX1QO5dOIhUCpxv252qJ94KUMtUv86iApDkX3iqu6FtpsKG7uAgR_zpUXzmuZOz1HKQHtexjaWjmUfigWbSi83nJfGIH3fXake7sklAU4CFs9Td1QdoJ4Ro99Ws9asfwIdPIMbAaxnIWTecWH5Yu0ChL6jNooG6ez3em9Q2PYBmbM32sd4G6ySqn0BUS8KCpLbY2HqWXWnYGV2v4rrKMziXhhe5SFss016DexiU1FSWXjwGzEg#/install-using-ois?id=部署-sspanel-uim)的教程进行部署，当执行php xcat createAdmin时，报错：
Unable to load class: \App\Command\createAdmin

且以下指令的执行也有类似的错误
$ php xcat syncusers            # 同步用户
$ php xcat initQQWry            # 下载IP解析库
$ php xcat resetTraffic         # 重置流量
$ php xcat initdownload         # 下载 ssr 程式

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
请告知如何处理这个这个问题，谢谢。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by GeekQuerxy** [comment]
#1026

**Comment by ccgakki** [comment]
大佬这个问题解决了吗
