### ISSUE TITLE
[BUG] Unable to load class: \App\Command\createAdmin

### ISSUE THREAD

**Issue by quanyingjie** [Anankke/SSPanel-Uim#1032]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
ubuntu18.04
php7.2
mysql5.6

**Commit**
使用的dev的代码

**Bug**
```
# php xcat createAdmin
Unable to load class: \App\Command\createAdmin
```

**Reproduce**
php xcat createAdmin执行报错，没法创建管理员，那个app那个目录我看文件夹都不见了，不知道是不是这个原因

**Comment by madmmmax** [comment]
同样的问题，搞了一天解决不了，dev分支. master没这个问题,但是master又不支持v2

**Comment by ainuoyan** [comment]
> 同样的问题，搞了一天解决不了，dev分支
> php xcat都报这个异常，但是文件和目录是在的，要是搞得懂PHP类的加载机制估计能解决
> master没这个问题,但是master都是一年前的代码了，不支持v2，不支持trojan

https://github.com/Anankke/SSPanel-Uim/pull/1026

**Comment by madmmmax** [comment]
感谢大佬回复，我该好好学学如何正确食用github了

**Comment by madmmmax** [comment]
> > 同样的问题，搞了一天解决不了，dev分支
> > php xcat都报这个异常，但是文件和目录是在的，要是搞得懂PHP类的加载机制估计能解决
> > master没这个问题,但是master都是一年前的代码了，不支持v2，不支持trojan
> 
> #1026

感谢大佬回复，我该好好学学如何正确食用github了

**Comment by MAOGE2018** [comment]
php xcat initdownload 这个也无法使用了

**Comment by dolkra** [comment]
同此error，希望作者能尽快修复
