### ISSUE TITLE
[BUG]管理员后台创建用户时数据库中没有其uuid。

### ISSUE THREAD

**Issue by ccgakki** [Anankke/SSPanel-Uim#1033]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [ ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [ ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
c7, PHP7.3，mysql5.6，使用dev分支

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
The bug information. 管理员后台创建用户，数据库中用户没有uuid，但管理员有uuid，其他用户面板上也有uuid，可能没有同步？上一dev分支可以。

**Reproduce**
Steps to reproduce the bug.

**Expected behavior**
如何解决这一问题。
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by ccgakki** [comment]
只有后台没有节点 数据库里才有uuid

**Comment by ccgakki** [comment]
当有节点时 无法在数据库写入uuid

**Comment by chauyuen** [comment]
php xcat Job CheckJob

**Comment by chauyuen** [comment]
运行上述命令看看行不行，行的话设置计划任务，每分钟执行一次。

**Comment by ccgakki** [comment]
执行后会报这样错误，看不太懂是哪里的问题。。。Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'online' in 'field list' in /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php:478
Stack trace:
#0 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(478): PDO->prepare('update `ss_node...')
#1 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `ss_node...', Array)
#2 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update `ss_node...', Array, Object(Closure))
#3 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update `ss_node...', Array, Object(Closure))
#4 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connecti in /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php on line 729

**Comment by ccgakki** [comment]
> 运行上述命令看看行不行，行的话设置计划任务，每分钟执行一次。

执行后会报这样错误，看不太懂是哪里的问题。。。Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'online' in 'field list' in /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php:478
Stack trace:
#0 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(478): PDO->prepare('update ss_node...') #1 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update ss_node...', Array)
#2 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update ss_node...', Array, Object(Closure)) #3 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update ss_node...', Array, Object(Closure))
#4 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connecti in /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php on line 729

**Comment by yeming-jump** [comment]
> > 运行上述命令看看行不行，行的话设置计划任务，每分钟执行一次。
> 
> 执行后会报这样错误，看不太懂是哪里的问题。。。Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'online' in 'field list' in /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php:478
> Stack trace:
> #0 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(478): PDO->prepare('update ss_node...') #1 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database{closure}(Object(Illuminate\Database\MySqlConnection), 'update ss_node...', Array)
> #2 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update ss_node...', Array, Object(Closure)) #3 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update ss_node...', Array, Object(Closure))
> #4 /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connecti in /www/wwwroot/web.xyz/vendor/illuminate/database/Connection.php on line 729

遇到了相同的问题...

**Comment by du5** [comment]
@yeming-jump bash 
mysqld --initialize
