### ISSUE TITLE
[Feature Request]请求添加国外支付接口的对接

### ISSUE THREAD

**Issue by MasterOfStar** [Anankke/SSPanel-Uim#1049]
请求添加如adyen 等国外的 支持支付宝/微信的支付接口
可以参考梨园的这篇文章https://liyuans.com/2018/06/global-payment-solutions.html
主要还是增加匿名性

**Comment by SukkaW** [comment]
@MasterOfStar PR is Welcome

**Comment by clatteringmarion** [comment]
这个不是Mailo有么？
https://malio.fxxkmy.life/

**Comment by maker2002** [comment]
> 这个不是Mailo有么？
> https://malio.fxxkmy.life/

你说的Mailo主题（https://github.com/Cadwalader307/Malio-Theme-for-SSPANEL/）支持BitPayX吗？
