### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bannedbook** [Anankke/SSPanel-Uim#1051]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [ x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [ x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
debian 10, php 7.3 fpm,nginx ,mysql  Ver 15.1 Distrib 10.3.22-MariaDB
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
最新版   61b9fe32..58c65e95  dev        -> origin/dev
**Bug**
The bug information. 请描述你遇到的 Bug。
后端v2ray-poseidon无法获得uuid, 报错
[Error] V2ray-Poseidon: panel#do > sync user > sync users to v2ray > rpc error: code = Unknown desc = v2ray.com/core/app/proxyman/command: failed to parse user > v2ray.com/core/proxy/vmess: failed to parse ID > invalid UUID:
查询面板数据库:
select uuid from user;
+------+
| uuid |
+------+
| NULL |
| NULL |
+------+
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
添加一个v2ray 节点,然后配置 V2ray-Poseidon 

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
 V2ray-Poseidon 能够正常 同步节点,获取到uuid 

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
Banned.

**Comment by bannedbook** [comment]
老大, 这是什么操作啊,怎么秒close

**Comment by narakuzi** [comment]
@bannedbook ，，，

**Comment by bannedbook** [comment]
我被 Banned 了吗, 什么原因呢

**Comment by regendsoh** [comment]
@bannedbook 麻烦找波塞冬 不是sspanel
建议大脑升级

**Comment by sigle0724** [comment]
@bannedbook 请自行排除问题 这不是任何后端的售后点
