### ISSUE TITLE
希望用mailgun邮箱时增加发信人名称

### ISSUE THREAD

**Issue by hombo125** [Anankke/SSPanel-Uim#1053]
$_ENV['mailgun_key']     = 
$_ENV['mailgun_domain']  = 
$_ENV['mailgun_sender']  = 
用mailgun邮箱时发信人默认是邮箱地址，希望能和smtp  sendgrid一样，增加发信人名称

**Comment by clatteringmarion** [comment]
Mailgun API好麻烦... 想加Sendgrid类似还得改Swift...
API在这里， 你可以试试改改： https://github.com/mailgun/mailgun-php/blob/master/doc/index.md

**Comment by raymao9** [comment]
不会改就用 SMTP 啊
