### ISSUE TITLE
我充值后没有到账怎么回事

### ISSUE THREAD

**Issue by 251013801** [Anankke/SSPanel-Uim#1055]
用户名209713683@qq.com

**Comment by aipeach** [comment]
@251013801 网站是什么

**Comment by Anankke** [comment]
gwps

**Comment by 251013801** [comment]
https://pud.kaolay.com/assets/auth/login.js




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cola"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 上午9:18
收件人: "Anankke/SSPanel-Uim"<SSPanel-Uim@noreply.github.com&gt;; 
抄送: "一_"<209713683@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Anankke/SSPanel-Uim] 我充值后没有到账怎么回事 (#1055)





 
@251013801 网站是什么

**Comment by 251013801** [comment]
布丁网络加速 https://pud.kaolay.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cola"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 上午9:18
收件人: "Anankke/SSPanel-Uim"<SSPanel-Uim@noreply.github.com&gt;; 
抄送: "一_"<209713683@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Anankke/SSPanel-Uim] 我充值后没有到账怎么回事 (#1055)





 
@251013801 网站是什么

**Comment by Anankke** [comment]
麻烦天天发广告搞病毒营销的傻逼布丁机场主管好你们的用户，招了壬不管小心被一瞬橄榄，，，
