### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amColinzzz** [Anankke/SSPanel-Uim#1056]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

操作系统:CentOS7
PHP版本:7.3
MySQL版本:5.7

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
58c65e95e4cc17c15197d013f5a3cb93cc877379

**Bug**
The bug information. 请描述你遇到的 Bug。
添加商品的时候,商品名称中有中文,就会报错,无法保存。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
添加商品，商品名中有中文即可复现

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
能够正常添加含有中文名的商品

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。
![2020-05-26_084204](https://user-images.githubusercontent.com/43057595/82851477-90846b80-9f32-11ea-8793-08a623bac49d.jpg)
![2020-05-26_084331](https://user-images.githubusercontent.com/43057595/82851481-937f5c00-9f32-11ea-8b1b-0509de22694c.jpg)
![2020-05-26_084252](https://user-images.githubusercontent.com/43057595/82851484-967a4c80-9f32-11ea-871e-3992d97682ca.jpg)
![2020-05-26_084025](https://user-images.githubusercontent.com/43057595/82851487-97ab7980-9f32-11ea-9d9a-3a53ed0b069c.jpg)
![2020-05-26_084309](https://user-images.githubusercontent.com/43057595/82851489-98441000-9f32-11ea-95ee-ba7c5b0c0dad.jpg)

**Comment by Anankke** [comment]
开一遍又一遍既不看说明又不搜 issue，，，log 也没有标题也不写小白开锤子机场呢赶紧用一键脚本上咸鱼卖合租去吧 banned，，，

**Comment by Anankke** [comment]
这就是刀砍壬🐎i了i了

**Comment by amColinzzz** [comment]
> 这就是刀砍壬🐎i了i了

本来很尊重你们这些有开源精神的作者，看到你这个态度。我想吐，看在用你的项目的份上，就不多说了。老子自己封装了一整套docker镜像实现一键部署，比你现在提供的docker好用的多。对，我们都是小白，你最厉害。

**Comment by Anankke** [comment]
本来对待你们这些小白很有耐心，看到你这个态度。我想吐，看在你刀砍升级壬的份上，就不多说了。老子当小白的时候还会问为什么 wget: command not found，比你现在问得问题高到不知道哪里去了。对，我们都有加不了中文的问题，你提出来真的是好棒棒呢要不要给你发个小红花。

**Comment by amColinzzz** [comment]
> 本来对待你们这些小白很有耐心，看到你这个态度。我想吐，看在你刀砍升级壬的份上，就不多说了。老子当小白的时候还会问为什么 wget: command not found，比你现在问得问题高到不知道哪里去了。对，我们都有加不了中文的问题，你提出来真的是好棒棒呢要不要给你发个小红花。

你大早上就一脸爹死娘改嫁的态度，你对待小白哪里热心了请问？昨天的issue，东西不全，所以我补充的资料，又发一遍，你怎么知道我没搜索历史issue？你怎么知道我没有看文档？你自己搜搜关键字试试能不能搜到？你不回复就不回复，一脸怼天怼地怼空气的样子。瞧你那副嘴脸，你把本来应该予以你的尊重摔在地上狠狠摩擦。

**Comment by amColinzzz** [comment]
你说没有Log，那是因为PHP FPM官方的docker 镜像就没有开启Log,我正在打开Log,还没来得及补充，你就直接关闭issue，你感觉缺少内容，你可以直接说需要补充什么材料你才能判断哪里的问题，或者给出相关的issue让我们参考，或者给出方向性的意见，你除了直接关issue就是关issue，你要是感觉没给你钱就不配提issue，就直说啊

**Comment by Anankke** [comment]
昨天 200 今天 500 但凡搜索个 issue 就知道是个什么问题也不至于牛逼成这样对不起我可不需要宁这种升级壬的尊重人类和刀砍壬是无法互相理解的嘻嘻

**Comment by Anankke** [comment]
建议亲亲查看正常 issue 的流程呢亲亲不是宁错了是全世界错了吖宁说对不对呢嘻嘻

**Comment by amColinzzz** [comment]
一大老爷们上着二次元女的头像，跟你说个屌。。。变态。项目是你的，不不屑一顾的issue就直接关闭？你懒得帮解决不代表其他人都不帮解决，你不回复我可以理解，你直接每次都是秒关issue，也不给别人帮忙解决的机会真可恶。

**Comment by Anankke** [comment]
![IMG_20200525_220448_728](https://user-images.githubusercontent.com/40639066/82853467-d9f19e00-9ed3-11ea-8925-51091de7bade.jpg)
![IMG_20200525_220507_211](https://user-images.githubusercontent.com/40639066/82853473-dcec8e80-9ed3-11ea-94db-01f52eedcdba.jpg)
这就是喷神🐎i了i了

**Comment by Anankke** [comment]
> 一大老爷们上着二次元女的头像，跟你说个屌。。。变态。项目是你的，不不屑一顾的issue就直接关闭？你懒得帮解决不代表其他人都不帮解决，你不回复我可以理解，你直接每次都是秒关issue，也不给别人帮忙解决的机会真可恶。

xs，建议宁详细了解一下我是谁然后别删 issue
脑瘫是不配得到任何帮助的qqxxx

**Comment by amColinzzz** [comment]
> > 一大老爷们上着二次元女的头像，跟你说个屌。。。变态。项目是你的，不不屑一顾的issue就直接关闭？你懒得帮解决不代表其他人都不帮解决，你不回复我可以理解，你直接每次都是秒关issue，也不给别人帮忙解决的机会真可恶。
> 
> xs，建议宁详细了解一下我是谁然后别删 issue
> 脑瘫是不配得到任何帮助的qqxxx

你是谁？呵，除了破娃我谁都不服

**Comment by Anankke** [comment]
pro，太 pro 了

**Comment by amColinzzz** [comment]
> ![IMG_20200525_220448_728](https://user-images.githubusercontent.com/40639066/82853467-d9f19e00-9ed3-11ea-8925-51091de7bade.jpg)
> ![IMG_20200525_220507_211](https://user-images.githubusercontent.com/40639066/82853473-dcec8e80-9ed3-11ea-94db-01f52eedcdba.jpg)
> 这就是喷神🐎i了i了

你好意思发截图？你怎么不发最后人家作者怎么给出的建议？就算在issue下亲切问候，人家作者还是正常回复的问题，反观你呢？不仅不帮解决问题，上来就怼，上来就挖苦嘲讽，屌丝

**Comment by amColinzzz** [comment]
你怎么知道我拿来开机场?你见过哪个机场全是国内节点?是不是觉得别人拿你开源的项目去赚钱你就心理不平衡?拿你的项目来研究学习，个人使用，在你眼里就是拿去赚钱了？没分给你，然后都是脑残，不配得到你的关爱？

**Comment by NimaQu** [comment]
瓜子矿泉水小板凳，这年头硬度这么高的不多了

**Comment by DaylightMonet** [comment]
好戏开锣啦，NMQ分点瓜子给我

**Comment by NimaQu** [comment]
1B 币 100 金瓜子

**Comment by WatanabeQwQ** [comment]
前排出售瓜子.可乐,洗衣机

**Comment by Anankke** [comment]
哦，所以宁亲切问候别人要反观我？对不起我可没这好脾气。我要是少你那点烂钱用得着搁着给恁维护开源项目受气？脑瘫果然是脑瘫，自己逻辑都理不利索lmao

**Comment by amColinzzz** [comment]
> 哦，所以宁亲切问候别人要反观我？对不起我可没这好脾气。我要是少你那点烂钱用得着搁着给恁维护开源项目受气？脑瘫果然是脑瘫，自己逻辑都理不利索lmao

请你不要误导观众，我亲切问候的不是作者，是不帮忙切上来就怼人的。人家作者不管，有问题回复问题是了。像你？就会秒关issue。关了以后还得出来嘲讽挖苦别人都是小白，都是傻逼。

**Comment by clatteringmarion** [comment]
坐看吃瓜

**Comment by AidenOfficial** [comment]
吃瓜

**Comment by leominor46** [comment]
m

**Comment by schwarzgelben** [comment]
啧

**Comment by idwangdana** [comment]
> 你怎么知道我拿来开机场?你见过哪个机场全是国内节点?是不是觉得别人拿你开源的项目去赚钱你就心理不平衡?拿你的项目来研究学习，个人使用，在你眼里就是拿去赚钱了？没分给你，然后都是脑残，不配得到你的关爱？

不要当了婊子 在这立牌坊，我代表TGCN 6682位机场主来询问你父母的近况，对线请来TGCN 官方TG群

**Comment by AmazingDM** [comment]
瓜

**Comment by dongfangmu** [comment]
这里聊没意思。进群吧。小伙子

**Comment by amColinzzz** [comment]
![2020-05-26_102853](https://user-images.githubusercontent.com/43057595/82854736-ec9fbd80-9f3b-11ea-8e2a-579d9eebebc8.jpg)
惹不起惹不起，大家快散了吧，我这把消息没回复完，服务器就被攻击了。

**Comment by AidenOfficial** [comment]
@amColinzzz 哈哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by idwangdana** [comment]
> ![2020-05-26_102853](https://user-images.githubusercontent.com/43057595/82854736-ec9fbd80-9f3b-11ea-8e2a-579d9eebebc8.jpg)
> 惹不起惹不起，大家快散了吧，我这把消息没回复完，服务器就被攻击了。

恁散恁🐎呢？

**Comment by dongfangmu** [comment]
做人别太狂

**Comment by AidenOfficial** [comment]
> ![2020-05-26_102853](https://user-images.githubusercontent.com/43057595/82854765-017c5100-9f3c-11ea-86c1-6eaf9b10307e.jpg)
> 
> 惹不起惹不起，大家快散了吧，我这把消息没回复完，服务器就被攻击了。

你不是搬瓦工么，咋变成 Kiwi 了

**Comment by amColinzzz** [comment]
散了吧，我只说一点，大家以后还是轻易不要来提issue了，一言不合就被这个项目的团队攻击了。
惹不起惹不起，这已经不是一个可以公平开放讨论的平台了。

**Comment by Mefixisnek** [comment]
瞬间车软

> ![2020-05-26_102853](https://user-images.githubusercontent.com/43057595/82854765-017c5100-9f3c-11ea-86c1-6eaf9b10307e.jpg)
> 
> 惹不起惹不起，大家快散了吧，我这把消息没回复完，服务器就被攻击了。

瞬间车软

**Comment by AidenOfficial** [comment]
@amColinzzz 不要停下来啊！作者是可爱的女孩子你说别人大老爷们

**Comment by amColinzzz** [comment]
> 瞬间车软
> 
> > ![2020-05-26_102853](https://user-images.githubusercontent.com/43057595/82854765-017c5100-9f3c-11ea-86c1-6eaf9b10307e.jpg)
> > 惹不起惹不起，大家快散了吧，我这把消息没回复完，服务器就被攻击了。
> 
> 瞬间车软

的确是软了。惹不起。。。讨论问题直接开启人身攻击，能不软吗

**Comment by SNSLogty** [comment]
公平开放讨论=给您🐎这个脑瘫无时无刻回复弱智问题，真当这里是售后呗

**Comment by AidenOfficial** [comment]
@amColinzzz 谁先攻击谁

**Comment by lilmonix33** [comment]
@AidenOfficial 別殺了別殺了 關愛弱智兒童！！！

**Comment by AidenOfficial** [comment]
@lilmonix33 我没有！你有证据吗？！

**Comment by idwangdana** [comment]
> 散了吧，我只说一点，大家以后还是轻易不要来提issue了，一言不合就被这个项目的团队攻击了。
> 惹不起惹不起，这已经不是一个可以公平开放讨论的平台了。

看看你的傻逼逻辑，提issue 是你一个？只有你一个人被打了？你在这骂东骂西 不是自找的？在以后的日子里，你会遭遇DDOS攻击以及支付网关在内的一切举报

**Comment by NimaQu** [comment]
公平开放讨论=上来就送🐎¿

**Comment by Anankke** [comment]
是这样的韩登辉先生，我们也从来不是什么带善壬，建议您以后还是谨言慎行，毕竟黄河科技大学也怪丢人的恁觉得呢
![1590460423333](https://user-images.githubusercontent.com/40639066/82855019-18895780-9ed8-11ea-92df-c95da74c118a.jpg)

**Comment by idwangdana** [comment]
> 是这样的韩登辉先生，我们也从来不是什么带善壬，建议您以后还是谨言慎行，毕竟黄河科技大学也怪丢人的恁觉得呢
> ![1590460423333](https://user-images.githubusercontent.com/40639066/82855019-18895780-9ed8-11ea-92df-c95da74c118a.jpg)

操操操操操

**Comment by AidenOfficial** [comment]
@Anankke 啊这

**Comment by NimaQu** [comment]
磨皮拉满了这是

**Comment by taizi-tp** [comment]
@idwangdana 呜呜，好帅啊（指ps过后），我坐地排卵力

**Comment by DaylightMonet** [comment]
![image](https://user-images.githubusercontent.com/45892976/82855098-f7bd0400-9ecf-11ea-9ba7-38f88d0eae22.png)
![image](https://user-images.githubusercontent.com/45892976/82855113-073c4d00-9ed0-11ea-9f3e-e0d57cd46eaa.png)
论公平与开放讨论。

**Comment by lilmonix33** [comment]
@DaylightMonet 別殺了別殺了！！！

**Comment by dongfangmu** [comment]
小哥哥我可以给你剁屌吗？

**Comment by idwangdana** [comment]
这就收线了？不行啊弟弟

**Comment by lilmonix33** [comment]
@dongfangmu 有一說一 這清純的感覺 剁掉可以穿下女裝

**Comment by MancyMiao** [comment]
哇呀呀 ，一瞬出道 可

**Comment by dongfangmu** [comment]
> @dongfangmu 有一說一 這清純的感覺 剁掉可以穿下女裝

那肯定没毛病。

**Comment by Anankke** [comment]
![Screenshot_20200525-224118__01](https://user-images.githubusercontent.com/40639066/82855321-ff34db00-9ed8-11ea-8bc4-05a315fb5c90.jpg)
早就说过了，恁不信邪就没办法力，，，
互动热线 13223038276，，，请

**Comment by amColinzzz** [comment]
删了吧，我不想这件事闹大，本来指向得到一点指点，你把我照片，信息都放在上面，影响我正常工作学习了。你怎么嘲讽我都可以，但是断人生路的事，还是别搞了，好不？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Anankke"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 上午10:44
收件人: "Anankke/SSPanel-Uim"<SSPanel-Uim@noreply.github.com&gt;; 
抄送: "Colin"<9487481@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Anankke/SSPanel-Uim] [BUG] (#1056)





 

 早就说过了，恁不信邪就没办法力，，，
 互动热线 13223038276，，，请

**Comment by DaylightMonet** [comment]
![image](https://user-images.githubusercontent.com/45892976/82855592-55058500-9ed1-11ea-9ba5-64b266cf9cfd.png)
“我想得到一点指点”

**Comment by AmazingDM** [comment]
妙啊

**Comment by starwish-01** [comment]
后排插眼吃瓜

**Comment by Anankke** [comment]
这个故事告诉我们恶人还需恶人磨，等国安找到你再删w

**Comment by hulisang** [comment]
所以说没事提什么issue，有事到50群里随随便便哪个大佬50就给你解决了实在不行100，再实在不行200

**Comment by Anankke** [comment]
![Screenshot_20200525-225922__01](https://user-images.githubusercontent.com/40639066/82856249-7ec3a980-9edb-11ea-9300-5a033e558469.jpg)
> 我 真 的 不 想 把 事 情 搞 大

**Comment by yry0008** [comment]
连debug都不会。。。
前排吃瓜

**Comment by Avimitin** [comment]
吃瓜插眼

**Comment by lilmonix33** [comment]
瓜怎麼沒了？出完道就沒了嗎

**Comment by AidenOfficial** [comment]
@lilmonix33 出  道  即  巅  峰

**Comment by mikifuns** [comment]
软的真快这么快就删号了，没意思.....

**Comment by Jimmun** [comment]
瓜 熟力

**Comment by chx818** [comment]
吃瓜吃瓜

**Comment by SaltyfishEd** [comment]
这瓜蛮香的

**Comment by SNSLogty** [comment]
一瞬出道，好瓜

**Comment by SukkaW** [comment]
@amColinzzz 啊，他号怎么没了

**Comment by Colinwood11** [comment]
@SukkaW 我没吃到瓜。。  难顶

**Comment by du5** [comment]
**来迟了**

**Comment by chirophy** [comment]
来吃瓜 结果迟了

**Comment by XiaoMouz** [comment]
挖坟瓜

**Comment by XiaoMouz** [comment]
我老火星了/kk
