### ISSUE TITLE
[BUG] 新主页 过滤器设置问题 导致 节点列表(/user/node) 列表项内最后一个字符缺失

### ISSUE THREAD

**Issue by Candinya** [Anankke/SSPanel-Uim#1057]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

## Solution 解决方案
可以对过滤器（`Node.vue，第126-130行`）加入特判，当查找不到“ - ”分割串时返回完整节点名称，否则应用过滤器
![image](https://user-images.githubusercontent.com/20502130/82866046-b6be0180-9f5a-11ea-8d0e-422405377a54.png)
一个样例（我不知道这样是否符合vue的语法）：
![image](https://user-images.githubusercontent.com/20502130/82866081-cd645880-9f5a-11ea-9301-715896ea956a.png)

**Environment 环境**
*演示站点*与*自己的站点*都有发生，浏览器是 Google Chrome 81.0.4044.138 (64bit)，系统是 Windows 10 1903

**Commit**
dev分支最新的commit（演示站）

**Bug**
在新主页的节点列表右侧存在列表项，但测试时发现每一个列表项的最后一个字符均出现了丢失。

**Reproduce**
1. 登陆账户，进入路径 /user/node 
2. 查看右边的节点列表

**Expected behavior**
正常显示节点的名字，不出现最后一个字符的缺失

**Addition**
![image](https://user-images.githubusercontent.com/20502130/82864538-54afcd00-9f57-11ea-950e-d5b47330f57d.png)
![image](https://user-images.githubusercontent.com/20502130/82864724-cab43400-9f57-11ea-90e4-f27bb766d68f.png)
![image](https://user-images.githubusercontent.com/20502130/82864942-41e9c800-9f58-11ea-8a70-9ba561f5200e.png)

原始代码与测试：
![image](https://user-images.githubusercontent.com/20502130/82865696-f506f100-9f59-11ea-81ac-7ca460394f53.png)
![image](https://user-images.githubusercontent.com/20502130/82865663-d30d6e80-9f59-11ea-8a87-bf6b684e3eb3.png)

**Comment by AidenOfficial** [comment]
@Candinya 前排友情提醒，ISSUE时切忌嘴臭。上午就有一个活生生的例子。

**Comment by regendsoh** [comment]
建议可以不Issue 直接PR然后等审核。

**Comment by idwangdana** [comment]
> 建议可以不Issue 直接PR然后等审核。

you 讲 得 昂

**Comment by regendsoh** [comment]
> > 建议可以不Issue 直接PR然后等审核。
> 
> you 讲 得 昂

PR后直接pull 岂不是不用麻烦其他人写
