### ISSUE TITLE
[Feature Request]在注册页面添加防傻逼注册选项

### ISSUE THREAD

**Issue by marcosteam** [Anankke/SSPanel-Uim#1065]
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
在注册页面添加防傻逼注册选项，当用户勾选“我不是轮子、民逗等白痴”选项后才可以继续注册。

**Comment by regendsoh** [comment]
@marcosteam @xiaobeiwei: 这个不是自己动手改一下就好了
