### ISSUE TITLE
新面板与旧面板订阅链接不统一导致无法订阅的问题

### ISSUE THREAD

**Issue by Huitiank** [Anankke/SSPanel-Uim#1076]
最新的2.2面板中，新界面与旧界面的订阅链接不统一，新面板中的无法使用。
新面板订阅链接最后为：mu=0
旧面板订阅链接最后为：sub=1

**Comment by regendsoh** [comment]
@Huitiank 自行修改 不好吗。

**Comment by Huitiank** [comment]
> @Huitiank自行修改不好嗎。

自行修改是可以，但这总算一个问题吧。

**Comment by regendsoh** [comment]
@Huitiank 并不觉得是问题
https://github.com/Anankke/SSPanel-Uim/blob/dev/src/Controllers/LinkController.php

122 到 141 行

**Comment by regendsoh** [comment]
@Huitiank 除非你订阅合并 后面连mu都没有
那哦豁 你得自写一个 (至少我是写了

**Comment by Huitiank** [comment]
> @Huitiank 除非你订阅合并 后面连mu都没有
> 那哦豁 你得自写一个 (至少我是写了
兼容旧版没问题，但是我订阅后 什么节点都没有，这是调用出问题了吗

**Comment by Lin-UN** [comment]
旧版的订阅链接并没有后面的?sub=1
