### ISSUE TITLE
红包请求解决节点API通讯耗费流量问题

### ISSUE THREAD

**Issue by JusufUs** [Anankke/SSPanel-Uim#1077]
前几天把所有节点等级降低了，然后网站流量突增
观察发现都是api的用户信息耗费的，查看后发现每隔几分钟就会有一个用户数据的大包出去，如图：https://i.loli.net/2020/06/18/Okg2aECmuGLPrRW.jpg

节点数量没有变，付费的人数也没有变

可以解决的联系我价格可谈或者其他你需要的答谢，我的TG @ChinaT

**Comment by du5** [comment]
等级设置降低=可用用户变多，1.6M ≈ 13000 用户

**Comment by JusufUs** [comment]
> 等级设置降低=可用用户变多，1.6M ≈ 13000 用户

不是这样的，是我操作让节点等级降低后才出现的，用户数量并没有变
所以说更不对了，整个机场加起来都没1.3W用户。更别说付费的了有那么多了。

**Comment by du5** [comment]
> > 等级设置降低=可用用户变多，1.6M ≈ 13000 用户
> 
> 不是这样的，是我操作让节点等级降低后才出现的，用户数量并没有变
> 所以说更不对了，整个机场加起来都没1.3W用户。更别说付费的了有那么多了。

等级设置降低=可用用户变多

**Comment by JusufUs** [comment]
@du5 目前还未解决，确认不是可用用户变多。
经观察，好像是后端获取用户列表比较频繁导致的，也就是说有用户到期或者开通后就会获取一次，不是增量获取。

**Comment by M1Screw** [comment]
請更新到最新的 dev 版，我們已經在 commit https://github.com/Anankke/SSPanel-Uim/commit/1e95559f2516e55312d660747489df1e380cdd16 以及 https://github.com/Anankke/SSPanel-Uim/commit/aa8cb0d8da70f8251bb97f48b3e0f1104c806acd 中糾正了 API 通訊流量消耗過高的問題，v2ray 以及 trojan 節點可觀察到50%左右的流量消耗降低。

**Comment by JusufUs** [comment]
> 請更新到最新的 dev 版，我們已經在 commit [1e95559](https://github.com/Anankke/SSPanel-Uim/commit/1e95559f2516e55312d660747489df1e380cdd16) 以及 [aa8cb0d](https://github.com/Anankke/SSPanel-Uim/commit/aa8cb0d8da70f8251bb97f48b3e0f1104c806acd) 中糾正了 API 通訊流量消耗過高的問題，v2ray 以及 trojan 節點可觀察到50%左右的流量消耗降低。

大佬牛逼！！！
另外数据库对接的优化没

**Comment by M1Screw** [comment]
@JusufUs 數據庫對接應該逐步走入歷史，遠程直連數據庫未免過於野蠻

**Comment by marcosteam** [comment]
> @JusufUs 數據庫對接應該逐步走入歷史，遠程直連數據庫未免過於野蠻

要不要考虑做个 gRPC（
