### ISSUE TITLE
[BUG] php composer.phar install 安装错误解决方法

### ISSUE THREAD

**Issue by LongYin-cn** [Anankke/SSPanel-Uim#1078]
把 composer.json文件里的 charlottedunois/yasmin 改成 laravel-discord/yasmin就可以了，原因是依赖包仓库没了

**Comment by waynehung1997** [comment]
> 把 composer.json文件里的 charlottedunois/yasmin 改成 laravel-discord/yasmin就可以了，原因是依赖包仓库没了

这个composer.json的文件在哪里找啊，没找到
，谢谢了

**Comment by LongYin-cn** [comment]
> > 把 composer.json文件里的 charlottedunois/yasmin 改成 laravel-discord/yasmin就可以了，原因是依赖包仓库没了
> 
> 这个composer.json的文件在哪里找啊，没找到
> ，谢谢了

下载目录里

**Comment by waynehung1997** [comment]
可是我找了很久，没找到有这个charlottedunois/yasmin

**Comment by Anankke** [comment]
小白不要开机场，，，
