### ISSUE TITLE
最新dev版邀请链接bug

### ISSUE THREAD

**Issue by xieruan** [Anankke/SSPanel-Uim#1081]
某用户通过邀请链接注册后，管理面板中该注册用户邀请id显示系统邀请，邀请用户邀请链接次数未变
![b1](https://user-images.githubusercontent.com/59883140/85300722-7e69fe80-b4d9-11ea-9bd4-8d03b9980064.png)
![b2](https://user-images.githubusercontent.com/59883140/85300734-83c74900-b4d9-11ea-840e-a5aeb7ecc193.png)

**Comment by regendsoh** [comment]
@xieruan 你奢望这样的issue我们可以为你做些什么？
