### ISSUE TITLE
[BUG]composer安装时报错，charlottedunois/yasmin似乎删库了？？？

### ISSUE THREAD

**Issue by Chiyukichan** [Anankke/SSPanel-Uim#1085]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
CentOS7x64,PHP7.4,MySQL 5.7
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
dev-23f28e8159f1e6db9c04ce4b636ab1735e2c9e66
**Bug**
The bug information. 请描述你遇到的 Bug。
php composer.phar install报错：

Problem 1
    - The requested package charlottedunois/yasmin could not be found in any version, there may be a typo in the package name.

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
部署SSPanel时php composer.phar install报错，无法自动进行下去

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
看了一下github找不到charlottedunois/yasmin这个库了，我不是专业的程序猿不知道这个依赖的用处，我在composer.json中将这一行依赖删除后即可正常安装其他依赖，希望大佬们看一下是不是出现了这个问题，如果是我自己笨，请直接关闭issue，如果确实是这样的情况，麻烦你们修复啦>w<等着用

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by narakuzi** [comment]
@Chiyukichan 自行删除即可

**Comment by du5** [comment]
@Chiyukichan 、 复读机

**Comment by JusufUs** [comment]
问之前不会先搜一下？

**Comment by Chiyukichan** [comment]
> 问之前不会先搜一下？

搜得到还用费了半天劲打issues？

**Comment by NimaQu** [comment]
#1078 #1029 #1024 #994

**Comment by du5** [comment]
> > 问之前不会先搜一下？
> 
> 搜得到还用费了半天劲打issues？

上一个这么牛逼的坟头草都三丈高了
