### ISSUE TITLE
[BUG] 用户界面翻页跳转按钮链接错误

### ISSUE THREAD

**Issue by Neuxin** [Anankke/SSPanel-Uim#1087]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
php-7.3

**Commit**
dev已更新到最新版

**Bug**
暂时只实验了用户界面的审计记录页面，在查看审计记录时，如果审计记录超过了15条（即产生了分页），下面几页的跳转按钮链接是错误的，比如点击第二页的链接是这样的：http://域名/?page=2， 然而正确的链接应该是（测试这样可以正确进入第二页）：http://域名/user/detect/log?page=2  

**Addition**
能进后面几页说明后台翻页代码逻辑是没问题的，只是这个按钮的链接有问题，审查元素发现这个按钮的链接直接是   /?page=2    问题就在这，多了一个"/"

**Comment by M1Screw** [comment]
![image](https://user-images.githubusercontent.com/14369594/114637595-bffdad00-9c97-11eb-8ae4-a81a842d981b.png)
無法復現。
