### ISSUE TITLE
[Feature Request]移除一些支付商家

### ISSUE THREAD

**Issue by leekunha** [Anankke/SSPanel-Uim#1090]
- [X] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
The feature you want.
有很多第三方支付商家因为各种原因跑路了，希望可以移除他们，再添加一些新商家（PayPal，stripe或是能有个说明文档方便对接）
希望支持recaptcha v3，hcaptcha 验证
**Solution**
If you have some solution about this issue, type it here.
番茄支付，idtpay都可以移除
新增stripe之类的支持支付宝的大型外国商家
实人认证如上文
**Addition**
Additional context here.

**Comment by Anankke** [comment]
pr welcome

**Comment by Anankke** [comment]
已完成
