### ISSUE TITLE
Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.

### ISSUE THREAD

**Issue by c2w570063013** [Anankke/SSPanel-Uim#1092]
进入到'#/user/panel'路由的时候，控制台现实 'Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.'， 然后页面一直在加载.

-----现在完全用不了了

**Comment by TheCGDF** [comment]
我发现 @laurieryayoi 将vue引入ssp之后带来的一个显著问题是：他咕了之后，其他人既不会给新newIndex修BUG也不会跟着完善功能，最近唯一一条和newIndex有关的更新是
https://github.com/Anankke/SSPanel-Uim/blob/7d44a9059d5e042c37a1dce7c45487bc1d426820/config/.config.example.php#L10

**Comment by laurieryayoi** [comment]
@TheCGDF 先把newindex关了吧，geekqu更新的功能没有更进，有问题的
