### ISSUE TITLE
首先很感谢各位开发者无私奉献，但这次确实升级最新新版后 数据库和php增加一半负担了  而且还是用的两台机子2C4G站库分离的，后期能不能优化下别再增加数据库负担了，谢谢，特别是每定时任务[BUG]

### ISSUE THREAD

**Issue by xmg665** [Anankke/SSPanel-Uim#1095]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
The bug information. 请描述你遇到的 Bug。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by xmg665** [comment]
首先很感谢各位开发者无私奉献，确实升级最新新版后 数据库和php 升级一半了了  而且还是用的两台机子2C4G站库分离的，后期能不能优化下别再增加数据库负担了，特别是每定时任务

**Comment by AidenOfficial** [comment]
@xmg665 pr welcome stfu

**Comment by sigle0724** [comment]
@xmg665 又想马儿跑又不让马儿吃草的想法

**Comment by Deoncn** [comment]
> @xmg665 又想马儿跑又不让马儿吃草的想法

这话说的太对了。

**Comment by TheCGDF** [comment]
数据库由于历史原因和各种无法挽回的设计失误导致有很多不必要的性能损耗，强烈建议不要设置“每x天增加y流量”的定期重置套餐，定期重置套餐会导致数据库性能爆炸且每日任务执行时间显著加强，同时因为ssp并没有锁表功能，每日任务执行时间变长会导致更多傻逼BUG。此类套餐应当尽快使用“自动续费”功能取代。

**Comment by Anankke** [comment]
@TheCGDF 有一说一，确实

**Comment by Anankke** [comment]
@TheCGDF 我建议直接砍点费拉功能，这样就能删掉很多设计上的脑瘫逻辑（

**Comment by TheCGDF** [comment]
> @TheCGDF 我建议直接砍点费拉功能，这样就能删掉很多设计上的脑瘫逻辑（

定期重置套餐恐怕已经不好删了，一堆机场要炸。（两年前要不是围墙拦着，我早就把这个删了

**Comment by ZBrettonYe** [comment]
唯一解决方法，改动数据库，并且提供一些转换脚本，来矫正数据库不规范

**Comment by M1Screw** [comment]
建議測試最新版的性能消耗是否能夠接受，另外就是數據庫這塊如果不希望升級機器的話可以考慮換用 MariaDB。
