### ISSUE TITLE
宝塔搭建教程页面522了

### ISSUE THREAD

**Issue by jackchan6521** [Anankke/SSPanel-Uim#1099]
![522](https://user-images.githubusercontent.com/67191774/88696167-7d119e80-d135-11ea-88b9-9f20a5e0f961.png)

**Comment by Anankke** [comment]
在修了在修了

**Comment by ArtherLogic** [comment]
> 在修了在修了
还没有修好吗？

**Comment by Anankke** [comment]
@ArtherLogic 没有的没有的

**Comment by du5** [comment]
越催越慢，再催歇火
