### ISSUE TITLE
关于master分支迁移到dev分支

### ISSUE THREAD

**Issue by Hobostar** [Anankke/SSPanel-Uim#1103]
分支间的数据库有较大改动，现有wiki内未见相关内容，希望能提供此方面的文档。

**Comment by Anankke** [comment]
多少有点复杂，主要是涉及好几个数据库操作

**Comment by xuelang113** [comment]
两张数据表哪来对比，每个表点开结构对比，总共8张表需要修改添加！已经成功。

**Comment by Alcu1n** [comment]
> 两张数据表哪来对比，每个表点开结构对比，总共8张表需要修改添加！已经成功。

遇到同样的问题，可以联系您解决吗
