### ISSUE TITLE
使用redis等方式降低数据库负载

### ISSUE THREAD

**Issue by Murasame0721** [Anankke/SSPanel-Uim#1116]
mysql占用内存太多了，需要改进，我一个1g内存的小机子，网络几乎0io，mysql吃了600m的内存，加swap都莫得用
**Feature**
优化数据库使用方法，降低内存

**Addition**
尽管我知道小机子跑面板很憋屈，但没想到这么憋屈

**Comment by NutterChen** [comment]
你觉得东西贵并不是东西的问题
同理

**Comment by Anankke** [comment]
目前数据库历史包袱太大需要等新版重构

**Comment by SukkaW** [comment]
@Murasame0721 安装文档和教程都已说明「请尽量选择内存大于 2G 性能充足的机器」。我们未来也会考虑在安装时添加硬件配置检查，避免面板运行在过低性能的机器上。
