### ISSUE TITLE
[BUG]2008r2 下clash windows客户端 出错 无法查询DNS

### ISSUE THREAD

**Issue by lowprofileusername** [Anankke/SSPanel-Uim#1127]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
php7 mysql 5.6
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
e8c15d6
**Bug**
The bug information. 请描述你遇到的 Bug。
2008 R2系统下，使用CLASH订阅 ，CLASH无法查询DNS，切换到log显示

xxx connect error: All DNS requests failed, first error:x509:certificate is valid for 223.5.5.5,223.6.6.6, not 223.5.5.5
![3](https://user-images.githubusercontent.com/9425810/93008700-2f98a600-f5aa-11ea-970b-4460326ebc87.PNG)

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
Windows 2008 R2 系统下使用CLASH WINDOWS客户端下载最新订阅。
**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
@mashirozx
#1123

**Comment by mashirozx** [comment]
在Windows 10 2004上使用最新版Clash for Windows没有出现这个问题。

请先确认一下你使用的是不是最新版clash客户端；另外无法排除是clash的DNS配置（从log看是配置文件中新增的DNS配置部分SSL证书异常）在老旧版本Windows上的支持性问题，建议在Clash for Windows项目那边报告该问题。

这个问题可能涉及到Clash的go内核相关代码，已经超出了sspanel项目的范围：
https://github.com/golang/go/issues/24293

**Comment by mashirozx** [comment]
在Windows 10 2004上使用最新版Clash for Windows未复现此问题。

首先建议检查使用的是否是最新版clash；其次不排除是clash在老旧版本系统上的兼容性问题。建议附上配置文件将此问题反馈到clash项目的issue上。

从log看是clash配置文件新增的DNS配置区块中DNS over SSL的证书异常，该问题可能涉及到clash的go内核，已经远远超出了sspanel项目的范畴：
https://github.com/golang/go/issues/24293

**Comment by mashirozx** [comment]
阿里DNS相关说明：https://www.alidns.com/faqs/?spm=a2chw.13814944.0.0.783a1760Q1CimU#dns-safe

**Comment by lowprofileusername** [comment]
的确本人在WINDOWS10下MAC下都没问题。有台机器是2008R2就是有问题。CLASH客户端是最新的了。只能暂时把DNS部分COMMENT掉来使用。

**Comment by regendsoh** [comment]
@lowprofileusername clash的问题不要来这边开issue 去找clash的。

**Comment by regendsoh** [comment]
不对 有点好奇 可能和ssp有关系？

**Comment by mashirozx** [comment]
应该是和SSP没有关系

**Comment by regendsoh** [comment]
默认conf form？但是看这情况 大概率是clash问题/系统问题吧

**Comment by mashirozx** [comment]
我有点怀疑会不会是win2008上没有装相应的CA证书
