### ISSUE TITLE
wiki无法访问

### ISSUE THREAD

**Issue by danuonuo** [Anankke/SSPanel-Uim#1130]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
-[x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [ ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

这并不是bug，但是你们的wiki确实没法访问了，被阿里云阻断了。。。
我无法查看安装教程。。。

**Comment by du5** [comment]
@danuonuo 好 递交下你的身份证进行备案才可以正常访问

**Comment by danuonuo** [comment]
> @danuonuo 好 递交下你的身份证进行备案才可以正常访问

。。。。。。。。。。你在搞笑么

**Comment by HynoR** [comment]
您好，您的danao不够高级，需要升级一下你的danao版本。

**Comment by regendsoh** [comment]
@danuonuo 阅读wiki需要实名认证，请提供以下信息:
- 名字
- 手机号
- 现居地址
- 手持身份证正反面

**Comment by danuonuo** [comment]
滚蛋

**Comment by Colinwood11** [comment]
@regendsoh 手持可以写上  仅供sspanel验证使用的字样或者水印

**Comment by regendsoh** [comment]
@Colinwood11 顺便拍一下正面 侧面照片 方便一下后续的流程
