### ISSUE TITLE
[BUG] 配置后端无法使用ss,请问ss是被砍了吗？

### ISSUE THREAD

**Issue by niancan** [Anankke/SSPanel-Uim#1131]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
centos7.4 

**Commit**
最新comit

**Bug**
无法处理ss数据

**Reproduce**
1.sspanel新建ss帐号
2.ss客户端连接node
3.无法连接成功

**Expected behavior**
ss成功连接

**Logs**
![photo_2020-09-19_18-36-38](https://user-images.githubusercontent.com/6178530/93670057-e0330800-faca-11ea-95f5-07ea11b39304.jpg)

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
？

**Comment by niancan** [comment]
使用配套的后端脚本 ss 无边连接成功  需要额外配置吗

**Comment by Anankke** [comment]
不能复现。

**Comment by regendsoh** [comment]
@niancan

**Comment by regendsoh** [comment]
> 请将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .
> 
> * [x]  我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
> * [x]  我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
> * [x]  我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
> 
> **Environment 环境**
> Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
> centos7.4
> 
> **Commit**
> 最新comit
> 
> **Bug**
> 无法处理ss数据
> 
> **Reproduce**
> 1.sspanel新建ss帐号
> 2.ss客户端连接node
> 3.无法连接成功
> 
> **Expected behavior**
> ss成功连接
> 
> **Logs**
> ![photo_2020-09-19_18-36-38](https://user-images.githubusercontent.com/6178530/93670057-e0330800-faca-11ea-95f5-07ea11b39304.jpg)
> 
> **Addition**
> Additional context here. 如有可能，请提供更多相关资料。

![403](https://user-images.githubusercontent.com/17229500/93670182-f8575700-facb-11ea-89d6-1f8ff078ff2c.jpeg)

**Comment by niancan** [comment]
复现条件:
1.sspanel新建ss帐号
2.mac环境使用 shadowsocks-NG 无法连通,
3.Android 环境 使用shadowsocks 也是无法连通。

我如何 给你提供更多信息
我没有多余的操作,部署sspanel-uim ，然后安装脚本。 
使用的是数据库连接,从日志上看,获取数据库信息没有问题，
但是我客户端连接进来,数据无法处理，我想知道ss是否被砍掉了

**Comment by Anankke** [comment]
![image](https://user-images.githubusercontent.com/40639066/93670236-f9569d00-fa67-11ea-9eb5-cbc277e0b715.png)
自己的问题就不要开 issue 污染大家的邮件时间线了，连用个 ss 翻墙都不会配置吗？

**Comment by niancan** [comment]
所以 你的意思是说 配套后端不支持ss？直接处理的是content 而不是域名？

**Comment by regendsoh** [comment]
@niancan 意思是你自己没有配置正确 和sspanel，ss项目都毫无关系，问题纯粹在于你本人

“小白开🔨机场” (anankke, 2019)

**Comment by NutterChen** [comment]
> ![image](https://user-images.githubusercontent.com/40639066/93670236-f9569d00-fa67-11ea-9eb5-cbc277e0b715.png)
> 自己的问题就不要开 issue 污染大家的邮件时间线了，连用个 ss 翻墙都不会配置吗？

看群消息 闹了一下午 不描述 问题

**Comment by M1Screw** [comment]
@niancan 首先面板配套的SSR後端安裝脚本用的是 https://github.com/Anankke/shadowsocks-mod ，基本就是原版的ssr python後端的一個fork，你要用SS自己獨有的一些加密方式和參數連不上是非常正常的

**Comment by niancan** [comment]
@M1Screw  加密只用的aes-256-cfb  我用 libev 或者别的python版本 ss没有问题，但是 用他配套的脚本ss 数据 是无法处理的。

**Comment by M1Screw** [comment]
問題信息太少，能夠正常啓動端口説明數據庫鏈接和後端運作都是正常的，請檢查VM網絡配置和本地連接配置。

**Comment by niancan** [comment]
@M1Screw  谢谢你的回答

我重新描述问题。
1.环境初搭(正常ssr)
2.安装配套python脚本.
3.从sspanel新建一个ss帐号
4.使用客户端连接 发现 python后端无法处理ss数据。

可以肯定的信息
   1.加密算法没有问题
   2.在当前环境下使用 libev 或者 别的python版本 ss正常,排除服务器网络原因

期望:
    修复这个问题,如果实在不行 就当交流了哈。

**Comment by Anankke** [comment]
我重新描述你的问题：
后端脸上了而且正常连接而且有连接数而且没有看到协议错误，所以是你自己的问题，开 issue 带脑子谢谢当复读机对你没有好处。

**Comment by Anankke** [comment]
Locked.
