### ISSUE TITLE
Optimized account deletion logic(

### ISSUE THREAD

**Issue by olperson** [Anankke/SSPanel-Uim#1139]
- [x ] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
The feature you want.

### **Solution**
If you have some solution about this issue, type it here.

**Addition**
Additional context here.
### Optimized account deletion logic(prevent the account from being deleted as soon as it class expires)
At line 606 in Job.php file Add  `$user->class_expired,`.

**Comment by Anankke** [comment]
？

**Comment by M1Screw** [comment]
It totally depends on your 'account_expire_delete_days' setting in .config.php and by default, it shouldn't be enabled at all, please double check your configuration before open any future issue, thanks.
