### ISSUE TITLE
演示站为什么是阿里云阻断页的？

### ISSUE THREAD

**Issue by ZHOURUFA** [Anankke/SSPanel-Uim#1140]
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
The feature you want.

**Solution**
If you have some solution about this issue, type it here.

**Addition**
Additional context here.

想排错却发现演示站是阿里云阻断页的？那么我怎么解决一大堆的问题呢。。。

**Comment by HynoR** [comment]
大脑等级不够，需要进行大脑升级

**Comment by ZHOURUFA** [comment]
> 大脑等级不够，需要进行大脑升级

好好说话！

**Comment by saobilin** [comment]
给ank塞114514个USDT就能打开了

**Comment by ZHOURUFA** [comment]
> 给ank塞114514个USDT就能打开了

。

**Comment by imldy** [comment]
我当时问也都阴阳怪气的，看这个项目就好了https://github.com/SSPanel-UIM/Wiki

**Comment by mxihan** [comment]
> > 大脑等级不够，需要进行大脑升级
> 
> 好好说话！

不爽可以不用谢谢
