### ISSUE TITLE
希望面板能支持VLess，目前V2ray客户端和服务端已经支持了

### ISSUE THREAD

**Issue by xuelang113** [Anankke/SSPanel-Uim#1149]
如题，希望面板能支持VLess，目前V2ray客户端和服务端已经支持了，
请问是否有开发计划？

**Comment by HynoR** [comment]
https://www.v2fly.org/config/protocols/vless.html#vless-%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%87%E5%87%86

**Comment by HynoR** [comment]
https://www.v2fly.org/config/protocols/vless.html#vless-%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%87%E5%87%86

**Comment by HynoR** [comment]
https://www.v2fly.org/config/protocols/vless.html#vless-%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%87%E5%87%86

然而并没有完全支持，请不要把实验性的东西随随便便往里面塞，如有需求请自行pr

**Comment by xray-v2ray-ss** [comment]
给sspanel增加增加 Vless / xtls 支持 的方法
https://github.com/xray-v2ray-ss/xPanel

**Comment by NutterChen** [comment]
@xray-v2ray-ss Welcome PR

**Comment by HynoR** [comment]
@NutterChen 自己pr添加功能，或者欢迎在群里50u让群友给你定制。莫当伸手党

**Comment by HynoR** [comment]
@xray-v2ray-ss 自己pr添加功能，或者欢迎在群里50u让群友给你定制。莫当伸手党

**Comment by Xavier-0619** [comment]
> 给sspanel增加增加 Vless / xtls 支持 的方法
> 
> https://github.com/xray-v2ray-ss/xPanel

这样似乎只有在通用链接里的V2RayN可以复制vless链接，但是对于其他一键导入配置而言仍然是vmess协议

**Comment by xray-v2ray-ss** [comment]
至少 v2rayN 订阅链接 可以了

**Comment by xray-v2ray-ss** [comment]
还有安卓 v2rayng 订阅链接也可以支持 Vless / xtls 了，它两一样的

**Comment by NutterChen** [comment]
@xray-v2ray-ss it seems that u have established ur new branch, if you want to contribute, you can PR, welcome

**Comment by xray-v2ray-ss** [comment]
和v2rayN/v2rayng 采用同样订阅格式的都可以了

**Comment by xray-v2ray-ss** [comment]
> @xray-v2ray-ss it seems that u have established ur new branch, if you want to contribute, you can PR, welcome

可以手工合一下 ， 根据这个记录改即可
https://github.com/xray-v2ray-ss/xPanel/commit/d874b56c758c931bc68f5867117c0f4c79e50ae2

**Comment by Xavier-0619** [comment]
ssp现在已有的协议普适全平台客户端，如果根据你的分支仅仅对类V2rayN进行适配，那么其他平台客户端怎么办？
