### ISSUE TITLE
[Feature Request]请求暴露更多的 API 接口

### ISSUE THREAD

**Issue by marcosteam** [Anankke/SSPanel-Uim#1151]
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**

目前 SSPanel 的公开 API 已经实现了绝大部分的功能，如用户基本信息、签到、AFF 返利获取等模块，但是还有部分模块 API 未完全暴露。

目前已知的未完全暴露API的功能如下：

- 流量记录

- 线路转发（GET 用户设置的转发）

- 审计规则与审计记录的获取

- IP记录

**Solution**

希望能继续暴露更多的 API，实现前后端分离。

**Addition**

None.

**Comment by Anankke** [comment]
支持！

**Comment by Deoncn** [comment]
可以的。

**Comment by XiaotuoluoConor** [comment]
ohhh

**Comment by crossfw** [comment]
研究了一下节点通信，瞎jb写了点
## 先决条件
所有API方法均需带上
params = {'node_id': id, 'key': 'mu_key'}
请自行替换

## 正文
1. 验证服务器存活<br>
GET "/func/ping"<br>
无JSON<br>
{"ret":1,"data":"pong"}

2. 用户数据使用量<br>
"/users/traffic"<br>
Json注解: "Upload, download, userid" 单次真实使用量<br>
{'data': [{'u': 308000, 'd': 905000, 'user_id': 24},{'u': 308000, 'd': 905000, 'user_id': 23}]}<br>
{"ret":1,"data":"ok"}

3. 服务器负载<br>
"/mod_mu/nodes/REPLECE/info"<--注意替换节点id<br>
Json注解: 存活时间, "5 10 15"平均负载<br>
{'uptime': '34712.77', 'load': '0.10 0.09 0.09\n'}<br>
{"ret":1,"data":"ok"}

4. 节点连接的ip数<br>
"/mod_mu/users/aliveip"<br>
Json注解: ip,对应的用户id<br>
{'data': [{'ip': '192.168.180.1', 'user_id': 1},{'ip': '192.168.130.1', 'user_id': 2}]}
{"ret":1,"data":"ok"}

5. 审计碰撞记录<br>
"/mod_mu/users/detectlog"<br>
UNKNOW

6. 节点信息
"/nodes/26/info"<br>
无额外参数提交<br>
{"ret":1,"data":{"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":1,"mu_only":1,"sort":0,"server":"YOU SERVER ADDR","type":"ss-panel-v3-}}


7. 节点用户<br>
"/mod_mu/users"<br>
{"ret":1,"data":[{"id":1,"email":"xxx","passwd"...}

8. 所有节点信息<br>
"/mod_mu/nodes"<br>
"{"ret":1,"data":[{"id":4,"name":"...}"

9. 审计规则<br>
"/mod_mu/func/detect_rules"<br>
"{"ret":1,"data":[{"id":1,"name":"BT1","text":"BT1","regex":"BitTorre...}"
