### ISSUE TITLE
[Feature Request] xcat 新增功能需求

### ISSUE THREAD

**Issue by simplepeoples** [Anankke/SSPanel-Uim#1152]
希望可以 php xcat User 可以增加 重置所有用户邀请码 和 清空全部用户cookie的功能

**Comment by Anankke** [comment]
第一个自己 sql，第二个意义不明

**Comment by simplepeoples** [comment]
第一个只需要动code列就好了吗，updated_at列有什么用处吗 需不需要动

第二个是某些情况下需要全部用户重新登录

感谢安安可的回复

**Comment by Anankke** [comment]
有意思，可是不是很想写

**Comment by simplepeoples** [comment]
重置

**Comment by Billtom** [comment]
建议增加用户流量排行榜，并可以给用户制裁措施

**Comment by Scholar-m** [comment]
@Billtom ????你是看见我的那个才有这种想法的?

**Comment by Billtom** [comment]
> @Billtom ????你是看见我的那个才有这种想法的？

一个大佬给我的建议，只不过我不会改啊

**Comment by Scholar-m** [comment]
@Billtom 为何要对用户那么苛刻

**Comment by Billtom** [comment]
> @Billtom为何要对用户那么苛刻

你不说，你是第一个发明者→_→？

**Comment by Scholar-m** [comment]
@Billtom 我不是,我已经纠正错误了

**Comment by Billtom** [comment]
> @Billtom我不是，我已经纠正错误了

我已删除，别人的想法不予剽窃
