### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by iaia1234iaia** [Anankke/SSPanel-Uim#1161]
Details
Type: ParseError
Message: syntax error, unexpected '}', expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST)
File: /www/wwwroot/s888.now.cc/src/Controllers/UserController.php
Line: 12
Trace
#0 /www/wwwroot/s888.now.cc/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/s8...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#2 /www/wwwroot/s888.now.cc/src/Controllers/AdminController.php(23): spl_autoload_call('App\\Controllers...')
#3 /www/wwwroot/s888.now.cc/vendor/composer/ClassLoader.php(444): include('/www/wwwroot/s8...')
#4 /www/wwwroot/s888.now.cc/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/s8...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#6 [internal function]: spl_autoload_call('App\\Controllers...')
#7 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/CallableResolver.php(98): class_exists('App\\Controllers...')
#8 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/CallableResolver.php(58): Slim\CallableResolver->resolveCallable('App\\Controllers...', 'index')
#9 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/CallableResolverAwareTrait.php(41): Slim\CallableResolver->resolve('App\\Controllers...')
#10 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/Route.php(276): Slim\Routable->resolveCallable('App\\Controllers...')
#11 /www/wwwroot/s888.now.cc/src/Middleware/Admin.php(25): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: App\Middleware\Admin->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(App\Middleware\Admin), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /www/wwwroot/s888.now.cc/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#21 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#24 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 /www/wwwroot/s888.now.cc/public/index.php(37): Slim\App->run()
#28 {main}

**Comment by Anankke** [comment]
请确认 PHP 版本是否符合最低标准
