### ISSUE TITLE
[BUG]點擊賬戶信息 failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by iaia1234iaia** [Anankke/SSPanel-Uim#1162]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP-7.1 MySQL 5.5.62
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
The bug information. 请描述你遇到的 Bug。
點擊賬戶信息
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

Whoops\Exception\ErrorException thrown with message "fopen(/www/wwwroot/s888.now.cc/app/../storage/qqwry.dat): failed to open stream: No such file or directory"

Stacktrace:
#22 Whoops\Exception\ErrorException in /www/wwwroot/s888.now.cc/src/Utils/QQWry.php:26
#21 fopen in /www/wwwroot/s888.now.cc/src/Utils/QQWry.php:26
#20 App\Utils\QQWry:__construct in /www/wwwroot/s888.now.cc/src/Controllers/UserController.php:408
#19 App\Controllers\UserController:profile in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:40
#18 call_user_func in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:40
#17 Slim\Handlers\Strategies\RequestResponse:__invoke in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/Route.php:281
#16 Slim\Route:__invoke in /www/wwwroot/s888.now.cc/src/Middleware/Auth.php:26
#15 App\Middleware\Auth:__invoke in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/DeferredCallable.php:57
#14 call_user_func_array in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/DeferredCallable.php:57
#13 Slim\DeferredCallable:__invoke in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#12 call_user_func in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#11 Slim\Route:Slim\{closure} in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#10 Slim\Route:callMiddlewareStack in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/Route.php:268
#9 Slim\Route:run in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/App.php:503
#8 Slim\App:__invoke in /www/wwwroot/s888.now.cc/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:70
#7 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/DeferredCallable.php:57
#6 call_user_func_array in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/DeferredCallable.php:57
#5 Slim\DeferredCallable:__invoke in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#4 call_user_func in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#3 Slim\App:Slim\{closure} in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#2 Slim\App:callMiddlewareStack in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/App.php:392
#1 Slim\App:process in /www/wwwroot/s888.now.cc/vendor/slim/slim/Slim/App.php:297
#0 Slim\App:run in /www/wwwroot/s888.now.cc/public/index.php:37

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
请仔细阅读安装文档。
