### ISSUE TITLE
采用新排版后，无法确定当前页面是第几页

### ISSUE THREAD

**Issue by JH2628** [Anankke/SSPanel-Uim#1163]
Commit

[16ed4076ae77786fcb19f2aeab2b9e82fb619d39](https://github.com/Anankke/SSPanel-Uim/commit/16ed4076ae77786fcb19f2aeab2b9e82fb619d39)

![2020-11-14_024347](https://user-images.githubusercontent.com/59839647/99109487-e1446980-2623-11eb-9bd5-44c7f26c595f.png)

采用新排版后，无法确定当前页面是第几页

**Comment by M1Screw** [comment]
這個問題應該是上次更新組件引起的，稍後修復

**Comment by M1Screw** [comment]
Fixed.
https://github.com/Anankke/SSPanel-Uim/commit/7fc977d53e3a1cbc5f105d79529ead73a807b6b0
