### ISSUE TITLE
Shadowrocket 里订阅地址采用专属订阅链接时的问题

### ISSUE THREAD

**Issue by JH2628** [Anankke/SSPanel-Uim#1164]
Commit

[16ed4076ae77786fcb19f2aeab2b9e82fb619d39](https://github.com/Anankke/SSPanel-Uim/commit/16ed4076ae77786fcb19f2aeab2b9e82fb619d39)

Shadowrocket 2.1.65

Shadowrocket 里订阅地址采用专属订阅链接时，获取的节点设置中额外ID 为空，加密算法为 chacha20-poly1305，而不是像 v2ray 订阅链接般为服务器所设定的ID、加密算法为 auto 。

左图为专属订阅，右图为 v2ray 订阅：

![2020-11-14_030854](https://user-images.githubusercontent.com/59839647/99111299-d212eb00-2626-11eb-9ba2-fd5922f97166.png)

**Comment by M1Screw** [comment]
专属订阅 指的是...?

**Comment by JH2628** [comment]
> 专属订阅 指的是...?

您好，指的是这里
![2020-11-14_033712](https://user-images.githubusercontent.com/59839647/99113747-b7db0c00-262a-11eb-909e-b71dec9fecea.png)

**Comment by M1Screw** [comment]
Please do try the latest version.

**Comment by JH2628** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/b3132c3beea3e1300524f219545da15853069362
效率太高了，你们太棒了，额外ID那修复好了，不过加密算法那还是会自动选择为  chacha20-poly1305 而不是 auto 。

![20-11-14 04-30-49 3007](https://user-images.githubusercontent.com/59839647/99118663-e8bf3f00-2632-11eb-8d7a-4640bf34ebe5.png)

**Comment by JH2628** [comment]
Fixed.
https://github.com/Anankke/SSPanel-Uim/commit/2c4689ef62609844de5d7cc026298c94e3ec5b07

**Comment by TheCGDF** [comment]
@JH2628 。。。fix个鬼啊，这是移动端特化feature，出于移动端省电的考虑所以强制
ChaCha20-Poly1305，然后alter id强制设置为2是因为数字越小内存占用越低，而曾经的节点端支持的最小alter id是2。现在设置为0或者1比较合理。。。

**Comment by JH2628** [comment]
> @JH2628 。。。fix个鬼啊，这是移动端特化feature，出于移动端省电的考虑所以强制
> ChaCha20-Poly1305，然后alter id强制设置为2是因为数字越小内存占用越低，而曾经的节点端支持的最小alter id是2。现在设置为0或者1比较合理。。。

好吧，不是很懂。
但是为什么采用v2ray订阅链接或直接复制节点信息导入Shadowrocket时，不会出现这个现象？

**Comment by TheCGDF** [comment]
> > @JH2628 。。。fix个鬼啊，这是移动端特化feature，出于移动端省电的考虑所以强制
> > ChaCha20-Poly1305，然后alter id强制设置为2是因为数字越小内存占用越低，而曾经的节点端支持的最小alter id是2。现在设置为0或者1比较合理。。。
> 
> 好吧，不是很懂。
> 但是为什么采用v2ray订阅链接或直接复制节点信息导入Shadowrocket时，不会出现这个现象？

因为不是同一个人写的，订阅链接和节点信息并没有考虑移动端（iOS）优化
要实现也是可以的，根据User-Agent判断用户是不是iOS就行了

**Comment by Anankke** [comment]
auto 是好的，建议配置里面写 对林檎用户不友好=true，强行全部下发  aes-128-gcm（
