### ISSUE TITLE
建议后台提供发起充值的记录，无论是成功还是失败的订单

### ISSUE THREAD

**Issue by xuelang113** [Anankke/SSPanel-Uim#1172]
在目前的后台，只记录了充值成功的订单，这存在一个问题：
假如支付回调失败，那么管理员后台也是无法看到这个失败的订单，
但实际上，在使用码支付时，款是收到了，只是各种原因，掉单了，
后台也没有记录是哪个用户发起的充值，码支付也没有记录用户ID，
导致根本无法找到用户。需要用户主动联系管理员才能处理。
是否考虑在以后的开发中加入这个功能。
感谢大佬们的开发。致敬

**Comment by liujang** [comment]
赞成

**Comment by Anankke** [comment]
那也不能把别的都加上啊

**Comment by jeassiy** [comment]
我充值了以后没有到账怎么办呀？没有客服我就迷路了请问可以有人帮帮我吗;(

**Comment by Subeting** [comment]
@jeassiy 人家充值没到账不应该是你赚了吗，至少四方平台收到款了，，，

**Comment by jeassiy** [comment]
> @jeassiy 人家充值没到账不应该是你赚了吗，至少四方平台收到款了，，，

我是充值的那个用户

**Comment by goudaozhu** [comment]
> > @jeassiy 人家充值没到账不应该是你赚了吗，至少四方平台收到款了，，，
> 
> 我是充值的那个用户

建议报警，支付宝/微信投诉

**Comment by Subeting** [comment]
@goudaozhu 建议报警

**Comment by HynoR** [comment]
@Subeting 建议自首

**Comment by taizi-tp** [comment]
@jeassiy 打110举报那个机场不到账啊
