### ISSUE TITLE
面板无法注册用户

### ISSUE THREAD

**Issue by ChuJian2** [Anankke/SSPanel-Uim#1173]
按照教程利用LNMP建好面板后，其他一切正常，只有用户注册时无法注册，返回http500，但是管理员可以在管理面板添加用户，是因为dev分支数据库结构和之前的不一样，而教程中导入的数据库仍然是之前的吗？

**Comment by Anankke** [comment]
如果你看的是新版教程应该就没问题，以及 500 你需要开 debug 看一眼具体报错不要玩星际

**Comment by ChuJian2** [comment]
错误日志：Cannot redeclare normalizer_is_normalized() (previously declared in /var/www/sspanel/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15) in /var/www/sspanel/vendor/voku/portable-utf8/src/voku/helper/bootup/intl.php on line 27" while reading response header from upstream

![image](https://user-images.githubusercontent.com/61411821/100615953-55387e80-3353-11eb-8287-d1815105bc0f.png)
![image](https://user-images.githubusercontent.com/61411821/100615984-62556d80-3353-11eb-9ba7-ad316384e0c6.png)
”不要玩星际“：此话怎讲？
