### ISSUE TITLE
关于 README

### ISSUE THREAD

**Issue by Sciencmine** [Anankke/SSPanel-Uim#1179]
> SSPanel UIM 不会对您的任何损失负责，包括但不限于服务中断、Kernel Panic、机器无法开机或正常使用、数据丢失或硬件损坏、原子弹爆炸、第三次世界大战、SCP 基金会无法阻止 SCP-3125 引发的全球 **MK 级现实重构**等

[原文](http://scp-wiki-cn.wikidot.com/scp-3125) 中称之为：

> SCP-3125尚未完全进入我们的现实中，一旦其完全到来，人类知识交互系统的高度互联将使其在不超过12小时、甚至少至4小时内包围、占领并替代全部人类思维。此时，作为抽象概念的“人类”，以及“文明”、“文化”、“社会”、“社群”等所有相关抽象将不复存在。基金会将此种可能事件命名为**MK级世界末日情景**。

其含义与 `EK级人类意识终结` 相同，更多请参见[K级情景完整列表](http://scp-wiki-cn.wikidot.com/k-class-complete-list)。

此外，理念圈部已识别到一次信息突破，MTF 正在赶来的路上。

**Comment by SukkaW** [comment]
1. SCP-3125 已被 Bart Hughes 和 Marion Wheeler 处决。
2. SCP-3125 于 2010 年的入侵被标注为 MK 级「人类意识全面丧失」世界末日情景。
3. MTF 机动特遣队一般处理普通设施人员无法或难以处理的特殊事故或威胁。信息突破将不会由 MTF 机动特遣队处理，请联系 记录与信息安全管理部（RAISA）和距离你最近的 HMCL 监督员。
