### ISSUE TITLE
你好我的登录密码丢失了，忘记密码填写outlook后无法收到重制邮件

### ISSUE THREAD

**Issue by ferried** [Anankke/SSPanel-Uim#1180]
email:harlancui@outlook.com

**Comment by M1Screw** [comment]
@ferried 你把現在站點的地址發一下，我幫你看看

**Comment by ferried** [comment]
> @ferried 你把現在站點的地址發一下，我幫你看看

登陆上去了原因是 大小写后缀问题，正确的账号为:harlancui@Outlook.com,输入的时候写成了harlancui@outlook.com导致密码不正确，感谢回复🙏

**Comment by regendsoh** [comment]
@ferried 网站发一下，由于这边有几个场子 我送你等级吧
