### ISSUE TITLE
[Enhanced] 部分表单提交时 content type 不完全一致

### ISSUE THREAD

**Issue by marcosteam** [Anankke/SSPanel-Uim#1183]
今天设计新版 SSPanel 前端 UI 的时候发现的。

具体重现：

监听 `/user/mail` `/user/gaset` 等在资料编辑页发出的请求，可见 content type 均为 `application/x-www-form-urlencoded`

监听`/auth/login` `/auth/login` `/user/password`等其他请求，content type 却是 `application/json`

**一 团 乱 麻**

**Comment by M1Screw** [comment]
![image](https://user-images.githubusercontent.com/14369594/111265162-10351100-85ff-11eb-834c-edda380ee8c0.png)
？
