### ISSUE TITLE
[BUG] 单月多购买多重置流量

### ISSUE THREAD

**Issue by regendsoh** [Anankke/SSPanel-Uim#1187]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
NGINX 1.17
PHP 7.4
MYSQL 5.7

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
https://github.com/Anankke/SSPanel-Uim/pull/1184
https://github.com/Anankke/SSPanel-Uim/pull/1186

**Bug**
The bug information. 请描述你遇到的 Bug。
购买多个可重置套餐，单月可能多次重置

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
单月不同天购买多次可重置套餐，后续有效期内单月多次重置

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
按最新的购买记录重置套餐流量

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
N/A

**Addition**
Additional context here. 如有可能，请提供更多相关资料。
N/A

**Comment by Anankke** [comment]
出来挨打

**Comment by HynoR** [comment]
貌似这是祖传bug了

**Comment by regendsoh** [comment]
基于某dalao forward给我看魔改dev群dalao们讨论，发现 renew 字段并不是重置的设置，而renew字段实为自动续费时间戳

Ref:

/dev/src/Controllers/UserController.php
第841行： 
`$bought->renew = 0;`

第957行
`$bought->renew = time() + $shop->auto_renew * 86400;`

**Comment by regendsoh** [comment]
++
https://github.com/Anankke/SSPanel-Uim/pull/1188

**Comment by Shuyakano** [comment]
Commit 最新记录。如图所示报错，不重置流量。
https://sm.ms/image/mFOYQl5Dq2EiLus

**Comment by regendsoh** [comment]
这东西已经revert了，按现在dev的先修改job.php

**Comment by yangyzp** [comment]
祖传bug，另外Commits on Dec 25, 2020的最新版本，测试后，问题依然存在。

**Comment by Anankke** [comment]
祖传bug
