### ISSUE TITLE
[BUG] 更新程序后，uuid列没有生成

### ISSUE THREAD

**Issue by ctrlbbj** [Anankke/SSPanel-Uim#1190]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP 7.3.25
Mysql 5.5.56

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
976e3943831dd0b7f7b99e008762d0eccf0e0e01
**Bug**
The bug information. 请描述你遇到的 Bug。
UIM版本从master分支硬切换到dev分支最新commit后，已经对数据库表进行了修改和补全，网站已正常工作，在使用php xcat Update 命令进行更新时，命令没有对uuid列进行自动填充，在数据库中表现为NULL。查找过历史issue，尝试执行php xcat Job CheckJob与php xcat Job DailyJob命令，没有看到uuid相关报错。但数据库中uuid列依旧为空。
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
在执行以下三个命令之一时，应该对为空的uuid列进行填充。
php xcat Update 
php xcat Job CheckJob
php xcat Job DailyJob
或者是否能在xcat中独立实现一个功能，实现主动的对uuid进行重置或者填充。
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。
用户主动修改连接密码会触发系统对uuid列的修改，此问题临时规避措施之一

**Comment by M1Screw** [comment]
@ctrlbbj 會考慮在xcat中加入一個為所有用戶重新生成uuid的功能。修改連接密碼的同時會重設uuid是預期的行爲，也是整個uuid生成重做的核心修改之一。

**Comment by ctrlbbj** [comment]
> 
> 
> @ctrlbbj 會考慮在xcat中加入一個為所有用戶重新生成uuid的功能。修改連接密碼的同時會重設uuid是預期的行爲，也是整個uuid生成重做的核心修改之一。

那现在来说，Update、CheckJob、DailyJob 都不会去主动对为空的uuid列进行填充，这个应该也是预期行为吧

**Comment by M1Screw** [comment]
原本的UUID填充式在CheckJob裏面做的，但是現在是從cron裏面移出去，改為用戶在注冊和手動修改連接密碼時候才會觸發。

**Comment by big51bba** [comment]
UUID可以自动填充吗？每次手動修改連接密碼時候才會觸發填充

**Comment by Anankke** [comment]
@M1Screw

**Comment by M1Screw** [comment]
php xcat User generateUUID
