### ISSUE TITLE
86400天后重置

### ISSUE THREAD

**Issue by CoreyAndres** [Anankke/SSPanel-Uim#1192]
https://github.com/Anankke/SSPanel-Uim/blob/02134772dffe4126892a4409de0379a1c9ed9693/src/Models/Bought.php#L78-L79

当unix=true时
请勿堆叠屎山

**Comment by TheCGDF** [comment]
流量重置功能就是屎山。
最初，购买流量重置型套餐会导致流量用完后用户既不能补充流量也不能切换套餐，除非直到下一个流量重置周期才能有流量可用，而且一旦购买就无法终止这个套餐（管理员都终止不了）。
后来为了缓解这个问题，又以非常肮脏的方式实现了另一个屎山——“流量叠加包”。
还给job徒增负担。
这个功能就应该删掉用自动续费取代，没人拦我我迟早把这玩意删了。
