### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by qingdeng8866** [Anankke/SSPanel-Uim#1197]
- [x] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
在线IP超限制，自动删除账号功能

**Solution**
If you have some solution about this issue, type it here.

**Addition**
Additional context here.
大佬您好，好像现在 一个账号连不同节点 可以超在线IP限制  面板虽然能检测到在线IP超额但是对链接没有任何影响，所以请问一下能不能 增加在线ip超额 自动删除账号功能。还有一个小bug就是 后台快速创建的账号，没有分配V2ray节点的UUID。

**Comment by qingdeng8866** [comment]
用的是dev分支

**Comment by HynoR** [comment]
自己动手 丰衣足食

**Comment by M1Screw** [comment]
> 还有一个小bug就是 后台快速创建的账号，没有分配V2ray节点的UUID。

這個是上次修改賬號UUID生成邏輯時候引入的bug，會做修復。

> 增加在线ip超额 自动删除账号功能

這個跟你用的後端也是有關係的，面板層面做的就是統計工作，觸發限制直接刪號顯然不是一個妥當的處理方法。
