### ISSUE TITLE
定时任务出错，请部什么原因呢？

### ISSUE THREAD

**Issue by fugood** [Anankke/SSPanel-Uim#1199]
运行：php  /www/wwwroot/ss.xxxxxxxxx.com/xcat Job checkjob  出然下面错误
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'coolyes.email_queue' doesn't exist in /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php:457
Stack trace:
#0 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(457): PDO->prepare()
#1 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run()
#4 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement()
#5 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#6 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Query/Buil in /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php on line 729

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'coolyes.email_queue' doesn't exist in /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php:457
Stack trace:
#0 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(457): PDO->prepare()
#1 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(458): Illuminate\Database\Connection->run()
#4 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php(414): Illuminate\Database\Connection->statement()
#5 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#6 /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Query/Buil in /www/wwwroot/ss.xxxxxxxxx.com/vendor/illuminate/database/Connection.php on line 729

**Comment by M1Screw** [comment]
@fugood 你庫少表

**Comment by NutterChen** [comment]
> @fugood 你庫少表

为什么你这么快

**Comment by fugood** [comment]
@M1Screw 少了那些呢，怎样补够，安装的时候是数据库版本问题吗？

**Comment by M1Screw** [comment]
@fugood Base table or view not found: 1146 Table 'coolyes.email_queue'

**Comment by fugood** [comment]
@M1Screw 问题是怎样添加，小白呀

**Comment by M1Screw** [comment]
@fugood phpmyadmin會用伐

**Comment by fugood** [comment]
![QQ截图20210127174502](https://user-images.githubusercontent.com/73930611/105973333-9507b200-60c7-11eb-99a9-29506c350ff4.jpg)
@M1Screw 这样保存就行？

**Comment by M1Screw** [comment]
@fugood https://github.com/Anankke/SSPanel-Uim/blob/dev/sql/email_queue.sql

**Comment by fugood** [comment]
@M1Screw 感谢
