### ISSUE TITLE
[Feature Request]Shadowsocks AEAD 单端口多用户 用户侧节点信息适配

### ISSUE THREAD

**Issue by crossfw** [Anankke/SSPanel-Uim#1203]
- [x] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
对于现在的ss/ssr单端口设定，在用户端的Shadowsocks配置中，密码均为单端口承载用户的密码，而最新的Xray-core已经实现SS AEAD加密的单端口多用户，其配置无须混淆插件即可完成设置。<br>
现在需要实现在用户侧SS的端口为单端口，密码则为用户自己唯一的密码, 端口、加密方式为统一的单端口与固定方式加密

**Solution**
是否可以在节点类型中新增sort=15的节点 “Shadowsocks AEAD 单端口” 来解决问题？这样可以同时兼顾现有ssr单端口配置。

**Comment by Anankke** [comment]
不接受任何 xtls 相关请求。
