### ISSUE TITLE
[BUG]用户首页没有 SS订阅按钮 请问是Feature还是Bug

### ISSUE THREAD

**Issue by crossfw** [Anankke/SSPanel-Uim#1204]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
CentOS 7 + PHP7.2 + MySQL8.0<br>

**Commit**
https://github.com/Anankke/SSPanel-Uim/commit/4301cfa1db37f4d5ca6f2d58424275042d355dd4

**Bug**
用户侧首页不显示 SS订阅按钮(使用sub=1的ssr订阅中未含纯ss订阅)

**Reproduce**
![image.png](https://i.loli.net/2021/02/14/BKIR7WzfxatOhHJ.png)

**Solution**
源码中已经留了
>sub=2

这个方法来分发SS订阅, 在某些软件的选项中,也留了ss订阅(如 Android-Kitsunebi)<br>
但是在首页上只有 "拷贝全部节点信息". 这是BUG还是Feature呢

**Comment by Anankke** [comment]
不懂就问，1202 年了 SS 的订阅统一了吗，虽然这部分好修来着

**Comment by marcosteam** [comment]
> 不懂就问，1202 年了 SS 的订阅统一了吗，虽然这部分好修来着

按照白皮书最新的应该是SIP008吧，SS Android和Windows客户端都采用了
