### ISSUE TITLE
Taiwan flag Replace

### ISSUE THREAD

**Issue by fr1g** [Anankke/SSPanel-Uim#1210]
- [x] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
Maybe you can consider to use the special flag "Blue sky White Plum Blossom" for Taiwan to replace the flag of "Republic of China" .

**Solution**
Change the old picture image to BSWPB flag picture.

**Addition**
Why?...I think RC was no longer exist anymore, since A.D.1949.
and BSWPB,the plum blossom is pretty,and equal to Chinese's culture, exactly equal to Taiwanese,Fujianese,Cantonese,Zhejiangnese,Hainanese and Jiangsunese.

**Comment by Anankke** [comment]
多少沾点

**Comment by fr1g** [comment]
> 多少沾点

啥啊 不就是建議把民國旗換成梅花旗幟嘛？

**Comment by Anankke** [comment]
那确实沾点。

**Comment by fr1g** [comment]
> 多少沾点

用戶應該是大陸人居多吧？你覺得放個民國旗幟在那裏很好嘛？

**Comment by Anankke** [comment]
LMFAO

**Comment by fr1g** [comment]
> LMFAO

你有點怪喔，也不象是個R吖 爲什麼這麼抵觸，是因爲contributer裏面有臺灣人嘛？

**Comment by Anankke** [comment]
我只是歧视小粉红罢了

**Comment by fr1g** [comment]
> 我只是歧视小粉红罢了

我那裏象粉紅了 只是和中國建交的國家至少在條文裏面承認了，那就算是普遍認爲民國已經是歷史了。所以才覺得你們這一點怪異另類吖
所以才這樣建議你們換個圖
你態度卻是不太好的樣子 是因爲換圖不是容易事嘛？

**Comment by fr1g** [comment]
> 我只是歧视小粉红罢了

不願意換就算了。
還有一點。。。
少逛微臉推，長壽不是吹 有的時候看臉書推特什麼的比較容易引肝火。

**Comment by fr1g** [comment]
> 我只是歧视小粉红罢了

反正就是勸你們、建議你們而已，不聽算了
還有吖 你也是反應過激 真是小粉紅的話會和我這樣嘛？我覺得我可是平和太多了XD

**Comment by Anankke** [comment]
笑嘻了

**Comment by M1Screw** [comment]
建議你好好讀一下現行中華民國憲法跟ISO 3166-2國際標準，還是說你覺得把旗幟換成這個你才開心？
![Taiwan](https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_World_Taiwanese_Congress.svg/1280px-Flag_of_World_Taiwanese_Congress.svg.png)
