### ISSUE TITLE
[Feature Request] 抽取请求订阅地址时的 IP 设立白名单防火墙

### ISSUE THREAD

**Issue by ghost** [Anankke/SSPanel-Uim#1211]
- [x] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**

> 白名单策略是指, 我们通过数据过滤防火墙, 只允许服务器接收特定 IP 来源的入站流量, 而拒绝所有别的流量. 具体而言, 我们 Setup 了两种服务器, 主服务器和子节点: 主服务器负责联络所有的子节点, 子节点负责给用户提供翻墙服务. 用户在翻墙前通过主节点记录自己的 IP, 主节点会把 IP 广播给所有的子节点, 从而把这个特定 IP 加入到白名单中. 这样我们就可以成功避开防火墙的探测.

**Addition**

请看这篇博文: https://blog.hiaoxui.com/blog/post/hiaoxui/whitelist-tech

**Comment by M1Screw** [comment]
訂閱IP紀錄這個功能其實是已經有的了，你說的這個功能只要把獲取過訂閱的IP地址這個API接口做出來就行了，其餘的白名單限制應該由服務端自己實現。不過我覺得這樣做一個有性能問題，另外一個有下發時效的問題，以及IP地址的有效期要給多少，還有故意構造訂閱地址獲取白名單要怎麼處理。

**Comment by TheCGDF** [comment]
@ygsk10 这个功能实现的东西和目前“限制用户IP数”的实现的完全一致，甚至只需要改大约两行代码就能完全变成你描述的那玩意，然而“限制用户IP数”是另一坨屎山（没人拦我我迟早也删了）。
最主要的是，在大陆这种大NAT环境下，获取用户IP并不现实，有时甚至相当愚蠢

**Comment by HynoR** [comment]
你这种想法非常乌托邦，中国有很多动态ip和各种乌七八糟的nat，还有蜂窝数据 用户ip变动都是家常便饭的事情。。用户估计切个wifi就断流，开关个数据就断流。而且用户可能会用到各种订阅转换托管api。其次你这个功能规模小你还好说，规模大了根本很难及时同步用户ip，而且会相当浪费性能。
