### ISSUE TITLE
关于用户ss链接密码长度

### ISSUE THREAD

**Issue by maker2002** [Anankke/SSPanel-Uim#1213]
根据这篇报道：
https://gfw.report/blog/ss_tutorial/zh/

SS链接的用户密码长度建议使用高强度长密码，以缓解Partitioning Oracle攻击。

目前用户的默认生成密码长度只有6位，如果手动输入也不能超过16位。

建议增加默认密码长度到20位以上。

**Comment by M1Screw** [comment]
> 如果手动输入也不能超过16位。

最初始的數據表設計如此，導致無法輸入過長的字串。這個問題要改的話修改面板的部分是不難，爲了現有用戶的兼容性會需要寫一個遷移脚本。

**Comment by crossfw** [comment]
> > 如果手动输入也不能超过16位。
> 
> 最初始的數據表設計如此，導致無法輸入過長的字串。這個問題要改的話修改面板的部分是不難，爲了現有用戶的兼容性會需要寫一個遷移脚本。

使用现成的 UUID 就方便了，也免去了修改数据库字段类型相关的操作。

**Comment by M1Screw** [comment]
Updated in https://github.com/Anankke/SSPanel-Uim/commit/b0e2444760b47e216b4006da083442f7ed8099aa
