### ISSUE TITLE
关于更新SS/SSR配套后端以抵御GFW主动探测

### ISSUE THREAD

**Issue by maker2002** [Anankke/SSPanel-Uim#1214]
根据这2篇文章：
https://gfw.report/blog/ss_advise/zh/
https://gfw.report/blog/ss_tutorial/zh/

建议更新 https://github.com/Anankke/shadowsocks-mod 代码仓库中的Shadowsocks-libev版本来抵御目前已知的GFW攻击。

**Comment by Anankke** [comment]
@maker2002 AEAD 并不能防止主动检测，被墙本来就是玄学的存在，快进到开源的 GFW 实现才行

**Comment by maker2002** [comment]
> 快进到开源的 GFW 实现才行

请问下这句是什么意思呀？

总之更新下版本也不是什么坏事嘛。

**Comment by HynoR** [comment]
与其提issue 不如自己pr更有效

**Comment by Scholar-m** [comment]
@maker2002 如何主动防止被墙，(你可以联系一下GFW，让他开源
