### ISSUE TITLE
关于如何排查无法收到邮件的问题？

### ISSUE THREAD

**Issue by maker2002** [Anankke/SSPanel-Uim#1215]
config配置了mailgun的API发信，前端提示邮件发送成功，但始终收不到邮件，请问可以在哪里排查邮件的发送情况和日志呀？
找了文档也没找到相关的内容，搜索issues也没搜到，只好开新的问下各位大神，谢谢了！

**Comment by JarvanDing** [comment]
先去mailgun 后台看看发送成功没有？

**Comment by maker2002** [comment]
> 先去mailgun 后台看看发送成功没有？

mailgun后台看不到发送数据，应该是就没有出去。
