### ISSUE TITLE
[BUG]最新的数据库文件导入时提示ERROR 1060 (42S21) at line 268: Duplicate column name 'uuid'

### ISSUE THREAD

**Issue by maker2002** [Anankke/SSPanel-Uim#1218]
使用最新的数据库文件glzjin_all.sql，
导入时提示：ERROR 1060 (42S21) at line 268: Duplicate column name 'uuid'ERROR 1060 (42S21) at line 268: Duplicate column name 'uuid'

测试了mysql 版本5.7和8.0
不管通过mysql命令行导入还是通过phpmyadmin导入都会报错。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/a5d36e4ed656c4604134847b0dc6cbe3cd006d9c , please git pull and re-try database import.
