### ISSUE TITLE
[Feature Request]关于验证节点IP地址的API

### ISSUE THREAD

**Issue by maker2002** [Anankke/SSPanel-Uim#1219]
目前sspanel使用“节点地址”作为后端的IP地址验证，而节点地址往往是域名且使用了CDN，导致后端节点校验IP的时候总是出错，但是在config中关闭IP校验又不太安全。

所以：能否采用校"节点IP“来实现IP校验，二不是校验”节点地址“？

**Comment by aipeach** [comment]
@maker2002 校验是采用节点IP，你可以使用server来重写节点地址

**Comment by M1Screw** [comment]
1. 套CDN這個顯然不是什麽經常會有的需求，特別是考慮到百度雲加速把ws全面封鎖了之後。
2. 加固你的節點機器並使用高强度 API Key ，確保所有基礎設施沒有安全隱患這個才是保證安全性的方式，而不是單單指望用一個IP校驗來保證安全。
