### ISSUE TITLE
[BUG] Trojan中转配置问题

### ISSUE THREAD

**Issue by ctrlbbj** [Anankke/SSPanel-Uim#1220]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [ ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
b0e2444
后端服务器为soga
**Bug**
The bug information. 请描述你遇到的 Bug。
Trojan在使用以下参数配置中转跳板的时候，面板无法识别服务器真实IP
中转机地址;port=落地机监听端口#中转机监听端口|host=证书域名
改成类似以下参数，面板无法正常识别中转配置
落地服务器;port=落地服务器端口|server=中转服务器|host=落地域名|outside_port=中转端口

以上问题是trojan的中转规则部分尚未开发导致的吗？

**Comment by ctrlbbj** [comment]
我进一步修改了一下
参照面板提示的规则
落地服务器;server=中转服务器|port=用户连接端口#监听端口
配置以后，重写入口的server规则不生效，还是使用了落地服务器。

**Comment by M1Screw** [comment]
配置下發問題請優先找付費後端作者咨詢，我們沒有教你怎麽用後端的義務。

**Comment by ctrlbbj** [comment]
重复一下我遇到的问题：
我是想用server参数在面板上把在用户节点列表中显示的节点地址重写为另一个地址。
这个参数在trojan的类型下没有生效，配置该参数后，面板依旧显示了原始的地址。
我想这个问题应该不涉及后端的处理吧

**Comment by ctrlbbj** [comment]
> 
> 
> 配置下發問題請優先找付費後端作者咨詢，我們沒有教你怎麽用後端的義務。

重复一下我遇到的问题：
我是想用server参数在面板上把在用户节点列表中显示的节点地址重写为另一个地址。
这个参数在trojan的类型下没有生效，配置该参数后，面板依旧显示了原始的地址。
我想这个问题应该不涉及后端的处理吧

**Comment by ldsj007** [comment]
遇到同样的疑问

**Comment by iamsaltedfish** [comment]
![69BD79F3-33F1-4247-9A3C-488388E40094](https://user-images.githubusercontent.com/90859800/145350591-bfdf46bd-ac2f-4de9-85f0-0b6012e30c8d.jpeg)
建议来个人整理一下语言，将怎么填，节点列表会怎么显示，客户端会怎么显示，以及期望怎么显示说清楚

**Comment by Anankke** [comment]
建议来个人整理一下语言，将怎么填，节点列表会怎么显示，客户端会怎么显示，以及期望怎么显示说清楚

**Comment by aipeach** [comment]
> 建议来个人整理一下语言，将怎么填，节点列表会怎么显示，客户端会怎么显示，以及期望怎么显示说清楚

我看了下，他们想说的是，像上版的SSR重写节点地址和端口那样吧。
![image](https://user-images.githubusercontent.com/44671411/145371185-1ba8b2fb-885a-4572-98e2-397dfa88b577.png)

```
8.8.8.8;server=in.nodeserver.com|port=80#10080
````
8.8.8.8为落地IP，80为后端节点端口，in.nodeserver.com是用户订阅出来的节点地址，10080是用户订阅出来偏移后的端口。

**Comment by ctrlbbj** [comment]
> > 建议来个人整理一下语言，将怎么填，节点列表会怎么显示，客户端会怎么显示，以及期望怎么显示说清楚
> 
> 我看了下，他们想说的是，像上版的SSR重写节点地址和端口那样吧。 ![image](https://user-images.githubusercontent.com/44671411/145371185-1ba8b2fb-885a-4572-98e2-397dfa88b577.png)
> 
> ```
> 8.8.8.8;server=in.nodeserver.com|port=80#10080
> ```
> 
> 8.8.8.8为落地IP，80为后端节点端口，in.nodeserver.com是用户订阅出来的节点地址，10080是用户订阅出来偏移后的端口。

是这样的，Trojan配置中转重写的行为和V2ray不一致，期望是改成一致就好了
