### ISSUE TITLE
[BUG]删除用户报错 [object Object] 发生了错误；

### ISSUE THREAD

**Issue by Lin-UN** [Anankke/SSPanel-Uim#1222]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息

centos7 php 7.4 mysql5.7

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

14315cd

**Bug**
The bug information. 请描述你遇到的 Bug。

删除用户报错：[object Object] 发生了错误。

F12  看到有个js挂了，不知是否是这个影响；

https://cdn.jsdelivr.net/npm/perfops-rom

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

删除用户即会；

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

<img width="1605" alt="111" src="https://user-images.githubusercontent.com/65696488/111835635-29f09400-8930-11eb-812b-c13c555e3044.png">

**Comment by M1Screw** [comment]
perfops-rom 那個是負責遙測數據收集的，就算沒法加載也不會影響使用的。報錯顯示的是後端500，這個問題你需要開面板debug和php錯誤顯示才能看到具體原因。

**Comment by Colinwood11** [comment]
@M1Screw 但是实际上开了debug也是返回的500  无任何可用输出   当时随机生成114514个用户的时候用过这个删除，发现没法删  反正我也不是做机场的   就没管了    感觉可能只是哪里超时吧

**Comment by Lin-UN** [comment]
> @M1Screw 但是实际上开了debug也是返回的500  无任何可用输出   当时随机生成114514个用户的时候用过这个删除，发现没法删  反正我也不是做机场的   就没管了    感觉可能只是哪里超时吧

是的，开了debug没有输出错误，有点迷失方向了0.0

**Comment by Lemonfun** [comment]
![屏幕截图 2021-04-04 135634](https://user-images.githubusercontent.com/69041250/113500037-9af99380-954d-11eb-93c3-d6d7e872f29e.png)

**Comment by M1Screw** [comment]
這個是上次 telegram_tasks 功能去掉之後的遺留問題。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/1f2528038b1db1364137e2ad78cfa549d34313f8
