### ISSUE TITLE
[BUG] 最新版dve机器人问题。

### ISSUE THREAD

**Issue by JarvanDing** [Anankke/SSPanel-Uim#1226]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
PHP7.4/MYSQL5.6  / centos7.9   宝塔

**Commit**
最新版 dev

**Bug**
用最新版dev 构建，tg机器人（新版）无法使用，群组不回话，私聊不回答。以前的回复是可以操作的
每分钟定时有报错，下面截图。
2个月前尝试升级同样错误，只好回滚。今天又升级，该错误依然存在，不知道是不是本来是这个bug，

希望我不是一个人。

**Logs**

![photo_2021-04-04_15-15-49](https://user-images.githubusercontent.com/31558141/113501591-e4031500-9558-11eb-8a6e-f0fbbf81ed4d.jpg)

**Comment by TheCGDF** [comment]
@JarvanDing 牛逼，不耻下问

**Comment by JarvanDing** [comment]
> @JarvanDing 牛逼，不耻下问

酝酿了几个月的勇气。。

**Comment by M1Screw** [comment]
@JarvanDing 終於有人問啦，太高興了。趕緊多點人試試新bot到底是什麼情況出錯，進行了什麼操作出錯。我目前的推測是上次更新完數據庫連接件然後更新composer依賴的時候把某些東西弄糊了，但是bot這東西不像前端糊了那麼容易解決，新版bot的輪子也不是我造的。所以還是有這個問題的機場都出來說說怎麼糊的，什麼時候糊的。

**Comment by ximliu** [comment]
机器人的确有问题 启用新机器人后tg机器人没有反应，关闭新机器人可以使用原版本机器人

**Comment by regendsoh** [comment]
@M1Screw 报错和你这个commit有关，至于能不能解决问题，等 @JarvanDing  反馈
https://github.com/Anankke/SSPanel-Uim/commit/bda350876c32215c3bbcf273ec57bed1aa0e5ea1#diff-b511c4f1ce0db7fbb3a9bad4d8e61722fb406d346038c684e4adc25d16c417d8

**Comment by JarvanDing** [comment]
> @M1Screw 报错和你这个commit有关，至于能不能解决问题，等 @JarvanDing 反馈
> [bda3508#diff-b511c4f1ce0db7fbb3a9bad4d8e61722fb406d346038c684e4adc25d16c417d8](https://github.com/Anankke/SSPanel-Uim/commit/bda350876c32215c3bbcf273ec57bed1aa0e5ea1#diff-b511c4f1ce0db7fbb3a9bad4d8e61722fb406d346038c684e4adc25d16c417d8)

我添加了删除的代码后，依然没有反应。新的报错
PHP Fatal error:  Uncaught Error: Class 'App\Models\TelegramTasks' not found in /www/wwwroot/xxxxxx/src/Command/Job.php:770
Stack trace:
#0 /www/wwwroot/xxxxxx/src/Command/Job.php(736): App\Command\Job->Telegram()
#1 /www/wwwroot/xxxxxx/src/Command/Job.php(52): App\Command\Job->CheckJob()
#2 /www/wwwroot/xxxxxx/xcat(51): App\Command\Job->boot()
#3 {main}
  thrown in /www/wwwroot/xxxxxx/src/Command/Job.php on line 770

Fatal error: Uncaught Error: Class 'App\Models\TelegramTasks' not found in /www/wwwroot/xxxxxx/src/Command/Job.php:770
Stack trace:
#0 /www/wwwroot/xxxxxx/src/Command/Job.php(736): App\Command\Job->Telegram()
#1 /www/wwwroot/xxxxxx/src/Command/Job.php(52): App\Command\Job->CheckJob()
#2 /www/wwwroot/xxxxxx/xcat(51): App\Command\Job->boot()
#3 {main}
  thrown in /www/wwwroot/xxxxxx/src/Command/Job.php on line 770

**Comment by regendsoh** [comment]
TelegramTasks
https://github.com/Anankke/SSPanel-Uim/commit/8047194935115fafdfcbab0b62ee7e4e3bf535f8

**Comment by regendsoh** [comment]
TelegramTasks.php
https://pastebin.com/ZH7uvAZX

**Comment by JarvanDing** [comment]
> TelegramTasks.php
> https://pastebin.com/ZH7uvAZX

每分钟定时任务的报错没有了，。  但是机器人依然不可用

**Comment by Sakitami** [comment]
> > TelegramTasks.php
> > https://pastebin.com/ZH7uvAZX
> 
> 每分钟定时任务的报错没有了，。 但是机器人依然不可用

是这样的，我也将代码添回，并且添加了Telegram task表，添加了TelegramTask.php，没有报错但不可用。

**Comment by ximliu** [comment]
我是拉取最新代码 只是显示我新机器人添加成功，但实际依然不可用，没有报错

**Comment by M1Screw** [comment]
@regendsoh 1. 這個功能壓根就沒做全，我自己實測下來也是殘廢的，跟bot沒有任何關係。有問題的功能外加無人維護，徹底移除沒有任何問題。
2. Bot的問題早在這個commit之前就出現了。

**Comment by M1Screw** [comment]
@regendsoh 以及一個明明是應該分類在 Tool 裏面的清理機器人消息的功能，爲什麽要做進 Job？外加文檔裏面也沒有任何説明， Job.php 的 description 裏面也沒有，這個功能到底是寫完還是沒寫完？甚至還加了一個數據表來存消息數據，那爲什麽不直接對著機器人消息 Delete All 來得方便快速？

**Comment by M1Screw** [comment]
@regendsoh Telegram Tasks 本身是跟那個 Bot 消息的自動刪除有關係，但是你把所有 Bot 產生消息都丟數據庫裏面處理顯然是不合適的，同時在某些設置下會產生大量的無用記錄。一開始刪掉的 Job 裏面那個功能確實是沒有做完的，Bot 消息自動移除那塊到底要徹底移除還是重寫先放一放，我現在測試下來老版本的 Bot 是沒有問題的，新版本的 Bot 無論如何都是不回復消息，而且在 Telegram Tasks 移除之前就已經出現這樣的情況了。

**Comment by M1Screw** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/1f2528038b1db1364137e2ad78cfa549d34313f8 這個裏面我已經徹底把 Telegram Tasks 相關的東西全部拆掉了，事實證明新版 Bot 還是有問題，需要進一步 debug 和更多信息。

**Comment by Fcatme** [comment]
把配置文件 $_ENV['use_new_telegram_bot'] = true;   true值改为false  即可

**Comment by cyanogenic** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/ae89ed76d30c0f7833af8769094f1b7232404e12
这个commit升级了illuminate/database到6.x，回滚到5.2.x以后新机器人恢复正常了

**Comment by JarvanDing** [comment]
> [ae89ed7](https://github.com/Anankke/SSPanel-Uim/commit/ae89ed76d30c0f7833af8769094f1b7232404e12)
> 这个commit升级了illuminate/database到6.x，回滚到5.2.x以后新机器人恢复正常了

请问 我直接吧 composer.json 里面的 illuminate/database 改为5.2.x  然后升级 composer 就可以了吗？

**Comment by cyanogenic** [comment]
> > [ae89ed7](https://github.com/Anankke/SSPanel-Uim/commit/ae89ed76d30c0f7833af8769094f1b7232404e12)
> > 这个commit升级了illuminate/database到6.x，回滚到5.2.x以后新机器人恢复正常了
> 
> 请问 我直接吧 composer.json 里面的 illuminate/database 改为5.2.x 然后升级 composer 就可以了吗？

是的，但是我没有详细测试这样对面板的其它功能有什么影响
