### ISSUE TITLE
希望增加一个开心码支付接口

### ISSUE THREAD

**Issue by heitu001** [Anankke/SSPanel-Uim#1227]
希望增加一个开心码支付接口
现有的接口感觉都不是很好用了~码支付也跑了
http://www.kxz6.cn/user/duijie.php

**Comment by TheCGDF** [comment]
@heitu001 连个https都没有的屑支付有什么对接的必要么。。。

**Comment by Scholar-m** [comment]
@heitu001 我觉得你完全可以自己尝试对接这种迷惑支付

**Comment by heitu001** [comment]
@Scholar-m 其实我也想自己尝试可惜能力有限~完全不会~大大们可以帮我单独写个对接吗！⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

**Comment by Xavier-0619** [comment]
@heitu001 加钱
