### ISSUE TITLE
[BUG]主页的主题不能设置吗？

### ISSUE THREAD

**Issue by maxwellhouse102** [Anankke/SSPanel-Uim#1229]
发现打开主页时两种主题会随机显示，这个不能设置固定显示某一主题吗？

**Comment by Xavier-0619** [comment]
亲亲，这边不建议您开机场，建议您回老家喂猪

**Comment by Xavier-0619** [comment]
vue功能早就已经砍掉了，你发issues的时候不确认commit，不贴log不如直接在群里付费50u解决

给你提供个解决思路 1.update 2.$_ENV['newIndex'] = false
