### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ovenone** [Anankke/SSPanel-Uim#1233]
搭建好以后注册页面出现如图所示的情况
![image](https://user-images.githubusercontent.com/6820936/115752732-f8eefd80-a3cc-11eb-8111-f82be3e75d46.png)

**Comment by wry666999888** [comment]
我的也一样

**Comment by ovenone** [comment]
> 我的也一样
问题可以在config中  关闭im记录     
但问题好像在ui中   抓包发现post没有发送有关联络方式的字段

**Comment by M1Screw** [comment]
建議用最新dev版再次嘗試，看起來是js代碼沒有被正確地加載出來的問題。

**Comment by ovenone** [comment]
后面找到解决方法了     在配置关闭im记录

**Comment by M1Screw** [comment]
@ovenone 我的意思是你可以嘗試重新把IM記錄那個選項打開看看還會不會報錯了

**Comment by M1Screw** [comment]
@ovenone 然後記得面板要更新到最新的

**Comment by ovenone** [comment]
> @ovenone然后记得面板要更新到最新的



> @ovenone我的意思是你可以尝试重新把IM记录那个选项打开看看将会不会报错了

现在没用它了  占时没搞了
