### ISSUE TITLE
[BUG]ss使用新加密方式无法拷贝出节点URL（连接）

### ISSUE THREAD

**Issue by maker2002** [Anankke/SSPanel-Uim#1249]
又发现个bug，使用单端口无法拷贝出节点连接（拷贝出2个换行符）
![Snipaste_2021-05-13_22-55-05](https://user-images.githubusercontent.com/77610980/118143894-6925f780-b43e-11eb-8f9d-014c9cde4f86.jpg)

**Comment by maker2002** [comment]
看了下问题应该出在这次更新这里：https://github.com/Anankke/SSPanel-Uim/commit/ca40dc0e490defb2f122055fef78ae9ba48ffe69#diff-af6839f0efa69e4e6498240b145bab75e44104fefff8b7fb083a5ac9643675f1

![photo_2021-05-13_23-40-02](https://user-images.githubusercontent.com/77610980/118253957-1e0ef180-b4dd-11eb-8144-bb935201573d.jpg)

**Comment by maker2002** [comment]
经过几天的摸索，终于发现问题不在单端口多用户上，而是出在 加密方式 上，如果选用新的5种AEAD Ciphers加密方式(x/chacha20-ieft-poly1305, aes-128/192/256-gcm)则无法拷贝出节点连接，使用过时的stream ciphers加密方式，则可以拷贝。
复现方法：
1.随便创建shadowsocks节点，无论是否使用单端口多用户。
2.用户加密方式选用AEAD Ciphers(x/chacha20-ieft-poly1305, aes-128/192/256-gcm)
3.到用户中心拷贝shadowsocks全部节点URL

简单的说：
AEAD Ciphers-->无法拷贝全部节点URL（功能异常BUG）
stream ciphers-->正常拷贝

另外，建议删除stream ciphers的加密支持，现在新版客户端已经不再支持。
@GeekQuerxy

**Comment by M1Screw** [comment]
F12看看請求有沒有報錯

**Comment by maker2002** [comment]
> F12看看請求有沒有報錯

没有，console中没有明显有关报错。
