### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tongfei11** [Anankke/SSPanel-Uim#1250]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Debian 10, PHP 7.4.18, MySQL 8.0.23.14

**Commit**
dev 4bfcb1e7a26b9487b6aa9c6a4859ac2fb11c5f33

**Bug**
用户中心报错500，管理后台的用户列表报DataTables warning: table id=table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Reproduce**
git更新到最新版本后就这样了，然后重新安装了sspanel一次还是如此

**Expected behavior**
用户中心正常可访问

**Logs**
Slim Application Error
The application could not run because of the following error:

Details
Type: Illuminate\Database\QueryException
Code: 42000
Message: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sspanel.alive_ip.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select * from `alive_ip` where `datetime` >= 1620922775 and `userid` = 1 group by `ip` order by `userid` desc)
File: /var/www/sspanel/vendor/illuminate/database/Connection.php
Line: 669
Trace
#0 /var/www/sspanel/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/sspanel/vendor/illuminate/database/Connection.php(338): Illuminate\Database\Connection->run()
#2 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2159): Illuminate\Database\Connection->select()
#3 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2147): Illuminate\Database\Query\Builder->runSelect()
#4 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2619): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2148): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /var/www/sspanel/vendor/illuminate/database/Eloquent/Builder.php(546): Illuminate\Database\Query\Builder->get()
#7 /var/www/sspanel/vendor/illuminate/database/Eloquent/Builder.php(530): Illuminate\Database\Eloquent\Builder->getModels()
#8 /var/www/sspanel/src/Models/User.php(402): Illuminate\Database\Eloquent\Builder->get()
#9 /var/www/sspanel/storage/framework/smarty/compile/6e6541dbeb24d86b1f139dc362e50bde044f5ca1_0.file.index.tpl.php(139): App\Models\User->online_ip_count()
#10 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_609d476c151b49_19586730()
#11 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#12 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#13 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#14 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#15 /var/www/sspanel/src/Controllers/UserController.php(97): Smarty_Internal_TemplateBase->display()
#16 [internal function]: App\Controllers\UserController->index()
#17 /var/www/sspanel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#18 /var/www/sspanel/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#19 /var/www/sspanel/src/Middleware/Auth.php(26): Slim\Route->__invoke()
#20 [internal function]: App\Middleware\Auth->__invoke()
#21 /var/www/sspanel/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#22 [internal function]: Slim\DeferredCallable->__invoke()
#23 /var/www/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#24 /var/www/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}()
#25 /var/www/sspanel/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#26 /var/www/sspanel/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#27 /var/www/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke()
#28 /var/www/sspanel/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#29 /var/www/sspanel/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#30 /var/www/sspanel/public/index.php(37): Slim\App->run()
#31 {main}
Previous exception
Type: PDOException
Code: 42000
Message: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sspanel.alive_ip.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
File: /var/www/sspanel/vendor/illuminate/database/Connection.php
Line: 331
Trace
#0 /var/www/sspanel/vendor/illuminate/database/Connection.php(331): PDO->prepare()
#1 /var/www/sspanel/vendor/illuminate/database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /var/www/sspanel/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#3 /var/www/sspanel/vendor/illuminate/database/Connection.php(338): Illuminate\Database\Connection->run()
#4 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2159): Illuminate\Database\Connection->select()
#5 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2147): Illuminate\Database\Query\Builder->runSelect()
#6 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2619): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /var/www/sspanel/vendor/illuminate/database/Query/Builder.php(2148): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /var/www/sspanel/vendor/illuminate/database/Eloquent/Builder.php(546): Illuminate\Database\Query\Builder->get()
#9 /var/www/sspanel/vendor/illuminate/database/Eloquent/Builder.php(530): Illuminate\Database\Eloquent\Builder->getModels()
#10 /var/www/sspanel/src/Models/User.php(402): Illuminate\Database\Eloquent\Builder->get()
#11 /var/www/sspanel/storage/framework/smarty/compile/6e6541dbeb24d86b1f139dc362e50bde044f5ca1_0.file.index.tpl.php(139): App\Models\User->online_ip_count()
#12 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_609d476c151b49_19586730()
#13 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#14 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#15 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#16 /var/www/sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#17 /var/www/sspanel/src/Controllers/UserController.php(97): Smarty_Internal_TemplateBase->display()
#18 [internal function]: App\Controllers\UserController->index()
#19 /var/www/sspanel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#20 /var/www/sspanel/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#21 /var/www/sspanel/src/Middleware/Auth.php(26): Slim\Route->__invoke()
#22 [internal function]: App\Middleware\Auth->__invoke()
#23 /var/www/sspanel/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#24 [internal function]: Slim\DeferredCallable->__invoke()
#25 /var/www/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#26 /var/www/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}()
#27 /var/www/sspanel/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#28 /var/www/sspanel/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#29 /var/www/sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke()
#30 /var/www/sspanel/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#31 /var/www/sspanel/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#32 /var/www/sspanel/public/index.php(37): Slim\App->run()
#33 {main}

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by M1Screw** [comment]
https://github.com/Anankke/SSPanel-Uim/issues/1200

**Comment by tongfei11** [comment]
用下面这条解决了

In Ubuntu

Step 1:

sudo vi /etc/mysql/mysql.conf.d/mysqld.cnf
Step 2: Go to last line and add the following

sql_mode = ""
Step 3: Save

Step 4: Restart mysql server.

**Comment by zcvxcv** [comment]
> 用下面这条解决了
> 
> In Ubuntu
> 
> Step 1:
> 
> sudo vi /etc/mysql/mysql.conf.d/mysqld.cnf Step 2: Go to last line and add the following
> 
> sql_mode = "" Step 3: Save
> 
> Step 4: Restart mysql server.

有用！
