### ISSUE TITLE
[BUG] 订阅链接报500 debug后报有语法错误 有大佬给点意见吗

### ISSUE THREAD

**Issue by cdlaimin** [Anankke/SSPanel-Uim#1257]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [ x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x ] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP版本:7.4
MySql版本:5.7
composer版本:1.10.22
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
2021.5.18 6fefb80

**Bug**
The bug information. 请描述你遇到的 Bug。
未打开debug模式订阅链接在网页中打开报500错误
打开debug模式,网页中有语法错误

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
升级版本后出现,切换回老版本没问题
**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
Slim Application Error
The application could not run because of the following error:

Details
Type: ParseError
Message: syntax error, unexpected ','
File: /www/wwwroot/www.baidu.com/src/Utils/AppURI.php
Line: 107
Trace
#0 /www/wwwroot/www.baidu.com/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /www/wwwroot/www.baidu.com/src/Controllers/LinkController.php(476): spl_autoload_call()
#3 /www/wwwroot/www.baidu.com/src/Controllers/LinkController.php(599): App\Controllers\LinkController::getListItem()
#4 /www/wwwroot/www.baidu.com/src/Controllers/LinkController.php(822): App\Controllers\LinkController::getListExtend()
#5 /www/wwwroot/www.baidu.com/src/Controllers/LinkController.php(175): App\Controllers\LinkController::getSub()
#6 [internal function]: App\Controllers\LinkController::GetContent()
#7 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#8 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#9 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke()
#10 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#11 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#12 /www/wwwroot/www.baidu.com/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke()
#13 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke()
#14 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#15 [internal function]: Slim\DeferredCallable->__invoke()
#16 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#17 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#18 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#19 /www/wwwroot/www.baidu.com/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#20 /www/wwwroot/www.baidu.com/public/index.php(37): Slim\App->run()
#21 {main}
**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by M1Screw** [comment]
fixed in https://github.com/Anankke/SSPanel-Uim/commit/d60ce45c889b1ca1730b587e2ba86d1d55870299
