### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OPPO9008** [Anankke/SSPanel-Uim#1260]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
php7.4 mysql8.0 
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
d60ce45c889b1ca1730b587e2ba86d1d55870299
**Bug**
The bug information. 请描述你遇到的 Bug。
无法更新订阅
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
git pull 到最新commit
**Expected behavior**
What you expected to happen. 请描述你预期的行为。
正常获取订阅内容
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

error] 3520#3520: *668608 FastCGI sent in stderr: "PHP message: PHP N
otice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.php on line 71PHP messag
e: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.php on line 71PH
P message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.php on l
ine 71PHP message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.
php on line 71PHP message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils
/AppURI.php on line 71PHP message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/s
rc/Utils/AppURI.php on line 71PHP message: PHP Notice:  Undefined index: sni in /var/www/
敏感内容/src/Utils/AppURI.php on line 71PHP message: PHP Notice:  Undefined index: sni in /v
ar/www/敏感内容/src/Utils/AppURI.php on line 71PHP message: PHP Notice:  Undefined index: s
ni in /var/www/敏感内容/src/Utils/AppURI.php on line 71PHP message: PHP Notice:  Undefined
index: sni in /var/www/敏感内容/src/Utils/AppURI.php on line 71PHP message: PHP Notice:  Un
defined index: sni in /var/www/敏感内容/src/Utils/AppURI.php on line 71PHP message: PHP Not
ice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.php on line 71PHP message:
 PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.php on line 71PHP
message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.php on lin
e 71PHP message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils/AppURI.ph
p on line 71PHP message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src/Utils/A
ppURI.php on line 71PHP message: PHP Notice:  Undefined index: sni in /var/www/敏感内容/src
/Utils/AppURI.php on line 71" while reading response header from upstream, client: 13.70.3
6.19, server: 敏感内容, request: "GET //link/敏感内容?sub=3 HTTP/1.1", upstream
: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "敏感内容"

**Addition**
Additional context here. 如有可能，请提供更多相关资料。
审计记录也500了

**Comment by Jia-wen** [comment]
新版本 数据库结构改动很大，你的数据库没有更新。

**Comment by OPPO9008** [comment]
ALTER TABLE ss_node CHANGE server server VARCHAR(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;
请问是需要执行这个吗

**Comment by OPPO9008** [comment]
> 新版本 数据库结构改动很大，你的数据库没有更新。

但是我git checkout 
到这个commit 问题解决了
99264840208eac3a116e23881f91ebcf5515d631

**Comment by M1Screw** [comment]
你把 PHP debug 關了
