### ISSUE TITLE
[BUG]关于使用AEAD Ciphers加密方式无法拷贝出全部ss节点连接的再提

### ISSUE THREAD

**Issue by maker2002** [Anankke/SSPanel-Uim#1261]
之前提过 https://github.com/Anankke/SSPanel-Uim/issues/1249
在t群里大猫猫说无法复现，因为我觉得@的方式回复能更有效的沟通，而后私聊他能否付费帮忙解决bug，但不知道戳到了他什么点，被大猫猫拉黑了，而后他关闭了我提的issue。在此对大猫猫造成的不便表示歉意。

但我又是个特别较真的人，为了排除环境带来的影响，今天在一台全新的centos8服务器安装了oneinstack的最新版，顺手PR了一些wiki指南中不完整的地方 https://github.com/sspanel-uim/Wiki/pull/29/commits/9f54c327ad33b06c6e8d8eba3a3654afb11d4d57

问题同样复现：
1.创建默认参数shadowsocks节点。
2.用户加密方式选用AEAD Ciphers(x/chacha20-ieft-poly1305, aes-128/192/256-gcm)的任意一种。
3.到用户中心拷贝shadowsocks全部节点URL。（无法拷贝出连接）

![Snipaste_2021-05-13_22-55-05](https://user-images.githubusercontent.com/77610980/118143894-6925f780-b43e-11eb-8f9d-014c9cde4f86.jpg)

**Comment by HynoR** [comment]
@maker2002 SS混淆单端和密码单端在sspanel里是个半头子功能，生成单连接这块没人填坑。你要想用上自己在里面改。自己动手丰衣足食。
https://github.com/Anankke/SSPanel-Uim/blob/dev/src/Utils/URL.php
