### ISSUE TITLE
[Feature Request]关于支持NaïveProxy的建议

### ISSUE THREAD

**Issue by Kia678** [Anankke/SSPanel-Uim#1263]
能否考虑支持NaïveProxy？此项目能很好的应对当前的tls指纹探测以及主动探测。目前支持NaïveProxy的客户端已有：SagerNet(Android)、Shadowrocket(iOS)以及Qv2ray(Win/macOS/Linux)，可见NaïveProxy在客户端生态方面已经较为完善，另外，NaïveProxy作者对于项目的更新维护也十分积极，希望考虑一下支持NaïveProxy，谢谢！

**Comment by NutterChen** [comment]
@Kia678 1.请先克隆项目编写相关代码  2.在确保你会对此做长期支持后请提交pull requests到项目，会考虑

**Comment by M1Screw** [comment]
客戶端支持得再多也沒有用，服務端的各大付費後端不跟進你讓機場全部手搓服務端嗎
