### ISSUE TITLE
[BUG] Webapi获取alive_ip导致数据库CPU占用过高

### ISSUE THREAD

**Issue by RManLuo** [Anankke/SSPanel-Uim#1264]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
PHP 7.2
MySQL 8.0 1C2G

**Commit**
c13847f6773ab9e20b9e2e917cfc9eb4fc811e02

**Bug**
在当前版本中通过webapi获取信息时会通过`(new \App\Models\Ip)->getUserAliveIpCount($user_raw->id)`获取每个用户最近1分钟内的在线ip，此操作有可能导致数据库占用过高。

检查发现，在数据库执行过程中会产生如下查询语句。
```
SELECT count(*) from alive_ip where userid = ? and datetime >= ?
```
正常逻辑应该为
```
SELECT count(*) from alive_ip where userid = $userid and datetime >=  time() - 60
```
怀疑是此函数输入的参数$userid有非数字情况，从而导致要枚举所有alive_ip表项

**Reproduce**
更新到c13847f6773ab9e20b9e2e917cfc9eb4fc811e02，设置用户设备限制为非0值。

**Expected behavior**
只获取正确输入的userid

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by M1Screw** [comment]
https://github.com/Anankke/SSPanel-Uim/blob/89dc533e5f9a4bfe4851c3bf37ecf5195ea89663/src/Models/Ip.php#L84-L87
實際上這個方法的實現跟你說的是一樣的，這個只是作爲部分老套餐的兼容性解決方案，實際要起作用需要節點的服務端配合，API和數據庫的性能損耗是在預料之中的，我們還是推薦不使用套餐連接數限制以避免這個問題。

**Comment by RManLuo** [comment]
用户alive_ip字段是在 1e95559f2516e55312d660747489df1e380cdd16 中引入的，在之前的老版本中似乎不需要提供alive_ip这一字段，而是只需node_connector字段的用户设备限制数量，如果为了兼容是否只需保留node_connector字段。

并且，由于alive_ip只是提供了用户在线ip的数量，而不是提供用户具体的在线ip，此字段可能无法帮助后端判断是否某一建立连接的ip是属于当前在线ip还是属于一个新建立连接的ip，从而决定是否阻断该ip的连接。

**Comment by M1Screw** [comment]
在 node_connector 數值為0的時候是不會統計每個用戶的 alive_ip 的。按照面板的統計方式，兩個設備從同一個IP發起鏈接就會產生一模一樣的兩個在綫IP，因此這個參數是用來做全局在綫設備限制的，你説的方式只能實現 per node 的限制，顯然是不合理的。至於爲什麽不下發完整在綫 IP 列表，這個主要是考慮API的流量消耗問題。

**Comment by du5** [comment]
Fixed.  https://github.com/Anankke/SSPanel-Uim/compare/c9721cdc...Anankke:dev
