### ISSUE TITLE
[BUG]最新dev设置DailyJob出现错误无法重置

### ISSUE THREAD

**Issue by jay-xie-p** [Anankke/SSPanel-Uim#1269]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
centos8,PHP 7.4
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
6dae8b3dce0170fce1b2d6cc542503c8185b74f1
**Bug**
The bug information. 请描述你遇到的 Bug。
php xcat Job DailyJob 出现错误
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
最新dev设置DailyJob出现错误无法重置
**Expected behavior**
What you expected to happen. 请描述你预期的行为。
希望修复，。
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
rm: cannot remove '/www/wwwroot/xxxxx/app/../storage/*.png': No such file or directory
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION xxxxx.json_unquote does not exist in /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php:331
Stack trace:
#0 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(331): PDO->prepare()
#1 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(338): Illuminate\Database\Connection->run()
#4 /www/wwwroot/xxxxx/vendor/illuminate/database/Query/Builder.php(2159): Illuminate\Database\Connection->select()
#5 /www/wwwroot/xxxxx/vendor/illuminate/database/Query/Builder.php(2311): Illuminate\Database\Query\Builder->runSelect()
#6 /www/wwwroot/xxxxx/vendor/illuminate/database/Query/Builder.php(2619): Illuminate\Database\Qu in /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php on line 669

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION xxxxx.json_unquote does not exist in /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php:331
Stack trace:
#0 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(331): PDO->prepare()
#1 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(662): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php(338): Illuminate\Database\Connection->run()
#4 /www/wwwroot/xxxxx/vendor/illuminate/database/Query/Builder.php(2159): Illuminate\Database\Connection->select()
#5 /www/wwwroot/xxxxx/vendor/illuminate/database/Query/Builder.php(2311): Illuminate\Database\Query\Builder->runSelect()
#6 /www/wwwroot/xxxxx/vendor/illuminate/database/Query/Builder.php(2619): Illuminate\Database\Qu in /www/wwwroot/xxxxx/vendor/illuminate/database/Connection.php on line 669
**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by blakelu** [comment]
升级你的mysql，mysql5.7以下不支持json格式数据处理
