### ISSUE TITLE
求问，最近到期邮件会一直重复发

### ISSUE THREAD

**Issue by JusufUs** [Anankke/SSPanel-Uim#1281]
每一个用户到期都会重复发很多封，并且都是同一个内容，都是到期提醒。
定时任务看上去正常 30 22 * * * php /www/wwwroot/xxxxx/xcat sendDiaryMail
最近半个月出现的，不知道是哪里的问题，请大哥们告知。

![132.jpg](https://i.loli.net/2021/07/11/C2ES4zVWqkR3hfd.jpg)

**Comment by TheCGDF** [comment]
@JusufUs 用户太多了导致checkjob无法在1分钟内执行完，导致多个checkjob会同时并行，老问题了

**Comment by JusufUs** [comment]
@TheCGDF 这就难受了，有啥解决办法不

**Comment by du5** [comment]
1. 更新版本
1. 开启列队

https://github.com/Anankke/SSPanel-Uim/blob/4a5199f317c651196ed55105425259eac1529dcd/config/.config.example.php#L39-L42
