### ISSUE TITLE
[BUG] Can't import glzjin_all.sql

### ISSUE THREAD

**Issue by onlyJinx** [Anankke/SSPanel-Uim#1282]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
CentOS7
php version 7.4
MariaDB Server 5.5.68
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
The bug information. 请描述你遇到的 Bug。

Hello,

按照[文档](https://wiki.sspanel.host/?__cf_chl_managed_tk__=f5cd16e0f441a3db203cd265deceb36a85ba5bcf-1625990508-0-AU6B2ijGHQKRPXjZ3LpvHGLXWe-4Wp_FU0MFDfu3oN7nsEoypHw6IhfR2fOVSUDseBVLJnFxt-zUfMQJDU41WleYdJoXuAzmSeeDVxk6Y_s4QTIbm0_Nghz7CgzWONBV2BdLOUAwDrPUpUPuPEuD3rlakPv_wsDYyJdJzaWf2rDSqoY0g_GYwM46qcgndEVsTWaXNag8p7GqdcSsFADEl6KGgKMAlVFlb9Q8lMPBDpWMCz3_knPWa9qooH6hHGlt20emS7OT6ZskKQ-p0oV0DDeI-BnBCM-trl7H4xN2BVSrFHTEnOt-PI8vGZ9tfEg4fvdphDBzYT4ZXBAvoxMaF26Y28YLCU6HxOgXMSkrn-dHcPbwduryWR0jgznRBUXI1uaTpnWt7EGlqj3Q0D024EgI_6wm9f6DRFgccDayghLjzr2rCCzlCEipVb9KKBA5htap5t_2m_uTgeWSUMINLL87obu2zxSp_oJq92nn_UlM0pfHX5mm3QYeesTKLjKZ819sB6ZXW1SvvNYJCUkr19E4SEwcs9Z3B5LDVjft60_aYauXpJKnNpNk5_bo9gCFQ7LzyEdVnQuG08xWM3UIyDYyYG0pYiJuLFvJMDiXHZtYjor3f7bxnLJpU0sSN_7LL6FCQ6a4f8uNBLo_Vb5GLrYGNtuBgfnBfhj5ZPhJ3rdI#/install-using-rpm) ，使用下面的命令导入glzjin_all.sql时出现报错，请问是什么原因，或者提示一下，我自己去Google搜索，谢谢啦

MariaDB [sspanel]> SOURCE /usr/local/nginx/html/sql/glzjin_all.sql;
Query OK, 0 rows affected (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

ERROR 1067 (42000) at line 5 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Invalid default value for 'reg_date'
Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1005 (HY000) at line 156 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.detect_ban_log' (errno: 150)
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1005 (HY000) at line 182 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.detect_log' (errno: 150)
Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1005 (HY000) at line 236 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.link' (errno: 150)
ERROR 1005 (HY000) at line 247 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.login_ip' (errno: 150)
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1005 (HY000) at line 270 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.paylist' (errno: 150)
Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1005 (HY000) at line 295 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.ss_invite_code' (errno: 150)
Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

Query OK, 0 rows affected, 1 warning (0.00 sec)

ERROR 1005 (HY000) at line 372 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.user_hourly_usage' (errno: 150)
ERROR 1005 (HY000) at line 384 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.user_subscribe_log' (errno: 150)
ERROR 1005 (HY000) at line 399 in file: '/usr/local/nginx/html/sql/glzjin_all.sql': Can't create table 'sspanel.user_token' (errno: 150)

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by M1Screw** [comment]
你的MariaDB已經是EOL的版本，推薦是用官方的rpm/deb源安裝最新版
