### ISSUE TITLE
[BUG]网站打开大概率黑屏，在主页可打开的情况下，点击登录报404

### ISSUE THREAD

**Issue by Charlie894** [Anankke/SSPanel-Uim#1289]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
CentOS7.6 php7.4 Nginx1.20.1
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
https://github.com/Anankke/SSPanel-Uim
**Bug**
The bug information. 请描述你遇到的 Bug。
刚搭建的网站打开大概率黑屏，就算加载出来了，点击登录也直接跳转，然后报404
具体可以看我的录屏：

https://user-images.githubusercontent.com/63108760/126150801-bddcba62-8a30-4b91-9d6e-5ef4baf87783.mp4

**Reproduce**
访问http://91.216.169.67

**Expected behavior**
显示黑板或点击登录后报404

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by sigle0724** [comment]
怕不是没加伪静态

**Comment by Charlie894** [comment]
加不了，报错

**Comment by Charlie894** [comment]
你们的Wiki访问不了啊啊啊

**Comment by Charlie894** [comment]
不过这也是不错的啦
至少还有个正在更新的程序

**Comment by Charlie894** [comment]
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
</IfModule>

**Comment by Charlie894** [comment]
这个试过，加完报ERROR:
nginx: [emerg] unknown directive "nginx: configuration file /www/server/nginx/conf/nginx.conf test failed

**Comment by qinghuas** [comment]
```
		location / 
		{
			try_files $uri $uri/ /index.php$is_args$args;		                
		}
```
你刚才发的是apache的规则

**Comment by Charlie894** [comment]
阿这

**Comment by Charlie894** [comment]
https://www.tenlonstudio.com/5233.html
请不要按照这篇教程建站坑太多

**Comment by Charlie894** [comment]
可是弄完之后还是黑板

**Comment by Charlie894** [comment]
会闪一下界面，然后就黑板

**Comment by M1Screw** [comment]
這個主頁還是拿掉吧，以後訪問面板根域名會直接跳轉登錄界面，避免版權問題的同時還能減少分發的程序體積。至於首頁的實現還是交給機場主自己使用商業html模板製作或者是購買帶主頁設計的商業SSP主題比較合適。

**Comment by Charlie894** [comment]
现在好了

**Comment by Charlie894** [comment]
看来解决的根源是换浏览器

**Comment by Charlie894** [comment]
登陆界面太丑了啦

**Comment by guanmengkai** [comment]
也是一样的问题哎，我是这两天刚搭建的新网站。希望能解决这个问题，谢谢

**Comment by guanmengkai** [comment]
也是一样的问题哎，我是这两天刚搭建的新网站。希望能解决这个问题，谢谢

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/b86f5e044c26995b7302df5e9020936363471fe5 .
