### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Happiness-in-Danger** [Anankke/SSPanel-Uim#1292]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [ X] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [X ] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [ X] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [X ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**

debian10 php7.4 mysql 5.6
**Commit**
dev. 

**Bug**
站点无法访问,只出现这样的页面
![图片](https://user-images.githubusercontent.com/45912561/126390540-789cd04d-06ef-4e62-9ff2-e07076d5e1ff.png)

**Reproduce**
删除站点,重新建.但是仍旧无法访问

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
![图片](https://user-images.githubusercontent.com/45912561/126390409-836d8700-0c3f-445a-a778-9cc129d900a6.png)
![图片](https://user-images.githubusercontent.com/45912561/126390466-d1e48b93-789c-453a-a58b-69fbfd4418e7.png)

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by M1Screw** [comment]
There is something wrong with your vhost configuration.

**Comment by Happiness-in-Danger** [comment]
@M1Screw 原来是可以正常访问的但是我在使用一个后端的过程中nginx有点冲突，我给卸载了，有重新安装了。不知道怎么回事就不行了
