### ISSUE TITLE
[BUG]WIKI無法訪問

### ISSUE THREAD

**Issue by Charlie894** [Anankke/SSPanel-Uim#1293]
WIKI無法訪問
網頁無法訪問，GITHUB頁面正常

**Comment by 120420** [comment]
@Charlie894 全局代理or拔掉网线访问

**Comment by Charlie894** [comment]
不，提示备案错误

**Comment by NimaQu** [comment]
@Charlie894 备案掉了，谁来帮忙备案下

**Comment by Charlie894** [comment]
我刚才弄了一个http://sswiki.894.ink/
把github上的内容直接当源码复制了一下，结果发现。。。
还真能用！
[保证安全无毒无害无修改]

**Comment by Charlie894** [comment]
@NimaQu 
我感觉我变成小广告了
