### ISSUE TITLE
[Feature Request][小白是我]将添加节点界面做回91vps的样子

### ISSUE THREAD

**Issue by Charlie894** [Anankke/SSPanel-Uim#1294]
- [x] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
我是个小白，实在不知道只填IP怎么用。。。。
所以求各位大佬将添加节点界面更会91vps的样子。。。。
直接拒绝我也不会说什么的，毕竟我是小白。。。。

**Comment by EmiyaTKK** [comment]
@Charlie894
