### ISSUE TITLE
更新到468643c后，首页打开黑屏，只显示登录和注册

### ISSUE THREAD

**Issue by jelly0925** [Anankke/SSPanel-Uim#1296]
更新到468643c后，首页打开黑屏，只显示登录和注册，这样是正常的？
![Snipaste_2021-07-24_06-53-06](https://user-images.githubusercontent.com/3022023/126848595-6fcc1b82-8123-4774-8f2c-a3f761236a78.png)

**Comment by jelly0925** [comment]
怎样设置可以打开网站自动跳转到登录界面呀，谢谢。

**Comment by tanpengsccd** [comment]
你的问题和我一样.不知道是啥原因.
https://github.com/Anankke/SSPanel-Uim/issues/1298
![image](https://user-images.githubusercontent.com/13959880/127190306-a93b614b-6e51-4d43-8d13-a87fe902b14d.png)
我换过几个浏览器,开隐私模式 的 都是这样子.好像是CSS都没加载.

**Comment by tanpengsccd** [comment]
教程是按照 https://blog.anank.ke/w/SSPanel_with_LNMP 来的.
