### ISSUE TITLE
[BUG] vless订阅链接生成问题

### ISSUE THREAD

**Issue by lbroot** [Anankke/SSPanel-Uim#1302]
不小心碰到回车了 正在编辑 对不起 (搞完了)

请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Debian10 php7.4 mysql5.7

**Commit**
Merge pull request #1301 from frainzy1477/grpc-support …     #6683362

**Bug**
1. 设置为vless情况下，用户页面-节点列表-展开节点详情-点击查看节点配置详情-复制链接 得到的仍然是vmess链接
2. grpc协议下设置servicename，订阅链接中servicename为空值，直接首页复制全部链接出来的vless链接中，servicename也是空值

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
1.如上
2. 节点地址设置为 1.2.3.4;30058;2;grpc;host=example.com|server=example.com|servicename=1145140|outside_port=443|enable_vless=true 
首页和订阅得到的链接为vless://2f060692-4dba-3c38-8a4b-a34302acf02c@1.2.3.4:30058?encryption=auto&type=grpc&security=&mode=multi&serviceName=#grpc

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
1.获得vless链接
2. vless://2f060692-4dba-3c38-8a4b-a34302acf02c@1.2.3.4:30058?encryption=**none**&type=grpc&security=&mode=multi&serviceName=**1145140**#grpc

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by lbroot** [comment]
我来继续补充关于VLESS链接的相关BUG

1. 首页，生成的VLESS链接中参数 ?encryption=auto 不正确，正确的写法应该是 ?encryption=none 
2. shadowrocket小火箭专用订阅链接获取到的仍然是 vmess 配置

**Comment by du5** [comment]
订阅支持很不完善，`/user/node` 页面显示也不太友好，建议先不要更新或添加VLESS节点

**Comment by baiyou2014** [comment]
请问vless与vmess怎么设置的？之前我是vmess升级完代码订阅出来的vless类型

**Comment by worldneedme** [comment]
我也同样有这个问题，请问楼主解决了吗
