### ISSUE TITLE
希望能对接云免签

### ISSUE THREAD

**Issue by wanglu58** [Anankke/SSPanel-Uim#1318]
- [√ ] I certify that I have read project Wiki and other issue may related to this one.
- [√] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
希望sspanel未来能对接云免签
**Solution**
云免签类似于码支付。但是码支付现在打不开。各位开发者可以对接云免签https://www.yunmianqian.com/

**Addition**
希望sspane未来能对接云免签

**Comment by M1Screw** [comment]
https://doc.yunmianqian.com/wen-ti/jin-zhi-jiao-yi.html

**Comment by iMerl** [comment]
最好对接境外支付

**Comment by wanglu58** [comment]
有sspanel大佬愿意开发对接吗？可资助！

**Comment by jldhrj** [comment]
没有快滚，在问打死你。

**Comment by xsidc** [comment]
strpie接口还正常吗？

**Comment by iMerl** [comment]
我有做跨境收款通道，但是这种服务，没人敢接的。有命赚没命花

**Comment by iMerl** [comment]
> strpie接口还正常吗？

stripe 发行是做vpn服务，直接停到

**Comment by xsidc** [comment]
strpie里的其他支付不会停，支付宝和微信会停。

**Comment by iMerl** [comment]
讨论这个问题没必要，八仙过海各显其能～～～～违法必究
