### ISSUE TITLE
[BUG]升级完版本之前的订阅vmess变为vless

### ISSUE THREAD

**Issue by baiyou2014** [Anankke/SSPanel-Uim#1319]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x ] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
centos7 php7.4 mysql 5.7 nginx1.20.1

**Commit**
最新的

**Bug**
升级之前订阅出来的还正常，升级之后订阅出来的类型变为vless了导致节点无法使用。接地那列表复制链接导入进v2rayn正常显示。难道要升级节点信息数据库？

**Comment by NutterChen** [comment]
升级前升级后是分别值哪两个版本？
半个月前就看到你在搞这个问题

**Comment by baiyou2014** [comment]
> 升级前升级后是分别值哪两个版本？
> 半个月前就看到你在搞这个问题

一直在用dev版本
https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d更新之前应该是这个fix bug

**Comment by kjwlegend** [comment]
> > 升级前升级后是分别值哪两个版本？
> > 半个月前就看到你在搞这个问题
> 
> 一直在用dev版本 [8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d更新之前应该是这个fix) bug

去你后台的节点里
节点地址 1.2.3.4.;XXXX;XXXX;XXX;;  
最后的地方添加上 enable_vless=0
就可以转换成vmess 协议了。我也是找了半天issue 和更新记录， 最后看源代码试出这个问题
