### ISSUE TITLE
[Feature Discussion] Send the online IP addresses in detail instead of just the total number.

### ISSUE THREAD

**Issue by RManLuo** [Anankke/SSPanel-Uim#1322]
- [x] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
Send the online IP addresses in detail instead of just the total number.

In order to globally limit the online IP address across the backend nodes, the details of each online IP address should be sent to the backend nodes. As discussed in https://github.com/Anankke/SSPanel-Uim/issues/1264#issuecomment-855183913 and XrayR-project/XrayR#47, if only the total online IP number is sent, it will cause the same IP on different nodes to disconnect while using the same device at the same time.

For example, a user with a connection limit of 1 when connected to server A will not be able to connect to server B with the same IP until the current connection is disconnected, causing a connection break if you try to switch between servers on the same device and IP.

**Solution**
I think all the online IP addresses of each user should be gathered and sent in this API implementation.
https://github.com/Anankke/SSPanel-Uim/blob/e4fbea9f68b932ab8506aca34021cd64989ac24d/src/Controllers/Mod_Mu/UserController.php#L97-L101

**Addition**
If the same IP on different backend servers should be considered as independent devices accourding to here.
https://github.com/Anankke/SSPanel-Uim/issues/1264#issuecomment-855228067

I think the `distinct` operation in this line should be removed.
https://github.com/Anankke/SSPanel-Uim/blob/8796132f323734a643f1141866c4c17b1550a71d/src/Models/Ip.php#L89

**Maybe a good discussion about the definition of DEVICE is required?**

**Comment by M1Screw** [comment]
We discussed this issue with the author of the soga backend before we began improving the WebAPI. We made a conclusion that provides each backend server with a full array of current online IP will not only cause unnecessary performance impact and also increase the traffic between the panel and the backend server, so that's why we craft a method to count the online IPs of each connecting user and only return user account's connection limit and current connection count.

**Comment by RManLuo** [comment]
> We discussed this issue with the author of the soga backend before we began improving the WebAPI. We made a conclusion that provides each backend server with a full array of current online IP will not only cause unnecessary performance impact and also increase the traffic between the panel and the backend server, so that's why we craft a method to count the online IPs of each connecting user and only return user account's connection limit and current connection count.

In this case, I believe the connection break is considered as a trade-off for traffic usage. I will follow the current global IP limit in the future update of XrayR. Thanks again for your reply.
