### ISSUE TITLE
使用aapanel搭建 部分定时任务无法执行

### ISSUE THREAD

**Issue by Gwyncassie** [Anankke/SSPanel-Uim#1324]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x]我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

Nginx1.20
MySQL8.0
PHP 7.4

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

Dev最新版本

**Bug**
The bug information. 请描述你遇到的 Bug。

不执行的：
例如config配置文件中设置自动删除多少天未使用未签到的账户、每日邮件报告、TelegramBot相关定时任务都不执行
正常执行的：
等级过期和账号过期能正常执行

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

我的定时任务：
*/1 * * * * php /www/wwwroot/sspanel/xcat  Job SendMail
*/1 * * * * php /www/wwwroot/sspanel/xcat  Job CheckJob
0 */1 * * * php /www/wwwroot/sspanel/xcat  Job UserJob
0 0 * * * php -n /www/wwwroot/sspanel/xcat Job DailyJob
30 23 * * * php /www/wwwroot/sspanel/xcat sendDiaryMail

大佬们这是什么情况呀

**Comment by iamsaltedfish** [comment]
手动执行看看有没有报错

**Comment by Gwyncassie** [comment]
**php -n /www/wwwroot/sspanel/xcat Job DailyJob 报错：**

rm: 无法删除'/www/wwwroot/sspanel/app/../storage/*.png': No such file or directory
开始下载或更新纯真 IP 数据库....
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /www/wwwroot/sspanel/src/Command/Tool.php on line 66

Warning: file_get_contents(): Failed to enable crypto in /www/wwwroot/sspanel/src/Command/Tool.php on line 66

Warning: file_get_contents(https://qqwry.mirror.noc.one/QQWry.Dat?from=sspanel_uim): failed to open stream: operation failed in /www/wwwroot/sspanel/src/Command/Tool.php on line 66
下载失败！请重试，或在 https://github.com/SukkaW/qqwry-mirror/issues/new 反馈！


**php /www/wwwroot/sspanel/xcat sendDiaryMail 报错：**

Unable to load class: \App\Command\sendDiaryMail

其他没问题。

**Comment by iamsaltedfish** [comment]
php xcat 可以查看支持的命令列表，你的sendDiaryMail少了个前缀（印象里应该是User）
你的第一个问题不太清楚，下载源应该没问题，可能是因为读写权限或openssl，谷歌查查吧
年纪轻轻用什么宝塔（

**Comment by Gwyncassie** [comment]
感谢大佬的解答
php xcat Job UserJob 手动执行后没有提示，也没有按config配置文件设置的任务执行。

**Comment by Gwyncassie** [comment]
> 感谢大佬的解答
> php xcat Job UserJob 手动执行后没有提示，也没有按配置文件设置的任务执行。

Telegram的定时删除消息也没有执行，这是什么原因呢

**Comment by Gwyncassie** [comment]
之前用国内版的宝塔就没有这样的情况，最近才换的aapanel，会不会是国际版宝塔的问题...

**Comment by iamsaltedfish** [comment]
看了下代码，还有一个auto_clean_min_money你配置了吗

**Comment by Gwyncassie** [comment]
> 看了下代码，还有一个auto_clean_min_money你配置了吗
配置了的
$_ENV['auto_clean_min_money']       = 0.01;            //余额低于多少的0级用户可以被清理

**Comment by M1Screw** [comment]
> > 感谢大佬的解答
> > php xcat Job UserJob 手动执行后没有提示，也没有按配置文件设置的任务执行。
> 
> Telegram的定时删除消息也没有执行，这是什么原因呢

Bot 自動刪除消息的功能已經在新版本裏面去掉了。

**Comment by iamsaltedfish** [comment]
服务器时间和时区对么，执行date看看
用户自动删除还需要满足class为0

**Comment by Gwyncassie** [comment]
![image](https://user-images.githubusercontent.com/90991681/133913167-65c6c2f4-b19c-49a9-b110-996690dbc77a.png)

都是0级用户

**Comment by Gwyncassie** [comment]
不知道是不是国际版的问题，晚点我滚回国内版的看看

**Comment by iamsaltedfish** [comment]
回滚（逃

**Comment by Gwyncassie** [comment]
![image](https://user-images.githubusercontent.com/90991681/134035089-39c7bcf4-7b39-4021-b925-f3e72f5e4a8a.png)
看了下 是注册时间异常，用户注册时间会一直刷新，这是什么情况...

**Comment by xuelang113** [comment]
我的定时任务也有问题，面板上用户流量可以更新，但数据库中的用户每小时流量没有记录，第二天后，用户过去流量没有更新，一直为0、如图：
![20210928093711](https://user-images.githubusercontent.com/45958811/135008139-c39b997c-2883-4d92-87ee-30653694ec38.png)


我的定时任务如下：
30 22 * * * php /www/wwwroot/www.dddd.xyz/xcat SendDiaryMail
0 0 * * * php -n /www/wwwroot/www.dddd.xyz/xcat Job DailyJob
0 0 * * * php -n /www/wwwroot/www.dddd.xyz/xcat dailyjob
0 0 * * * php -n /www/wwwroot/www.dddd.xyz/xcat Job SendMail
*/1 * * * * php /www/wwwroot/www.dddd.xyz/xcat Job CheckJob
*/1 * * * * php /www/wwwroot/www.dddd.xyz/xcat Job UserJob
6 0 * * 0 php /www/wwwroot/www.dddd.xyz/xcat ExtMail sendNoMail
5 0 * * * php /www/wwwroot/www.dddd.xyz/xcat FinanceMail day
6 0 * * 0 php /www/wwwroot/www.dddd.xyz/xcat FinanceMail week
7 0 1 * * php /www/wwwroot/www.dddd.xyz/xcat FinanceMail month
*/1 * * * * php /www/wwwroot/www.dddd.xyz/xcat DetectGFW
*/1 * * * * php /www/wwwroot/www.dddd.xyz/xcat DetectBan

其他功能正常。我从5月版本测试到现在这个版本，都是这个过去已用流量不会更新。我一直搞不懂，大佬请指导一下。

**Comment by ecyecy** [comment]
debian 10 lnmp环境下搭建也是这种情况

> > ![image](https://user-images.githubusercontent.com/90991681/134035089-39c7bcf4-7b39-4021-b925-f3e72f5e4a8a.png)
> > 看了下 是注册时间异常，用户注册时间会一直刷新，这是什么情况...
> 
> 国内宝塔和国际版宝塔 安装最新版本Dev 注册时间会一直刷新为最新时间
> 
> 例如： 编辑用户后，注册时间会刷新 用户正在使用节点时，注册时间会随着刷新 用户签到后，注册时间会刷新 用户充值后，注册时间会刷新 用户购买套餐后，注册时间会刷新
> 
> 以上遇到的问题都是全新环境安装的，以前的旧版本升级到最新版本没有出现这种问题。

**Comment by iamsaltedfish** [comment]
已复现，审查相关代码，未见异常。原因可能出在user表reg_date字段设定

```
reg_date` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '注册时间',
```
使用以下sql语句修复此问题
```
ALTER TABLE `user` CHANGE `reg_date` `reg_date` DATETIME NOT NULL COMMENT '注册时间';
```
经测试，未见签到后刷新注册时间

@M1Screw 快来修（

**Comment by Anankke** [comment]
> 已复现，审查相关代码，未见异常。原因可能出在user表reg_date字段设定
> 
> ```
> reg_date` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '注册时间',
> ```
> 
> 使用以下sql语句修复此问题
> 
> ```
> ALTER TABLE `user` CHANGE `reg_date` `reg_date` DATETIME NOT NULL COMMENT '注册时间';
> ```
> 
> 经测试，未见签到后刷新注册时间
> 
> @M1Screw 快来修（

速速 PR 秒通过

**Comment by M1Screw** [comment]
> 已复现，审查相关代码，未见异常。原因可能出在user表reg_date字段设定
> 
> ```
> reg_date` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '注册时间',
> ```
> 
> 使用以下sql语句修复此问题
> 
> ```
> ALTER TABLE `user` CHANGE `reg_date` `reg_date` DATETIME NOT NULL COMMENT '注册时间';
> ```
> 
> 经测试，未见签到后刷新注册时间
> 
> @M1Screw 快来修（

Hmmm， 康康是誰引入的這個 bug。另外你這個可以單獨做個 sql 文件就叫做 reg_date.sql 。

**Comment by iamsaltedfish** [comment]
> > 已复现，审查相关代码，未见异常。原因可能出在user表reg_date字段设定
> > ```
> > reg_date` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT '注册时间',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 使用以下sql语句修复此问题
> > ```
> > ALTER TABLE `user` CHANGE `reg_date` `reg_date` DATETIME NOT NULL COMMENT '注册时间';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 经测试，未见签到后刷新注册时间
> > @M1Screw 快来修（
> 
> Hmmm， 康康是誰引入的這個 bug。另外你這個可以單獨做個 sql 文件就叫做 fix_reg_date.sql 。

https://github.com/Anankke/SSPanel-Uim/commit/76422aea2f2cee1b9d4b4993aff80118b716c415#diff-dcf69d57852eb461dbd974bb9c9e4bd7d518fe135bdce46158be1eda52c6d815

**Comment by Colinwood11** [comment]
@iamsaltedfish 把孔雀抓来透

**Comment by 412jht** [comment]
> 

解决了么？

**Comment by 412jht** [comment]
> 我的定时任务也有问题，面板上用户流量可以更新，但数据库中的用户每小时流量没有记录，第二天后，用户过去流量没有更新，一直为0、如图： ![20210928093711](https://user-images.githubusercontent.com/45958811/135008139-c39b997c-2883-4d92-87ee-30653694ec38.png)
> 
> 我的定时任务如下： 30 22 * * * php /www/wwwroot/www.dddd.xyz/xcat SendDiaryMail 0 0 * * * php -n /www/wwwroot/www.dddd.xyz/xcat Job DailyJob 0 0 * * * php -n /www/wwwroot/www.dddd.xyz/xcat dailyjob 0 0 * * * php -n /www/wwwroot/www.dddd.xyz/xcat Job SendMail */1 * * * * php /www/wwwroot/www.dddd.xyz/xcat Job CheckJob */1 * * * * php /www/wwwroot/www.dddd.xyz/xcat Job UserJob 6 0 * * 0 php /www/wwwroot/www.dddd.xyz/xcat ExtMail sendNoMail 5 0 * * * php /www/wwwroot/www.dddd.xyz/xcat FinanceMail day 6 0 * * 0 php /www/wwwroot/www.dddd.xyz/xcat FinanceMail week 7 0 1 * * php /www/wwwroot/www.dddd.xyz/xcat FinanceMail month */1 * * * * php /www/wwwroot/www.dddd.xyz/xcat DetectGFW */1 * * * * php /www/wwwroot/www.dddd.xyz/xcat DetectBan
> 
> 其他功能正常。我从5月版本测试到9月份的版本，都是这个过去已用流量不会更新。我一直搞不懂，大佬请指导一下。

解决了么？

**Comment by iamsaltedfish** [comment]
手动执行定时任务，把报错贴出来
