### ISSUE TITLE
[Feature Request]能否支持Xray的回落Fallback

### ISSUE THREAD

**Issue by rex5652** [Anankke/SSPanel-Uim#1352]
- [X] I certify that I have read project Wiki and other issue may related to this one.
- [X] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
某些后端支持Xray的Vless回落功能，但在面板上一个节点只能配置一种协议。如果为了配置第二种协议，就需要新增一个节点配置，这样节点ID就不一样了。

**Solution**
可以在面板的的服务器配置部分增加fallback参数来支持？

**Comment by wsf3266** [comment]
网站打不开，节点无法使用
