### ISSUE TITLE
[Feature Request] 修改用戶名

### ISSUE THREAD

**Issue by bestpika** [Anankke/SSPanel-Uim#1359]
- [x] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**

我看了一下原始碼發現各用戶有唯一的 `id` 欄位
所以用戶名 `user_name` 欄位應該是可以修改的
想請問是否可以在管理者的部分增加這個欄位的修改
謝謝

**Comment by M1Screw** [comment]
可
