### ISSUE TITLE
[BUG]更新到新版本多支付接口、配置数据库化遇到的问题

### ISSUE THREAD

**Issue by ecyecy** [Anankke/SSPanel-Uim#1361]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
Centos 8
Nginx 1.21
MariaDB 10.5
PHP 7.4

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
[de5080e4083f9d3c3def8301a15f6e4e7660ad97](https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97)
[db50202e9be620d9e52a4c1cfeae8a29e8c43bd1](https://github.com/Anankke/SSPanel-Uim/commit/db50202e9be620d9e52a4c1cfeae8a29e8c43bd1)

**Bug**
The bug information. 请描述你遇到的 Bug。
更新多支付接口后，支付后没有弹出充值成功提示，也没有自动刷新页面，没更新前是有的。余额是能正常到账的，就是需要手动刷新才能看到。
更新到最新版本配置数据库化，网站无法打开，报错 fatal error (可能是还没完工吧)
![001](https://user-images.githubusercontent.com/91567869/141613973-66632fcc-f6fe-48a7-b2aa-24b59c904b2d.png) (附上一张群友的截图)

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
支付后弹窗充值成功提示，并自动刷新页面。
![001](https://user-images.githubusercontent.com/91567869/141614016-45eb396e-2e40-43fd-93f5-efe2fe44c60a.jpg)

配置数据库化等完工。

**Comment by iamsaltedfish** [comment]
导入 sql/config.sql 啊

**Comment by ecyecy** [comment]
> 导入 sql/config.sql 啊

导入了

**Comment by iamsaltedfish** [comment]
config表截图看看

**Comment by ecyecy** [comment]
> config表截图看看

好吧，是我导错了，我导入了gconfig.sql....
网站现在能打开，但是上面报错这个：
Non-static method App\Models\Setting::getPublicConfig() should not be called statically in/www/wwwroot/sspanel/src/Services/Config.phpon line27

Non-static method App\Models\Setting::obtain() should not be called statically in/www/wwwroot/sspanel/src/Services/Captcha.phpon line15

Non-static method App\Models\Setting::obtain() should not be called statically in/www/wwwroot/sspanel/src/Services/Captcha.phpon line18

Non-static method App\Models\Setting::obtain() should not be called statically in/www/wwwroot/sspanel/src/Controllers/UserController.phpon line83

**Comment by iamsaltedfish** [comment]
试试编辑 src\Models\Setting.php
将所有的
public function
改成
public static function

**Comment by iamsaltedfish** [comment]
宝塔用户么？

**Comment by ecyecy** [comment]
> 试试编辑 src\Models\Setting.php 将所有的 public function 改成 public static function

搞定了 大佬牛皮

**Comment by ecyecy** [comment]
使用的是平头哥支付，在管理面板设置中心配置好后，在用户中心充值弹出这个：
![image](https://user-images.githubusercontent.com/91567869/141615495-aea5e2af-21aa-49e5-961a-457a2844f2f1.png)

**Comment by iamsaltedfish** [comment]
f12看看响应的报错提示
不确定是不是我的pr问题，只测试了f2f和v免签

**Comment by ecyecy** [comment]
> f12看看响应的报错提示 不确定是不是我的pr问题，只测试了f2f和v免签

![image](https://user-images.githubusercontent.com/91567869/141615647-973f5b6b-3584-4f7d-aab8-158e85dec937.png)
是这个吗

**Comment by iamsaltedfish** [comment]
network那

**Comment by iamsaltedfish** [comment]
抱歉审查代码没注意
src/Services/Gateway/THeadPay.php
在use App\Models\Paylist;后追加
use App\Models\Setting;

**Comment by ecyecy** [comment]
> 抱歉审查代码没注意，编辑
> 
> ```
> src/Services/Gateway/THeadPay.php
> ```
> 
> 在
> 
> ```
> use App\Models\Paylist;
> ```
> 
> 后追加
> 
> ```
> use App\Models\Setting;
> ```

OK了，蟹蟹大佬。
现在支付码能显示出来，支付也成功，余额也到账，但是没有弹窗提示充值成功，还是需要手动刷新，以前是能自动跳转的。

**Comment by iamsaltedfish** [comment]
.config.php 配置了baseUrl 了么

**Comment by ecyecy** [comment]
> .config.php 配置了baseUrl 了么

配置了的

**Comment by iamsaltedfish** [comment]
你试试这个（没有合并多网关支持的）
https://github.com/Anankke/SSPanel-Uim/commit/ee1c9b66a50563576e13a3e12982443d4000b6a7
和这个（合并了多网关支持的）
https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97
看看问题会不会复现

**Comment by ecyecy** [comment]
> 你试试这个（没有合并多网关支持的） [ee1c9b6](https://github.com/Anankke/SSPanel-Uim/commit/ee1c9b66a50563576e13a3e12982443d4000b6a7) 和这个（合并了多网关支持的） [de5080e](https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97) 看看问题会不会复现

我现在用的就是 ee1c9b6 这个，是能弹窗提示，也会自动跳转 ，我基本都是随commits更新的，就是最近更新到多网关支持这里出现问题。

**Comment by iamsaltedfish** [comment]
数据库话配置之前，支持多网关之后的commit能用么（https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97）

**Comment by ecyecy** [comment]
> 支持多网关之后，数据库化配置之前的这个commit能用么 [de5080e](https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97)

其实就充值后，不提示充值状态，不跳转这个问题。

**Comment by iamsaltedfish** [comment]
那就不是我的锅了（

**Comment by ecyecy** [comment]
> 那就不是我的锅了（

emm 好吧，感谢大佬的耐心解答。

**Comment by iamsaltedfish** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97 这个没有数据库话配置，你是在config.php配置的吧？

**Comment by ecyecy** [comment]
> [de5080e](https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97) 这个没有数据库化配置，你是在config.php配置的吧？

这个版本都是在.config.php里配置的吧

**Comment by iamsaltedfish** [comment]
> > [de5080e](https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97) 这个没有数据库化配置，你是在config.php配置的吧？
> 
> 这个版本都是在.config.php里配置的吧

最新的不是，我发的那个是

**Comment by ecyecy** [comment]
> > > [de5080e](https://github.com/Anankke/SSPanel-Uim/commit/de5080e4083f9d3c3def8301a15f6e4e7660ad97) 这个没有数据库化配置，你是在config.php配置的吧？
> > 
> > 
> > 这个版本都是在.config.php里配置的吧
> 
> 最新的不是，我发的那个是

我知道，我说 de5080e 这个版本之前都是在 .config.php 里配置的
其实充值结果需要手动刷新页面才能看到，也就小问题吧，就是会稍微影响使用体验。
