### ISSUE TITLE
[Feature Request] 删除未使用或未签到用户 增加一个累计充值判断

### ISSUE THREAD

**Issue by ecyecy** [Anankke/SSPanel-Uim#1367]
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
The feature you want.
删除××天未使用或未签到的用户，能否增加个选项，比如累计充值过多少金额的用户不会被删除账号，而不是只依据当前账户可用余额。

**Comment by ecyecy** [comment]
还有就是能否增加个用户等级过期后限速××Mbps的功能...

**Comment by 123456ZYF88** [comment]
加 1 我用了很长时间了 中间都是两个月两个月的开的 中间账号就被删除了不下三次

**Comment by ecyecy** [comment]
> 还有就是能否增加个用户等级过期后限速××Mbps的功能...

希望免费用户也能使用邀请返利功能
