### ISSUE TITLE
[BUG] 若用户总流量数值设置太大，下发时JSON的格式有问题

### ISSUE THREAD

**Issue by rex5652** [Anankke/SSPanel-Uim#1369]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [X] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [X] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [X] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [X] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
面板 202.10，soga 社区版 2.6.3

**Commit**
Releases的那个

**Bug**
用户总流量数值设置为999999999（G），则下发的JSON格式有问题：
get users failed: parse users failed: json: cannot unmarshal number 1.0737418229262582e+18 into Go struct field XQx70zRz.data.transfer_enable of type int64, result:
{"id":1,"uuid":"XXXXXXXXXXXXXXX","u":8077153,"d":232915228,"transfer_enable":1.0737418229262582e+18,"node_speedlimit":0,"node_connector":0}]}
Soga

**Reproduce**
如上

**Expected behavior**
下发正确值，或对最大数限制。目前我用9999999（G），可以正常下发

**Comment by M1Screw** [comment]
這個確實是一個很有意思的問題，我會嘗試在本地復現一下。

**Comment by M1Screw** [comment]
已經證明可以復現。

**Comment by M1Screw** [comment]
因爲 WebAPI 的邏輯是在用戶流量耗盡時就不再下發這個用戶的配置，所以向節點下發已用流量以及縂流量是沒有必要的，u/d/transfer_enable 這三個參數會被從下發的 json 中移除。另外就是要直接以 int 的方式下發 999999999G 對應的正確 bit 值是不可能的，除非轉換為 string ，這個是 PHP 本身的一個限制（當然你要用 GMP 庫來做也不是不行，不過沒有必要罷了）。另外就是我覺得可以新增一個設定為特定數值的流量則面板自動將該用戶視爲無限流量的功能。 @iamsaltedfish

**Comment by rex5652** [comment]
> u/d/transfer_enable 這三個參數會被從下發的 json 中移除
这个我觉得可行

**Comment by Anankke** [comment]
@M1Screw 正确的
