### ISSUE TITLE
[BUG]最新版依然导致输入端报错。。。。

### ISSUE THREAD

**Issue by planxx** [Anankke/SSPanel-Uim#1370]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
centos 8+MariaDB 10.6.4+PHP 7.4.26

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
40f62c6

**Bug**
The bug information. 请描述你遇到的 Bug。
SSR服务端报错。。。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
修复这个问题。。。。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

Nov 30 05:48:32 localhost nohup[35612]:   utils.DeprecatedIn35,
Nov 30 05:48:32 localhost nohup[35612]: INFO: loading config from user-config.json
Nov 30 05:48:32 localhost nohup[35612]: 2021-11-30 05:48:32 INFO     util.py:47 loading libcrypto from libcrypto.so.1.1
Nov 30 05:48:32 localhost nohup[35612]: 2021-11-30 05:48:32 INFO     asyncdns.py:323 dns server: [('100.64.1.1', 53), ('100.64.2.2', 53)]
Nov 30 05:48:33 localhost nohup[35612]: 2021-11-30 05:48:33 ERROR    web_transfer.py:545 Traceback (most recent call last):
Nov 30 05:48:33 localhost nohup[35612]:   File "/soft/shadowsocks/web_transfer.py", line 540, in thread_db
Nov 30 05:48:33 localhost nohup[35612]:     last_rows, rows
Nov 30 05:48:33 localhost nohup[35612]:   File "/soft/shadowsocks/web_transfer.py", line 235, in del_server_out_of_bound_safe
Nov 30 05:48:33 localhost nohup[35612]:     del md5_users[row["id"]]["u"]
Nov 30 05:48:33 localhost nohup[35612]: KeyError: 'u'

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
@planxx 请使用最新版后端

**Comment by planxx** [comment]
我看了一下，虽然是一键脚本安装的，但是确实是最新版本后端。。。。。

**Comment by Anankke** [comment]
@planxx 那很有可能不是

**Comment by planxx** [comment]
@Anankke 肯定是……脚本是https://github.com/M1Screw/Airport-toolkit这里的脚本，我打开看了一下，是直接从您这下载安装的。。。。

**Comment by Anankke** [comment]
@planxx @m1scew_bot

**Comment by planxx** [comment]
没明白。。。大佬。。。。

**Comment by planxx** [comment]
@Anankke 大佬，我刚刚，手动安装了您最新的后端。。。还是一样的问题。。。。

**Comment by M1Screw** [comment]
看起來是後端裏面讀了一個不存在的參數導致的，你試一下把 /soft/shadowsocks/web_transfer.py 的第 235 行和 236 行去掉看看還會不會報錯。

**Comment by planxx** [comment]
timeout=10,
Nov 30 06:36:52 localhost nohup[1030]:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
Nov 30 06:36:52 localhost nohup[1030]:     return self.request('GET', url, **kwargs)
Nov 30 06:36:52 localhost nohup[1030]:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
Nov 30 06:36:52 localhost nohup[1030]:     resp = self.send(prep, **send_kwargs)
Nov 30 06:36:52 localhost nohup[1030]:   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
Nov 30 06:36:52 localhost nohup[1030]:     r = adapter.send(request, **kwargs)
Nov 30 06:36:52 localhost nohup[1030]:   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
Nov 30 06:36:52 localhost nohup[1030]:     raise ConnectionError(e, request=request)
Nov 30 06:36:52 localhost nohup[1030]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='demo.sspanel.host', port=443): Max retries exceeded with url: /mod_mu/func/ping?key=sspanel (Caused by NewConnectionError('<urllib3.connection.Verified

**Comment by planxx** [comment]
试过了。。。还是有问题。。。。ORZ...

**Comment by planxx** [comment]
@M1Screw @Anankke 二位大佬，我又测试了一遍，按照大猫猫大佬说的，删掉之后。。。。正常了：）
