### ISSUE TITLE
[BUG]使用邀请链接注册，注册失败后清除邀请码的问题

### ISSUE THREAD

**Issue by vonaxs** [Anankke/SSPanel-Uim#1377]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Bug**
当用户使用邀请链接注册的时候，系统会自动填写邀请码。
但是如果用户一次注册没有成功，比如密码填错之类的，这时候按照下面的代码：

SSPanel-Uim/resources/views/material/auth/register.tpl 第293行
setCookie('code', '', 0);
$("#code").val(getCookie('code'));

系统会清除邀请码。
此时如果用户没有注意到邀请码被清除了，继续注册，会导致没有邀请人。

**Reproduce**
能否直接删除以下2行代码
setCookie('code', '', 0);
$("#code").val(getCookie('code'));

**Comment by Anankke** [comment]
我觉得你说的对

**Comment by vonaxs** [comment]
> 我觉得你说的对

那这2行代码能不能直接删除

**Comment by du5** [comment]
我觉得你说的对
