### ISSUE TITLE
[BUG]Error on single port but mutiple port is feasible

### ISSUE THREAD

**Issue by CNYoki** [Anankke/SSPanel-Uim#1378]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
CentOS 7.6
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
2021.10 release

**Bug**
The bug information. 请描述你遇到的 Bug。
The back-end program warns that the ip is forbidden during single-port multi-user bearer operation and cannot connect normally. This error will not occur for single-multi-port

version: https://wiki.sspanel.org/#/turnkey-install-for-ssr-node?id=%e5%90%8e%e7%ab%af%e4%b8%80%e9%94%ae%e5%ae%89%e8%a3%85%e8%84%9a%e6%9c%ac%ef%bc%88%e5%a4%a7%e7%8c%ab%e7%8c%ab%e7%89%88%ef%bc%89

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
`2021-12-08 22:52:21 INFO     server_pool.py:146 starting server at [::]:8000
2021-12-08 22:52:21 WARNING  server_pool.py:170 IPV6 'forbidden_ip' 
2021-12-08 22:52:21 INFO     server_pool.py:188 starting server at 0.0.0.0:8000
2021-12-08 22:52:21 WARNING  server_pool.py:205 IPV4 'forbidden_ip' 
2021-12-08 22:53:21 ERROR    web_transfer.py:543 Traceback (most recent call last):
  File "/soft/shadowsocks/web_transfer.py", line 529, in thread_db
    ping = webapi.getApi("func/ping")
  File "/soft/shadowsocks/webapi_utils.py", line 24, in getApi
    timeout=10,
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
`
**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by M1Screw** [comment]
Check your python version.
