### ISSUE TITLE
[BUG]payment stripe no variables in sql database

### ISSUE THREAD

**Issue by demianrey** [Anankke/SSPanel-Uim#1383]
when saving the parameters in the payment configuration I get error 500

Thanks & Regards

**Comment by iamsaltedfish** [comment]
Edit /config/.config.php to enable debug mode, and f12 displays an error in the network bar of the browser

**Comment by iamsaltedfish** [comment]
If the upgrade is from an earlier version, perform this operation
```
php xcat Tool importAllSettings
composer install
```

**Comment by demianrey** [comment]
> 

It works perfect, thanks for your prompt response and sorry if I missed documenting to know how it works.

I have a question about of paymentwall, I can't find the Pingback URL, do you know about it ? or do I open a new issue?

**Comment by iamsaltedfish** [comment]
About paymentwall, I can't help you any more.

**Comment by demianrey** [comment]
> About paymentwall, I can't help you any more.

Thanks anyway, I proceed to close the issue
