### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ywggf** [Anankke/SSPanel-Uim#1384]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
The bug information. 请描述你遇到的 Bug。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context her
![捕获](https://user-images.githubusercontent.com/71186289/146352372-7f80e6c2-d4a3-405d-955e-0e2dcd2cfa8e.PNG)
e. 如有可能，请提供更多相关资料。

php7.1/mysql5.6.50
我在最后一步添加管理员账号的步骤上出现了报错
使用代码了php -n xcat createAdmin

想问一下各位大佬帮忙看看，感谢

**Comment by iamsaltedfish** [comment]
导入sql文件，然后config.php填好数据库信息，再来执行这个命令，找个完整点的教程吧

**Comment by ywggf** [comment]
> 

你好，我这边按照教程导入的all数据库，然后访问权限也是所有人

**Comment by ywggf** [comment]
> 导入sql文件，然后config.php填好数据库信息，再来执行这个命令，找个完整点的教程吧
都是按照教程走的，不知道哪一步出错了，还请大佬指导

**Comment by ywggf** [comment]
@iamsaltedfish 大佬
