### ISSUE TITLE
[BUG]使用php xcat ClientDownload时github token报错

### ISSUE THREAD

**Issue by em34j** [Anankke/SSPanel-Uim#1386]
php xcat ClientDownload时github token报错
access_token不要放在query参数中，而是要放在header里面

PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.github.com/repos/HMBSbige/ShadowsocksR-Windows/releases/latest?access_token=xxxxxxxx` resulted in a `400 Bad Request` response:
{
  "message": "Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

**Comment by M1Screw** [comment]
@GeekQuerxy

**Comment by M1Screw** [comment]
@GeekQu
