### ISSUE TITLE
[Feature Request]玩梗也太艹了，就是个屑代理工具罢了😂

### ISSUE THREAD

**Issue by xidaner** [Anankke/SSPanel-Uim#1392]
- [ ] I certify that I have read project Wiki and other issue may related to this one.
- [ ] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
感谢给我无聊的生活平添了乐趣

**Solution**
If you have some solution about this issue, type it here.

**Addition**
Additional context here.

**Comment by Anankke** [comment]
你又事哪块小饼干，，
