### ISSUE TITLE
【新功能】流媒体解锁检测

### ISSUE THREAD

**Issue by iamsaltedfish** [Anankke/SSPanel-Uim#1403]
## 项目地址
[https://github.com/iamsaltedfish/check-stream-media](https://github.com/iamsaltedfish/check-stream-media)

## 怎么用
更新完 `sspanel` 后，在你的节点上执行
```
wget https://raw.githubusercontent.com/iamsaltedfish/check-stream-media/main/csm.sh
bash csm.sh
```
- 依照脚本提示，选择一个执行频率（1~24 hour 可选）
- 依照脚本提示，输入你的面板地址和 `mukey`
- 脚本会检测你刚才输入的信息是否有效
- 如果没问题，脚本就会执行检测函数，然后把检测结果提交到面板上
- 访问 `/user/media` 查看检测结果

## 注意事项
- 只会读取最近 `86460` 秒（一天多一分钟）内的检测结果，如果你删除了一个节点，而该节点的解锁检测结果还在，等 24 小时就会自动隐去了

**Comment by iamsaltedfish** [comment]
演示地址：[https://demo.sspanel.org/user/media](https://demo.sspanel.org/user/media)
账户：`admin@sspanel.org`

**Comment by stardock** [comment]
多个node id对应同一台服务器应该如何填写？

**Comment by iamsaltedfish** [comment]
> 多个node id对应同一台服务器应该如何填写？

抽个时间写一下，配置文件里加个关联数组，然后指定哪些节点沿用哪个节点的测试结果就可以了

**Comment by stardock** [comment]
[x] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ss.stream_media' doesn't exist (SQL: SELECT DISTINCT node_id FROM stream_media)  

数据库中缺少对应表，最好是做一个 stream_media.sql 方便现有数据库直接导入。

**Comment by iamsaltedfish** [comment]
9102年了
https://github.com/Anankke/SSPanel-Uim/issues/1402

**Comment by iamsaltedfish** [comment]
> [x] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ss.stream_media' doesn't exist (SQL: SELECT DISTINCT node_id FROM stream_media)
> 
> 数据库中缺少对应表，最好是做一个 stream_media.sql 方便现有数据库直接导入。

拉取更新后执行

composer update
vendor/bin/phinx migrate

**Comment by iamsaltedfish** [comment]
> 多个node id对应同一台服务器应该如何填写？

更新了，现在支持了。拉取更新后，在 `.config.php` 文件添加如下内容
```
//流媒体解锁 如下设置将使397，297号节点复用4号节点的检测结果 使用时去掉注释符 //
$_ENV['streaming_media_unlock_multiplexing'] = [
    //'397' => '4',
    //'297' => '4',
];
```

**Comment by stardock** [comment]
经测试，multiplexing 只有最后一条生效。如下
就只有 '297' => '4', 生效，前面的都不显示。

$_ENV['streaming_media_unlock_multiplexing'] = [
    '197' => '2',
    '397' => '3',
    '297' => '4',
];

**Comment by iamsaltedfish** [comment]
> 经测试，multiplexing 只有最后一条生效。如下 就只有 '297' => '4', 生效，前面的都不显示。
> 
> ```
> $_ENV['streaming_media_unlock_multiplexing'] = [
>     '197' => '2',
>     '397' => '3',
>     '297' => '4',
> ];
> ```

再拉取一下更新试试看

**Comment by stardock** [comment]
现已显示正常

**Comment by tanpengsccd** [comment]
1.  csm.sh 脚本 似乎有问题.
密码错误时: {"ret":0,"data":"Token is invalid."}
帐密都正确: {"ret":0,"data":"IP is invalid. Now, your IP address is 144.168.58.102"}
账户不对时: 不会返回数据
所以正确时“invalid” 总是能捕获到.也会报错.
所以改为 
![image](https://user-images.githubusercontent.com/13959880/150536069-6aad780e-a474-49a5-870b-22c342d53ad0.png)
感觉才对.
2. 如何添加多个节点检测呢?

**Comment by iamsaltedfish** [comment]
> 1. csm.sh 脚本 似乎有问题.
>    密码错误时: {"ret":0,"data":"Token is invalid."}
>    帐密都正确: {"ret":0,"data":"IP is invalid. Now, your IP address is 144.168.58.102"}
>    账户不对时: 不会返回数据
>    所以正确时“invalid” 总是能捕获到.也会报错.
>    所以改为
>    ![image](https://user-images.githubusercontent.com/13959880/150536069-6aad780e-a474-49a5-870b-22c342d53ad0.png)
>    感觉才对.
> 2. 如何添加多个节点检测呢?

这个脚本没有账户这个概念吧，密码也是沿用的mukey的值。然后因为你开了节点ip校验，又是在自己电脑的浏览器上访问的这个url，mukey虽然正确，但是你的ip在节点表中不存在，所以才会报“IP is invalid”，在节点上执行怎么会有这个错误呢？

至于多节点检测，在需要检测的节点上执行脚本不就行了吗

**Comment by tanpengsccd** [comment]
> 

soga,我懂了.感谢解答. 脚本没有问题.是我理解错误了. 我是在面板鸡上跑的.我应该是节点鸡上跑的才对.

**Comment by RealSlakey** [comment]
用cloudflare Warp获取原生ipv6的方式解锁的Netflix，使用该脚本检测通过
`wget -O nf https://github.com/sjlleo/netflix-verify/releases/download/2.61/nf_2.61_linux_amd64 && chmod +x nf && clear && ./nf`
然后改了xray的outbound和rule设定，让Netflix走ipv6,
随后用这个脚本检测依然检测不支持网飞，有办法解决吗

**Comment by X-Firefly** [comment]
请问如果不想用怎么卸载掉？

**Comment by xsidc** [comment]
同问，怎么卸载？
如果要修改节点ID，在哪个文件上修改？

**Comment by xsidc** [comment]
终于找到哪里修改了
/root/.csm.config
这个地方
