### ISSUE TITLE
[BUG] Connection blocked when changing network

### ISSUE THREAD

**Issue by thebadgateway** [Anankke/SSPanel-Uim#1404]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP 7.2
MySQL 8.0

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
The bug information. 请描述你遇到的 Bug。
My back-end is old and I edit it myself. I am using XrayR. I recently noticed that limiting active connections for an account stopped working. I changed the code according to this commit Anankke/SSPanel-Uim@c9721cd...Anankke:87961 and now limiting connections works again. But when the user has a limit of 1 connection, then it is worth trying to switch the server 1-2 times and you will see a connection error. How to solve this problem? Previously, when there was a comparison of the IP compliance, everything worked fine. But now users are constantly complaining that they cannot change the server. Each reconnection takes 20-60 seconds.

**Comment by Anankke** [comment]
@thebadgateway 无法做到实时限制，没有这种 API，老的链接会有过期时间

**Comment by thebadgateway** [comment]
You said:
_Real-time restrictions cannot be achieved. Without this API, old links will have an expiration time._


If I understand you correctly, the new API does not make it possible to work with users in real time. Then you need to make a delay for more connections, because it's terribly annoying when you disconnect from Wi-fi and wait 1 minute for vpn.

**Comment by Anankke** [comment]
@thebadgateway 对的没法实时，节点一分钟同步一次数据，你需要把限制拉大一点或者自行修改限制连接的那部分

**Comment by thebadgateway** [comment]
Okay, I will change the connection limit with a time interval of one more connection, but you should fix it for the sake of user convenience.

**Comment by Anankke** [comment]
@thebadgateway pr welcome, there is nothing that I "should," use it or not

**Comment by thebadgateway** [comment]
Although you are right. Should not be doing that.
