### ISSUE TITLE
[BUG]套餐流量重置bug

### ISSUE THREAD

**Issue by aipeach** [Anankke/SSPanel-Uim#1410]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP 7.3.16/mariadb 10.6
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
046affad79fb1e08f1c8e0cde98dc8b3dc37e7fe
**Bug**
The bug information. 请描述你遇到的 Bug。
流量重置逻辑错误，套餐流量重置会使用用户套餐记录里面ID小的，也就是旧套餐，这样用户之前购买的套餐过期了，新套餐也不会重置流量。
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
我新建了4个测试套餐，如下图

![image](https://user-images.githubusercontent.com/44671411/150924640-2dfcbc9e-c945-4c42-afb7-25318bdb8071.png)

新建了5个测试用户，给每个测试用户添加了两个流量重置的套餐，并把总流量修改为0，如下图

![image](https://user-images.githubusercontent.com/44671411/150926057-9c823354-3c8e-440d-b874-0bda10bc678e.png)

套餐关系如下图

![image](https://user-images.githubusercontent.com/44671411/150926451-f32e50c0-ad0a-41a4-be6d-0f1f6ac3e3a9.png)

手动执行定时任务，用户ID为**3、4、6**的用户重置流量

![image](https://user-images.githubusercontent.com/44671411/150926910-791ca2ed-4ffc-4a46-8932-81d2aaf62ea2.png)
![image](https://user-images.githubusercontent.com/44671411/150926811-bc4b6c98-bac9-48da-b6d8-d293a20d38b1.png)

以下是三个流量重置用户的套餐截图

![image](https://user-images.githubusercontent.com/44671411/150927071-51abc332-d827-424a-b9f3-9060382f4ca5.png)
![image](https://user-images.githubusercontent.com/44671411/150927226-4d965fb7-f493-4736-ac12-9dd4223e2102.png)
![image](https://user-images.githubusercontent.com/44671411/150927334-3688f033-50a5-4628-82a8-123c5c2e722e.png)

可以观察到，重置的都是bought id小的，但这是不正确的，套餐重置应该是重置最新的套餐的也就是id大的。
**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by RManLuo** [comment]
确认数据库disable了only full group by。
