### ISSUE TITLE
请问支付账号是怎么解决的？

### ISSUE THREAD

**Issue by videni** [Anankke/SSPanel-Uim#1416]
大家是用的， 境外公司申请的支付账号吗？

**Comment by NimaQu** [comment]
@videni 是的捏，不会有人不在境外也敢非法使用其他信道进行国际联网吧

**Comment by videni** [comment]
@NimaQu  兄弟，telegram的账号是多少，加我一下，新手，可以咨询点问题吗？

**Comment by iamsaltedfish** [comment]
钩咸饵直？

**Comment by Anankke** [comment]
> @NimaQu 兄弟，telegram的账号是多少，新手，可以咨询点问题吗？

你在违法啊你知道吗

**Comment by videni** [comment]
了解一下啊，不然不知道怎么用这个项目。
