### ISSUE TITLE
[BUG] Custom_config中的参数对前端/订阅不生效

### ISSUE THREAD

**Issue by ctrlbbj** [Anankke/SSPanel-Uim#1419]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
e2f28a4
**Bug**
The bug information. 请描述你遇到的 Bug。
配置新增的Custom_config功能中，offset_port_user和server_user不生效，配置后前端/订阅还是使用了节点地址配置的信息

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by jack338c** [comment]
@ctrlbbj 请问：这个SSPanel Custom Config是在前端修改，还是去前端目录文件或是前端网页管理界面里的节点ip下面那行?

**Comment by jack338c** [comment]
@Anankke 
大神
请问这个SSPanel Custom Config是在前端吗，去目录文件还是网页界面的红色圈地方处修改？（请看附图），如果是后者，首先点哪里啊，我想用xtls方式
![Screen Shot 2022-03-10 at 10 32 30 PM](https://user-images.githubusercontent.com/10782586/157985004-f4ee3c2c-e49d-44eb-8506-97e528c277eb.png)

另外，如果我想Disable CustomConfig，应该去哪里设置？

**Comment by baiyou2014** [comment]
我夜想问问这个是在哪里？

**Comment by iamsaltedfish** [comment]
> 请将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .
> 
> * [x]  我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
> * [x]  我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
> * [x]  我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
> * [x]  我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
> 
> **Environment 环境** Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
> 
> **Commit** The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。 [e2f28a4](https://github.com/Anankke/SSPanel-Uim/commit/e2f28a48c25a7c7b8f75ba193da4d5c2a56a8067) **Bug** The bug information. 请描述你遇到的 Bug。 配置新增的Custom_config功能中，offset_port_user和server_user不生效，配置后前端/订阅还是使用了节点地址配置的信息
> 
> **Reproduce** Steps to reproduce the bug. 请逐步描述如何复现 Bug。
> 
> **Expected behavior** What you expected to happen. 请描述你预期的行为。
> 
> **Logs** If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
> 
> **Addition** Additional context here. 如有可能，请提供更多相关资料。

这是一个新功能，需要连接客户端那边的支持。目前尚未形成完整的生态，因此添加节点仍需使用传统方式

**Comment by baiyou2014** [comment]
> > 请将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .
> > 
> > * [x]   我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
> > * [x]   我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
> > * [x]   我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
> > * [x]   我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
> > 
> > **Environment 环境** Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
> > **Commit** The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。 [e2f28a4](https://github.com/Anankke/SSPanel-Uim/commit/e2f28a48c25a7c7b8f75ba193da4d5c2a56a8067) **Bug** The bug information. 请描述你遇到的 Bug。 配置新增的Custom_config功能中，offset_port_user和server_user不生效，配置后前端/订阅还是使用了节点地址配置的信息
> > **Reproduce** Steps to reproduce the bug. 请逐步描述如何复现 Bug。
> > **Expected behavior** What you expected to happen. 请描述你预期的行为。
> > **Logs** If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
> > **Addition** Additional context here. 如有可能，请提供更多相关资料。
> 
> 这是一个新功能，需要连接客户端那边的支持。目前尚未形成完整的生态，因此添加节点仍需使用传统方式

请问一下，怎么先禁用这个呢？DisableCustomConfig这个apiconfig没找到在哪

**Comment by iamsaltedfish** [comment]
> > > 请将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .
> > > 
> > > * [x]    我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
> > > * [x]    我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
> > > * [x]    我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
> > > * [x]    我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
> > > 
> > > **Environment 环境** Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
> > > **Commit** The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。 [e2f28a4](https://github.com/Anankke/SSPanel-Uim/commit/e2f28a48c25a7c7b8f75ba193da4d5c2a56a8067) **Bug** The bug information. 请描述你遇到的 Bug。 配置新增的Custom_config功能中，offset_port_user和server_user不生效，配置后前端/订阅还是使用了节点地址配置的信息
> > > **Reproduce** Steps to reproduce the bug. 请逐步描述如何复现 Bug。
> > > **Expected behavior** What you expected to happen. 请描述你预期的行为。
> > > **Logs** If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
> > > **Addition** Additional context here. 如有可能，请提供更多相关资料。
> > 
> > 
> > 这是一个新功能，需要连接客户端那边的支持。目前尚未形成完整的生态，因此添加节点仍需使用传统方式
> 
> 请问一下，怎么先禁用这个呢？DisableCustomConfig这个apiconfig没找到在哪

这个参数不在面板设置。请参考此 commit
https://github.com/XrayR-project/XrayR/commit/d4ee256bd112818aa76a573d208c28225c429232

**Comment by baiyou2014** [comment]
> > > > 请将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .
> > > > 
> > > > * [x]     我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
> > > > * [x]     我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
> > > > * [x]     我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
> > > > * [x]     我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
> > > > 
> > > > **Environment 环境** Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
> > > > **Commit** The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。 [e2f28a4](https://github.com/Anankke/SSPanel-Uim/commit/e2f28a48c25a7c7b8f75ba193da4d5c2a56a8067) **Bug** The bug information. 请描述你遇到的 Bug。 配置新增的Custom_config功能中，offset_port_user和server_user不生效，配置后前端/订阅还是使用了节点地址配置的信息
> > > > **Reproduce** Steps to reproduce the bug. 请逐步描述如何复现 Bug。
> > > > **Expected behavior** What you expected to happen. 请描述你预期的行为。
> > > > **Logs** If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
> > > > **Addition** Additional context here. 如有可能，请提供更多相关资料。
> > > 
> > > 
> > > 这是一个新功能，需要连接客户端那边的支持。目前尚未形成完整的生态，因此添加节点仍需使用传统方式
> > 
> > 
> > 请问一下，怎么先禁用这个呢？DisableCustomConfig这个apiconfig没找到在哪
> 
> 这个参数不在面板设置。请参考此 commit [XrayR-project/XrayR@d4ee256](https://github.com/XrayR-project/XrayR/commit/d4ee256bd112818aa76a573d208c28225c429232)

谢谢了，我陷入误区了，一直以为在面板设置的

**Comment by jack338c** [comment]
> > > > 请将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .
> > > > 
> > > > * [x]     我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
> > > > * [x]     我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
> > > > * [x]     我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
> > > > * [x]     我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
> > > > 
> > > > **Environment 环境** Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
> > > > **Commit** The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。 [e2f28a4](https://github.com/Anankke/SSPanel-Uim/commit/e2f28a48c25a7c7b8f75ba193da4d5c2a56a8067) **Bug** The bug information. 请描述你遇到的 Bug。 配置新增的Custom_config功能中，offset_port_user和server_user不生效，配置后前端/订阅还是使用了节点地址配置的信息
> > > > **Reproduce** Steps to reproduce the bug. 请逐步描述如何复现 Bug。
> > > > **Expected behavior** What you expected to happen. 请描述你预期的行为。
> > > > **Logs** If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
> > > > **Addition** Additional context here. 如有可能，请提供更多相关资料。
> > > 
> > > 
> > > 这是一个新功能，需要连接客户端那边的支持。目前尚未形成完整的生态，因此添加节点仍需使用传统方式
> > 
> > 
> > 请问一下，怎么先禁用这个呢？DisableCustomConfig这个apiconfig没找到在哪
> 
> 这个参数不在面板设置。请参考此 commit [XrayR-project/XrayR@d4ee256](https://github.com/XrayR-project/XrayR/commit/d4ee256bd112818aa76a573d208c28225c429232)

这个应该是自动禁用了吧，我不是很懂
