### ISSUE TITLE
lnmp环境建站数据库迁移报错：The file "phinx.yml" does not exist

### ISSUE THREAD

**Issue by awds888** [Anankke/SSPanel-Uim#1423]
在/home/wwwroot/xx.xx.xx/vendor/bin/下执行：
./phinx migrate
Phinx by CakePHP - https://phinx.org.

In FileLocator.php line 71:

  The file "phinx.yml" does not exist (in: "/home/wwwroot/sspanel/vendor/bin", "/home/wwwroot/sspanel/vendor/bin/").

migrate [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [--no-info] [-e|--environment ENVIRONMENT] [-t|--target TARGET] [-d|--date DATE] [-x|--dry-run] [--fake]

**Comment by iamsaltedfish** [comment]
哪个教程教你在 vendor/bin 目录下执行的？

phinx.php 在网站根目录，在根目录执行 vendor/bin/phinx migrate

**Comment by awds888** [comment]
https://wiki.sspanel.org/#/install-using-lnmp
这个官方教程这样写的，它没有说必须在根目录执行，是我愚笨我确实没有理解到要在根目录执行。前序步骤也不在根目录

**Comment by iamsaltedfish** [comment]
在
```
安装面板
关闭防跨站

cd /home/wwwroot/sspanel
chattr -i .user.ini
rm .user.ini
```
