### ISSUE TITLE
[BUG]用户等级到期后，可以继续使用高级节点

### ISSUE THREAD

**Issue by zgll** [Anankke/SSPanel-Uim#1426]
简单描述下：

定时任务查看日志执行是正常的，用户到期后会发通知邮件，等级恢复到0。

问题：

等级为0依旧可以使用等级为1的节点，更新订阅后同样。

**Comment by iamsaltedfish** [comment]
如果是使用webapi，理论上不会这样。因为返回的用户列表数据，已经是根据节点等级筛选了的结果。
