### ISSUE TITLE
[BUG]谷歌reCaptcha验证没有加载完成就提交，会卡死不动

### ISSUE THREAD

**Issue by vonaxs** [Anankke/SSPanel-Uim#1428]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
windows chrome

**Commit**
/resources/views/material/auth/login.tpl
/resources/views/material/auth/register.tpl

**Bug**
开启谷歌reCaptcha验证，打开sspanel网站登录或注册页面。
如果网速慢，谷歌reCaptcha验证还没有加载完成时（比如验证框还没有加载出来）
此时如果点击注册/登录按钮，
按照/resources/views/material/auth/register.tpl第265行，
js在执行到recaptcha: grecaptcha.getResponse()时就会卡死不动。

**Reproduce**
var googleResponse = jQuery('#g-recaptcha-response').val();
if (!googleResponse) {
    $("#result").modal();
    $$.getElementById('msg').innerHTML = ‘你需要先通过验证’;
    return ;
}
在258行加上这些代码是否可以解决问题？

期待修复这个问题。

**Comment by DANVEZ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
