### ISSUE TITLE
[Feature]Uim-bridge

### ISSUE THREAD

**Issue by laurieryayoi** [Anankke/SSPanel-Uim#1430]
添加一个主题叫json，tpl直接输出json格式的页面需要的数据

前端开发者可借助这些页面接口开发前端页面，无痛实现前后端分离

[repo](https://github.com/sspanel-uim/SSPanel-Uim-bridge) 
目前只整理了三个页面，等全部弄完以后推送到主项目的对应分支

[前端项目示例](https://github.com/sspanel-uim/uim-bridge-react-template)
react多页面模版，可以根据需求自行替换别的UI组件库，或使用vue, 配置都差不多

部署的话自己动动脑筋吧（，摆弄一下nginx的事情

**Comment by Anankke** [comment]
@laurieryayoi 添加一个接口即可
