### ISSUE TITLE
安装完毕登录出现SQLSTATE[42S02]

### ISSUE THREAD

**Issue by lucyddd** [Anankke/SSPanel-Uim#1431]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.fingerprint' doesn't exist (SQL: insert into `fingerprint` (`user_id`, `fingerprint`, `created_at`) values (1, 4dc2e7b1f0e758a82, 1650811))

**Comment by iamsaltedfish** [comment]
```
vendor/bin/phinx migrate
```
