### ISSUE TITLE
[BUG]新主题分支：后台添加节点后Custom_config变为null

### ISSUE THREAD

**Issue by BaoziCDR** [Anankke/SSPanel-Uim#1432]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
Debian 9 PHP7.4.21
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
https://github.com/Anankke/SSPanel-Uim/commit/d275a520fa9cb09ea548f42d25a7706edf794a51

**Bug**
The bug information. 请描述你遇到的 Bug。
后台添加节点后Custom_config变为null

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
在/admin/node/create添加节点，按以下格式输入Custom_config信息
![image](https://user-images.githubusercontent.com/44897251/166148369-faa5103d-d375-4ca2-8007-a6f3f166cb22.png)
添加成功后，点击编辑发现Custom_config为空，且后端获取到的custom_config也为null
![image](https://user-images.githubusercontent.com/44897251/166148519-55afc349-0913-4157-8bbc-a0f28af81e82.png)
![image](https://user-images.githubusercontent.com/44897251/166148468-f5849578-d6db-44d6-9eac-89bd0a0ea68b.png)

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by iamsaltedfish** [comment]
v2ray 类型节点测试没有复现

**Comment by BaoziCDR** [comment]
> v2ray 类型测试没有复现

。。。这边v2ray 和Trojan均会出现这种情况

**Comment by BaoziCDR** [comment]
> v2ray 类型测试没有复现

顺便想问一下，新主题的支付系统还没做好是么

**Comment by iamsaltedfish** [comment]
> > v2ray 类型测试没有复现
> 
> 顺便想问一下，新主题的支付系统还没做好是么

需要兼容的支付可以发这里我弄一下

**Comment by BaoziCDR** [comment]
> > > v2ray 类型测试没有复现
> > 
> > 
> > 顺便想问一下，新主题的支付系统还没做好是么
> 
> 需要兼容的支付可以发这里我弄一下

不用了 谢谢。我回退到旧主题分支了

**Comment by DANVEZ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
