### ISSUE TITLE
[BUG]套餐购买后，无法在生效中的套餐查询到

### ISSUE THREAD

**Issue by BaoziCDR** [Anankke/SSPanel-Uim#1436]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP7.4.21

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
https://github.com/Anankke/SSPanel-Uim/tree/f7da24f40a5b13fa5c43a3483b8dcd9c24c107a7

**Bug**
The bug information. 请描述你遇到的 Bug。
套餐购买后，无法在生效中的套餐查询到，重复购买限制失效

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
1. 购买套餐之后，在`/user/profile`页面生效中的套餐表格内容为空
2. 购买套餐之后，可重复购买。这在之前版本是不允许的，会提示`您购买的含有自动重置系统的套餐还未过期，无法购买新套餐`

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by iamsaltedfish** [comment]
旧的商店系统一团浆糊，你可以再回退到 new-feat （

**Comment by BaoziCDR** [comment]
> 旧的商店系统一团浆糊，你可以再回退到 new-feat （

行吧（去世

**Comment by Anankke** [comment]
@BaoziCDR 新的也是（确信）

**Comment by iamsaltedfish** [comment]
> > 旧的商店系统一团浆糊，你可以再回退到 new-feat （
> 
> 行吧（去世，能帮我对接个V免签吗

加上了

**Comment by BaoziCDR** [comment]
> > > 旧的商店系统一团浆糊，你可以再回退到 new-feat （
> > 
> > 
> > 行吧（去世，能帮我对接个V免签吗
> 
> 加上了

感谢
