### ISSUE TITLE
Is this a bug or is it missing from my installation

### ISSUE THREAD

**Issue by 354345345htfhft** [Anankke/SSPanel-Uim#1438]
![image](https://user-images.githubusercontent.com/105011968/167239843-05f05d6d-e4fa-41d7-8743-626804dc6ee3.png)
![image](https://user-images.githubusercontent.com/105011968/167239860-c699e46f-8052-4060-a6f5-e9452575d481.png)

**Comment by iamsaltedfish** [comment]
Enable the debug mode in `.config.php`

**Comment by iamsaltedfish** [comment]
昨日全新安装，没有复现问题。

建议参考教程：[https://github.com/sspanel-uim/Wiki/blob/master/install-using-lnmp-dev.md](https://github.com/sspanel-uim/Wiki/blob/master/install-using-lnmp-dev.md)
