### ISSUE TITLE
[BUG] Stripe does not show the configuration

### ISSUE THREAD

**Issue by demianrey** [Anankke/SSPanel-Uim#1439]
Hi, when selecting Stripe in payment configuration, it does not show the data to configure (previously it did)

**Comment by iamsaltedfish** [comment]
Provide a more detailed description.

**Comment by demianrey** [comment]
[
![IMG_20220507_105326](https://user-images.githubusercontent.com/48655207/167262092-cf695b7a-9ecf-4339-88b9-7a619a7989d5.jpg)
]
When selecting Stripe it does not show configuration, I am up to date on dev branch, before everything worked fine

**Comment by demianrey** [comment]
I updated the image with the original project

**Comment by iamsaltedfish** [comment]
有关此问题的修复方法，我已经提交pr。在合并之前，你可以按图片修改文件来临时解决问题

![](https://static01.imgkr.com/temp/4f9a2ae5c0fe4908976fdf3513f39f83.png)

![](https://static01.imgkr.com/temp/9e79201a08a74fb98b98cd2ac2674599.png)

**Comment by demianrey** [comment]
> 有关此问题的修复方法，我已经提交pr。在合并之前，你可以按图片修改文件来临时解决问题
> 
> ![](https://camo.githubusercontent.com/26a9d2b1be0380fc399f43b1c46cd3b3b6af4176cf9b6eb7e7715b65f11ae6af/68747470733a2f2f73746174696330312e696d676b722e636f6d2f74656d702f34663961326165356330666534393038393736666466333531336633396638332e706e67)
> 
> ![](https://camo.githubusercontent.com/040de9c61d7716a14606f35027ee4ff86f54cfa8858bf28fdec3e084224cc9bd/68747470733a2f2f73746174696330312e696d676b722e636f6d2f74656d702f39653739323031613038613734666239386239386364326163323637343539392e706e67)

thank you

**Comment by demianrey** [comment]
Edit. Now the error seems to be from the database 
![Screenshot_2022-05-08-13-12-30-721_com android chrome](https://user-images.githubusercontent.com/48655207/167309650-b7368543-9cf6-4ff4-a05b-03cc9cd298bc.jpg)

**Comment by iamsaltedfish** [comment]
config.php文件开启debug模式，然后在电脑上用浏览器查看控制台具体请求的详细的报错

**Comment by demianrey** [comment]
![image](https://user-images.githubusercontent.com/48655207/167331327-d68a18a1-4d48-4eb9-8f57-da355ef6da6c.png)

is that what you need to see?

**Comment by demianrey** [comment]
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null (SQL: update `config` set `value` = ? where `id` = 137)","file":"\/www\/wwwroot\/pruebas.demianred.tk\/vendor\/illuminate\/database\/Connection.php","line":669}}

the problem is the value of stripe_card

**Comment by iamsaltedfish** [comment]
https://github.com/iamsaltedfish/SSPanel-Uim/commit/05670b751aade360f637a4d541577fece8b68b66

**Comment by demianrey** [comment]
> [iamsaltedfish@05670b7](https://github.com/iamsaltedfish/SSPanel-Uim/commit/05670b751aade360f637a4d541577fece8b68b66)

almost solved, but it doesn't show the Stripe box in the user/code page

**Comment by iamsaltedfish** [comment]
https://github.com/Anankke/SSPanel-Uim/pull/1444/files

测试显示是没问题了，支付和确认到账你再试下

**Comment by demianrey** [comment]
> https://github.com/Anankke/SSPanel-Uim/pull/1444/files
> 
> 测试显示是没问题了，支付和确认到账你再试下

now if everything works fine, thanks ;)
