### ISSUE TITLE
new feat分支 请求后台管理增加新用户功能

### ISSUE THREAD

**Issue by suxiyun** [Anankke/SSPanel-Uim#1440]
new feat分支 请求后台管理增加新用户功能

**Comment by iamsaltedfish** [comment]
已加入此功能

# 如何同步更新

如果你使用新版本主题（new-feat）分支，，可以在网站根目录下执行以下命令
```
git pull origin new-feat:new-feat
```
这会与 github 上的 `new-feat` 分支同步文件变动。有时候，光这么做可能不够，你可能还需要
```
composer update
vendor/bin/phinx migrate
php xcat Tool importAllSettings
```
同时需要注意有没有什么参数在 `.config.example.php` 文件中有，而在你的 `.config.php` 文件中没有的（你可以谷歌一些在线文本比对工具来方便排查）
