### ISSUE TITLE
[BUG] 开启审计规则后，工单卡顿504 并多条重发

### ISSUE THREAD

**Issue by OPPO9008** [Anankke/SSPanel-Uim#1443]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP 7.4.28 (fpm-fcgi) (built: Feb 17 2022 16:16:01)
debian 10
nginx version: nginx/1.20.2
mysql  Ver 8.0.23-14 for Linux on x86_64 (Percona Server (GPL), Release '14', Revision '3558242')

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
d41166d4dc9ce2a5e15ce54cfa85ccd4f5d94438

**Bug**
The bug information. 请描述你遇到的 Bug。
工单回复 关闭按钮卡顿很久后 ，返回错误504
但已经发出工单

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
开启审计规则后开始卡顿，但是已经删除完审计规则还是卡顿

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
工单秒发出，不卡顿

**Logs**
```
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
2022/05/09 13:25:11 [error] 28356#28356: *33507195 FastCGI sent in stderr: "tice:  Undefined offset: 1788 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1808 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1810 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1819 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1832 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1836 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1837 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1844 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1853 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1861 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1867 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1868 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1874 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1878 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1889 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php on line 99PHP message: PHP Notice:  Undefined offset: 1890 in /var/www/SSPanel-Uim/src/Controllers/Mod_Mu/UserController.php 
```
**Addition**
Additional context here. 如有可能，请提供更多相关资料。
没有用宝塔，已确定不是禁用函数的问题

**Comment by iamsaltedfish** [comment]
- 是否配置了有效的发信设置，并且测试发信正常工作？
- 是否在config.php文件中开启了工单右邮件提醒？

**Comment by OPPO9008** [comment]
> * 是否配置了有效的发信设置，并且测试发信正常工作？
> 
>     * 是否在config.php文件中开启了工单右邮件提醒？

谢谢你，已解决

**Comment by zlingxi** [comment]
> 
如何解决的？我的用户工单界面菜单点击后也会500
