### ISSUE TITLE
[BUG]new Feat： 支付测试时除余额支付以外，其他的支付方式会卡在正在处理，无法跳转

### ISSUE THREAD

**Issue by suxiyun** [Anankke/SSPanel-Uim#1450]
F12错误码 ：Failed to load resource: the server responded with a status of 500 (Internal Server Error)
另外能不能把验证码功能打开
辛苦了

**Comment by iamsaltedfish** [comment]
在config.php文件里的支付配置截取发出来看看

**Comment by suxiyun** [comment]
'epay' => [
        'name' => '易支付',
        'min' => '10',
        'max' => '1000',
        'visible_range' => false, // 限制支付方式的可见范围
        'visible_min_range' => '', // 此支付方式可见最小用户id（含）
        'visible_max_range' => '', // 可见最大用户id（含）
        'gateway' => 'http://text.xiyun.co/',
        'uid' => '1000',
        'key' => 'oD06fC6L6J3cC3qD3Il07FgmqD7yO43Q',
        'enable' => true,

**Comment by iamsaltedfish** [comment]
co/改成co试试，还是不行先开debug，然后浏览器控制台看报错

**Comment by suxiyun** [comment]
取消/ 再测试还是不行
控制台提示 Failed to load resource: the server responded with a status of 500 (Internal Server Error)  请求在网络面板中不可用，请重新加载已检查的页面
同时我刷新了一下 支付页面的网页
出现这个网页 HTTP ERROR 502
http://www.xiyun.co/user/order/87d466248379
无法请求的 页面

**Comment by iamsaltedfish** [comment]
截图，看具体的网络请求的响应

**Comment by suxiyun** [comment]
![屏幕截图 2022-05-11 231103](https://user-images.githubusercontent.com/95904036/167885392-e606beed-9f82-46e7-b79d-8ed380b3e752.jpg)
![屏幕截图 2022-05-11 231202](https://user-images.githubusercontent.com/95904036/167885404-9e465d5d-4696-41f9-b3ae-b3fb9e0286bd.jpg)

**Comment by iamsaltedfish** [comment]
点图2的响应

**Comment by suxiyun** [comment]
> 加了新的支付文件执行 composer update 就可以用了

执行之后似乎也是不能用
提示{"error":{"type":"Error","message":"Class 'App\\Services\\Gateway\\AbstractPayment' not found","file":"\/www\/wwwroot\/xiyun\/src\/Services\/Gateway\/WellPay.php","line":10}}
似乎这个支付插件的问题，它支持原版的uim...
或许我应该 在改一下，感谢您的回复
生活愉快~！

**Comment by iamsaltedfish** [comment]
文件的完整内容贴一下，我做一下兼容

**Comment by suxiyun** [comment]
> 文件的完整内容贴一下，我做一下兼容

`<?php

namespace App\Services\Gateway;

use App\Services\View;
use App\Services\Auth;
use App\Services\Config;
use App\Models\Paylist;

class WellPay extends AbstractPayment
{
    
    private $appid;
    private $appkey;
    private $gatewayUri;
    
    /**
     * 签名初始化
     * @param merKey    签名密钥
     */
    

    public static function _name()
    {
        return 'wellpay';
    }
    
    public static function _enable()
    {
        return self::getActiveGateway('wellpay');
    }
    public static function _readableName() {
        return "wellpay";
    }
    public function __construct()
    {
       // $this->appid = '5bk8mnMX';
       //  $this->appkey = 'GNLEHFiA85SKCXqlua';
       
       $this->gatewayUri = 'https://check.bbapk.xyz/api/Wellpay/create';
        
    }
   
    /**
     * @name    准备签名/验签字符串
     */
    public function prepareSign($data)
    {
        ksort($data);
        return http_build_query($data);
    }

    /**
     * @name    生成签名
     * @param sourceData
     * @return    签名数据
     */
    public function sign($data)
    {
        return strtolower(md5($data . $this->appSecret));
    }

    /*
     * @name    验证签名
     * @param   signData 签名数据
     * @param   sourceData 原数据
     * @return
     */
     
    public function verify($context_arr, $signature)
    {
        $s_key = Config::get('wellpay_app_secret');
        $return_arr_forsort=array();
        foreach ($context_arr as $key => $val) {
            if($key!='sign'&&$key!='sign_type'&&$key!='data'&&$val!=null&&$val!='')
                $return_arr_forsort[$key]=$val;
                
                if($key=='data')
                {
                    foreach($val as $key1=>$val1)
                    {
                        if($val1!=null&&$val1!='')
                            $return_arr_forsort[$key1]=$val1;
                    }
                }
        }
        /** 按ASCII码从小到大进行排序 */
       ksort($return_arr_forsort);
        $signStr = htmlspecialchars(http_build_query($return_arr_forsort));
        $sign2 = strtolower(md5($signStr . $s_key));
        return $sign2 === $signature;
    }
    
 public function post($url,$data)
    {
		if (is_array($data))
        {
            $data = http_build_query($data, null, '&');
        }
		
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_HEADER, 0);
        
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
         curl_setopt($curl, CURLOPT_HTTPHEADER,  array(
            "Content-Type: application/x-www-form-urlencoded") );
            
        $data = curl_exec($curl);
        // $data = curl_getinfo($curl,CURLINFO_EFFECTIVE_URL);
        
        
        
        curl_close($curl);
        return $data;
    }
    function http_post_data($url, $data_string) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            "Content-Type: application/x-www-form-urlencoded ") );
        ob_start();
        curl_exec($ch);
        $return_content = ob_get_contents();
        ob_end_clean();
        $return_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        return $return_content;
    }
    
    
    public function purchase($request, $response, $args)
    {
        $price = $request->getParam('price');
        if ($price <1) {
            return json_encode(['code' => -1, 'msg' => '付款金额至少要1.00元.']);
        }
        $user = Auth::getUser();
        $orderno = date("Ymdhms").sprintf("%05d", rand(1, 99999));
        if ($paylist_id == 0) {
            
            $pl = new Paylist();
            $pl->userid = $user->id;
            $pl->total = $price;
            if ($buyshop['id'] != 0) $pl->shop = json_encode($buyshop);
            $pl->datetime = time();
            $pl->tradeno = $orderno;
            $pl->save();
        } else {
            
            $pl = Paylist::find($paylist_id);
            if ($pl->status === 1){
                return ['errcode' => -1, 'errmsg' => "该订单已交易完成"];
            }
        }
    
       
        $appid = Config::get('wellpay_app_id');
        $nonce_str = md5(time());
         $ip = $this->getip();
        $business = array(
           
            'request_time' => time(),// 请求时间
            'version' =>'1.01', //版本号，固定值
            'ip'=> $ip,
            'remark'=>""
        );
        $notify_url = Config::get('baseUrl') . '/payment/notify/wellpay';
        $return_url = Config::get('baseUrl') . '/user/code';
        $price = sprintf("%.2f",$price);
       
        $data = array(
            'appid'=>$appid,//商户编号
            'orderno' => $orderno,//商户订单号，需保证在商户平台唯一
            'totalfee'=> $price,//单位元
            'notifyurl' => $notify_url,//	异步通知地址
            'returnurl' => $return_url,// 支付成功后网页自动跳转地址
          
        
        );
        $appkey = Config::get('wellpay_app_secret');
        ksort($data);
        $sign1 = htmlspecialchars(http_build_query($data));
      
        $sign = strtolower(md5($sign1 . $appkey));
        $business["sign"] = $sign;
        $business["data"] = $data;
   
        $json_return_content= $this->post( $this->gatewayUri, $business);
       
 
        $context_arr = json_decode($json_return_content, true);
 
        $tradeno = $context_arr['data']['waterid'];
        return json_encode(['url' => $context_arr['data']['url'], 'code' => 0, 'pid' => $context_arr['data']['order_no']]);
       // return json_encode(['url' => $result['data']['pay_url'], 'code' => 0, 'pid' => $pl->tradeno]);
    }
    
    public function notify($request, $response, $args)
    {
       
        if (!$this->verify($request->getParams(), $request->getParam('sign'))) {
            die('FAIL');
        }
        $data = $request->getParams();
        //file_put_contents(BASE_PATH . '/storage/easypay.log',$data['data']['order_no'], FILE_APPEND);
        $this->postPayment($data['orderno'], 'wellpay');
        die('success');
    }
    
    public static function getPurchaseHTML()
    {
        return '<div class="card-inner">
						<div class="form-group pull-left">
                            <p class="modal-title">wellpay支持多种充值</p>
                            <div class="form-group form-group-label">
                                <label class="floating-label" for="amount-coinpay">充值金额</label>
                                <input id="amount-coinpay" class="form-control maxwidth-edit" name="amount-coinpay" />
                            </div>
                            <div class="form-group form-group-label">
                               <label><input name="paytype" type="radio" value="alipay" checked="checked"/>支付宝 </label>
                                <label><input name="paytype" type="radio" value="wxpay" />微信 </label>
                            </div>
                             <a class="btn btn-flat waves-attach" id="submitCoinPay" style="padding: 8px 24px;color: #fff;background: #1890ff;"><span class="icon">check</span>&nbsp;充&nbsp;值&nbsp;</a>
                        </div>
                    </div>
                        <script>
                        window.onload = function(){
        $("#submitCoinPay").click(function() {
            var price = parseFloat($("#amount-coinpay").val());
            var paytype = $("input[name=\'paytype\']:checked").val();;
            if (isNaN(price)) {
                $("#result").modal();
                $("#msg").html("非法的金额!");
                return false;
            }
            $(\'#readytopay\').modal();
            $("#readytopay").on(\'shown.bs.modal\', function () {
                $.ajax({
                    \'url\': "/user/payment/purchase/wellpay",
                    \'data\': {
                        \'price\': price,
                        \'paytype\':paytype,
                    },
                    \'dataType\': \'json\',
                    \'type\': "POST",
                    success: (data) => {
                        if (data.code == 0) {
                            $("#result").modal();
                            $("#msg").html("正在跳转WellPay支付网关...");
                            window.location.href = data.url;
                        } else {
                            $("#result").modal();
                            $$.getElementById(\'msg\').innerHTML = data.msg;
                            console.log(data);
                        }
                    }
                });
            });
        });
    };</script>
';
    }
    
    public function getReturnHTML($request, $response, $args)
    {
        header('Location:/user/code');
    }
    
    public function getStatus($request, $response, $args)
    {
        $return = [];
        $p = Paylist::where('tradeno', $_POST['pid'])->first();
        $return['ret'] = 1;
        $return['result'] = $p->status;
        return json_encode($return);
    }
    function getip() {
        
        static $ip = '';
        
        $ip = $_SERVER['REMOTE_ADDR'];
        
        if(isset($_SERVER['HTTP_CDN_SRC_IP'])) {
            
            $ip = $_SERVER['HTTP_CDN_SRC_IP'];
            
        } elseif (isset($_SERVER['HTTP_CLIENT_IP']) && preg_match('/^([0-9]{1,3}\.){3}[0-9]{1,3}$/', $_SERVER['HTTP_CLIENT_IP'])) {
            
            $ip = $_SERVER['HTTP_CLIENT_IP'];
            
        } elseif(isset($_SERVER['HTTP_X_FORWARDED_FOR']) AND preg_match_all('#\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}#s', $_SERVER['HTTP_X_FORWARDED_FOR'], $matches)) {
            
            foreach ($matches[0] AS $xip) {
                
                if (!preg_match('#^(10|172\.16|192\.168)\.#', $xip)) {
                    
                    $ip = $xip;
                    
                    break;
                    
                }
                
            }
            
        }
        
        return $ip;
        
    }


}`

麻烦您了

**Comment by suxiyun** [comment]
[WellPay.txt](https://github.com/Anankke/SSPanel-Uim/files/8675693/WellPay.txt)

**Comment by suxiyun** [comment]
`<?php

namespace App\Services\Gateway;

use App\Services\View;
use App\Services\Auth;
use App\Services\Config;
use App\Models\Paylist;
use App\Controllers\UserController;

class WellPay
{
    
    private $appid;
    private $appkey;
    private $gatewayUri;
    
    /**
     * 签名初始化
     * @param merKey    签名密钥
     */
    

    public static function _name()
    {
        return 'wellpay';
    }
    
    public static function _enable()
    {
        if (empty($_ENV['active_payments']['wellpay']) || $_ENV['active_payments']['wellpay']['enable'] == false) {
            return false;
        }

        return true;
    }
    public static function _readableName() {
        return "wellpay";
    }
    public function __construct()
    {
       // $this->appid = '5bk8mnMX';
       //  $this->appkey = 'GNLEHFiA85SKCXqlua';
       
       $this->gatewayUri = 'https://check.bbapk.xyz/api/Wellpay/create';
        
    }
   
    /**
     * @name    准备签名/验签字符串
     */
    public function prepareSign($data)
    {
        ksort($data);
        return http_build_query($data);
    }

    /**
     * @name    生成签名
     * @param sourceData
     * @return    签名数据
     */
    public function sign($data)
    {
        return strtolower(md5($data . $this->appSecret));
    }

    /*
     * @name    验证签名
     * @param   signData 签名数据
     * @param   sourceData 原数据
     * @return
     */
     
    public function verify($context_arr, $signature)
    {
        $s_key = $_ENV['active_payments']['wellpay']['wellpay_app_secret'];
        $return_arr_forsort=array();
        foreach ($context_arr as $key => $val) {
            if($key!='sign'&&$key!='sign_type'&&$key!='data'&&$val!=null&&$val!='')
                $return_arr_forsort[$key]=$val;
                
                if($key=='data')
                {
                    foreach($val as $key1=>$val1)
                    {
                        if($val1!=null&&$val1!='')
                            $return_arr_forsort[$key1]=$val1;
                    }
                }
        }
        /** 按ASCII码从小到大进行排序 */
       ksort($return_arr_forsort);
        $signStr = htmlspecialchars(http_build_query($return_arr_forsort));
        $sign2 = strtolower(md5($signStr . $s_key));
        return $sign2 === $signature;
    }
    
 public function post($url,$data)
    {
		if (is_array($data))
        {
            $data = http_build_query($data, null, '&');
        }
		
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_HEADER, 0);
        
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($curl, CURLOPT_POST, 1);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $data);
         curl_setopt($curl, CURLOPT_HTTPHEADER,  array(
            "Content-Type: application/x-www-form-urlencoded") );
            
        $data = curl_exec($curl);
        // $data = curl_getinfo($curl,CURLINFO_EFFECTIVE_URL);
        
        
        
        curl_close($curl);
        return $data;
    }
    function http_post_data($url, $data_string) {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            "Content-Type: application/x-www-form-urlencoded ") );
        ob_start();
        curl_exec($ch);
        $return_content = ob_get_contents();
        ob_end_clean();
        $return_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        return $return_content;
    }
    
    
    public function createOrder($amount, $order_no, $user_id)
    {
        $price = $amount;
        if ($price <1) {
            return json_encode(['code' => -1, 'msg' => '付款金额至少要1.00元.']);
        }
        $user = Auth::getUser();
        $orderno = date("Ymdhms").sprintf("%05d", rand(1, 99999));
        
    
       
        $appid = $_ENV['active_payments']['wellpay']['wellpay_app_id'];
       
        $nonce_str = md5(time());
         $ip = $this->getip();
        $business = array(
            'request_time' => time(),// 请求时间
            'version' =>'1.01', //版本号，固定值
            'ip'=> $ip,
            'remark'=>""
        );
        $notify_url = $_ENV['baseUrl'] . '/payments/notify/wellpay';
        $return_url = $_ENV['baseUrl'] . '/user/order/' . $order_no;
        $price = sprintf("%.2f",$price);
       var_dump($notify_url);die;
        $data = array(
            'appid'=>$appid,//商户编号
            'orderno' => $order_no,//商户订单号，需保证在商户平台唯一
            'totalfee'=> $price,//单位元
            'notifyurl' => $notify_url,//	异步通知地址
            'returnurl' => $return_url,// 支付成功后网页自动跳转地址
          
        
        );
        $appkey = $_ENV['active_payments']['wellpay']['wellpay_app_secret'];
        ksort($data);
        $sign1 = htmlspecialchars(http_build_query($data));
      
        $sign = strtolower(md5($sign1 . $appkey));
        $business["sign"] = $sign;
        $business["data"] = $data;
   
        $json_return_content= $this->post( $this->gatewayUri, $business);
       
 
        $context_arr = json_decode($json_return_content, true);
        //file_put_contents(BASE_PATH . '/storage/wellpay.log',$context_arr, FILE_APPEND);
        // $tradeno = $context_arr['data']['waterid'];
        return json_encode([
            'ret' => 1,
            'type' => 'link',
            'link' => $context_arr['data']['url'],
        ]);
        // return json_encode(['url' => $context_arr['data']['url'], 'code' => 0, 'pid' => $context_arr['data']['order_no']]);
       // return json_encode(['url' => $result['data']['pay_url'], 'code' => 0, 'pid' => $pl->tradeno]);
    }
    
    public function notify($request, $response, $args)
    {
        $data = $request->getParams();
        
        file_put_contents(BASE_PATH . '/storage/wellpay1.log',$data['data']['order_no'], FILE_APPEND);
        if (!$this->verify($request->getParams(), $request->getParam('sign'))) {
            die('FAIL');
        }
        $data = $request->getParams();
        
        // $this->postPayment($data['orderno'], 'wellpay');
        UserController::execute($data['data']['order_no']);
        die('success');
    }
    
    public static function getPurchaseHTML()
    {
        return '<div class="card-inner">
						<div class="form-group pull-left">
                            <p class="modal-title">wellpay支持多种充值</p>
                            <div class="form-group form-group-label">
                                <label class="floating-label" for="amount-coinpay">充值金额</label>
                                <input id="amount-coinpay" class="form-control maxwidth-edit" name="amount-coinpay" />
                            </div>
                            <div class="form-group form-group-label">
                               <label><input name="paytype" type="radio" value="alipay" checked="checked"/>支付宝 </label>
                                <label><input name="paytype" type="radio" value="wxpay" />微信 </label>
                            </div>
                             <a class="btn btn-flat waves-attach" id="submitCoinPay" style="padding: 8px 24px;color: #fff;background: #1890ff;"><span class="icon">check</span>&nbsp;充&nbsp;值&nbsp;</a>
                        </div>
                    </div>
                        <script>
                        window.onload = function(){
        $("#submitCoinPay").click(function() {
            var price = parseFloat($("#amount-coinpay").val());
            var paytype = $("input[name=\'paytype\']:checked").val();;
            if (isNaN(price)) {
                $("#result").modal();
                $("#msg").html("非法的金额!");
                return false;
            }
            $(\'#readytopay\').modal();
            $("#readytopay").on(\'shown.bs.modal\', function () {
                $.ajax({
                    \'url\': "/user/payment/purchase/wellpay",
                    \'data\': {
                        \'price\': price,
                        \'paytype\':paytype,
                    },
                    \'dataType\': \'json\',
                    \'type\': "POST",
                    success: (data) => {
                        if (data.code == 0) {
                            $("#result").modal();
                            $("#msg").html("正在跳转WellPay支付网关...");
                            window.location.href = data.url;
                        } else {
                            $("#result").modal();
                            $$.getElementById(\'msg\').innerHTML = data.msg;
                            console.log(data);
                        }
                    }
                });
            });
        });
    };</script>
';
    }
    
    public function getReturnHTML($request, $response, $args)
    {
        header('Location:/user/code');
    }
    
    public function getStatus($request, $response, $args)
    {
        $return = [];
        $p = Paylist::where('tradeno', $_POST['pid'])->first();
        $return['ret'] = 1;
        $return['result'] = $p->status;
        return json_encode($return);
    }
    function getip() {
        
        static $ip = '';
        
        $ip = $_SERVER['REMOTE_ADDR'];
        
        if(isset($_SERVER['HTTP_CDN_SRC_IP'])) {
            
            $ip = $_SERVER['HTTP_CDN_SRC_IP'];
            
        } elseif (isset($_SERVER['HTTP_CLIENT_IP']) && preg_match('/^([0-9]{1,3}\.){3}[0-9]{1,3}$/', $_SERVER['HTTP_CLIENT_IP'])) {
            
            $ip = $_SERVER['HTTP_CLIENT_IP'];
            
        } elseif(isset($_SERVER['HTTP_X_FORWARDED_FOR']) AND preg_match_all('#\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}#s', $_SERVER['HTTP_X_FORWARDED_FOR'], $matches)) {
            
            foreach ($matches[0] AS $xip) {
                
                if (!preg_match('#^(10|172\.16|192\.168)\.#', $xip)) {
                    
                    $ip = $xip;
                    
                    break;
                    
                }
                
            }
            
        }
        
        return $ip;
        
    }


}`

--------------------------------------
我调了下 可以支付了
但是不能回调 支付之后回调总是失败

**Comment by suxiyun** [comment]
[wallpay.zip](https://github.com/Anankke/SSPanel-Uim/files/8679570/wallpay.zip)

**Comment by iamsaltedfish** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/ee26f05b74d08b197d5ed2b1a6b5fad4160b17f9

需要在网站根目录执行 `composer update`，你那样改文件的方法不方便

**Comment by suxiyun** [comment]
> [ee26f05](https://github.com/Anankke/SSPanel-Uim/commit/ee26f05b74d08b197d5ed2b1a6b5fad4160b17f9)
> 
> 需要在网站根目录执行 `composer update`，你那样改文件的方法不方便

嗯..今天才有时间测试一单，没问题了大哥 可以正常支付回调
