### ISSUE TITLE
[BUG]支付宝当面付Data too long

### ISSUE THREAD

**Issue by reizhi** [Anankke/SSPanel-Uim#1451]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP 8.1.5/mysql  Ver 8.0.25
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
6e68ac51cef407037c8697940096806846bb60a2
**Bug**
The bug information. 请描述你遇到的 Bug。
支付宝F2F无法添加公钥和私钥
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
设置，支付，F2FPAY，填写公钥和私钥，点击提交导致错误500。
**Expected behavior**
What you expected to happen. 请描述你预期的行为。
正常提交
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
````message: "SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'value' at row 1 (SQL: update `config` set `value` =...........````
**Addition**
Additional context here. 如有可能，请提供更多相关资料。
value字段值类型varchar，默认长度255明显不够容纳公钥和私钥。手动修改后一切恢复正常。

**Comment by reizhi** [comment]
F2F在线充值：`[object Object] 发生错误了`，不能正确显示二维码。
PHP报错：
````
{
    "message": "Slim Application Error",
    "error": [
        {
            "type": "TypeError",
            "code": 0,
            "message": "App\\Services\\Gateway\\AopF2F::purchase(): Return value must be of type Psr\\Http\\Message\\ResponseInterface, string returned",
            "file": "\/home\/wwwroot\/**\/src\/Services\/Gateway\/AopF2F.php",
            "line": 80,
            "trace": [
                "#0 \/home\/wwwroot\/**\/src\/Services\/Payment.php(94): App\\Services\\Gateway\\AopF2F->purchase()",
                "#1 [internal function]: App\\Services\\Payment::purchase()",
                "#2 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/Handlers\/Strategies\/RequestResponse.php(40): call_user_func()",
                "#3 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/Route.php(281): Slim\\Handlers\\Strategies\\RequestResponse->__invoke()",
                "#4 \/home\/wwwroot\/**\/src\/Middleware\/Auth.php(21): Slim\\Route->__invoke()",
                "#5 [internal function]: App\\Middleware\\Auth->__invoke()",
                "#6 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/DeferredCallable.php(57): call_user_func_array()",
                "#7 [internal function]: Slim\\DeferredCallable->__invoke()",
                "#8 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(70): call_user_func()",
                "#9 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(117): Slim\\Route->Slim\\{closure}()",
                "#10 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/Route.php(268): Slim\\Route->callMiddlewareStack()",
                "#11 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/App.php(503): Slim\\Route->run()",
                "#12 \/home\/wwwroot\/**\/vendor\/zeuxisoo\/slim-whoops\/src\/Zeuxisoo\/Whoops\/Provider\/Slim\/WhoopsMiddleware.php(70): Slim\\App->__invoke()",
                "#13 [internal function]: Zeuxisoo\\Whoops\\Provider\\Slim\\WhoopsMiddleware->__invoke()",
                "#14 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/DeferredCallable.php(57): call_user_func_array()",
                "#15 [internal function]: Slim\\DeferredCallable->__invoke()",
                "#16 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(70): call_user_func()",
                "#17 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/MiddlewareAwareTrait.php(117): Slim\\App->Slim\\{closure}()",
                "#18 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/App.php(392): Slim\\App->callMiddlewareStack()",
                "#19 \/home\/wwwroot\/**\/vendor\/slim\/slim\/Slim\/App.php(297): Slim\\App->process()",
                "#20 \/home\/wwwroot\/**\/public\/index.php(37): Slim\\App->run()",
                "#21 {main}"
            ]
        }
    ]
}
````
确认 APPID 公钥，私钥均正确，同一时间在另一程序相同配置可以生成支付二维码。

**Comment by iamsaltedfish** [comment]
https://github.com/Anankke/SSPanel-Uim/pull/1452/commits/a7c329a1550ed68e285cb6ca5b2e9b22ad30dac6

**Comment by iamsaltedfish** [comment]
已修复，感谢反馈
