### ISSUE TITLE
new-feat分支，请求用户套餐自动续费功能

### ISSUE THREAD

**Issue by miyling** [Anankke/SSPanel-Uim#1453]
- [*] I certify that I have read project Wiki and other issue may related to this one.
- [x] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
new-feat分支，UserJob定时任务为用户过期商品提供自动续费功能

**Solution**

**Addition**

**Comment by iamsaltedfish** [comment]
这个功能只在能够配合付款方式自动扣费的情况下有意义。

让用户先冲一笔钱，然后引导他们使用自动订阅月付套餐，多少有些多此一举。

**Comment by miyling** [comment]
> 这个功能只在能够配合付款方式自动扣费的情况下有意义。
> 
> 让用户先冲一笔钱，然后引导他们使用自动订阅月付套餐，多少有些多此一举。

好的，我明白了
