### ISSUE TITLE
[Error] 执行 vendor/bin/phinx migrate 命令后报错

### ISSUE THREAD

**Issue by Caiueo** [Anankke/SSPanel-Uim#1463]
**Environment 环境**
PHP：7.4
MySQL 5.6.50

**Commit**
new-feat分支

**Error**
执行 vendor/bin/phinx migrate 命令后出现如下错误：
’‘’PDOException: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'remark' can't have a default value in /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:193
Stack trace:
#0 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(193): PDO->exec()
#1 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(108): Phinx\Db\Adapter\PdoAdapter->execute()
#2 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(611): Phinx\Db\Util\AlterInstructions->execute()
#3 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(972): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps()
#4 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\PdoAdapter->executeActions()
#5 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(420): Phinx\Db\Adapter\AdapterWrapper->executeActions()
#6 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(151): Phinx\Db\Adapter\TimedOutputAdapter->executeActions()
#7 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute()
#8 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(623): Phinx\Db\Table->executeActions()
#9 /www/wwwroot/site.domain/databases/migrations/20220419163350_node_remark.php(23): Phinx\Db\Table->update()
#10 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): NodeRemark->change()
#11 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(385): Phinx\Migration\Manager\Environment->executeMigration()
#12 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#13 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#14 /www/wwwroot/site.domain/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute()
#15 /www/wwwroot/site.domain/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#16 /www/wwwroot/site.domain/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#17 /www/wwwroot/site.domain/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#18 /www/wwwroot/site.domain/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun()
#19 /www/wwwroot/site.domain/vendor/robmorgan/phinx/bin/phinx(27): Symfony\Component\Console\Application->run()
#20 /www/wwwroot/site.domain/vendor/bin/phinx(112): include('/www/wwwroot/ww...')
#21 {main}‘’‘

**Reproduce**
配置好数据库，导入数据库 glzjin_all.sql 后，再去执行 vendor/bin/phinx migrate 就报如上错误了

**Comment by iamsaltedfish** [comment]
https://github.com/Anankke/SSPanel-Uim/blob/a354888374759b78011797e130615358de0dc7c2/databases/migrations/20220419163350_node_remark.php#L22

text改string再执行试试

**Comment by Caiueo** [comment]
text改string后再执行也还是报同样的error

**Comment by iamsaltedfish** [comment]
换mysql8或mariadb吧

**Comment by iamsaltedfish** [comment]
删掉以下内容再试试
, 'default' => '无'

**Comment by Caiueo** [comment]
换到 mariadb 后解决了，谢谢
