### ISSUE TITLE
[BUG] Errors in the connection information

### ISSUE THREAD

**Issue by demianrey** [Anankke/SSPanel-Uim#1473]
Updated to today
PHP 8.0
Hi,
When consulting the subscription in v2ray it shows the following, therefore it is not possible to use the subscription
v2rayNG
![image](https://user-images.githubusercontent.com/48655207/168899877-4b1664de-a584-4946-85ab-ff78a60100fa.png)
viewing node information
![image](https://user-images.githubusercontent.com/48655207/168900172-4793db2f-0fe0-46e7-b302-765d41d80b0e.png)

**Comment by iamsaltedfish** [comment]
已修复
