### ISSUE TITLE
[BUG] 官网上 部署 dev 分支 教程 有误，已无法顺利 架设成功

### ISSUE THREAD

**Issue by gn73679** [Anankke/SSPanel-Uim#1474]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
php 8.0
md 10.3
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
 dev 分支
**Bug**
The bug information. 请描述你遇到的 Bug。
官网上 部署 dev 分支 教程 有误，已无法顺利 架设成功
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
请求更新教程
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

流程问题 在

执行数据库迁移

vendor/bin/phinx migrate

**Comment by Anankke** [comment]
@gn73679 会于近日更新

**Comment by iamsaltedfish** [comment]
贴出执行出错的命令的具体输出

**Comment by gn73679** [comment]
依教程 架设 dev，已重复 做了10次 架设
都是 出这错误

![1](https://user-images.githubusercontent.com/70200185/169099930-90ccf422-cde7-44a1-b1c5-862f99f7f0b4.jpg)

依教程 架设 new-feat ，一次就成功

**Comment by iamsaltedfish** [comment]
域名漏了，帮你删了。

看起来是.config.php配置的数据库用户有问题，数据库用户密码不对，或者没有调整表的权限，你检查一下？

**Comment by gn73679** [comment]
數據庫用戶 是 使用 root 帐号 密码  ， 满怪的状况是 相同 架设环境，我只改  php 8.0 > php 7.2，架设 new，数据库搬移命令 是正常的

**Comment by iamsaltedfish** [comment]
没懂你的意思

**Comment by gn73679** [comment]
> 没懂你的意思

同一台机器，同 架设环境

使用 php 7.2  MariaDB 10.4   <成功
架设 部署 new-feat 分支

使用 php 8.0 MariaDB 10.4  < 不成功
架设 部署 dev

**Comment by iamsaltedfish** [comment]
宝塔还是lnmp？

**Comment by gn73679** [comment]
都有试过

宝塔 试了 6次

lnmp 试了 4次

**Comment by iamsaltedfish** [comment]
> 都有试过
> 
> 宝塔 试了 6次
> 
> lnmp 试了 4次
> 
> 系统 使用 deb 10 也试过 deb 11
> 
> vps 是2c3g

数据库名称用的是sspanel么

**Comment by gn73679** [comment]
是，一切 都照 教程

**Comment by iamsaltedfish** [comment]
> 是，一切 都照 教程

没有复现问题。你有设置这个么：

```
$_ENV['db_host']      = '127.0.0.1';
```

**Comment by gn73679** [comment]
有设置

**Comment by gn73679** [comment]
又 重装了 5次

问题有新 进展
使用 php 8.1.5 
网站直接 出 php 错误

降版 php 8.0

网站运行 正常
但 节点 及 切换 用户时 会发生错误

[object Object] 发生了错误。
![1001](https://user-images.githubusercontent.com/70200185/169688281-8583e8b0-ffb3-4e5b-8f1e-a5e473688d0b.jpg)

**Comment by iamsaltedfish** [comment]
不能切换用户的问题修了

**Comment by iamsaltedfish** [comment]
“用户 点 节点资料，显示错误”需要提供更多信息

**Comment by iamsaltedfish** [comment]
“invalid character '<' after top-level value”已修复

**Comment by gn73679** [comment]
> “invalid character '<' after top-level value”已修复

回报  更新 dev 至最新后， 切换 用户 已 正常



用户 点 节点资料，显示错误

![image](https://user-images.githubusercontent.com/70200185/169785387-1f98079e-976f-43ba-bf8a-46d19d9ab6df.png)

![image](https://user-images.githubusercontent.com/70200185/169786336-209882d5-362e-45ee-a358-b5499c4bee5e.png)



“用户 点 节点资料，显示错误”需要提供更多信息 
除了  这2张图，不知 还需要 提供什么

**Comment by iamsaltedfish** [comment]
修了 https://github.com/Anankke/SSPanel-Uim/pull/1510/files
