### ISSUE TITLE
[BUG]支付相关问题

### ISSUE THREAD

**Issue by reizhi** [Anankke/SSPanel-Uim#1475]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
PHP 8.1.5 MySQL 8.0.25
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
70d2be6
**Bug**
The bug information. 请描述你遇到的 Bug。
1.当面付到账金额自动取整
2.VMQ充值不到账
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
1.当面付充值7.5，充值记录显示为7.5，到账金额为8。
2.VMQ支付宝或微信充值任意金额，VMQ系统订单状态为已完成，跳转回SSPanel后不到账。
跳转路径：`https://**/user/payment/purchase/vmqpay?price=2.9&type=1` > `https://**/createOrder?payId=1652866332&type=1&price=2.9&sign=6e1fadbb****2fc0b532887&param=1&isHtml=1&notifyUrl=https%3A%2F%2F**%2Fpayment%2Fnotify%2Fvmqpay&returnUrl=https%3A%2F%2F**%2Fuser%2Fcode` > `https://**/user/code?payId=1652866332&param=1&type=1&price=2.90&reallyPrice=2.90&sign=f591a219919a0****e4fd004e`
**Expected behavior**
What you expected to happen. 请描述你预期的行为。
1.到账金额不应取整或四舍五入。
2.充值金额正确到账
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。
2.应该是小数精度不一致导致sign不匹配所致（2.9 > 2.90）。

**Comment by iamsaltedfish** [comment]
https://github.com/Anankke/SSPanel-Uim/blob/70d2be6d492172f3b27ea9146c9cdc25dc229919/src/Services/Gateway/Vmqpay.php#L65

ResponseInterface 改 string 试试

vmq 后台显示通知成功了吗

按理说应该和金额的小数格式没问题，vmq 那边生成签名的原始数据应该就是2.90？

**Comment by reizhi** [comment]
改 string：
````
Declaration of App\Services\Gateway\Vmqpay::notify($request, $response, $args): string must be compatible with App\Services\Gateway\AbstractPayment::notify(Slim\Http\Request $request, Slim\Http\Response $response, array $args): Psr\Http\Message\ResponseInterface
````
vmq 后台订单是完成状态，不然也不会回调了。
我手算了一下，callback sign 是正确的。

**Comment by iamsaltedfish** [comment]
@Anankke

**Comment by reizhi** [comment]
1.数据库字段设置问题，默认为`decimal(10,0)`，改为`decimal(10,2)`后恢复正常。
2.VMQ 所在机器 PHP 版本问题，降级到7.3后恢复正常。
