### ISSUE TITLE
用户购买套餐后，节点后端报错

### ISSUE THREAD

**Issue by Xavier-0619** [Anankke/SSPanel-Uim#1479]
https://github.com/Anankke/SSPanel-Uim/blob/659602a9abce6eee6a434db8275c04e19a4bc440/src/Controllers/Node/UserController.php#L95

WARNING - get users failed: parse users failed: invalid character '<' after top-level value, result: {"ret":1,"data":[……{"id":127,"uuid":"93be8edb-a320-38c6-a201-077ed49207a7","node_speedlimit":0,"node_connector":1,"alive_ip":null},……]}<br />

<b>Warning</b>:  Undefined array key 127 in <b>/src/Controllers/Node/UserController.php</b> on line <b>95</b><br />

用户购买套餐后，节点后端报错，soga和XrayR都会报类似的错误

commit 659602a9abce6eee6a434db8275c04e19a4bc440 、 php8.0 、 MariaDB 10.1

另外，使用当面付时会有报错：
```
file: "/vendor/anankke/omnipay-alipay/src/Common/Signer.php"
line: 169
message: "Function openssl_free_key() is deprecated"
type: "Whoops\\Exception\\ErrorException"
```

使用易支付时也会有报错：
```
Type: TypeError
Message: trim(): Argument #1 ($string) must be of type string, null given
File: /src/Services/Gateway/Epay.php
Line: 70
```

**Comment by iamsaltedfish** [comment]
问题一：已修复，试试看还会不会这样
问题二：应该不影响用，你可以将具体的文件行中的`openssl_free_key`改成`unset`
问题三：已修复

**Comment by iamsaltedfish** [comment]
此次 `git pull` 后需要执行 `vendor/bin/phinx migrate`

**Comment by Xavier-0619** [comment]
TG bot好像有问题，会一直不断回复同一个指令的内容，所以bot的log咋看？

**Comment by Xavier-0619** [comment]
https://github.com/Anankke/SSPanel-Uim/blob/7465371ab76f39f7b90eee420a802668fdb796e1/src/Utils/Tools.php#L498

节点详细信息页面

`Attempt to read property "server" on string`

**Comment by Xavier-0619** [comment]
https://github.com/Anankke/SSPanel-Uim/blob/7465371ab76f39f7b90eee420a802668fdb796e1/src/Utils/AppURI.php#L61

v2rayn订阅

<b>Warning</b>:  Undefined array key "vtype" in <b>/src/Utils/AppURI.php</b> on line <b>61</b><br />

**Comment by iamsaltedfish** [comment]
修了，`empty` 用惯了。。。换 `isset` 写错了。。

**Comment by vagur1689** [comment]
@iamsaltedfish 大佬帮忙看看 #1497
