### ISSUE TITLE
查看v2ray的节点信息后报错

### ISSUE THREAD

**Issue by blakelu** [Anankke/SSPanel-Uim#1485]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
PHP 8.0 , MySQL 5.7.34

**Bug**
![image](https://user-images.githubusercontent.com/13463232/170186882-6614fce7-b0ef-425d-a616-45b1f3d73dfd.png)
节点配置
![image](https://user-images.githubusercontent.com/13463232/170187516-75530846-cde1-4796-b6ec-cd73bf5de072.png)

**Comment by blakelu** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/13463232/170873533-43e49924-bab4-4f54-a62c-15ff2f4f1622.png">
这个URL.php传入的参数已经是$node下sever字符串了，不是$node对象了
下个方法就会报错
<img width="654" alt="image" src="https://user-images.githubusercontent.com/13463232/170873644-507fda50-d13d-4af7-8e0b-6c1b891a1192.png">
还望大佬修复一下~~

**Comment by zhyi828** [comment]
我也是这里报这个错，会导致500错误，v2ray节点用不了，XrayR后端有这样的信息
```
xrayr-release-xrayr-1  | 2022/06/24 14:05:41 request https://panel.my-domain.com/mod_mu/users/traffic failed: <!DOCTYPE HTML>
xrayr-release-xrayr-1  | <html lang="en">
xrayr-release-xrayr-1  | <head>
xrayr-release-xrayr-1  |     <meta charset="UTF-8">
xrayr-release-xrayr-1  |     <title>Internal Server Error - SSPanel</title>
xrayr-release-xrayr-1  |     <link rel="shortcut icon" href="/favicon.ico"/>
xrayr-release-xrayr-1  |     <link rel="bookmark" href="/favicon.ico" type="image/x-icon"/>
xrayr-release-xrayr-1  |     <link rel="stylesheet" href="/assets/css/error-pages.min.css"/>
xrayr-release-xrayr-1  | </head>
xrayr-release-xrayr-1  | <body>
xrayr-release-xrayr-1  | <div class="container">
xrayr-release-xrayr-1  |     <div class="copy-container center-xy">
xrayr-release-xrayr-1  |         <p>
xrayr-release-xrayr-1  |             500, Internal Server Error.
xrayr-release-xrayr-1  |         </p>
xrayr-release-xrayr-1  |     </div>
xrayr-release-xrayr-1  | </div>
xrayr-release-xrayr-1  |
xrayr-release-xrayr-1  |
xrayr-release-xrayr-1  | </body>
xrayr-release-xrayr-1  | </html>
xrayr-release-xrayr-1  | , %!s(<nil>)
```
看上去是[这次commit](https://github.com/Anankke/SSPanel-Uim/commit/8d677b61aed5420686f9f9dbfbebe16bd7d1c481#diff-93e01b04ead7e0520597044c3b127f882fd7ee2278e39b26f677ed7852edc0ee)引入的，辛苦 @Anankke 大佬帮忙看看

**Comment by hmachine1999** [comment]
一样的报错，用custom config填节点信息的话就506行出错。debian11 php8.1.3 MariaDB 10.3.32

**Comment by vagur1689** [comment]
一样的报错，用custom config填节点信息的话就506行出错。debian11 php8.1.3 MariaDB 10.3.32

**Comment by iamsaltedfish** [comment]
需要提供这些信息：
1）地址栏填写的内容
2）json编辑器中填写的内容

**Comment by iamsaltedfish** [comment]
修了 https://github.com/Anankke/SSPanel-Uim/pull/1510/files
