### ISSUE TITLE
[Feature Request]能不能把之前的server酱添加到new-feat

### ISSUE THREAD

**Issue by DarkMoonCBK** [Anankke/SSPanel-Uim#1492]
- [ ] I certify that I have read project Wiki and other issue may related to this one.
- [ ] I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.

**Feature**
The feature you want.

**Solution**
If you have some solution about this issue, type it here.

**Addition**
Additional context here.

能不能把之前的server酱添加到new-feat

**Comment by iamsaltedfish** [comment]
个人感觉没什么用，没有意义
