### ISSUE TITLE
[BUG]当没有0级节点时, 打开节点列表不会自动展开

### ISSUE THREAD

**Issue by AuthurNero** [Anankke/SSPanel-Uim#1500]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
ubuntu20, php7.4.28

**Commit**
new-feat

**Bug**
当没有0级节点时, 打开节点列表不会自动展开

**Reproduce**
![image](https://user-images.githubusercontent.com/42066536/176814231-c4373f03-38f1-4641-9a2f-d0619ef2ca52.png)

**Expected behavior**
当没有0级节点时, 希望能自动展开第一个tab

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by iamsaltedfish** [comment]
已修复

https://github.com/Anankke/SSPanel-Uim/commit/194e34df7374110ab024e5314f4aa42dfd352551
