### ISSUE TITLE
[BUG]后台【最近登录记录】出现”本机地址“的报告

### ISSUE THREAD

**Issue by lsbjkc** [Anankke/SSPanel-Uim#1507]
就是用户登录记录出现IP地址”127.0.0.1“的本机地址，并且显示登录成功，不知道是安全漏洞还是IP查询bug

**Comment by Anankke** [comment]
有没有可能是 real ip 给你配糊了

**Comment by lsbjkc** [comment]
那应该就是CF的real ip糊了
