### ISSUE TITLE
前端发送邮件提示500

### ISSUE THREAD

**Issue by kailin98** [Anankke/SSPanel-Uim#1520]
使用的gmail smtp
能够确定gmail信息是正确的，且帐号相关服务已开启
之前是好的，突然不知为何提示500
请问大佬如何查看日志进行调试，感谢🙏

**Comment by Anankke** [comment]
@kailin98 打开debug，浏览器 F12 看网络请求的返回报错

**Comment by kailin98** [comment]
调试返回：
`{"error":{"type":"Exception","message":"SMTP connect() failed. https:\/\/github.com\/PHPMailer\/PHPMailer\/wiki\/Troubleshooting","file":"\/www\/wwwroot\/xxx\/src\/Services\/Mail\/Smtp.php","line":68}}
`

我的邮件配置如图：
![image](https://user-images.githubusercontent.com/40024182/183787038-79a7ac7d-875b-4162-b766-d388ab124a48.png)

**Comment by kailin98** [comment]
服务器使用telnet结果如下：
![image](https://user-images.githubusercontent.com/40024182/183787280-d568cb79-3f6e-495f-85e3-66ba8ce5624f.png)

**Comment by Anankke** [comment]
服务商屏蔽了吧

**Comment by kailin98** [comment]
。。。行吧，那我换个方式了，阿里嘎多~
