### ISSUE TITLE
[BUG]trojan 节点端口都是显示的443和后台自己设置的不一样，需要自己手动修改软件中导入节点的端口才行

### ISSUE THREAD

**Issue by XiaoLangCat** [Anankke/SSPanel-Uim#1541]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x]  我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x]  我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x]  我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x]  我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
dev版本是php8.0 new-feat是php7.4 是在一台服务器上搭建的 用的是 MySQL 10.4.14-MariaDB
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
dev / new-feat
**Bug**
The bug information. 请描述你遇到的 Bug。

trojan节点下发的端口都是443端口，我用XrayR 后端对接的，导入到V2rayN 需要手动修改自己后台设置的节点才可以。
我的节点是这样写的。XXXXx.codepay.xxxxxxx;port=12564#12564|host=xxxxxxxxx.codepay.xxxxxxxx

面板用户端trojan节点显示的如下：
<html>
<body>

连接地址： | xxxxxx.codepay.xxxxxx
-- | --
连接端口： | 443
连接密码： | bf456ce8-ba48-3b20-b3b0-4441335c2bcc

<br class="Apple-interchange-newline">
</body>
</html>
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

请查看我搭建好的测试网站，账号：[test@test.com](mailto:test@test.com) 密码：test
https://dev.fanqiangvpnnet.xyz/
http://temp.fanqiangvpnnet.xyz/

**Comment by iamsaltedfish** [comment]
```
XXXXx.codepay.xxxxxxx;port=12564#12564|host=xxxxxxxxx.codepay.xxxxxxxx
```
=>
```
XXXXx.codepay.xxxxxxx;port=12564#12564|host=xxxxxxxxx.codepay.xxxxxxxx|offset_port_user=12345
```
