### ISSUE TITLE
[BUG]new-feat分支，升级 SSPanel UIM發生- Root composer.json requires php >=8.0 but your php version (7.4.30) does not satisfy that requirement.

### ISSUE THREAD

**Issue by bawbaw** [Anankke/SSPanel-Uim#1574]
**Environment 环境**

OS:    centos 7
PHP version:    7.4.30
DB version:    MySQL 10.3.22-MariaDB
Commit:    commit a22a2a6579cb3f31f83a72392fbb47ef7d97b6f2

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
new-feat分支，升级 SSPanel UIM發生底下錯誤，無法升級

php composer.phar u
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php >=8.0 but your php version (7.4.30) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires illuminate/database ^9.0 -> satisfiable by illuminate/database[v9.0.0, ..., v9.28.0].
    - illuminate/database[v9.0.0, ..., v9.28.0] require php ^8.0.2 -> your php version (7.4.30) does not satisfy that requirement.
  Problem 3
    - Root composer.json requires illuminate/pagination ^9.0 -> satisfiable by illuminate/pagination[v9.0.0, ..., v9.28.0].
    - illuminate/pagination[v9.0.0, ..., v9.28.0] require php ^8.0.2 -> your php version (7.4.30) does not satisfy that requirement.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by iamsaltedfish** [comment]
直接 git pull 拉的是 dev 分支，拉 new-feat 应该执行
```
git pull origin new-feat:new-feat
```

**Comment by bawbaw** [comment]
是按照手冊中，更新本地文件至最新版本（new-feat分支）：
$ git fetch --all
$ git reset --hard origin/dev
$ git pull origin new-feat:new-feat

出現的錯誤
