### ISSUE TITLE
[Feature Request] 請問是否可以添加藍新金流平台

### ISSUE THREAD

**Issue by hsly109** [Anankke/SSPanel-Uim#1672]
**Feature 功能请求**

Describe the feature you want. 请描述你想要的功能。
藍新金流收單平台
https://www.newebpay.com/
另外m1你的tg是註銷了麼 我在private chat找不到你了
另外這個功能如果可以加的話希望你直接給我一個報價 以USDT/USDC/BUSD支付

**Comment by M1Screw** [comment]
![TgSticker_3d6e8688](https://github.com/Anankke/SSPanel-Uim/assets/14369594/a1e65513-b036-4642-8710-7a7d3733d2bf)
