### ISSUE TITLE
[BUG] 最新版本每日财务报表报warning，TG机器人每日使用总流量为0

### ISSUE THREAD

**Issue by huah6571** [Anankke/SSPanel-Uim#1673]
**Environment 环境**

OS:    
PHP version:    8.0
DB version:    mysql8.0
Commit:    a77d4683281787052abd6a89f87fa314ee757b56

手动执行财务报表报错如下：

root@debian:~# php /www/wwwroot/airport/xcat FinanceMail day 
PHP Warning:  Trying to access array offset on value of type bool in /www/wwwroot/airport/vendor/esdeathlove/datatables/src/Datatables.php on line 87

Warning: Trying to access array offset on value of type bool in /www/wwwroot/airport/vendor/esdeathlove/datatables/src/Datatables.php on line 87
PHP Warning:  Cannot modify header information - headers already sent by (output started at /www/wwwroot/airport/vendor/esdeathlove/datatables/src/Datatables.php:87) in /www/wwwroot/airport/vendor/esdeathlove/datatables/src/Datatables.php on line 268

Warning: Cannot modify header information - headers already sent by (output started at /www/wwwroot/airport/vendor/esdeathlove/datatables/src/Datatables.php:87) in /www/wwwroot/airport/vendor/esdeathlove/datatables/src/Datatables.php on line 268
Send offline mail to user: 1

同时，tg群中的每日推送，流量为0。这个问题前几天也有人提到过，写着fix了，但tg群这里还是有问题，不知道和上面的warning是否有关系

机场小机器人, [2022/11/21 7:24]
今日签到人数：0 
 今日使用总流量：0B

机场小机器人, [2022/11/21 7:24]
成功执行每日任务

机场小机器人, [2022/11/21 7:24]
今日签到人数：0 
 今日使用总流量：0B

机场小机器人, [2022/11/21 7:24]
成功执行每日任务

**Comment by huah6571** [comment]
> 確認這個問題可以復現。

大佬2022.12版本会修这个问题吗

**Comment by lipeng0820** [comment]
我也有此问题，应该最近还顾不上修这个问题吧。我是因为想解决这个问题，所以才一直保持追随dev版本更新的~哈哈

**Comment by huah6571** [comment]
> 我也有此问题，应该最近还顾不上修这个问题吧。我是因为想解决这个问题，所以才一直保持追随dev版本更新的~哈哈

现在最新的版本，依然存在这个问题？

**Comment by lipeng0820** [comment]
> > 我也有此问题，应该最近还顾不上修这个问题吧。我是因为想解决这个问题，所以才一直保持追随dev版本更新的~哈哈
> 
> 现在最新的版本，依然存在这个问题？

是的，还需要多些耐心等待。或者现在上车，协助开发者大佬们一起捉虫

**Comment by lipeng0820** [comment]
> 經過生產環境的測試，這個問題這次（真的）在 [8069daf](https://github.com/Anankke/SSPanel-Uim/commit/8069daf15363ccece285016dce7127b6b2e4d2df) 及其之後的 commit 中修好了。

😂相信大佬一定是解决了，我也再去重新配置一下，看看是我哪个地方做错了。找到问题前来分享~

也希望大佬有时间的时候能帮忙看下V2ray协议的自定义配置应该如何填写。现在没有了demo站点，希望有一个比较清晰的教程指导，方便大家能够更好的使用sspanel。感谢~

**Comment by M1Screw** [comment]
財務報告功能已經在 https://github.com/Anankke/SSPanel-Uim/commit/029fd4f96d975eba0030ef747e002b27b8c4760c 中修復。
