### ISSUE TITLE
BUG无法添加节点

### ISSUE THREAD

**Issue by wujinxinghe** [Anankke/SSPanel-Uim#1711]
CentOS 7 x64  

PHP 8.0 

SSPanel-Uim-2022.12.0.1

怎么都试了 ，就是无法保存

![1](https://user-images.githubusercontent.com/115438437/206844176-151028e4-246a-4a46-8676-7f5d3bcaffe3.png)

**Comment by Ella-Alinda** [comment]
直接往数据库塞数据吧

**Comment by wujinxinghe** [comment]
> 你好，请问该问题是如何解决的？

路径错误，开发者已经更新了

**Comment by miladrajabi2002** [comment]
i have this issue in 2022.12 version

ubuntu 20
PHP 8.1

I've tried everything, but I can't save
![Screenshot 2022-12-19 012309](https://user-images.githubusercontent.com/51949453/208321428-f3139c3e-a99c-4445-bded-2e92918bfdae.png)
