### ISSUE TITLE
V2ray+WS+TLS使用自定义配置无法连接到节点

### ISSUE THREAD

**Issue by lipeng0820** [Anankke/SSPanel-UIM#1718]
**Environment 环境**

OS:    
PHP version:    
DB version:    
Commit:    

**Bug Info**
冒昧重开这个问题，之前的问题解决了。感谢各位开发者，这次我重新整理一下表述，我认为可能是之前没有表述清楚。
使用环境：纯Ipv6的主机+CF warp（提供ipv4地址用）

面板自定义配置：
连接地址:节点的IPv4 Warp地址

{
  "offset_port_node": "443",
  "offset_port_user": "443",
  "server_sub": "节点的IPv4 Warp地址",
  "host": "CF优选IP的域名",
  "alter_id": "0",
  "network": "ws",
  "security": "tls",
  "ws-opts": {
    "path": "/v2ray",
    "headers": {
      "host": "节点的IPv6地址"
    }
  }
}

XrayR后端：
NodeType：V2ray
CertDomain：节点的IPv6地址

当前的这个配置确实反复尝试2天都没法连接成功。现在订阅能够搜到，但是处于timeout状态。也请教了相关的友人，并没有能够共同找到解决办法。希望能够获得前辈们的一些指点。

**Comment by lipeng0820** [comment]
问题似乎出现在了v2这一部分的代码上。

测试发现，问题聚焦在ws的path上，当我把path的路径写为： 
`  "ws-opts": {
    "path": [
      "/v2ray"
    ],`时，小火箭终于可以使用了，但是还带着⚠叹号，原因不明，Clash下同时提示‘ws-opts.path’expected type 'string',got unconvertible type '[]interface{}'。

如果去掉中括号，报错失效，但同时两端都不可再联通。

另外在log的报错中，也曾看到类似 "path":"/\v2ray" 的报错提示。辛苦开发者大大检查一下这一部分？

**Comment by Ruicw** [comment]
新版确实不能下发，下发的配置都为空
servicename: ''
  ws-opts: null
  h2-opts: null
  http-opts: null
  grpc-opts: null
目前只能TCP模式先用着

**Comment by lipeng0820** [comment]
经过两周的努力，终于找到了最优的且不报错的解法。最后一个小问题留给开发者完善，面板上识别到的IPv6地址不支持缩写模式，比如::1，xrayr默认ipv6缩写，所以会造成客户端报错。over，准备关贴
