### ISSUE TITLE
[BUG]使用install.sh安装时，数据库无法更名，若不输入sspanel则安装过程数据库报错

### ISSUE THREAD

**Issue by lipeng0820** [Anankke/SSPanel-Uim#1729]
**Environment 环境**

OS:    
PHP version:    
DB version:    
Commit:    

**Bug Info**

[BUG]使用install.sh安装时，数据库无法更名，若不输入sspanel则安装过程数据库报错

**Comment by lipeng0820** [comment]
config里其他都正确

**Comment by M1Screw** [comment]
Should be fixed in https://github.com/Anankke/SSPanel-Uim/commit/c2e7ac0d67121a1594413d154c1b26419e8669bf.
