### ISSUE TITLE
节点组别不为0时CLASH订阅获取不到服务器

### ISSUE THREAD

**Issue by lowprofileusername** [Anankke/SSPanel-Uim#1740]
例：用户组别和节点组别同为7,面板里可以看到节点，通过CLASH订阅地址获取不到该节点。

**Comment by qq569500** [comment]
> lowprofileusername

我也遇到相同的问题 + 1

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/b6ecf9abad38430be49159f257e91cf7e55e2df4 .
