### ISSUE TITLE
[BUG]当站点注册设置处于关闭注册或者邀请注册的时候，后台无法添加用户

### ISSUE THREAD

**Issue by chauyuen** [Anankke/SSPanel-Uim#1742]
**Environment 环境**

OS: Debian GNU/Linux 11 x86_64
PHP version: 8.0.22
DB version: MYSQL 8.0.24
Commit: https://github.com/Anankke/SSPanel-Uim/commit/0358e3fc6b26506615cd5ef61723238c4f55f612

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

在后台新增用户，提示添加成功并给出了随机密码但是没有用户被新增。

找到这里实际使用AuthController::registerHelper来新增用户
https://github.com/Anankke/SSPanel-Uim/blob/0358e3fc6b26506615cd5ef61723238c4f55f612/src/Controllers/Admin/UserController.php#L132

给这一行加上return，在F12里能看到回复是提示暂时不对外开放注册

查看这个函数https://github.com/Anankke/SSPanel-Uim/blob/0358e3fc6b26506615cd5ef61723238c4f55f612/src/Controllers/AuthController.php#L247

函数第一步就会判断当前站点设置的注册状态，以及Controllers/Admin/UserController里面邀请码传递为空值。也就是说，当站点处于关闭注册或者邀请注册状态下，后台无法新增用户。

**Comment by Anankke** [comment]
@M1Screw 可以加个管理员的

**Comment by M1Screw** [comment]
我重新看了一下 AuthController，顯然裏面有兩個重複的檢查，實際上只需要保留一個即可正常實現注冊限制的功能，因此你説的這個功能是可以實現的。

**Comment by M1Screw** [comment]
在 https://github.com/Anankke/SSPanel-Uim/commit/7aa4ea3f53532c023f355c7b4590c066075d2ef0 及之後的版本中已經可以正常通過管理員頁面手動添加用戶。
