### ISSUE TITLE
[BUG] xcat Job DailyJob 最新版运行失败

### ISSUE THREAD

**Issue by qq569500** [Anankke/SSPanel-Uim#1751]
**Environment 环境**

OS:    Debian 10
PHP version:    8.0
DB version:    MariaDB 10.7.3
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

当执行每日定时任务是抛出如下错误：

# php xcat Job DailyJob
PHP Warning:  Undefined array key 0 in /www/wwwroot/src/Utils/Tools.php on line 324

Warning: Undefined array key 0 in /www/wwwroot/src/Utils/Tools.php on line 324
PHP Warning:  Trying to access array offset on value of type null in /www/wwwroot/src/Utils/Tools.php on line 324

Warning: Trying to access array offset on value of type null in /www/wwwroot/src/Utils/Tools.php on line 324
PHP Warning:  Attempt to read property "content" on null in /www/wwwroot/src/Command/Job.php on line 88

Warning: Attempt to read property "content" on null in /www/wwwroot/src/Command/Job.php on line 88

**Comment by M1Screw** [comment]
這個應該是你站點裏面沒有任何公告導致的。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/a6c39b1f9eba1596b62ed225ef22cfe56acd0bdb .
