### ISSUE TITLE
[BUG] 订阅下发的端口与"offset_port_user": ""不一致

### ISSUE THREAD

**Issue by qwinwin** [Anankke/SSPanel-Uim#1757]
**Environment 环境**

OS:    Debian 11
PHP version:    8.2
DB version:    8.0
Commit:    https://github.com/Anankke/SSPanel-Uim/releases/tag/2022.12.1-beta3
客户端：ClashForWindows 0.20.10
后端：XrayR 0.8.8

**Bug Info**
订阅获取到的端口依旧为面板分配的用户连接端口，导致clash连接失败，手动将端口修改为“offset_port_user”(40800)可正常使用。
（节点列表中节点状态为绿色正常运行）
节点信息:
<img src="https://pic7.58cdn.com.cn/nowater/webim/big/n_v24cb9dabb596246218276a460b15ada1d.png" alt="image.png" title="image.png" />

**Comment by qq569500** [comment]
参考文档：[可配置选项一览](https://wiki.sspanel.org/#/setup-custom-config?id=%e5%8f%af%e9%85%8d%e7%bd%ae%e9%80%89%e9%a1%b9%e4%b8%80%e8%a7%88)
根据  【//Clash 相关，不影响节点配置下发】提及的部分尝试修改自定义配置

**Comment by M1Screw** [comment]
Shadowsocks 不支持偏移相關設置。
