### ISSUE TITLE
[BUG] 在仅使用中转节点的情况下 后端无法获取节点信息

### ISSUE THREAD

**Issue by Aunero** [Anankke/SSPanel-Uim#1762]
**Environment 环境**

OS:    centos 7.5
PHP version:    8.0
DB version:    mariadb 10
Commit:    2022.12.1-beta4

**Bug Info**

在配置中转节点后, 服务器ip被识别为中转机器的ip, 后端机器无法获取节点信息

建议逻辑: 访问面板节点信息时, 对ip的校验加入custom_config中的host配置ip

日志:
Panel Start fialed: ret {"ret":0,"data":"IP is invalid. Now, your IP address is xx.xx.xx.xx"} invalid

**Comment by M1Screw** [comment]
1. 禁用IP校驗
2. 使用DNS做分區解析
