### ISSUE TITLE
[BUG] 2022.12 fresh installation, can't create node, seems the xhr request URL was wrong

### ISSUE THREAD

**Issue by topcheer** [Anankke/SSPanel-Uim#1763]
**Environment 环境**

OS:    Ubuntu 22
PHP version:    8.2
DB version:    MariaDB 10
Commit:    

**Bug Info**

2022.12 fresh installation, when trying to add node, 404 occured and the xhr request seems to be [domian.root]/node which doesn't exist.

**Comment by topcheer** [comment]
It seems the template file resources/views/tabler/admin/node/create.tpl has incorrect ajax URL defined.   it was /node but should be /admin/node, right?

**Comment by M1Screw** [comment]
You can use the beta version or change the tpl file as a workaround.
