### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wuchen4588** [Anankke/SSPanel-Uim#1767]
**Environment 环境**

OS:    
PHP version: 7.4   
DB version: MySQL5.7   
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

支付报错200
{"ret":1,"type":"url","tradeno":"69CEF1F1","url":"https:\/\/pay.payzy.cn\/submit.php?money=11111111111&name=\u9970\u54c1¬ify_url=https:\/\/panel.wuchencloud.online\/payment\/notify\/xiyunPay&out_trade_no=69CEF1F1&pid=1006&return_url=https:\/\/panel.wuchencloud.online\/user\/code&sitename=SSPanel&type=alipay&sign=540e8c2fc6428af37d8819d339d2a1c6&sign_type=MD5"}
Deprecated: Function get_magic_quotes_gpc() is deprecated in /www/wwwroot/panel.wuchencloud.online/src/Services/Gateway/xiyunPay/epay_core.function.php on line 26

![image](https://user-images.githubusercontent.com/60568101/213613648-d6541e5b-63bd-42ad-ae61-1f5f09ba3f1d.png)

请问一下各位大佬怎么回事，我自己挂的易支付免签无法正常使用，查配置也是正常的。就是不知道200报错到底怎么回事

**Comment by M1Screw** [comment]
非 SSPanel-UIM 安装。
