### ISSUE TITLE
[BUG] shadowrocket连上没网

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1773]
**Environment 环境**

OS:    16
PHP version:    8
DB version:    8
Commit:    

**Bug Info** 

Describe the issue you run into. 请描述你遇到的问题。

shadowrocket小火箭通过订阅能够获取到节点，连通性测试也是有响应时间，但连上后就是没有网络，经过排查，是因为下发的订阅节点自动填充的传输方式为http，我通过手工的方式在小火箭客户端将节点的传输方式改为none  ，然后该节点就可以上网了。然后我去面板里面尝试设置“obfs”: "none"参数无效，通过配置transport_plugin也无效。

**Comment by 34556676** [comment]
求解！

**Comment by 34556676** [comment]
现在节点配置为：
{
  "host": "jp-aws-18-176-38-73.myclash.xyz",
  "obfs": "none",
  "network": "tcp",
  "alter_id": "0",
  "security": "tls",
  "server_sub": "jp-aws-18-176-38-73.myclash.xyz",
  "offset_port_node": "12345"
}



小火箭仍然是vmess+http。这样上不了网，小火箭手动改传输方式为none才解决。请问订阅咋个配置?

**Comment by 34556676** [comment]
经测试，nginx+trojan小火箭支持。

**Comment by zesai** [comment]
找到问题了，目前需要你手动改一下代码
位置 获取订阅点击-》获取 clash 格式数据-〉类型 11
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/39072304/229865031-cfc53c3c-41e2-43ee-b082-fbc8466dab9d.png">
 http-opts 虽然默认是 null 但是导入小火箭后还是默认会使用 http 传输方式
 通过判断 不处理  http-opts 参数，可以行得通
 @M1Screw 您好，请教您一下，这样写会有其他问题吗

**Comment by M1Screw** [comment]
這個是 Shadowrocket 那邊的問題，CFW 和 Statsh 都能正常 ignore null值，就他們不行。

**Comment by 34556676** [comment]
经过测试，trojon小火箭支持，没得问题，建议面板还是加上一键导入小火箭的按钮，后台可控制是否展示。





------------------ 原始邮件 ------------------
发件人: M1Screw ***@***.***&gt;
发送时间: 2023年4月5日 01:55
收件人: Anankke/SSPanel-Uim ***@***.***&gt;
抄送: 聆听雨 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Anankke/SSPanel-Uim] [BUG] shadowrocket连上没网 (Issue #1773)





 
這個是 Shadowrocket 那邊的問題，CFW 和 Statsh 都能正常 ignore null值，就他們不行。
