### ISSUE TITLE
[BUG]点击添加节点按钮无反应SSpanel版本 [2022.12]

### ISSUE THREAD

**Issue by yusheng6a** [Anankke/SSPanel-Uim#1774]
**Environment 环境**

OS:    centos8 
PHP version:    8.0
DB version:    10.6
SSpanel版本
[2022.12]
[使用 OneinStack 部署 SSPanel UIM]
**Bug Info**
添加节点时点击保存按钮无反应，用浏览器开发人员工具查看 网络
显示：
请求 URL: https://**.**/node
请求方法: POST
状态代码: 404

**Comment by Karatla** [comment]
我以为是我操作错误呢，2022.12 和以后的版本都是这样的，都试过了。郁闷折腾了一天

**Comment by Karatla** [comment]
目前哪个版本最稳定？

**Comment by wyUshio** [comment]
> 我以为是我操作错误呢，2022.12 和以后的版本都是这样的，都试过了。郁闷折腾了一天

你数据要都填写正确才能添加

**Comment by wyUshio** [comment]
> 目前哪个版本最稳定？

我之前也是,搞了好久以为是装的有问题,实际上是要所有信息都填写上就可以了...

**Comment by Karatla** [comment]
> > 目前哪个版本最稳定？
> 
> 我之前也是,搞了好久以为是装的有问题,实际上是要所有信息都填写上就可以了...

真的假的，我昨天换了3个版本了，太累了不敢折腾了，目前2022.12稳定吗？2022.12.0.1呢？

**Comment by wyUshio** [comment]
> 


> > > 目前哪个版本最稳定？
> > 
> > 
> > 我之前也是,搞了好久以为是装的有问题,实际上是要所有信息都填写上就可以了...
> 
> 真的假的，我昨天换了3个版本了，太累了不敢折腾了，目前2022.12稳定吗？2022.12.0.1呢？

真的,你可以在另外一个文件夹在装一个版本...没问题在替换过去...直接拉最新的...其实是没问题的...就是所有信息填上就能正常添加..但是少信息控制台会500错还是哪个..我给忘记了

**Comment by itsLittleKevin** [comment]
> > > 目前哪个版本最稳定？
> > 
> > 
> > 我之前也是,搞了好久以为是装的有问题,实际上是要所有信息都填写上就可以了...
> 
> 真的假的，我昨天换了3个版本了，太累了不敢折腾了，目前2022.12稳定吗？2022.12.0.1呢？

一样的问题，[2022.12]和[2022.12.0.1]在添加节点页面上F12都显示状态代码: 404。所有信息都按Custom Config的格式填了一样没反应。请问有解决方案了吗还是只能用老版本？
另外相关文档https://wiki.sspanel.org/#/setup-custom-config不存在，找的是[这里](https://xrayr-project.github.io/XrayR-doc/dui-jie-sspanel/sspanel/sspanel_custom_config.html)的

**Comment by DarckRM** [comment]
同样是这个问题，似乎是按钮响应事件请求接口错了

**Comment by mohammadkamali-309** [comment]
same for me too

**Comment by wyUshio** [comment]
> 

![image](https://user-images.githubusercontent.com/30750943/222957680-4da7b111-bcca-4778-b420-5d4b8b468578.png)
右边的参数不要留空...不知道就写0..就能正常添加

**Comment by itsLittleKevin** [comment]
试了一样没反应，不知道什么问题orz

wyUshio ***@***.***> 于2023年3月5日周日 19:27写道：

**Comment by Sam-Mey** [comment]
> 我以为是我操作错误呢，2022.12 和以后的版本都是这样的，都试过了。郁闷折腾了一天

2023.3

**Comment by xf857** [comment]
麻痹的，真的够折腾的，我他么折腾了两天装上了，2023.4版本，结果呢，同样遇到无法添加节点这个问题，这他么快一年了，压根儿都没人维护么……吐血了，你们都怎么解决的呢，我全都填写了呀，哎，伤不起
