### ISSUE TITLE
你好，我是严金炜，我的身份证号是440608200412030014，我的妈妈是陆日英，我爸爸是严永雄，快来操我妈妈的逼

### ISSUE THREAD

**Issue by ZYH-B** [Anankke/SSPanel-Uim#1775]
你好，我是严金炜，我的身份证号是440608200412030014，我的妈妈是陆日英，我爸爸是严永雄，快来操我妈妈的逼
![IMG_20230102_194039_590](https://user-images.githubusercontent.com/120896667/216281719-98d2bf93-5b82-4a9e-8824-ef67695d44d9.jpg)

**Comment by Anankke** [comment]
卧槽，↑ ↓ 啊！

**Comment by ZYH-B** [comment]
你好，我是严金炜，我的身份证号是440608200412030014，我的妈妈是陆日英，我爸爸是严永雄，快来操我妈妈的逼
![IMG_20230102_194039_590](https://user-images.githubusercontent.com/120896667/216292555-684e9bbd-c0c8-4af5-bbcd-ac3c0fb42867.jpg)

**Comment by ZYH-B** [comment]
你好，我是严金炜，我的身份证号是440608200412030014，我的妈妈是陆日英，我爸爸是严永雄，快来操我妈妈的逼
![Uploading IMG_20230102_194039_590.jpg…]()
