### ISSUE TITLE
订阅链接问题

### ISSUE THREAD

**Issue by zgll** [Anankke/SSPanel-Uim#1777]
版本：2022.12
问题：复制出来的地址，在v2rayN里面提示 订阅内容解码失败(非BASE64码)。升级后出现的问题

**Comment by Aunero** [comment]
v2rayN更新一下

**Comment by zgll** [comment]
> v2rayN更新一下

没有选项开启，旧版兼容吗。新版本更新出来的节点信息也有点问题
