### ISSUE TITLE
同样的系统，完全照wiki上面的操作，也出现这个错误。

### ISSUE THREAD

**Issue by aiturang** [Anankke/SSPanel-Uim#1780]
在最后使用php xcat Tool createAdmin时
报如下错误，
PHP Fatal error:  Uncaught Error: Class "App\Utils\GA" not found in /var/www/aaa/src/Command/Tool.php:302
Stack trace:
#0 /var/www/aaa/src/Command/Tool.php(44): App\Command\Tool->createAdmin()
#1 /var/www/aaa/xcat(51): App\Command\Tool->boot()
#2 {main}
  thrown in /var/www/aaa/src/Command/Tool.php on line 302

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/641dbf378385a243690961b0d403cf357c5d7c62 .

**Comment by aiturang** [comment]
> Fixed in [641dbf3](https://github.com/Anankke/SSPanel-Uim/commit/641dbf378385a243690961b0d403cf357c5d7c62) .

how to use it ?
