### ISSUE TITLE
[BUG]邮箱修改$antiXss->xss_clean($newemail) 漏洞

### ISSUE THREAD

**Issue by vonaxs** [Anankke/SSPanel-Uim#1785]
**Bug Info**

用户修改邮箱的时候
在/src/Controllers/UserController.php 560 行，有以下代码：
$user->email = $antiXss->xss_clean($newemail);

如果用户填写的邮箱含有+号，比如abcd+123@gmail.com.
上面的代码会把邮箱变成：abcd 123@gmail.com.

最后修改成功了，但是保存到数据库的邮箱和用户填写的邮箱不一样，用户无法登录了

**Comment by vonaxs** [comment]
在注册的时候，代码是这样： $user->email = $email;
没有用到antiXss
为什么可以这样？

**Comment by M1Screw** [comment]
這是一個很好的問題。

**Comment by M1Screw** [comment]
https://github.com/voku/anti-xss/issues/15
https://github.com/voku/anti-xss/issues/49
看起來這個像是上游庫最近的某個修改導致的問題，并且相同的問題之前也出現過，建議你更新一下本地的 composer 版本，觀察一下新版本是否還有這樣的情況。

**Comment by vonaxs** [comment]
> [voku/anti-xss#15](https://github.com/voku/anti-xss/issues/15) [voku/anti-xss#49](https://github.com/voku/anti-xss/issues/49) 看起來這個像是上游庫最近的某個修改導致的問題，并且相同的問題之前也出現過，建議你更新一下本地的 composer 版本，觀察一下新版本是否還有這樣的情況。

我的面板比较很就没有更新了。
如果更新composer 版本，怕出现错误。

请问在注册的时候，代码是这样： $user->email = $email;
没有用到antiXss

如果在修改邮箱的时候，用下面的代码检查邮箱是否合格后，我是否可以去掉antiXss
Check::isEmailLegal($email);

**Comment by M1Screw** [comment]
缺失 xss filter 的問題已經在 https://github.com/Anankke/SSPanel-Uim/commit/7aa4ea3f53532c023f355c7b4590c066075d2ef0 中修復。
