### ISSUE TITLE
VLESS订阅问题定位

### ISSUE THREAD

**Issue by sfwtw** [Anankke/SSPanel-Uim#1787]
V2rayNG中vless导入导出是以明文格式或者全base64加密格式，而非vmess的vmess://base64的格式
正确格式应为:
vless://用户id@地址:端口?encryption=none&flow=xtls-rprx-origin&security=tls&sni=&alpn=http%2F1.1&type=tcp&headerType=none&host=aaa.com#别名
或
dmxlc3M6Ly/nlKjmiLdpZEDlnLDlnYA656uv5Y+jP2VuY3J5cHRpb249bm9uZSZmbG93PXh0bHMtcnByeC1vcmlnaW4mc2VjdXJpdHk9dGxzJnNuaT0mYWxwbj1odHRwJTJGMS4xJnR5cGU9dGNwJmhlYWRlclR5cGU9bm9uZSZob3N0PWFhYS5jb20j5Yir5ZCNCg==

而原代码生成的为
vless://55So5oi3aWRA5Zyw5Z2AOuerr+WPoz9lbmNyeXB0aW9uPW5vbmUmZmxvdz14dGxzLXJwcngtb3JpZ2luJnNlY3VyaXR5PXRscyZzbmk9JmFscG49aHR0cCUyRjEuMSZ0eXBlPXRjcCZoZWFkZXJUeXBlPW5vbmUmaG9zdD1hYWEuY29tI+WIq+WQjQo=

因此V2rayNG中无法直接导入VLESS节点

希望大佬能修复

**Comment by sfwtw** [comment]
并且格式也不一样，是  用户id@地址:端口?encryption=none&flow=xtls-rprx-origin&security=tls&sni=&alpn=http%2F1.1&type=tcp&headerType=none&host=aaa.com#别名

而非{xxxx,xxxx,xxxx}形式

**Comment by M1Screw** [comment]
現在的 v2 訂閲是照著 https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2) 做的，如果 vless 那邊有問題的話就先移除出去，之後放到單獨的 function 處理。

説實話，目前我唯一能找到的關於 vless 鏈接格式的討論 https://github.com/XTLS/Xray-core/discussions/716 最後也是不了了之，然後看到另外一個 issue 是這樣講的：

![image](https://user-images.githubusercontent.com/14369594/219899776-bb002fb6-f6fc-4e62-b1f6-54457157f334.png)

我個人的建議是等你們“秒天秒地秒空氣”協議的作者自己先想好這個協議到底要怎麽做再來提 issue =.=
另外現在 LinkController 的架構也足夠簡化了，有能力的還是自己提個 PR 比較快。
