### ISSUE TITLE
[BUG]php xcat Migration new error

### ISSUE THREAD

**Issue by uranus829** [Anankke/SSPanel-Uim#1792]
**Environment 环境**

OS:    Rocky8.7
PHP version:    8.1
DB version:    Mariadb 10.8
Commit:    

**Bug Info**
git clone -b master https://github.com/Anankke/SSPanel-Uim.git .
dev版本下db/migrations/20000101000000_init_database.php.new 没有此文件

Describe the issue you run into. 请描述你遇到的问题。

install.sh 的脚本会执行重命名，是否有误？

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.config' doesn't exist in /data/sspanel_dev/vendor/illuminate/database/Connection.php:414
Stack trace:

**Comment by M1Screw** [comment]
Should be fixed in https://github.com/Anankke/SSPanel-Uim/commit/0ad873a98856102abff3deb4627b7498a36f9d7c by @iamsaltedfish .
