### ISSUE TITLE
[BUG]Warning : Undefined array key "enable_telegram_login" 

### ISSUE THREAD

**Issue by chauyuen** [Anankke/SSPanel-Uim#1808]
**Environment 环境**

OS:Debian GNU/Linux 11 x86_64    
PHP version: 8.0.22 
DB version: MYSQL 8.0.24
Commit:https://github.com/Anankke/SSPanel-Uim/commit/fe583ebc73c9f2e0dd9b34c101701f53d97f1a16

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
首页有报错
Warning: Undefined array key "enable_telegram_login" in/www/wwwroot/SSPanel-Uim/src/Services/Config.php on line 34
需要清理下

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/595de5637286aaeb9ed75174e9115ef4432e4405 .
