### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by lostsoul6** [Anankke/SSPanel-Uim#1813]
Hello I'm using centos 9 as suggested in your installation tutorial but this command shows error :

dnf install php-fpm php-cli php-mysqlnd php-curl php-gd php-mbstring php-xml php-xmlrpc php-opcache php-zip php php-json php-bz2 php-bcmath

error :    

Last metadata expiration check: 0:21:22 ago on Sun 12 Mar 2023 07:38:38 AM EDT.
No match for argument: php-xmlrpc
Error: Unable to find a match: php-xmlrpc

**Comment by M1Screw** [comment]
Skip the package.
