### ISSUE TITLE
[BUG] 新版本登录成功，无法进不了用户中心

### ISSUE THREAD

**Issue by getpool** [Anankke/SSPanel-Uim#1814]
**Environment 环境**

OS:    debian 11
PHP version:    8.2
DB version:    mariadb 10.6.11
Commit:    

**Bug Info**

2022.12.1-rc2版本登录成功，无法进不了用户中心。重新回到登录界面。/db/migrations里的数据不完整？

**Comment by M1Screw** [comment]
檢查一下你瀏覽器裏面的 cookie 有沒有正確設置，如果你沒有用 https 訪問大概率是無法登錄的。

**Comment by getpool** [comment]
明

**Comment by chenyu1990** [comment]
> 檢查一下你瀏覽器裏面的 cookie 有沒有正確設置，如果你沒有用 https 訪問大概率是無法登錄的。

为何如此设计？那本地无法测试吗？
一登录就跳回登录界面，偶尔能看见登录成功的提示！
