### ISSUE TITLE
[BUG]资料修改页面报错Undefined array key "enable_email_verify" in

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1816]
**Environment 环境**

OS:    
PHP version:    8.2
DB version:    mysql 8.0
Commit:    

**Bug Info**   Undefined array key "enable_email_verify" in

Describe the issue you run into. 请描述你遇到的问题。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/b10257df5ea17ac2b534c9105375e1b1fa6bbeb8 .
