### ISSUE TITLE
[BUG] 传统订阅(link订阅)获取内容为空

### ISSUE THREAD

**Issue by lmfcc** [Anankke/SSPanel-Uim#1821]
**Environment 环境**

OS: CentOS 7.4
PHP version: PHP-8.1
DB version: mysql mariadb_10.6
Commit:

**Bug Info**
传统订阅(link订阅)获取内容为空

src/Controllers/LinkController.php下getXXX function 内的判断条件 if ($node_raw->sort === '0') 会有问题

目前至最新dev的db init 内数据表node的sort 设定型态仍为 INT（11）
但此处 '0' 写法的型态会为String 
故 $node_raw->sort === '0' 会为False

实测以下两种方法都能解决该问题: 
A. 数据库不动，更改代码判断值为INT型态如  if ($node_raw->sort === 0) / if ($node_raw->sort === 11) / if ($node_raw->sort === 14) 
（建议） 

B. 代码不动，更改数据库下node数据表的sort 类型为varchar
      （不建议，因为不清楚还有没有其他使用此Sort值的代码）

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/5c3f94d9a100e229f275170483c621cd1ea7fb15 .
