### ISSUE TITLE
[BUG] 新Cron抛出错误「 Attempt to assign property  」

### ISSUE THREAD

**Issue by lmfcc** [Anankke/SSPanel-Uim#1824]
**Environment 环境**

OS: CentOS 7.4
PHP version: PHP-8.1
DB version: mysql mariadb_10.6
Commit:

**Bug Info**
当未获取用户账户等待激活的订单及未获取用户账户已激活的订单时，新Cron抛出错误「 Attempt to assign property "status" on null  」。  

在/src/CommandCron.php的变量$pending_activation_orders 去查询数据库返回不到内容时，该变量型态仍为object，判断object内容不为空在此写法 $pending_activation_orders !== null 仍会为 true，会造成进入if内，此时因$order无内容即是不存在status属性，故形成Attempt to assign property 的问题

以下建议方式可以解决该问题：
a. 使用 count() 函数可以计算对象的属性和方法数量，如果数量为 0，则该对象为空对象，反之数量大于0则不为空对象。
    Ex:   count($pending_activation_orders) > 0

**Comment by M1Screw** [comment]
這個不返回 null 不是正常的表現，測試環境裏面沒有辦法復現。建議檢查一下 MariaDB 的嚴格模式是否關閉，參考 https://mariadb.com/kb/en/sql-mode/ 。

**Comment by lmfcc** [comment]
> 這個不返回 null 不是正常的表現，測試環境裏面沒有辦法復現。建議檢查一下 MariaDB 的嚴格模式是否關閉，參考 https://mariadb.com/kb/en/sql-mode/ 。

首先感謝回覆與提醒檢查 MariaDB 的嚴格模式，經將嚴格模式關閉/禁用後，執行Cron仍然顯示「 Attempt to assign property "status" on null 」的問題。

mysql -e "SELECT @@SQL_MODE, @@GLOBAL.SQL_MODE;"
+------------+-------------------+
| @@SQL_MODE | @@GLOBAL.SQL_MODE |
+------------+-------------------+
|            |                   |
+------------+-------------------+

可能是我敘述不夠清晰，我重新描述一下:

在查詢數據庫未獲取帳戶等待激活的訂單時，此處使用get方法是返回一個包含結果集的集合( collection ) ，所以在查詢數據庫返回獲取值時，如果沒有符合條件的記錄，是空集合，仍是會為object 類型，且在PHP中，"!=="為嚴格比較運算子，表示不僅值必須相等，類型也必須相等，因此在此情況下，也不會等於 null，因為它們的類型不同。

綜合以上原因，當此情況下，按此!==null方式依然會為true，且二者條件都為true執行if true 的內容，此時$order獲取到的是空集合，所以也不存在status屬性，因此拋出Attempt to assign property 的Error。

故若依然使用get方法獲取查詢內容的話，建議可以使用上面提到的count()函數來檢查該object的屬性和方法數量判斷是為空集合或不為空集合。

**另外說明下，$activated_order可以返回null，是使用first方法，first方法是返回一個包含結果的物件 ( single model instance )，如果沒有符合條件的記錄，它將返回 null。

**Comment by M1Screw** [comment]
This is why PHP is a such STUPID language. What the fuck is wrong with this inconsistency between different methods?
