### ISSUE TITLE
[BUG] 新商店商品编辑页面购买限制保存丢失

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1825]
**Environment 环境**

OS:    win11 谷歌浏览器
PHP version:    8.2
DB version:    8.0
Commit:    

**Bug Info**

购买限制表单填写内容后保存了仍然是空，没有正常保存写入数据库。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/ad2cbb5ab7a9d48f8550d56290f6b215d2ce38e1 .
