### ISSUE TITLE
[BUG] 新商品编辑Undefined property: stdClass::$class

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1826]
**Environment 环境**

OS:    谷歌浏览器
PHP version:    8.2
DB version:    8.0
Commit:    

**Bug Info**

新添加的商品编辑报错

等级 <br /><b>Warning</b>:  Undefined property: stdClass::$class in <b>/www/wwwroot/sspanel/storage/framework/smarty/compile/e3a1ef48d3156d7d6e7fa09058bf3c39c28d48c2_0.file.edit.tpl.php</b> on line <b>126</b><br />

等级时长  <br /><b>Warning</b>:  Undefined property: stdClass::$class_time in <b>/www/wwwroot/sspanel/storage/framework/smarty/compile/e3a1ef48d3156d7d6e7fa09058bf3c39c28d48c2_0.file.edit.tpl.php</b> on line <b>134</b><br />

可用流量 <br /><b>Warning</b>:  Undefined property: stdClass::$bandwidth in <b>/www/wwwroot/sspanel/storage/framework/smarty/compile/e3a1ef48d3156d7d6e7fa09058bf3c39c28d48c2_0.file.edit.tpl.php</b> on line <b>142</b><br />

用户分组 <br /><b>Warning</b>:  Undefined property: stdClass::$node_group in <b>/www/wwwroot/sspanel/storage/framework/smarty/compile/e3a1ef48d3156d7d6e7fa09058bf3c39c28d48c2_0.file.edit.tpl.php</b> on line <b>150</b><br />

连接限制  <br /><b>Warning</b>:  Undefined property: stdClass::$speed_limit in <b>/www/wwwroot/sspanel/storage/framework/smarty/compile/e3a1ef48d3156d7d6e7fa09058bf3c39c28d48c2_0.file.edit.tpl.php</b> on line <b>158</b><br />

同时连接ip限制 <br /><b>Warning</b>:  Undefined property: stdClass::$ip_limit in <b>/www/wwwroot/sspanel/storage/framework/smarty/compile/e3a1ef48d3156d7d6e7fa09058bf3c39c28d48c2_0.file.edit.tpl.php</b> on line <b>166</b><br />

**Comment by 34556676** [comment]
解决了。





------------------ 原始邮件 ------------------
发件人: zgll ***@***.***&gt;
发送时间: 2023年4月4日 19:57
收件人: Anankke/SSPanel-Uim ***@***.***&gt;
抄送: 聆听雨 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Anankke/SSPanel-Uim] [BUG] 新商品编辑Undefined property: stdClass::$class (Issue #1826)





 
一样的报错，解决了吗

**Comment by zgll** [comment]
> 解决了。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: zgll ***@***.***&gt; 发送时间: 2023年4月4日 19:57 收件人: Anankke/SSPanel-Uim ***@***.***&gt; 抄送: 聆听雨 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [Anankke/SSPanel-Uim] [BUG] 新商品编辑Undefined property: stdClass::$class (Issue #1826) 一样的报错，解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

求分享。
