### ISSUE TITLE
[BUG]2022.12.1 新商店—账单管理,任何用户都能看到所有账户的账单

### ISSUE THREAD

**Issue by MichaelYang1125** [Anankke/SSPanel-Uim#1827]
**Environment 环境**

OS:    centOS 7.9
PHP version:    8.1 with OPcache
DB version:    MariaDB 10.6
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
新商店—账单管理
1.任何用户都能看到所有账户的账单
2.用户只能点击“查看”自己账单信息，点击其他用户账单“查看”无效。

**Comment by iamsaltedfish** [comment]
好一个平级越权2333

**Comment by M1Screw** [comment]
因為 ajax 部分的代碼是從管理員那邊複製粘貼過去的。這個就是為甚麼需要單元測試和 tester，然而都沒人願意試一下 beta 和 rc 版本那結果就是出這種問題，所有人當小白鼠。不過訂單和帳單那邊本身做過過濾所以問題不大。
