### ISSUE TITLE
[BUG] 订单已激活但时长流量都没有变

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1829]
**Environment 环境**

OS:    centos7.9
PHP version:    8.2
DB version:    8.0
Commit:    

**Bug Info**

订单已激活但时长流量什么都没有变。

**Comment by M1Screw** [comment]
麻煩把問題說具體一點。

**Comment by 34556676** [comment]
> 麻煩把問題說具體一點。

已找到原因了，升级的时候数据库版本报错导致的，我自己修改了字段非空不定义默认default ''就可以了。
