### ISSUE TITLE
[BUG] 管理员页面 管理/邮件设置 保存提交ERROR 和 SMTP设置分页内UI问题

### ISSUE THREAD

**Issue by lmfcc** [Anankke/SSPanel-Uim#1833]
**Environment 环境**

OS: CentOS 7.4
PHP version: PHP-8.1
DB version: mysql mariadb_10.6
Commit:

**Bug Info**
1. 邮件设置 保存提交ERROR

Admin/setting/email.tpl的JS保存click function 的 Ajax的url误植了/admin/setting/captcha ，按route url应该是/admin/setting/email

2. SMTP设置分页内UI问题 ：
   SMTP 用户名重复了三次

**Comment by M1Screw** [comment]
Issue #1 fixed in https://github.com/Anankke/SSPanel-Uim/commit/c4ed1cd3da344be5cee1e9981cbe55b011826459 .

**Comment by M1Screw** [comment]
Issue #2 fixed in https://github.com/Anankke/SSPanel-Uim/commit/c95393e21576524658250d340f0b2a8b60d5c75e .
