### ISSUE TITLE
[BUG] 添加审计规则保存不上

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1835]
**Environment 环境**

OS:    centos7.9
PHP version:    8.2
DB version:    8.0
Commit:    

**Bug Info**

添加审计规则 保存不上。

**Comment by ooo0luo** [comment]
同样问题，审计规则无法保存！
OS: centos8.0
PHP version: 8.1
DB: 10.6

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/2ae2e15f2edba448ddfa85dfbc298a37683affba .
