### ISSUE TITLE
[BUG] 订单支付时 抛出Error

### ISSUE THREAD

**Issue by lmfcc** [Anankke/SSPanel-Uim#1837]
Environment 环境

OS: CentOS 7.4
PHP version: PHP-8.1
DB version: mysql mariadb_10.6
Commit:

Bug Info:
用户在订单支付时，显示错误

错误信息：
App\\Models\\UserMoneyLog::addMoneyLog(): Argument #2 ($before) must be of type float, string given, called in /sspanel/src/Controllers/User/InvoiceController.php on line 111

function addMoneyLog的before和after为 float型态
目前数据库init设定 user的money为decimal(10,2)，在PHP获取后变成string

实测将InvoiceController.php 的使用函数addMoneyLog内的变量  $money_before 与 $user->money 强制转型态为 (float) 可以解决问题

不清楚此处强制转型是否会有其他问题，建议贵团队再测试下。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/c4ed1cd3da344be5cee1e9981cbe55b011826459 .
