### ISSUE TITLE
[BUG] 购买商品没有更新账户过期时间导致节点超时问题

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1841]
**Environment 环境**

OS:    
PHP version:    8.2
DB version:    8.0
Commit:    

**Bug Info**

购买完商品后并没有更新账户过期时间，如果账号已经过期，获取订阅后节点全部超时。

建议在编辑商品页面和后台创建用户页面增加账户过期时间设置选项。

**Comment by M1Screw** [comment]
檢查 ```商品时长 (天)`` 是否正確設置，這個設置決定了為客戶增加的賬戶有效期。

**Comment by 34556676** [comment]
正确设置了商品时长，账号原本没有过期的话他会和商品时长一起增加时间，但账户原本已过期了购买商品后账户过期时间就没有增加。

**Comment by M1Screw** [comment]
我想了一下，唯一觸發這個問題的可能就是你的用戶賬戶過期時間距離當前時間的時間差超過了商品本身的時長（比如用戶賬戶已經過期了60天，但是你的商品本身的時長只有30天）。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/c1abb585a82776ecaef35d6a87a8b26ef7cd503b.

**Comment by 34556676** [comment]
我刚刚发现新注册的用户账号还没过期，充值套餐激活后，过期时间要比等级过期时间少一个月。

**Comment by 34556676** [comment]
大多数情况又是正常的，好像偶尔发生一样。搞不懂，反正是有点问题。

**Comment by 34556676** [comment]
现在用户续费账号过期时间没有更新，影响很大，我都后悔了，在没有解决之前建议不要使用新商店。

**Comment by M1Screw** [comment]
其實賬號本來就不應該過期才對= =，根本就跟新商店系統無關。賬號會過期和定時清理都是以前 sspanel-v3-mod 時代留下來的遺產，那個時候公益機場需要清理用戶否則用戶表會爆滿，放在現在完全是無用的功能。

**Comment by 34556676** [comment]
我也觉得没多大用，可以把这个功能取消掉，或者设置为永久不过期。
