### ISSUE TITLE
[Feature Request] 建议将默认全局模式设置规则模式或是后台可设置

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1842]
**Feature 功能请求**

每次升完级都得手动去修改代码调整为规则模式，有时候升级完就忘记了，很不友好，建议调整为规则模式或者是在后台增加个设置选项。

**Comment by lmfcc** [comment]
藉此Request提个与此Request相关的Clash Config建议：

目前若在appprofile额外设定proxy-groups内容时，不会有节点选项，因为目前是在SubController写了固定的填入方式，升级更新也需要进入此SubController去增加index的值。

故，建议能在appprofile或后台增加个设置选项，用来判断proxy-groups内每个的proxy是否要额外有节点选项。

**Comment by M1Screw** [comment]
> 藉此Request提个与此Request相关的Clash Config建议：
> 
> 目前若在appprofile额外设定proxy-groups内容时，不会有节点选项，因为目前是在SubController写了固定的填入方式，升级更新也需要进入此SubController去增加index的值。
> 
> 故，建议能在appprofile或后台增加个设置选项，用来判断proxy-groups内每个的proxy是否要额外有节点选项。

這個是目前訂閲系統的一個缺陷，即不夠模塊化，這個也跟通用訂閲系統初始設計有關係。之後的目標是將該系統修改為與 Payment 類似的 Hot Swap 插件形式，這樣在支持小衆客戶端時更爲方便。

**Comment by M1Screw** [comment]
這個功能已經在 https://github.com/Anankke/SSPanel-Uim/commit/5dd93254543991bdc29705d11ef7943661ad3a83 中實現，你只需要用默認配置覆蓋現有的 config/appprofile.php，然後按照你的需求修改 Clash 的下發配置即可。
