### ISSUE TITLE
[BUG] Error 500 when trying to create a new node, on a newly installed sspanel

### ISSUE THREAD

**Issue by peter-weiss-2569** [Anankke/SSPanel-Uim#1846]
**Environment 环境**

OS:   Ubuntu 22.04
PHP version:   8.1
DB version:   MariaDB 10.6
Commit:  branch 2022.12.1

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

when trying to create a new node, no matter what type or setting, I get a 500 error:
the error states:

Warning: Undefined array key "exceptionId" in <b>/www/wwwroot/site dir/storage/framework/smarty/compile/bd6f24975afe766496661f955a776b9dc5a96ebd_0.file.500.tpl.php on line 44
Warning:  Attempt to read property "value" on null in <b>/www/wwwroot/site dir/storage/framework/smarty/compile/bd6f24975afe766496661f955a776b9dc5a96ebd_0.file.500.tpl.php on line 44

**Comment by M1Screw** [comment]
Make sure you filled in every required item in the form.
