### ISSUE TITLE
升级过程报错

### ISSUE THREAD

**Issue by zgll** [Anankke/SSPanel-Uim#1848]
现运行版本：2022.12 准备升级到最新 2022.12.1。
执行命令后提示：Forward to 2023020100
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'alive_ip' already exists

请问该如何解决

**Comment by M1Screw** [comment]
先通過 ```php xcat Tool importAllSettings``` 導入 setting.json，然後應該就能正常觸發遷移了。

**Comment by zgll** [comment]
> 先通過 `php xcat Tool importAllSettings` 導入 setting.json，然後應該就能正常觸發遷移了。

执行之后，提示我：没有任何新数据库设置项需要添加

我尝试执行：php xcat Migration latest
同样的报错提示：
Current database version 20230201.

Found migration version 2023030500.
Found migration version 2023031700.
Found migration version 2023021600.
Found migration version 2023031701.
Found migration version 2023020100.

Forward to 2023020100
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'alive_ip' already exists in /db/migrations/2023020100-init.php:12

感觉是数据库一直迁移不了，能通过别的方式迁移升级吗

**Comment by zgll** [comment]
> 你看一下 config 表裏面 db_version 是不是 20230201，如果是的話就改成 2023020100。

确实是20230201，改了

现在执行是新的报错信息：php xcat Migration latest
Current database version 2023020100.

Found migration version 2023030500.
Found migration version 2023031700.
Found migration version 2023021600.
Found migration version 2023031701.
Found migration version 2023020100....skip

Forward to 2023021600
Forward to 2023030500
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `invoice_id` int(11) DEFAULT 0' at line 1 in db/migrations/2023030500-add_paylist_invoice_id.php:11

我的数据库是MySQL 8.0，关闭了严格模式，新版本现在是不兼容了吗

**Comment by M1Screw** [comment]
Readme 還是 Wiki 都很明確寫明了要用 MariaDB 10.6+ 是有他的原因的，MySQL 8 跟 MariaDB 最新的 LTS 版本不能視作完全兼容。你這個會報錯的原因是因爲 ALTER TABLE xxx ADD COLUMN IF NOT EXISTS 這個 statement 是 MariaDB 10.0.2 以上才有的，MySQL 要實現這個功能就必須用 IF 配合額外的 select 去做判斷。

https://stackoverflow.com/questions/972922/add-column-to-mysql-table-if-it-does-not-exist
https://mariadb.com/kb/en/alter-table/#add-column
