### ISSUE TITLE
[Feature Request]如何在群辉上部署sspanel呢？

### ISSUE THREAD

**Issue by maxage** [Anankke/SSPanel-Uim#1854]
**Feature 功能请求**

Describe the feature you want. 请描述你想要的功能。

如何在群辉实现部署sspanel呢？

dockerhub上找到一个镜像，部署一直出错。

不知道是否这个项目可部署在群辉？有没有大佬出一个教程？

**Comment by M1Screw** [comment]
群暉有個功能叫做 Virtual Machine Manager，用其部署一個 Linux VM 然後照著教程裝就行了。

https://www.synology.com/zh-tw/dsm/feature/virtual_machine_manager
