### ISSUE TITLE
[Feature Request] 请加回管理员切换到用户功能

### ISSUE THREAD

**Issue by Ruicw** [Anankke/SSPanel-Uim#1855]
**Feature 功能请求**

Describe the feature you want. 请描述你想要的功能。
经常需要协助用户，没有这个旧主题上的这个功能太不方便啦

**Comment by 34556676** [comment]
商品套餐流量每月重置是不是也没了？

**Comment by M1Screw** [comment]
這個功能可以加回去，但是要等 UserAPI/AdminAPI 那邊重寫，Auth 系統重做完成才行。Admin 和 User 從來就不應該共用同一組 Cookie 驗證更不要說直接互相切換權限等級，這個如果不謹慎的話就是一個災難在等待發生。

**Comment by Sam-Mey** [comment]
release 2023.3 后台管理面板admin 经常自动跳转到用户 user 页面   ？！！！

**Comment by Sam-Mey** [comment]
新版本 release 2023.3 版本

{
	"offset_port_user": "这里填用户分配的端口无法保存，并且显示❌", //前端/订阅中下发的端口
    "offset_port_node": "12345", //节点服务器下发的端口
    "server_user": "hk.domain.com", //前端/订阅中下发的服务器地址
    "mu_encryption": "chacha20-ietf-poly1305", // `aes-128-gcm`, `aes-256-gcm`, `chacha20-ietf-poly1305`三者之一
}
