### ISSUE TITLE
[Feature Request] Reality Secutity

### ISSUE THREAD

**Issue by kontorol** [Anankke/SSPanel-Uim#1856]
**Feature 功能请求**
Reality Secutity.
Describe the feature you want. 请描述你想要的功能。
Reality Secutity.

**Comment by M1Screw** [comment]
看了一下，似乎目前只有 Clash.Meta 這個 Clash Kernel 可以支持，不過要改的地方不算太多就是了。

**Comment by M1Screw** [comment]
Clash Meta support is added at https://github.com/Anankke/SSPanel-Uim/commit/977794f670dac62e136e0ff916cf587bca8718f4.
