### ISSUE TITLE
你好，关于数据库的疑惑

### ISSUE THREAD

**Issue by IMwing-020** [Anankke/SSPanel-Uim#1864]
你好，我下载了“SSPanel V3 魔改再次修改版”这个版本，对于数据库文件有点疑惑，在db文件夹里面有个update.sql，请问这个update.sql是数据库升级文件还是这个版本的数据库文件？如果是升级文件，那应该从哪个版本来先安装后升级？

**Comment by M1Screw** [comment]
update.sql 適用於 2021.12.1 之前的版本升級至 2021.12.1 版本所使用的，如果是新安裝則忽略該文件即可。
