### ISSUE TITLE
[Feature Request] 礼品卡充值功能

### ISSUE THREAD

**Issue by SHIINMASHIRO** [Anankke/SSPanel-Uim#1869]
**Feature 功能请求**

Describe the feature you want. 请描述你想要的功能。
希望加回以前的充值码储值功能，目前只看到管理界面有生成礼品卡功能。

**Comment by jiderlesi** [comment]
同样强烈建议添加充值码储值功能

**Comment by M1Screw** [comment]
在做了，在做了.jpg
