### ISSUE TITLE
[BUG]更换MariaDB后使用 php vendor/bin/phinx migrate 升级到 UpdateTicket 仍然报错

### ISSUE THREAD

**Issue by OPPO9008** [Anankke/SSPanel-Uim#1872]
**Environment 环境**

OS:    Ubuntu 22.4
PHP version:     PHP 8.1.2-1ubuntu2.11 (cli)
DB version:    Server version: 10.7.8-MariaDB-1:10.7.8+maria~ubu2004 mariadb.org binary distribution
Commit:    152be519fa5a62ecf988250f2beeab836ae0aec1

**Bug Info**

上一次的错误 #1865 后，升级数据库仍然报错，是不是要先清空ticket 表

```
PDOException: SQLSTATE[23000]: Integrity constraint violation: 4025 CONSTRAINT `ticket.content` failed for `****`.`ticket` in /var/www/test/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
```

**Comment by M1Screw** [comment]
> 是不是要先清空ticket 表

是的。
