### ISSUE TITLE
[BUG] 账户信息页面报错

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1875]
**Environment 环境**

OS:    
PHP version:    8.2
DB version:    mariadb10.6
Commit:    

**Bug Info**

Slim Application Error
The application could not run because of the following error:

Details
Type: Error
Code: 0
Message: Class "GeoIp2\Database\Reader" not found
File: /www/wwwroot/sspanel/src/Utils/GeoIP2.php
Line: 20
Trace
#0 /www/wwwroot/sspanel/src/Utils/Tools.php(27): App\Utils\GeoIP2->__construct()
#1 /www/wwwroot/sspanel/src/Controllers/UserController.php(81): App\Utils\Tools::getIpLocation()
#2 /www/wwwroot/sspanel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): App\Controllers\UserController->profile()
#3 /www/wwwroot/sspanel/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#4 /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#5 /www/wwwroot/sspanel/src/Middleware/Auth.php(28): Slim\MiddlewareDispatcher->handle()
#6 /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): App\Middleware\Auth->process()
#7 /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#8 /www/wwwroot/sspanel/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#9 /www/wwwroot/sspanel/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#10 /www/wwwroot/sspanel/src/Middleware/ErrorHandler.php(28): Slim\Routing\RouteRunner->handle()
#11 /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): App\Middleware\ErrorHandler->process()
#12 /www/wwwroot/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#13 /www/wwwroot/sspanel/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#14 /www/wwwroot/sspanel/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#15 /www/wwwroot/sspanel/public/index.php(40): Slim\App->run()
#16 {main}
[Go Back](https://www.myclash.xyz/user/profile#)

**Comment by lmfcc** [comment]
在实例化时，找不到本地地址库/storage/GeoLite2-City/GeoLite2-City.mmdb和/storage/GeoLite2-Country/GeoLite2-Country.mmdb所抛出的错误

解决方法：
在Config.conf 补上缺少GEOIP2的KEY变量和值，之后执行php xcat Update，让系统去maxmind获取下载地址库
// MaxMind License Key
$_ENV['maxmind_license_key'] = ''

不然就是手动去maxmind下载GeoLite2-City.mmdb和GeoLite2-Country.mmdb放到指定的位置。

**Comment by M1Screw** [comment]
composer 安裝的話直接運行 update.sh，同時你還需要配置 Maxmind 的帳號 API 金鑰以進行自動更新。

**Comment by 34556676** [comment]
[
  {
    "type": "TypeError",
    "code": 0,
    "message": "App\\Utils\\Tools::getIpLocation(): Return value must be of type string, null returned",
    "file": "/www/wwwroot/sspanel/src/Utils/Tools.php",
    "line": 39
  }
]
