### ISSUE TITLE
[BUG] 已激活实际时长没更新

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1879]
**Environment 环境**

OS:    
PHP version:    
DB version:    
Commit:    

**Bug Info**

前端时间就出现过这个情况，不知道是不是刚升级导致的。定时任务查看执行都是successful，已激活就是没有实际更新等级时间。

**Comment by M1Screw** [comment]
不如你貼一下你的產品到底是怎麽設置的，不然是沒有辦法復現你説的問題。

**Comment by 34556676** [comment]
PHP Fatal error:  Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `sspanel`.`user`.`node_group` at row 1 in /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php:570
Stack trace:
#0 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(570): PDOStatement->execute()
#1 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#3 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(558): Illuminate\Database\Connection->run()
#4 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(510): Illuminate\Database\Connection->affectingStatement()
#5 /www/wwwroot/sspanel/vendor/illuminate/database/Query/Builder.php(3356): Illuminate\Database\Connection->update()
#6 /www/wwwroot/sspanel/vendor/illuminate/database/Eloquent/Builder.php(1011): Illuminate\Database\Query\Builder->update()
#7 /www/wwwroot/sspanel/vendor/illuminate/database/Eloquent/Model.php(1214): Illuminate\Database\Eloquent\Builder->update()
#8 /www/wwwroot/sspanel/vendor/illuminate/database/Eloquent/Model.php(1131): Illuminate\Database\Eloquent\Model->performUpdate()
#9 /www/wwwroot/sspanel/src/Command/Cron.php(87): Illuminate\Database\Eloquent\Model->save()
#10 /www/wwwroot/sspanel/xcat(51): App\Command\Cron->boot()
#11 {main}

Next Illuminate\Database\QueryException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `sspanel`.`user`.`node_group` at row 1 (SQL: update `user` set `transfer_enable` = 13194139533312, `node_speedlimit` = 50, `node_iplimit` = 3, `class` = 2, `class_expire` = 2024-03-31 21:27:01, `expire_in` = 2024-03-31 21:27:01, `node_group` =  where `id` = 40) in /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php:760
Stack trace:
#0 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback()
#1 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(558): Illuminate\Database\Connection->run()
#2 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(510): Illuminate\Database\Connection->affectingStatement()
#3 /www/wwwroot/sspanel/vendor/illuminate/database/Query/Builder.php(3356): Illuminate\Database\Connection->update()
#4 /www/wwwroot/sspanel/vendor/illuminate/database/Eloquent/Builder.php(1011): Illuminate\Database\Query\Builder->update()
#5 /www/wwwroot/sspanel/vendor/illuminate/database/Eloquent/Model.php(1214): Illuminate\Database\Eloquent\Builder->update()
#6 /www/wwwroot/sspanel/vendor/illuminate/database/Eloquent/Model.php(1131): Illuminate\Database\Eloquent\Model->performUpdate()
#7 /www/wwwroot/sspanel/src/Command/Cron.php(87): Illuminate\Database\Eloquent\Model->save()
#8 /www/wwwroot/sspanel/xcat(51): App\Command\Cron->boot()
#9 {main}
  thrown in /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php on line 760

**Comment by 34556676** [comment]
[https://www.myclash.xyz/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-04-01%20213707.png](url)

**Comment by 34556676** [comment]
[](https://www.myclash.xyz/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202023-04-01%20213707.png)

**Comment by 34556676** [comment]
紧急求助啊

**Comment by 34556676** [comment]
Centos7.9
Php8.2
Mariadb10.6

**Comment by 34556676** [comment]
咋说

**Comment by M1Screw** [comment]
> *Cron这处建议应该写个throw会比较严谨点，如果抛错了，没有save上，order就不打上activated、update和echo 已激活

This has been implemented along with a better input check.

**Comment by 34556676** [comment]
仍然报以上错误，我手动修改定时任务cron.php文件中的$user->node_group = $content->node_group;为$user->node_group = 0;就正常。请紧急排查修复。已严重影响运营使用。

**Comment by 34556676** [comment]
我手动修改了product表里面的content字段当中的json数据为"node_group":"0" 。现在定时任务没有报错，问题卡在订单一直处于等待激活状态，不激活。

**Comment by 34556676** [comment]
我新注册个账户就可以，之前那个账户手动设置等级过期，订单就一直处于未激活，如果是订单购买自然过期的就没问题。
