### ISSUE TITLE
[BUG]登录请求后跳转到/user的时候http请求报302 Found

### ISSUE THREAD

**Issue by newswow** [Anankke/SSPanel-Uim#1881]
**Environment 环境**

OS:    centos team9
PHP version:    8.1
DB version:   db10.11 
Commit:    

**Bug Info**
按照centos 9的流程搭建完毕后，
登录请求后跳转到/user的时候http请求报302 Found。还是停留在登入界面。

**Comment by M1Screw** [comment]
必須使用 HTTPS 才能正常設置登錄 cookie。
