### ISSUE TITLE
[BUG] 更新时报错，导致数据库无法创建online_log

### ISSUE THREAD

**Issue by lowprofileusername** [Anankke/SSPanel-Uim#1884]
**Environment 环境**

OS:    ubuntu 22.04
PHP version:    php 8.2
DB version:    0.6.12-MariaDB
Commit:    latest 

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

.config.php 文件备份成功。
没有任何新 .config.php 配置项需要添加。
迁移完成。
没有任何新数据库设置项需要添加
Current database version 20230201.

Found migration version 2023032600.
Found migration version 2023031701.
Found migration version 2023021600.
Found migration version 2023030500.
Found migration version 2023020100.
Found migration version 20000101000000.
PHP Fatal error:  Uncaught Error: Class "Phinx\Migration\AbstractMigration" not found in /home/xxx/web/x.xxx.xx/public_html/SSPanel-Uim/db/migrations/20000101000000_init_database.php:8
Stack trace:
#0 /home/xxx/web/x.xxx.xx/public_html/SSPanel-Uim/src/Command/Migration.php(85): require_once()
#1 /home/xxx/web/x.xxx.xx/public_html/SSPanel-Uim/xcat(51): App\Command\Migration->boot()
#2 {main}
  thrown in /home/xxx/web/x.xxx.xx/public_html/SSPanel-Uim/db/migrations/20000101000000_init_database.php on line 8

升级后后端无法启动，看记录应该也是找不到这个表。不知道为什么会报错PHP Fatal error:  Uncaught Error: Class "Phinx\Migration\AbstractMigration" not found 。是php的问题还是MariaDB的问题？谢谢

**Comment by M1Screw** [comment]
把 db 資料夾裏面的 20000101000000 migration 文件去掉，那個是以前老版本遷移中留下來的。
