### ISSUE TITLE
[BUG]全新安装最新dev 在线IP 无法显示

### ISSUE THREAD

**Issue by hehe2g3** [Anankke/SSPanel-Uim#1885]
**Environment 环境**

OS:    ubuntu 22
PHP version:    8.1
DB version:    10.6
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

按照wiki执行了所有步骤
打开页面admin/online报错
DataTables warning: table id=data_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

浏览器dev显示
jquery.min.js:2          POST https://XXX/admin/online/ajax 500
请问是什么情况？

**Comment by M1Screw** [comment]
先配置 `config/.config.php` 中的 `maxmind_license_key` 配置項，然後執行 `php xcat Update`。
