### ISSUE TITLE
[Feature Request] 商品套餐的逻辑

### ISSUE THREAD

**Issue by zesai** [Anankke/SSPanel-Uim#1886]
**Feature 功能请求**
希望可以设置商品重置周期，或者增加一种限制比如每月使用多少多少

Describe the feature you want. 请描述你想要的功能。
目前新版的商品套餐逻辑
如果没有使用时长比较长的套餐，用户还得定期去购买（新版目前没看到自动续费的逻辑）
如果定的时间比较长，流量一次性给用户特别多，容易吧一个节点跑完，节点就做不到稳定持续提供服务😂
这几点疑惑，有啥好的解决办法吗，或者后期会迭代其他功能吗

**Comment by M1Screw** [comment]
如果用舊商店系統的那種間隔 X 天重置 X GB流量，在用戶和訂單數量變多之後資料庫的查詢壓力會直綫上升，同時也會碰到 Cron  PHP 超時的情況。目前在考慮的自動續費方案是在商品到期前 X 天生成一個續費訂單，然後用戶支付相關賬單後就會進入等待激活的狀態，待原訂單過期後面自動接續激活。

**Comment by zesai** [comment]
> 如果用旧商店系统的那种间隔X 天重置X GB流量，在用户和订单数量变多之后资料库的查询压力会直线上升，同时也会碰到Cron PHP 超时的情况。目前在考虑的自动续费方案是在商品到期前X 天生成一个续费订单，然后用户支付相关账单后就会进入等待激活的状态，待原订单过期后面自动接续激活。

您说的这个方案很好
后面会加上充值到余额的功能吗？，这样商品就可以设置成月包，到期自动续费月包，也可以避免用户需要一直去网站付款也能解决大流量包刷光节点流量😂
