### ISSUE TITLE
[BUG]网站后台报错

### ISSUE THREAD

**Issue by AllCheeks** [Anankke/SSPanel-Uim#1888]
**Environment 环境**

OS: Debian 10
PHP version:  8.1
DB version:  MySQL5.7
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
网站日志报错
[error] 9803#0: *1 FastCGI sent in stderr: ＂PHP message: PHP Warning:  Undefined array key ＂exceptionId＂ in /www/wwwroot/v2/storage/framework/smarty/compile/97a503ea10366bf52c211f3a86f215a4fe499cca_0.file.500.tpl.php on line 44PHP message: PHP Warning:  Attempt to read property ＂value＂ on null in /www/wwwroot/v2/storage/framework/smarty/compile/97a503ea10366bf52c211f3a86f215a4fe499cca_0.file.500.tpl.php on line 44＂ while reading response header from upstream, client: 183.47.30.131, server: XXX.COM, request: ＂DELETE /admin/order/8 HTTP/2.0＂, upstream: ＂fastcgi://unix:/tmp/php-cgi-81.sock:＂, host: ＂XXX.COM＂, referrer: ＂https://XXX.COM/admin/order＂

**Comment by M1Screw** [comment]
我比較感興趣的是這個本來應該顯示 500.tpl 的頁面本身就報錯這個問題，看起來這個 Sentry 集成需要整個重寫。
至於你的問題，你想刪除 ID 為 8 的訂單，你自己開 debug 用 F12 看看到底是什麽報錯讓你刪不掉訂單。

**Comment by M1Screw** [comment]
Sentry-related errors are fixed in https://github.com/Anankke/SSPanel-Uim/commit/c5507fd376db56d1d27661775cbb92fdc2fd0484.
