### ISSUE TITLE
[BUG]Tg机器人报错

### ISSUE THREAD

**Issue by wuwuwu223** [Anankke/SSPanel-Uim#1892]
**Environment 环境**

OS:    AlmaLinux9
PHP version:    8.1.8
DB version:    MariaDb 10.11
Commit:    b37b52c501f007ee8c68560f1d0db6a4fd2681c4

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

<!doctype html><html lang="en">    <head>        <meta charset="utf-8">        <meta name="viewport" content="width=device-width, initial-scale=1">        <title>Slim Application Error</title>        <style>            body{margin:0;padding:30px;font:12px/1.5 Helvetica,Arial,Verdana,sans-serif}            h1{margin:0;font-size:48px;font-weight:normal;line-height:48px}            strong{display:inline-block;width:65px}        </style>    </head>    <body>        <h1>Slim Application Error</h1>        <div><p>The application could not run because of the following error:</p><h2>Details</h2><div><strong>Type:</strong> Error</div><div><strong>Code:</strong> 0</div><div><strong>Message:</strong> Typed static property Telegram\Bot\Api::$container must not be accessed before initialization</div><div><strong>File:</strong> /data/sspanel/vendor/irazasyed/telegram-bot-sdk/src/Traits/HasContainer.php</div><div><strong>Line:</strong> 38</div><h2>Trace</h2><pre>#0 /data/sspanel/vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(231): Telegram\Bot\Api-&gt;hasContainer()
#1 /data/sspanel/vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(72): Telegram\Bot\Commands\CommandBus-&gt;resolveCommand()
#2 /data/sspanel/vendor/irazasyed/telegram-bot-sdk/src/Commands/CommandBus.php(57): Telegram\Bot\Commands\CommandBus-&gt;addCommand()
#3 [internal function]: Telegram\Bot\Commands\CommandBus-&gt;addCommands()
#4 /data/sspanel/vendor/irazasyed/telegram-bot-sdk/src/Api.php(124): call_user_func_array()
#5 /data/sspanel/src/Utils/Telegram/Process.php(20): Telegram\Bot\Api-&gt;__call()
#6 /data/sspanel/src/Controllers/HomeController.php(56): App\Utils\Telegram\Process::index()
#7 /data/sspanel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): App\Controllers\HomeController-&gt;telegram()
#8 /data/sspanel/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse-&gt;__invoke()
#9 /data/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route-&gt;handle()
#10 /data/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher-&gt;handle()
#11 /data/sspanel/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher-&gt;handle()
#12 /data/sspanel/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route-&gt;run()
#13 /data/sspanel/src/Middleware/ErrorHandler.php(29): Slim\Routing\RouteRunner-&gt;handle()
#14 /data/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): App\Middleware\ErrorHandler-&gt;process()
#15 /data/sspanel/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous-&gt;handle()
#16 /data/sspanel/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher-&gt;handle()
#17 /data/sspanel/vendor/slim/slim/Slim/App.php(183): Slim\App-&gt;handle()
#18 /data/sspanel/public/index.php(40): Slim\App-&gt;run()
#19 {main}</pre></div>        <a href="#" onclick="window.history.go(-1)">Go Back</a>    </body></html>

**Comment by M1Screw** [comment]
確認 PHP 8.1 可以復現。

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/d2779b3f7150af74b9076665b2600e7e9274bc94 & https://github.com/Anankke/SSPanel-Uim/commit/8ff00d8a7292fd537df82c70610e40502868529c.
