### ISSUE TITLE
[BUG]Attempt to read property "user_name" on null in Admin/InviteController.php

### ISSUE THREAD

**Issue by reizhi** [Anankke/SSPanel-Uim#1895]
**Environment 环境**

OS:    Debian 11.5
PHP version:    8.1
DB version: MySQL 8.0.30
Commit:    4c1cae587372976901df8a703ed430835da88411

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
进入 日志-邀请 页面后会有报错 `Attempt to read property "user_name" on null in ...Admin/InviteController.php on line 154`
查看数据库应该是有账号注销导致的，旧版的material主题没有这个问题

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/f2a465fc781dc64916460042fc36a7135cdeba96.
