### ISSUE TITLE
[BUG] 2023.1 账户信息 - 500

### ISSUE THREAD

**Issue by MorpheusNew** [Anankke/SSPanel-Uim#1903]
**Environment 环境**

OS:   docker
PHP version:    8.2
DB version:    10.11
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

2023.1 账户信息 - 500
![image](https://user-images.githubusercontent.com/129601803/231504725-cd52203e-3428-4b2f-8609-1e866535e0be.png)

**Comment by chauyuen** [comment]
盲猜跟这个有关，试试？
配置 config/.config.php 中的 maxmind_license_key 选项，然后执行如下命令php xcat Update

**Comment by zlingxi** [comment]
那是你没有搞新版的ip策略

**Comment by chauyuen** [comment]
不过，我相信这是一个推荐选项，Wiki【如果你希望使用 Maxmind GeoLite2 数据库来提供 IP 地理位置信息】把这个表示为一个可选项。因此如果因为缺乏IP库导致页面500，其实应该是不符合预期的

**Comment by MorpheusNew** [comment]
添加，确实ke这个IP归属地，其实这个嘛，可以可选嘛
![image](https://user-images.githubusercontent.com/129601803/231812939-ae44fa19-a962-459a-8631-8ebbfa617cc2.png)

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/7e8db5e880824b55c2d5c473807967a09ca2004b.

**Comment by lipeng0820** [comment]
求助 @77-QiQi ,升级SSpanel后，Xrayr后端报错，降级后恢复正常。这个报错也是跟Maxmind的设置有关么？感谢~
May 05 06:26:38 tester-nl XrayR[25118]: XrayR 0.9.0 (A Xray backend that supports many panels)
May 05 06:26:38 tester-nl XrayR[25118]: 2023/05/05 06:26:38 Start the panel..
May 05 06:26:38 tester-nl XrayR[25118]: 2023/05/05 06:26:38 Xray Core Version: 1.7.5
May 05 06:26:38 tester-nl XrayR[25118]: 2023/05/05 06:26:38 [Warning] core: Xray 1.7.5 started
May 05 06:26:39 tester-nl XrayR[25118]: 2023/05/05 06:26:39 Panel Start fialed: request https://x.xxxx.xx/mod_mu/users failed: <!DOCTYPE HTML>
May 05 06:26:39 tester-nl XrayR[25118]: <html lang="zh">
May 05 06:26:39 tester-nl XrayR[25118]: <head>
May 05 06:26:39 tester-nl XrayR[25118]:     <meta charset="UTF-8">
May 05 06:26:39 tester-nl XrayR[25118]:     <meta name="robots" content="noindex">
May 05 06:26:39 tester-nl XrayR[25118]:     <title>Internal Server Error - xxxx</title>
May 05 06:26:39 tester-nl XrayR[25118]:     <link rel="shortcut icon" href="/favicon.ico"/>
May 05 06:26:39 tester-nl XrayR[25118]:     <link rel="bookmark" href="/favicon.ico" type="image/x-icon"/>
May 05 06:26:39 tester-nl XrayR[25118]:     <link rel="stylesheet" href="/assets/css/error-pages.min.css"/>
May 05 06:26:39 tester-nl XrayR[25118]: </head>
May 05 06:26:39 tester-nl XrayR[25118]: <body>
May 05 06:26:39 tester-nl XrayR[25118]: <div class="container">
May 05 06:26:39 tester-nl XrayR[25118]:     <div class="copy-container center-xy">
May 05 06:26:39 tester-nl XrayR[25118]:         <p>
May 05 06:26:39 tester-nl XrayR[25118]:             500, Internal Server Error.
May 05 06:26:39 tester-nl XrayR[25118]:         </p>
May 05 06:26:39 tester-nl XrayR[25118]:     </div>
May 05 06:26:39 tester-nl XrayR[25118]: </div>
May 05 06:26:39 tester-nl XrayR[25118]: </body>
May 05 06:26:39 tester-nl XrayR[25118]: </html>
May 05 06:26:39 tester-nl XrayR[25118]: , %!s(<nil>)
May 05 06:26:39 tester-nl XrayR[25118]: panic: Panel Start fialed: request

**Comment by Kia678** [comment]
> 



> （推荐）请正确设置 ./config/.config.php
> 
> ```
> // Maxmind GeoIP2 database
> $_ENV['maxmind_license_key'] = '';
> $_ENV['geoip_locale'] = 'en';
> ```
> 
> 而后执行 php xcat Update
> 
> 或者确保 ./storage/GeoLite2-City/* ./storage/GeoLite2-Country/* 路径内存在正确的IP资料库，而后执行 php xcat Update

![image](https://github.com/Anankke/SSPanel-Uim/assets/85081567/12037390-76e7-4f01-b2bd-28e2b18e426c)
![image](https://github.com/Anankke/SSPanel-Uim/assets/85081567/48367bdb-529d-4d46-8641-749ffbdee272)

如上图，加入了ip资料库，执行 php xcat Update 之后，查看账户信息还是500

**Comment by lipeng0820** [comment]
tg 我，我试着帮你搞定，我昨天自己搞定了 500 的问题

**Comment by Kia678** [comment]
> tg 我，我试着帮你搞定，我昨天自己搞定了 500 的问题

你tg多少

**Comment by lipeng0820** [comment]
同名账号

**Comment by MorpheusNew** [comment]
谢谢，谢谢，添加上了
