### ISSUE TITLE
[Feature Request]修复php8.2下geoip2的弃用警告

### ISSUE THREAD

**Issue by chauyuen** [Anankke/SSPanel-Uim#1905]
**Feature 功能请求**

Describe the feature you want. 请描述你想要的功能。

目前在php 8.2打开display_errors的情况下，/admin/subscribe 表格无法显示。查看F12 /admin/subscribe/ajax

<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b>
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$city_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>20</b><br />
<b>Deprecated</b>:  Creation of dynamic property App\Utils\GeoIP2::$country_reader is deprecated in <b>/www/wwwroot/SSPanel-Uim/src/Utils/GeoIP2.php</b> on line <b>21</b><br />

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/75f60577c1443096387ec2796aebb3b318ecc5ad.
