### ISSUE TITLE
[BUG] 节点配置自定义配置custom config不生效

### ISSUE THREAD

**Issue by atomhym** [Anankke/SSPanel-Uim#1906]
**Environment 环境**

OS:    CENTOS7
PHP version:    8.1
DB version:    MariaDB 10.6
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

在节点配置中根据要求设置自定义配置，但是不生效，在用户界面查看节点配置端口什么的都无效，如果在节点地址那里配置信息是可以生效的。

![image](https://user-images.githubusercontent.com/16837846/232238593-a0014d8b-cb44-4a5f-b91e-393ed4da7b4a.png)

![image](https://user-images.githubusercontent.com/16837846/232238608-e35c43af-09e5-472e-82a9-5a1ce3d5958e.png)

**Comment by M1Screw** [comment]
在 2020.10 版本之前的舊訂閲系統和前端模板中確實是不會顯示 custom config 配置項的，你需要使用傳統的 server 欄位配置或者是更新面板版本。
