### ISSUE TITLE
[BUG] 订单状态

### ISSUE THREAD

**Issue by Reinering** [Anankke/SSPanel-Uim#1907]
**Environment 环境**
2023.1
OS:    Debian
PHP version:    8.2
DB version:    10.9
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
已支付的订单，却一直是等待支付
用户侧：
![image](https://user-images.githubusercontent.com/29029467/232279881-5f7eae24-2c9b-4d2d-86d4-9abfd0b7a00c.png)
![image](https://user-images.githubusercontent.com/29029467/232279893-434cd53e-2817-40e2-b16d-9a930f476eda.png)
![image](https://user-images.githubusercontent.com/29029467/232279909-d8dbab63-de8d-4f46-8a73-39e0aed9ff92.png)
管理侧：
![image](https://user-images.githubusercontent.com/29029467/232279977-c31e1582-8a99-4b37-ac34-6447bc2abdc5.png)
![image](https://user-images.githubusercontent.com/29029467/232280004-ca0c1df4-b5fa-4e5c-9a45-3a7255d12d70.png)

**Comment by M1Screw** [comment]
開通之後最多等五分鐘才會進行激活，如果超出一個 Cron 周期（5分鐘）之後仍未開通則檢查 Cron 是否正確配置。

**Comment by Reinering** [comment]
好的，我检查下Cron，谢谢
