### ISSUE TITLE
[BUG]关于用户重复购买套餐剩余时间不叠加和账单详情页面排版问题

### ISSUE THREAD

**Issue by JanXingit** [Anankke/SSPanel-Uim#1909]
**Environment 环境**

OS:    Debian11
PHP version:    8.1 with OPcache
DB version:    10.6
Commit:    
1.
![屏幕截图 2023-04-16 223410](https://user-images.githubusercontent.com/130652210/232320560-c68ecbe2-e5a7-4070-adc8-f841cfe889b6.png)

2.
![屏幕截图 2023-04-16 223516](https://user-images.githubusercontent.com/130652210/232320847-76eef686-be17-41e9-81cd-d24f719422f7.png)

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

1.在当前套餐未过期的情况下，用户重复购买同一个套餐，订单只会处于等待激活的状态，并不会激活，也就是不会将目前套餐剩余时间再增加一个套餐周期的时间

2.第二张图显示的用户端订单详情页面的关联账单一栏的排版好像有些许错误

**Comment by M1Screw** [comment]
1. 這個是新商店系統設計的一部分，因爲不同商品可能有不同的等級和不同的流量，所以在前置商品訂單過期之後才會激活第二個商品訂單，避免兩個訂單内容互相影響。
2. 這個不是排版錯誤，UI設計即是如此。

**Comment by yongxiaodong** [comment]
有没有立刻让新订单激活的方法
