### ISSUE TITLE
[BUG]centos9安装dev2023.1执行php composer.phar install时报错

### ISSUE THREAD

**Issue by tachikawa48** [Anankke/SSPanel-Uim#1912]
**Environment 环境**

OS:    centos9
PHP version:    8.2 with OPcache
DB version:    10.6
Commit:    

**Bug Info**

**根据Wiki通过oneinstack安装，执行**
`git clone -b 2023.1 --depth 1 https://github.com/Anankke/SSPanel-Uim.git`
`wget https://getcomposer.org/installer -O composer.phar`
`php composer.phar`
**后执行`php composer.phar install`出现报错**
Your lock file does not contain a compatible set of packages. Please run composer update.
  Problem 1
    - slim/http is locked to version 1.3 and an update of this package was not requested.
    - slim/http 1.3 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/php/etc/php.ini
    - /usr/local/php/etc/php.d/02-opcache.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-fileinfo` to temporarily ignore these required extensions.
**根据报错提示运行`php composer.phar update`返回**
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Root composer.json requires slim/http ^1.3 -> satisfiable by slim/http[1.3].
    - slim/http 1.3 requires ext-fileinfo * -> it is missing from your system. Install or enable PHP's fileinfo extension.
To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/php/etc/php.ini
    - /usr/local/php/etc/php.d/02-opcache.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-fileinfo` to temporarily ignore these required extensions.
**根据`php composer.phar install/update`报错内容可能是缺少fileinfo扩展？但Wiki中未提及安装此项。**
**通过执行`php composer.phar install --ignore-platform-req=ext-fileinfo`可以忽略但是否可以告知是否会对后续产生影响？**
**还是通过安装且启用fileinfo扩展尝试解决会是更优解？**

或许不属于BUG
未接触过此类报错，还请各路大神解惑，谢谢~

**Comment by M1Screw** [comment]
> 可能是缺少fileinfo扩展？
對。
