### ISSUE TITLE
[BUG]Vmess节点使用ws+tls时，Clash订阅链接配置中没有path参数，传统V2ray订阅链接则正常

### ISSUE THREAD

**Issue by jiderlesi** [Anankke/SSPanel-Uim#1917]
**Environment 环境**

OS:    Debian bookworm
PHP version:    8.2
DB version:    10.11.2
Commit:    latest dev (Apr 19, 2023)

**Bug Info**

节点中同时有Trojan和Vmess节点，使用Clash订阅连接时，获取到Vmess节点没有path参数，无法正常链接，通过传统V2ray订阅链接获取到的则可以正常使用，配置文件如下，其中部分参数使用“example”做了替换，实际为实际参数。

{
  "offset_port_node": "example",
  "server_sub": "example",
  "host": "example",
  "alter_id": "0",
  "network": "ws",
  "security": "tls",
  "path": "/example"
}

**Comment by iefnuy** [comment]
参考 https://github.com/Anankke/SSPanel-Uim/issues/1705 
加上这个，Host的H大写shadowrocket获取订阅就没⚠️
```
"ws-opts": {
"path": "/v2ray",
"headers": {
"Host": "hk.domain.com"
}
```

**Comment by jacksunhack** [comment]
> 参考 #1705 加上这个，Host的H大写shadowrocket获取订阅就没⚠️
> 
> ```
> "ws-opts": {
> "path": "/v2ray",
> "headers": {
> "Host": "hk.domain.com"
> }
> ```

怎么解决的？
