### ISSUE TITLE
[Feature Request]能否提供三方认证模块的接入能力

### ISSUE THREAD

**Issue by gitHardie** [Anankke/SSPanel-Uim#1918]
**Feature 功能请求**

Describe the feature you want. 请描述你想要的功能。
希望可以提供三方认证模块接入：比如标准的saml、auth2、oicd等
或者对接radius进行认证，方便进行集中的账号管理，避免创建独立账号密码。

**Comment by M1Screw** [comment]
目前是沒有計劃提供 OAuth 登錄的能力，因爲這樣會導致用戶資料管理困難和用戶個資與第三方共享的問題。但是如果只是希望能夠對賬戶進行集中管理，目前確實是有 User/Admin API 在規劃當中。
