### ISSUE TITLE
[BUG] 兑换礼品卡选项在移动设备上无法正常显示

### ISSUE THREAD

**Issue by jiderlesi** [Anankke/SSPanel-Uim#1922]
**Environment 环境**

OS:    Debian bookworm
PHP version:    8.2
DB version:    10.11.2
Commit:    latest dev (23 Apr 2023)

**Bug Info**

在用户的“商店余额”中，在移动设备上无法正常显示“兑换礼品卡”选项，在桌面设备或将UA改为桌面设备后则正常显示。

**Comment by M1Screw** [comment]
確認可以復現。之前一直沒發現這個問題是因爲移動端的測試都是在 iPad 上面做的 =.=

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/15b2449657b60fb6203f7b11055acd7b52477119.
