### ISSUE TITLE
[BUG] 优惠码功能无法使用

### ISSUE THREAD

**Issue by jiderlesi** [Anankke/SSPanel-Uim#1923]
**Environment 环境**

OS:    Debian bookworm
PHP version:    8.2
DB version:    10.11.2
Commit:    latest dev (23 Apr 2023)

**Bug Info**

在管理后台生成优惠码后，购买商品时总是显示 “优惠码无效“

**Comment by iefnuy** [comment]
优惠码不设置过期时间会有这个问题，要设置个时间

**Comment by M1Screw** [comment]
Fixed in https://github.com/sspanel-uim/SSPanel-Uim-Dev/commit/72dc535d0578058b6a9cbb0eb3a30e888d7680fb.
