### ISSUE TITLE
[BUG] 用户流量会超很多

### ISSUE THREAD

**Issue by zesai** [Anankke/SSPanel-Uim#1928]
**Environment 环境**

OS:    
PHP version:    
DB version:    
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
限制了1g流量，但是能多用很多这是哪里的问题呀
![image](https://user-images.githubusercontent.com/39072304/235605707-3d1a91c9-cb89-40ea-bdb5-cda3f1d2277f.jpeg)

**Comment by M1Screw** [comment]
檢查是否啓用 `keep_connect`。

**Comment by zesai** [comment]
> 檢查是否啓用 `keep_connect`。
看到了，以设置为false ，感谢🙏
