### ISSUE TITLE
[BUG] 日志记录页面报错

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1933]
**Environment 环境**

OS:    centos7.9
PHP version:    8.2
DB version:    10.6
Commit:    

**Bug Info**

{message: "Slim Application Error",…}
exception：[{type: "Error", code: 0, message: "Call to a member function getCity() on null",…}]
 0：{type: "Error", code: 0, message: "Call to a member function getCity() on null",…}
    code: 0
    file： "/www/wwwroot/sspanel/src/Utils/Tools.php"
    line： 38
    message："Call to a member function getCity() on null"
    type: "Error"
message: "Slim Application Error"

**Comment by yaoyao1128** [comment]
没有在 `config/.config.php` 设置 Maxmind GeoIP2 database 的 Key 或者设置后没有使用 `php xcat Update` 获取位置信息导致。
请配置后获取 GeoIP 信息尝试。
