### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xltxb** [Anankke/SSPanel-Uim#1936]
**Environment 环境**
最新版本 2023.2
OS:    
PHP version:    
DB version:    
Commit:    

**Bug Info**
epay 支付完成 回调之后，/user/code 404 sspanel 记录显示 未支付 状态
Describe the issue you run into. 请描述你遇到的问题。

**Comment by xltxb** [comment]
> `.config.php`中站点地址是不是尾部写了 `/` ? 例如 `https://example.com/` ? 删除斜杠写 `https://example.com`

没有，就是 https://www.example.com 这样的域名

**Comment by zesai** [comment]
/user/code 是旧系统路由，新版的好像没有了，给用户设置为使用新商店吧
