### ISSUE TITLE
[Feature Request] 所有静态资源文件不要用任何第三方CDN

### ISSUE THREAD

**Issue by Kia678** [Anankke/SSPanel-Uim#1938]
**Feature 功能请求**

所有资源文件不要用任何第三方CDN
所有资源文件放在用户本地server即可，请脱离第三方CDN依赖
本身就没多少静态资源文件，直接全部从本地server加载就可以了

**Comment by Kia678** [comment]
为何直接close了？

**Comment by M1Screw** [comment]
你在教我前端開發？
