### ISSUE TITLE
[Feature Request] jsdelivr已经被污染

### ISSUE THREAD

**Issue by Kia678** [Anankke/SSPanel-Uim#1939]
**Feature 功能请求**

建议资源文件不要用任何第三方CDN [ 例如：jsdelivr ]
从本地server加载就可
![image](https://user-images.githubusercontent.com/85081567/236804023-e97e2f7a-c41e-482d-b3bc-a01a28b51b9a.png)

**Comment by Kia678** [comment]
jsdelivr都已经被污染了，还要close？

**Comment by M1Screw** [comment]
![image](https://user-images.githubusercontent.com/14369594/236806340-21ab5457-edde-4b9c-a8f8-44dd0a786ee0.png)
This graph clearly indicates normal connectivity from China to jsdelivr, thus I suggest you shut the fuck up and stop wasting the dev's time to dealing with your bullshit.

**Comment by zesai** [comment]
不用梯子访问，确实经常会加载不出来，导致页面打不开，开了梯子缓存一次静态文件才能正常访问
概率事件
