### ISSUE TITLE
[BUG] 开启验证码时，无法正常登陆

### ISSUE THREAD

**Issue by ctrlbbj** [Anankke/SSPanel-Uim#1943]
**Environment 环境**

OS:    
PHP version:    
DB version:    
Commit:    Tags/2023.2

**Bug Info**
在开启登陆需要极验验证码时候，无法成功登陆。
浏览器控制台存在以下报错
Uncaught TypeError: geetest.getValidate is not a function
    <anonymous> https://example.com/auth/login:79

**Comment by M1Screw** [comment]
無法復現，檢查 geetest id & key 是否正確配置，gt4.js 是否正常加載。

**Comment by ctrlbbj** [comment]
![图片](https://github.com/Anankke/SSPanel-Uim/assets/20785494/87b264cd-aab4-4647-85cc-3d5bc9423ea8)
火狐浏览器 ESR102.10，gt4.js脚本可以正常加载并执行，仅在提交时出现错误
id与key已经正确配置，在签到处开启验证码，功能完全正常。
目前仅发现登陆时验证码功能存在问题

**Comment by ctrlbbj** [comment]
![图片](https://github.com/Anankke/SSPanel-Uim/assets/20785494/758c5050-99fc-4e6a-a8d1-a4262022c49d)
补充测试在chrome 109.0.5414.120同样错误

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/173ad1a91abd3330f4ff64de776cf0f6d4fab550.
