### ISSUE TITLE
今天刷新系统都变成白色的了

### ISSUE THREAD

**Issue by zesai** [Anankke/SSPanel-Uim#1956]
开发者您好：

这是界面图
![image](https://github.com/Anankke/SSPanel-Uim/assets/39072304/14ad9ad9-b030-4ef0-bded-2641f3adc947)
这是最后一次拉取 dev 分支的时间节点
<img width="1224" alt="image" src="https://github.com/Anankke/SSPanel-Uim/assets/39072304/b5b9cfa4-ca59-41ae-8456-f116dee77240">
我自己修改的部分没有涉及到样式啥的，查看网络所有的样式 js 啥的状态码都正常，今天就变白了
新版的定时任务还没有看明白，所以还没敢拉最新的代码
这是因为啥引起的，有暂时解决的办法吗，谢谢🙏

**Comment by M1Screw** [comment]
patch 在這個 commit 裏面 https://github.com/Anankke/SSPanel-Uim/commit/3b5b67581e920dbdd46763c67da35c79c7dcc729 。
