### ISSUE TITLE
发现文档的审计正则部分会失效

### ISSUE THREAD

**Issue by zesai** [Anankke/SSPanel-Uim#1963]
后端用的 xrayr

举例，360审计规则 (.+\.|^)(360|so)\.(cn|com)
<img width="1313" alt="image" src="https://github.com/Anankke/SSPanel-Uim/assets/39072304/a116b32d-b1c3-49ed-b474-dd9a9a8a6523">

1. 访问 www.360.com 时可以被阻断
<img width="1289" alt="image" src="https://github.com/Anankke/SSPanel-Uim/assets/39072304/15915162-1b35-4d81-9e18-1a3fa31806cd">

2. 访问 360.com 时没有被阻断
<img width="1648" alt="image" src="https://github.com/Anankke/SSPanel-Uim/assets/39072304/0b23e476-f606-4097-9644-ee010c53de44">

想问一下，这是规则的问题，还是 Xrayr 的问题呀，导致有些没有被阻断了

**Comment by M1Screw** [comment]
https://regex101.com/ 你自己試試 regex 規則能不能匹配。另外 Wiki 裏面的規則已經很久很久沒有維護過了，如果發現有失效的規則的話就自己改改提個 PR 吧。
