### ISSUE TITLE
[BUG] mod_mu/nodes/3/info failed and /mod_mu/users/traffic failed

### ISSUE THREAD

**Issue by Reinering** [Anankke/SSPanel-Uim#1969]
**Environment 环境**

OS:    debian11
PHP version:    8.2.1
DB version:   2023032600 
Commit:    f913d68a10a22f239607c25c6b68c4d3bd928ae4
**Bug Info**
xrayr 获取信息错误

今天更新dev后出现，回退到2023.2后错误消失

Describe the issue you run into. 请描述你遇到的问题。
![image](https://github.com/Anankke/SSPanel-Uim/assets/29029467/5e0d18c2-f1a9-43b9-b271-5b5fd0d10a50)
![image](https://github.com/Anankke/SSPanel-Uim/assets/29029467/663aaf47-e9fd-4e57-8a09-dcd13f0905af)

**Comment by Reinering** [comment]
我忘记更新数据库了

**Comment by Reinering** [comment]
数据我已经更新到2023050800
![image](https://github.com/Anankke/SSPanel-Uim/assets/29029467/bdc39258-70c2-42ae-89dd-a01f47133325)
问题依然存在

**Comment by M1Screw** [comment]
https://github.com/XrayR-project/XrayR/commit/b49798ab16cea65e70fca9a32a50a99092b4982e XrayR 需要更新至此 commit 方可支持最新版本的 WebAPI。
