### ISSUE TITLE
[BUG] Clash通用配置Json未转换成Yml导致内核无法正确识别

### ISSUE THREAD

**Issue by miyling** [Anankke/SSPanel-Uim#1977]
**Environment 环境**

OS:  Ubuntu 22.04
PHP version:    8.2
DB version:   10.11.2
Commit:    f913d68a10a22f239607c25c6b68c4d3bd928ae4

**Bug Info**

自定义配置使用Clash或Clash Meta的通用配置`ws-opts`,`h2_opts`,`http_opts`,`grpc_opts`,`reality_opts`，未将配置的Json内容转换为yaml格式

**Comment by M1Screw** [comment]
This issue should be fixed at https://github.com/Anankke/SSPanel-Uim/commit/8029f80e85a0604d27087ac94192d707e27dff81, please give it a try.
