### ISSUE TITLE
[BUG] alive_ip 数组超范围

### ISSUE THREAD

**Issue by OPPO9008** [Anankke/SSPanel-Uim#1984]
**Environment 环境**

OS:    Debian 5.10.158-2
PHP version:    PHP 7.4.33 (cli) (built: Apr  9 2023 16:54:16) ( NTS )
DB version:    mysql  Ver 15.1 Distrib 10.7.8-MariaDB
Commit:    d41166d4dc9ce2a5e15ce54cfa85ccd4f5d94438

**Bug Info**

这一行代码
https://github.com/Anankke/SSPanel-Uim/blob/d41166d4dc9ce2a5e15ce54cfa85ccd4f5d94438/src/Controllers/Mod_Mu/UserController.php#LL99C17-L99C17
的$alive_ip[strval($user_raw->id)];  由于数组中的索引超出范围而报错 Undefined offset: 1

**Comment by M1Screw** [comment]
能不能不要拿著兩年前的代碼來提 issue？
