### ISSUE TITLE
[BUG] 创建订单时未跳转，导致创建了多个订单

### ISSUE THREAD

**Issue by zesai** [Anankke/SSPanel-Uim#1985]
手机端
购买商品创建订单时 会弹出成功窗口，这种情况下如果手动点击按钮会导致还停留在当前页面，其实订单已经创建成功（会导致创建了好多订单）
如果不点击按钮，等待自动跳转是可以跳转成功的

https://github.com/Anankke/SSPanel-Uim/assets/39072304/65119e76-e9d3-4292-b4cd-d754594fa87b

**Comment by M1Screw** [comment]
Fixed in https://github.com/Anankke/SSPanel-Uim/commit/2c42a73c8bf709100d24096b4f31c99c7ff7f248.
