### ISSUE TITLE
最近经常收到说不挂梯子打不开网站

### ISSUE THREAD

**Issue by zesai** [Anankke/SSPanel-Uim#2000]
我最近也试了试，不挂梯子有时候这些资源会请求错误
这是本地网络的原因么，网站是能正常返回的，就是js，css，icon这些偶尔会错误
<img width="866" alt="image" src="https://github.com/Anankke/SSPanel-Uim/assets/39072304/5b88436c-0225-441c-af1e-27d326afd9e1">

**Comment by M1Screw** [comment]
A static resources cache feature will be added to xcat to mitigate this issue.
