### ISSUE TITLE
[BUG] 重置用户流量命令出错

### ISSUE THREAD

**Issue by Ruicw** [Anankke/SSPanel-Uim#2002]
**Environment 环境**

OS:    
PHP version:    
DB version:    
Commit:    

**Bug Info**

# php xcat Tool resetTraffic
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'enable' in 'where clause' (SQL: update `user` set `d` = 0, `u` = 0, `transfer_today` = 0 where `enable` = 1)

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/721ba073d879e00599627c7fde76f8d24e66e1f6.
