### ISSUE TITLE
[BUG] 创建的管理员账户在前端不能登录

### ISSUE THREAD

**Issue by Simonaorg** [Anankke/SSPanel-Uim#2004]
**Environment 环境**

OS:    ubuntu
PHP version:    8.2
DB version:    10.6
Commit:    

**Bug Info**
2023.3 以及2023.2 版本，成功创建管理员账户后，进入网站不能用已创建的管理员账户信息登录，提示邮箱或密码错误。使用后台已创建的管理员账户信息可在网页端注册为普通用户。

**Comment by Simonaorg** [comment]
刚测试，创建的管理员账户可以登录了。

**Comment by M1Screw** [comment]
An improvement patch has been added at https://github.com/Anankke/SSPanel-Uim/commit/07f12af0000066f0936a26c9fe13e49d23ff164c.

**Comment by LaiWu1997** [comment]
我也有同样的问题，一模一样，请问是怎样解决的？
