### ISSUE TITLE
订阅设置处自定义订阅地址没有强制要求使用HTTPS会导致中间人攻击(被运营商监控)

### ISSUE THREAD

**Issue by happy0717** [Anankke/SSPanel-Uim#2009]
订阅设置处自定义订阅地址没有强制要求使用HTTPS会导致中间人攻击(被运营商监控)

![image](https://github.com/Anankke/SSPanel-Uim/assets/36958703/fbe85791-67d1-43db-b31a-03f930ae06f8)
![image](https://github.com/Anankke/SSPanel-Uim/assets/36958703/7547b18c-40c7-4052-a48b-c0fec20f8b2d)
某平台监测到的流量如下：
![image](https://github.com/Anankke/SSPanel-Uim/assets/36958703/e4c363c7-9378-4cb0-b51d-67a6ce8d4634)
![image](https://github.com/Anankke/SSPanel-Uim/assets/36958703/2b376793-b061-442e-a298-b840a1e38bb7)

如果有网络日志或者Wireshark可以解析的原始流量直接搜索 "powered by sspanel" 就可以过滤出来使用sspanel的IP地址  之后再搜索/sub/ 或 /link/ 就可以定位到订阅的信息，导致订阅信息泄漏出去，极大的影响了节点的安全性。

修复：1.强制要求对订阅地址使用TLS加密
2.在用户自定义设置时进行提示

**Comment by M1Screw** [comment]
It's the operator's fault for not using HTTPS(and the newer version already disabled login via HTTP), so I really don't know wtf you are talking about.

**Comment by happy0717** [comment]
Yes, not using https is the user's problem, but as a product, it should prompt the user that there is a risk of man-in-the-middle attack at the right time. If you don't know what I'm talking about it's probably because of the translation. You can check out articles about man-in-the-middle attacks and carrier link hijacking

**Comment by happy0717** [comment]
是的  逻辑上没有问题，就像我的车在车位里停着骑车的人过来给我撞了我还要对骑车人负责是一样的。
如果您这边认为这个不是问题直接忽略就好，我就提醒一下  谁不希望产品能做的更好呢

https://www.secrss.com/articles/18690
未使用 HTTPS 的漏洞通常被称为“未加密传输漏洞”（Unencrypted Transport Vulnerability）或“明文传输漏洞”（Clear Text Transmission Vulnerability）。

这种漏洞通常发生在客户端和服务器之间的通信过程中，因为通信过程中的数据传输是明文的，不经过任何加密处理，因此攻击者可以轻松地截取和查看通信内容，包括敏感信息（如密码、信用卡号等）。攻击者还可以修改通信内容，篡改数据或者执行中间人攻击等恶意行为。

为了防止未加密传输漏洞，应该尽可能地使用 HTTPS 协议来加密通信内容。HTTPS 使用 SSL/TLS 协议来加密通信内容，可以防止数据被截取和篡改，提高了通信的安全性。同时，还可以使用其他安全措施，如数据加密、数字签名等来保护通信内容和验证通信双方的身份。

除了使用 HTTPS 协议之外，还应该遵循其他最佳实践，如使用强密码、定期更改密码、更新软件以修补安全漏洞、限制对敏感数据的访问权限等，以提高系统和应用程序的安全性。
