### ISSUE TITLE
/src/Command/ClientDownload.php getSourceFile函数中使用的php内置函数system时没有限制传入的参数可以导致命令执行漏洞

### ISSUE THREAD

**Issue by happy0717** [Anankke/SSPanel-Uim#2012]
/src/Command/ClientDownload.php getSourceFile函数中使用的php内置函数system时没有限制传入的参数可以导致命令执行漏洞

类型: 安全缺陷
命令注入是指应用程序执行外部命令时，被当作命令的字符串或字符串的一部分是不可信的数据，程序没有对这些不可信的数据进行验证、过滤，导致程序执行恶意命令的一种攻击方式。  
**例如**：下面的PHP代码片段使用system()执行命令。  
```private function getSourceFile(string $fileName, string $savePath, string $url): bool
    {
        try {
            if (! file_exists($savePath)) {
                echo '目标文件夹 ' . $savePath . ' 不存在，创建中...' . PHP_EOL;
                system('mkdir ' . $savePath);
            }
            echo '- 开始下载 ' . $fileName . '...' . PHP_EOL;
            $request = $this->client->get($url);
            echo '- 下载 ' . $fileName . ' 成功，正在保存...' . PHP_EOL;
            $result = file_put_contents($savePath . $fileName, $request->getBody()->getContents());
            if ($result === false) {
                echo '- 保存 ' . $fileName . ' 至 ' . $savePath . ' 失败.' . PHP_EOL;
            } else {
                echo '- 保存 ' . $fileName . ' 至 ' . $savePath . ' 成功.' . PHP_EOL;
                system('chown ' . $_ENV['php_user_group'] . ' ' . $savePath . $fileName);
            }
            return true;
        } catch (Exception $e) {
            echo '- 下载 ' . $fileName . ' 失败...' . PHP_EOL;
            echo $e->getMessage() . PHP_EOL;
            return false;
        }
    }
```
代码没有对$_ENV['php_user_group']、$savePath做输入验证，如果恶意用户输入以下内容：  
```
;rm -rf /  
```
system函数执行的命令变成如下内容：  
```
ls -l /home/;rm -rf /  
```
由于分号";"在Linux和Unix系统下是命令分隔符，系统会首先执行ls命令，然后执行rm命令，删除系统的所有文件。  
![image](https://github.com/sspanel-uim/SSPanel-Uim-Dev/assets/36958703/26442b37-7a82-4711-b54a-c4c6436645bc)

修复：
防止命令注入的方法如下：  
1. 白名单：如果只允许运行有限的命令，可以创建一份安全字符串列表，限制用户只能输入该列表中的数据。  
2. 输入验证：根据业务逻辑，对用户的输入进行合理验证，比如输入仅允许是字母和数字。

**Comment by M1Screw** [comment]
Stupid fucker thinks he's some kind of genius knowing that system() can nuke file system. That's the site owner's freedom if they want to do that, just like I am free to lock your dumbass issue.

**Comment by Anankke** [comment]
少用啥软 GPT 3.5
