### ISSUE TITLE
2023.3版 XrayR 报错

### ISSUE THREAD

**Issue by Simonaorg** [Anankke/SSPanel-Uim#2033]
**Environment 环境**

OS:   ubuntu
PHP version:    8.2
DB version:    10.6
Commit:    

**Bug Info**
2023.2 版 XrayR 对接正常 2023.3版报错，报错如下：

2023/06/16 20:21:47 request https://domain.com/mod_mu/nodes/21/info failed: <!doctype html>
Jun 16 20:21:47 tiktok XrayR[74086]: <html lang="zh">
Jun 16 20:21:47 tiktok XrayR[74086]: <head>
Jun 16 20:21:47 tiktok XrayR[74086]:     <meta charset="utf-8" />
Jun 16 20:21:47 tiktok XrayR[74086]:     <meta name="robots" content="noindex">
Jun 16 20:21:47 tiktok XrayR[74086]:     <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
Jun 16 20:21:47 tiktok XrayR[74086]:     <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
Jun 16 20:21:47 tiktok XrayR[74086]:     <meta http-equiv="X-UA-Compatible" content="ie=edge" />
Jun 16 20:21:47 tiktok XrayR[74086]:     <title>test</title>
Jun 16 20:21:47 tiktok XrayR[74086]:     
Jun 16 20:21:47 tiktok XrayR[74086]:     <link href="//cdn.jsdelivr.net/npm/@tabler/core@latest/dist/css/tabler.min.css" rel="stylesheet" />
Jun 16 20:21:47 tiktok XrayR[74086]:     <link href="//cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css" rel="stylesheet" />
Jun 16 20:21:47 tiktok XrayR[74086]:     
Jun 16 20:21:47 tiktok XrayR[74086]:     <script src="/assets/js/fuck.min.js"></script>
Jun 16 20:21:47 tiktok XrayR[74086]:     <script src="//cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
Jun 16 20:21:47 tiktok XrayR[74086]: </head>
Jun 16 20:21:47 tiktok XrayR[74086]: <body class="border-top-wide border-primary d-flex flex-column">
Jun 16 20:21:47 tiktok XrayR[74086]: <div class="page page-center">
Jun 16 20:21:47 tiktok XrayR[74086]:     <div class="container-tight my-auto">
Jun 16 20:21:47 tiktok XrayR[74086]:         <div class="empty">
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="empty-header">405</div>
Jun 16 20:21:47 tiktok XrayR[74086]:             <p class="empty-title">不允许的请求方式</p>
Jun 16 20:21:47 tiktok XrayR[74086]:             <p class="empty-subtitle text-secondary">
Jun 16 20:21:47 tiktok XrayR[74086]:                 Wanna try something stupid I see, now go back to the home page.
Jun 16 20:21:47 tiktok XrayR[74086]:             </p>
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="empty-action">
Jun 16 20:21:47 tiktok XrayR[74086]:                 <a href="/" class="btn btn-primary">
Jun 16 20:21:47 tiktok XrayR[74086]:                     <i class="icon ti ti-chevron-left"></i>
Jun 16 20:21:47 tiktok XrayR[74086]:                     返回主页
Jun 16 20:21:47 tiktok XrayR[74086]:                 </a>
Jun 16 20:21:47 tiktok XrayR[74086]:             </div>
Jun 16 20:21:47 tiktok XrayR[74086]:         </div>
Jun 16 20:21:47 tiktok XrayR[74086]:     </div>
Jun 16 20:21:47 tiktok XrayR[74086]: </div>
Jun 16 20:21:47 tiktok XrayR[74086]: <div class="modal modal-blur fade" id="success-dialog" tabindex="-1" role="dialog" aria-hidden="true">
Jun 16 20:21:47 tiktok XrayR[74086]:     <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
Jun 16 20:21:47 tiktok XrayR[74086]:         <div class="modal-content">
Jun 16 20:21:47 tiktok XrayR[74086]:             <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="modal-status bg-success"></div>
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="modal-body text-center py-4">
Jun 16 20:21:47 tiktok XrayR[74086]:                 <i class="ti ti-circle-check icon mb-2 text-green icon-lg" style="font-size:3.5rem;"></i>
Jun 16 20:21:47 tiktok XrayR[74086]:                 <p id="success-message" class="text-secondary">成功</p>
Jun 16 20:21:47 tiktok XrayR[74086]:             </div>
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="modal-footer">
Jun 16 20:21:47 tiktok XrayR[74086]:                 <div class="w-100">
Jun 16 20:21:47 tiktok XrayR[74086]:                     <div class="row">
Jun 16 20:21:47 tiktok XrayR[74086]:                         <div class="col">
Jun 16 20:21:47 tiktok XrayR[74086]:                             <a id="success-confirm" href="" class="btn w-100" data-bs-dismiss="modal">
Jun 16 20:21:47 tiktok XrayR[74086]:                                 好
Jun 16 20:21:47 tiktok XrayR[74086]:                             </a>
Jun 16 20:21:47 tiktok XrayR[74086]:                         </div>
Jun 16 20:21:47 tiktok XrayR[74086]:                     </div>
Jun 16 20:21:47 tiktok XrayR[74086]:                 </div>
Jun 16 20:21:47 tiktok XrayR[74086]:             </div>
Jun 16 20:21:47 tiktok XrayR[74086]:         </div>
Jun 16 20:21:47 tiktok XrayR[74086]:     </div>
Jun 16 20:21:47 tiktok XrayR[74086]: </div>
Jun 16 20:21:47 tiktok XrayR[74086]: <div class="modal modal-blur fade" id="fail-dialog" tabindex="-1" role="dialog" aria-hidden="true">
Jun 16 20:21:47 tiktok XrayR[74086]:     <div class="modal-dialog modal-sm modal-dialog-centered" role="document">
Jun 16 20:21:47 tiktok XrayR[74086]:         <div class="modal-content">
Jun 16 20:21:47 tiktok XrayR[74086]:             <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="modal-status bg-danger"></div>
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="modal-body text-center py-4">
Jun 16 20:21:47 tiktok XrayR[74086]:                 <i class="ti ti-circle-x icon mb-2 text-danger icon-lg" style="font-size:3.5rem;"></i>
Jun 16 20:21:47 tiktok XrayR[74086]:                 <p id="fail-message" class="text-secondary">失败</p>
Jun 16 20:21:47 tiktok XrayR[74086]:             </div>
Jun 16 20:21:47 tiktok XrayR[74086]:             <div class="modal-footer">
Jun 16 20:21:47 tiktok XrayR[74086]:                 <div class="w-100">
Jun 16 20:21:47 tiktok XrayR[74086]:                     <div class="row">
Jun 16 20:21:47 tiktok XrayR[74086]:                         <div class="col">
Jun 16 20:21:47 tiktok XrayR[74086]:                             <a href="" class="btn btn-danger w-100" data-bs-dismiss="modal">
Jun 16 20:21:47 tiktok XrayR[74086]:                                 确认
Jun 16 20:21:47 tiktok XrayR[74086]:                             </a>
Jun 16 20:21:47 tiktok XrayR[74086]:                         </div>
Jun 16 20:21:47 tiktok XrayR[74086]:                     </div>
Jun 16 20:21:47 tiktok XrayR[74086]:                 </div>
Jun 16 20:21:47 tiktok XrayR[74086]:             </div>
Jun 16 20:21:47 tiktok XrayR[74086]:         </div>
Jun 16 20:21:47 tiktok XrayR[74086]:     </div>
Jun 16 20:21:47 tiktok XrayR[74086]: </div>
Jun 16 20:21:47 tiktok XrayR[74086]: <script src="//cdn.jsdelivr.net/npm/@tabler/core@latest/dist/js/tabler.min.js"></script>
Jun 16 20:21:47 tiktok XrayR[74086]: </body>
Jun 16 20:21:47 tiktok XrayR[74086]: </html>

**Comment by LaiWu1997** [comment]
我也有同样的问题，一模一样，请问是怎样解决的？

**Comment by Simonaorg** [comment]
没解决 2023.2版对接没问题 但是clash 下发不了订阅
