### ISSUE TITLE
clash订阅链接打开后显示内容错误，以及站点刚建就疑似被墙干扰？

### ISSUE THREAD

**Issue by crazysvn** [Anankke/SSPanel-Uim#2036]
**Environment 环境**

OS:    WIN10
PHP version:   8.1 
DB version:    MySQL 10.7.3-MariaDB
Commit:    

**Bug Info**

用clash下载订阅信息，提示 download profile (...) failed with error: Network Error.

在chrome中打开这个链接，显示出一大堆不是我自己建的节点信息，如图：
![@9AD1EQH0FZ(GAI{DAV22$V](https://github.com/Anankke/SSPanel-Uim/assets/26742593/95b7786d-1f8c-469e-ab71-563a4cd03fd4)

难道是被DNS服务商重定向到了一个广告页面？

另外，我这sspanel网站刚建（SSL正常），直连时就显示网站不安全打不开，但开代理后就能正常打开，这是被墙干扰了？

**Comment by crazysvn** [comment]
补充：浏览器打开通用订阅（json）链接后，显示节点信息为空。

**Comment by crazysvn** [comment]
浏览器打开传统订阅（Trojan），链接后，显示空白。

**Comment by M1Screw** [comment]
有没有一種可能，你的訂閲裏面沒有任何可用節點？
