### ISSUE TITLE
[Feature Request] 优化用户数量大的场景

### ISSUE THREAD

**Issue by wudgaby** [Anankke/SSPanel-Uim#2060]
当用户数很多时,如1W,10W
webapi获取节点用户接口/mod_mu/users, 就会变得很慢,很卡,json数据包很大.
是否可以考虑用户量大时的方案?

**Comment by M1Screw** [comment]
現在版本的 WebAPI 性能取決於 MariaDB 本身的查詢性能（即 raw SQL query 性能）。如果希望緩解性能問題的話可以考慮從資料庫本身的性能優化下手，比如更換 MariaDB Server 11.x 版本以使用新版的 query optimizer 提升資料庫伺服器 QPS，或者是優化資料庫參數，使用記憶體緩存功能等等。

當然要從根本上解決問題還是要在 WebAPI 中提供 diff update 功能，即節點伺服器可以差量更新用戶資料而不是每次都需要全量更新，但是這個需要節點開發者的配合。結論就是，這個功能還在考慮與規劃過程中，目前沒有辦法給出具體的 timeline。

**Comment by wudgaby** [comment]
好的.谢谢解答
