### ISSUE TITLE
[BUG] Call to undefined method App\Models\User::lastSsTime()

### ISSUE THREAD

**Issue by lmfcc** [Anankke/SSPanel-Uim#2075]
**Environment 环境**

OS: CentOS 7.4
PHP version: PHP-8.1
DB version: mysql mariadb_10.6
Commit:

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

`Fatal error: Uncaught BadMethodCallException: Call to undefined method App\Models\User::lastSsTime() in /www/wwwroot/sspanel/vendor/illuminate/support/Traits/ForwardsCalls.php:71 Stack trace: #0 /www/wwwroot/sspanel/vendor/illuminate/support/Traits/ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException() #1 /www/wwwroot/sspanel/vendor/illuminate/database/Eloquent/Model.php(2330): Illuminate\Database\Eloquent\Model->forwardCallTo() #2 /www/wwwroot/sspanel/storage/framework/smarty/compile/f1c87df6961230ef213618505e5731acc406987c_0.file.live_chat.tpl.php(66)`

在 /resources/views/tabler/live_chat.tpl 的 [33](https://github.com/Anankke/SSPanel-Uim/blob/0a137bd9bb75dd7e0477ad5bb7ba2e9896ad5d8d/resources/views/tabler/live_chat.tpl#L33C45-L33C55)、[51](https://github.com/Anankke/SSPanel-Uim/blob/0a137bd9bb75dd7e0477ad5bb7ba2e9896ad5d8d/resources/views/tabler/live_chat.tpl#L51)
两处仍使用旧的function lastSsTime()，没有修改到最新dev的src/Models/User.php使用的function lastUseTime() ，故导致呼叫不到function的错误。

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/c6462efcef4788b2dcecc9bf5fab10713c916203.
