### ISSUE TITLE
使用php xcat时出现的问题

### ISSUE THREAD

**Issue by baixuanyou** [Anankke/SSPanel-Uim#2082]
当我输入文档中的这个命令时：php xcat Migration new
显示Database is not empty, do not use "new" as version.
但是我的数据库时刚刚才安装的，没有新东西
此外，我在写入配置文件时，找不到数据库名称和dbsocket的路径
我查看了/etc/my.cnf  这个文件并找到了上述两个问题，不知我的做法是否正确

**Comment by rex5652** [comment]
在.config.php里设置数据库信息，数据地址可以用127.0.0.1，就不用dbsocket了。

**Comment by baixuanyou** [comment]
您好，您说的时不用dbsocket去用dbhost嘛，如果是的话我按照您的方法更改一次，但是我在执行php xcat Migration new这个命令还是显示do not use "new" as version.，请指教一下

**Comment by rex5652** [comment]
do not use "new" as version. 说明数据库里有数据，先把这个数据库删掉，重建后再试一次
