### ISSUE TITLE
[BUG] Ajax 发送 PUT请求错误

### ISSUE THREAD

**Issue by rainsuns** [Anankke/SSPanel-Uim#2091]
**Environment 环境**

OS:    centos7.9
PHP version:    8.2
DB version:    10.7
Commit:    2023.4

**Bug Info**

修改节点时保存配置失败，发现凡使用PUT方法的都会保存失败。
搜了一下Issues，可能是个例。
![image](https://github.com/Anankke/SSPanel-Uim/assets/26184114/4a068fd4-29b5-4ae7-b63a-4cc89cb741ca)

**Comment by M1Screw** [comment]
無法復現。
