### ISSUE TITLE
2023.3_2023.4 bug提交

### ISSUE THREAD

**Issue by bxoooooo** [Anankke/SSPanel-Uim#2099]
2023.3 GeoIP2搭建后查看账户信息报错
2023.4 资料修改提示500报错2023.3正常

**Comment by M1Screw** [comment]
無法復現。

**Comment by bxoooooo** [comment]
此问题已解决 
由于23.4部分数据交由Redis处理
我Redis设置了密码导致无法访问
在Redis取消密码  或者config.php处填写密码即解决
