### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by bxoooooo** [Anankke/SSPanel-Uim#2102]
请问css  js这些资源能放到本地吗
cdn很多地区被墙了     不挂代理加载不出来 
机场又一般销售国内    如果用户第一次使用 又没代理软件就很无解 
在此谢谢作者的开源贡献

**Comment by M1Screw** [comment]
A mitigation config is provided at https://github.com/Anankke/SSPanel-Uim/commit/e3e878dc204a8f63fd5cd77c66754fbefdd216a4.
