### ISSUE TITLE
[BUG] 用户订阅记录

### ISSUE THREAD

**Issue by bxoooooo** [Anankke/SSPanel-Uim#2108]
**Environment 环境**

OS:    8
PHP version:    8.2
DB version:    11
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
开启订阅记录后能正常记录   但是显示数据表错误
![IMG_20230809_171055](https://github.com/Anankke/SSPanel-Uim/assets/120531761/4f11e273-ec85-4998-b52b-c92498b8913e)

**Comment by bxoooooo** [comment]
测试环境  dev

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/77e759ceee47cabb068ee9432f32c7d03edc7c63.
