### ISSUE TITLE
[BUG] 对接节点玄学

### ISSUE THREAD

**Issue by bxoooooo** [Anankke/SSPanel-Uim#2112]
**Environment 环境**

OS:    8
PHP version:    8.2
DB version:    11
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
对接xrayr     节点和面板对接一下可以一下不行
同一个节点

**Comment by M1Screw** [comment]
調整 $_ENV['rate_limit_webapi']。

**Comment by bxoooooo** [comment]
你好  可能我描述有问题  
  是不同节点 有的可以对接  有的不行
用v2board测试全部通的

**Comment by bxoooooo** [comment]
11 10:46:50 kr1 XrayR[383643]:         log/log.go:391 +0x67
Aug 11 10:46:50 kr1 XrayR[383643]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005b7340)
Aug 11 10:46:50 kr1 XrayR[383643]:         github.com/XrayR-project/XrayR/panel/panel.go:211 +0x59b
Aug 11 10:46:50 kr1 XrayR[383643]: main.main()
Aug 11 10:46:50 kr1 XrayR[383643]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Aug 11 10:46:50 kr1 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 11 10:46:50 kr1 systemd[1]: XrayR.service: Failed with result 'exit-code'.
Aug 11 10:47:00 kr1 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 7.
Aug 11 10:47:00 kr1 systemd[1]: Stopped XrayR Service.
Aug 11 10:47:00 kr1 systemd[1]: Started XrayR Service.
Aug 11 10:47:00 kr1 XrayR[383668]: XrayR 0.9.0 (A Xray backend that supports many panels)
Aug 11 10:47:01 kr1 XrayR[383668]: 2023/08/11 10:47:01 Start the panel..
Aug 11 10:47:01 kr1 XrayR[383668]: 2023/08/11 10:47:01 Xray Core Version:
1.7.5
Aug 11 10:47:01 kr1 XrayR[383668]: 2023/08/11 10:47:01 [Warning] core: Xray 1.7.5 started
Aug 11 10:47:01 kr1 XrayR[383668]: 2023/08/11 10:47:01 Panel Start fialed: request https://bb.hudelu.top/mod_mu/nodes/2/info failed: {"ret":0,"data":"Invalid request IP."}, %!s(<nil>)
Aug 11 10:47:01 kr1 XrayR[383668]: panic: Panel Start fialed: request https://bb.top/mod_mu/nodes/2/info failed: {"ret":0,"data":"Invalid request IP."}, %!s(<nil>)
Aug 11 10:47:01 kr1 XrayR[383668]: goroutine 1 [running]:
Aug 11 10:47:01 kr1 XrayR[383668]: log.Panicf({0x3283dcd?, 0x3706700?}, {0xc000919e80?, 0xc0003f1200?, 0x2b3a6c0?})
Aug 11 10:47:01 kr1 XrayR[383668]:         log/log.go:391 +0x67
Aug 11 10:47:01 kr1 XrayR[383668]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005b5340)
Aug 11 10:47:01 kr1 XrayR[383668]:         github.com/XrayR-project/XrayR/panel/panel.go:211 +0x59b
Aug 11 10:47:01 kr1 XrayR[383668]: main.main()
Aug 11 10:47:01 kr1 XrayR[383668]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Aug 11 10:47:01 kr1 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 11 10:47:01 kr1 systemd[1]: XrayR.service: Failed with result 'exit-code'.
