### ISSUE TITLE
[BUG] 节点后端提示Server error - Invalid request IP.

### ISSUE THREAD

**Issue by AS13379** [Anankke/SSPanel-Uim#2124]
**Environment 环境**

OS:    Ubuntu22.04(节点) CentOS9(面板)
PHP version:    8.2
DB version:    10.11
Commit:    2023.4

**Bug Info**
使用AirU安装后端到DMIT HK机器，配置为SSpanel,面板自定义配置为空，链接地址为CF DNS解析的IP地址，IP地址填写为真是IP地址

**Comment by AS13379** [comment]
如果这是我的问题，麻烦各位大佬回复我而不是直接关闭，再次感谢！

**Comment by AS13379** [comment]
解决问题：由于CloudFlare开启了代理导致面板无法正确访问到节点IP地址，使用另一个域名关闭CDN后即可解决

**Comment by bxoooooo** [comment]
和我一样的操作
