### ISSUE TITLE
[BUG] 后端节点无法访问面板

### ISSUE THREAD

**Issue by AS13379** [Anankke/SSPanel-Uim#2127]
**Environment 环境**

OS:    CentOS Stream9
PHP version:    8.2
DB version:    10.11
Commit:    2023.4

**Bug Info**

后端XrayR或者AirU无论如何无法连接面板，返回405而且是有UI的

**Comment by bxoooooo** [comment]
你自己姿势不对

**Comment by AS13379** [comment]
烦请解答
