### ISSUE TITLE
[BUG] 这确实是一个关于SSpanel-UIM 2023.4 中Shadowsocks自定义配置与注册用户默认值的连接设置的问题。如果开发者觉得不是问题请回复我再关闭，感谢相互尊重

### ISSUE THREAD

**Issue by AlphaEldon** [Anankke/SSPanel-Uim#2132]
我会坚持提问这个问题直到您开始重视
在前端配置中使用 "offset_port_user"："xxxx" ←端口与用户注册默认值中的连接设置一致，同样会导致用户注册失败

**Comment by M1Screw** [comment]
@Anankke Please block this motherfucker.
