### ISSUE TITLE
[BUG] 似乎2023.3版中还在以POST的方式请求节点的info

### ISSUE THREAD

**Issue by lipeng0820** [Anankke/SSPanel-Uim#2134]
**Environment 环境**

OS:    
PHP version:    
DB version:    
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

似乎2023.3版中还在以POST的方式请求节点的info，Xrayr的后端在持续提示错误405.辛苦开发者确认。应该是2023.2版中就移除了吧？还是我自己的某一步配置存在问题？

![image](https://github.com/Anankke/SSPanel-Uim/assets/23327389/d59ba075-c8a4-42b7-82b5-fc30c22152de)
![image](https://github.com/Anankke/SSPanel-Uim/assets/23327389/68287f79-6a2b-4bb8-95f3-070a7dc17046)
![image](https://github.com/Anankke/SSPanel-Uim/assets/23327389/149d69d4-2f3d-40d3-9171-0bbaabeae16e)

**Comment by M1Screw** [comment]
https://t.me/sspanel_Uim/174
