### ISSUE TITLE
[BUG] Unknown column 'telegram_id' in 'user'

### ISSUE THREAD

**Issue by wyx2685** [Anankke/SSPanel-Uim#2136]
**Environment 环境**

OS:    ubuntu22
PHP version:    8.2
DB version:    10.11.2-MariaDB-1
Commit:    latest

**Bug Info**
php xcat Migration new
Current database version 0.

Found migration version 2023061800.
Found migration version 2023020100.
Found migration version 2023080900.
Found migration version 2023060300.
Found migration version 2023031700.
Found migration version 2023063000.
Found migration version 2023053000.
Found migration version 2023081800.
Found migration version 2023032600.
Found migration version 2023071600.
Found migration version 2023030500.
Found migration version 2023050800.
Found migration version 2023071700.
Found migration version 2023082000.
Found migration version 2023072000.
Found migration version 2023031701.
Found migration version 2023021600.
Found migration version 2023071000.

Forward to 2023020100
Forward to 2023021600
Forward to 2023030500
Forward to 2023031700
Forward to 2023031701
Forward to 2023032600
Forward to 2023050800
Forward to 2023053000
Forward to 2023060300
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'telegram_id' in 'user' in /var/www/html/SSPanel-Uim/db/migrations/2023060300-add_user_locale_and_update_data_type.php:11
Stack trace:
#0 /var/www/html/SSPanel-Uim/db/migrations/2023060300-add_user_locale_and_update_data_type.php(11): PDO->exec()
#1 /var/www/html/SSPanel-Uim/src/Command/Migration.php(103): App\Interfaces\MigrationInterface@anonymous->up()
#2 /var/www/html/SSPanel-Uim/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /var/www/html/SSPanel-Uim/db/migrations/2023060300-add_user_locale_and_update_data_type.php on line 11

应该是这个commit删了`telegram_id` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'Telegram ID',
https://github.com/Anankke/SSPanel-Uim/pull/2135/commits/e4dbb079fff4ad7eb4f84ed2d9f314fe363489e4

**Comment by visense** [comment]
怎么解决啊。。。
