### ISSUE TITLE
能否直接添加充值功能  或者购买礼品卡功能?

### ISSUE THREAD

**Issue by bxoooooo** [Anankke/SSPanel-Uim#2140]
**Feature 功能请求**

现在礼品卡功能有点用不上,能否添加个购买礼品卡,或者直接充值功能

**Comment by ligongfu** [comment]
礼品卡原名充值码，用来补充在线充值的线下充值方式
要在线发售的话可以搭个发卡网进行售卖

**Comment by M1Screw** [comment]
禮品卡的用意是站點運營者進行促銷/推廣/第三方平臺銷售用的。
譬如有些支付網關不支持銷售代理服務，不能直接接入 SSPanel，這個時候就可以通過第三方比如發卡或WHMCS等平臺進行銷售禮品卡的方式繞過限制。
又或者是你希望通過第三方渠道推廣，這個時候禮品卡就可以作爲贈品使用。
至於直接充值至賬戶的功能，目前暫時沒有計劃，以後可能會加，沒有保證。
