### ISSUE TITLE
流量商店

### ISSUE THREAD

**Issue by bxoooooo** [Anankke/SSPanel-Uim#2158]
用户疯狂反馈商店的不合理

1.时间流量包,重复购买用完不激活下一个,有些不会买流量

2.没年付这些 不好营销

3.uim强大的一匹,听听咱们的意见想法吧,是真想用下去

**Comment by bxoooooo** [comment]
我知道大佬玩的是技术

我相信一个好的产品肯定是易用简洁的.一目了然的.当然这只是我们这些想搞商业化的想法而已

**Comment by M1Screw** [comment]
> 1.时间流量包,重复购买用完不激活下一个,有些不会买流量

我想你可能對商店系統的使用有些誤解，https://wiki.sspanel.org/#/new-shop 這篇文檔中已經詳細地解釋了三種產品類型的設計與工作模式，流量耗盡不會觸發產品訂單到期是從 sspanel-v3-mod 時代就有的設計，新的商店系統只是沿襲了舊的套餐邏輯而已。
至於連流量包都不會買的用戶，這個更像是運營者本身沒有盡到教育用戶的責任，而不是面板本身的設計問題。因爲流量包的底層邏輯也是跟舊版本的 SSPanel 商店系統完全一致，除了多了一個需要等待一個 Cron 周期方可激活的額外步驟之外。

> 2.没年付这些 不好营销

有沒有一種可能，TABP可以設定30天以上的有效時長。
