### ISSUE TITLE
我的/资料中的IM账号绑定显示Username invalid用户名无效，不能绑定

### ISSUE THREAD

**Issue by mywejianyun** [Anankke/SSPanel-Uim#2159]
![屏幕截图 2023-09-06 235312](https://github.com/Anankke/SSPanel-Uim/assets/142806757/2557d111-50c8-4bb9-b855-10dbc67ca34f)
这个地方没有可以填写绑定账号的地方，显示Username invalid无效用户

**Comment by M1Screw** [comment]
你這個是 Botfather 那邊都沒正確配置 Bot domain 才會這樣。然後修改完配置要更新一下 Telegram 的 webhook 否則就會出各種奇怪的問題。

**Comment by jacksunhack** [comment]
> 

![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/a41c6b09-d30b-4fdd-8643-5e077b0cc2d6)
现在这边儿显示正常了 但是机器人发送指令还是没有反应如图
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/8b4b61af-dff6-443d-92ae-75dd3056ba48)

但是增加节点信息、规则能够有消息提示：
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/3f7a45c3-818d-4029-a103-06461214205b)


另外discord配置好了能够发送测试信息 但是guide ID 不知道
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/a6d3641d-e6cb-4d1d-843c-ac4960abd551)

尝试在reddit上找到了guide ID的位置 但配置也不成功
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/da823d42-209f-48ba-91ad-10f8188106b0)

显示OAuth2 redirect_uri 无效
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/7009e471-a42e-40c2-b471-8e6b758bb4b3)

**Comment by jacksunhack** [comment]
> 你這個是 Botfather 那邊都沒正確配置 Bot domain 才會這樣。然後修改完配置要更新一下 Telegram 的 webhook 否則就會出各種奇怪的問題。

> 

![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/a41c6b09-d30b-4fdd-8643-5e077b0cc2d6)
现在这边儿显示正常了 但是机器人发送指令还是没有反应如图
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/8b4b61af-dff6-443d-92ae-75dd3056ba48)

但是增加节点信息、规则能够有消息提示：
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/3f7a45c3-818d-4029-a103-06461214205b)


另外discord配置好了能够发送测试信息 但是guide ID 不知道
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/a6d3641d-e6cb-4d1d-843c-ac4960abd551)

尝试在reddit上找到了guide ID的位置 但配置也不成功
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/da823d42-209f-48ba-91ad-10f8188106b0)

显示OAuth2 redirect_uri 无效
![image](https://github.com/Anankke/SSPanel-Uim/assets/47632644/7009e471-a42e-40c2-b471-8e6b758bb4b3)

**Comment by bxoooooo** [comment]
大佬  tg怎么配置 能教教吗

**Comment by M1Screw** [comment]
Discord Bot 的部分目前還沒有實裝，在所有 IM 系統相關的更改完成之後會有更完善的配置文檔供運營者參考。
