### ISSUE TITLE
[BUG] 对于2023.5版本，使用xrayR后端进行对接时，会显示"ret":0,"data":"Invalid request IP."}, %!s(<nil>

### ISSUE THREAD

**Issue by iampandora** [Anankke/SSPanel-Uim#2160]
**Environment 环境**
Centos 9 Stream

OS:    
PHP version:     PHP 8.2 with OPcache
DB version:    MariaDB 10.11
Commit:     /

**Bug Info**
使用Xray后端对接时，会有如下错误：
2023/09/07 14:48:47 Panel Start fialed: request https://xxxx.xyz/mod_mu/nodes/1/info failed: {"ret":0,"data":"Invalid request IP."}, %!s(<nil>)
panic: Panel Start fialed: request https://dellcome.xyz/mod_mu/nodes/1/info failed: {"ret":0,"data":"Invalid request IP."}, %!s(<nil>)

goroutine 1 [running]:
log.Panicf({0x3283dcd?, 0x3706700?}, {0xc000a51e80?, 0xc00094c980?, 0x2b3a6c0?})
	log/log.go:391 +0x67
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00082d740)
	github.com/XrayR-project/XrayR/panel/panel.go:211 +0x59b
main.main()
	github.com/XrayR-project/XrayR/main/main.go:97 +0x250
此时，可在面板前端的服务器上，看到nginx的log显示如下：
46.xxx.xxx.xxx - - [07/Sep/2023:14:42:47 +0800] "GET /mod_mu/nodes/1/info?key=xxxxxxxxxxxxxxxxxxxxxxxx212f61ca9&muKey=xxxxxxxxxxxxxxxxxxxxxxxx212f61ca9 HTTP/2.0" 401 35 "-" "go-resty/2.7.0 (https://github.com/go-resty/resty)"

Describe the issue you run into. 请描述你遇到的问题。
面板搭建好后，无法使用xrayx正常对接前端。

**Comment by iampandora** [comment]
信息补充：环境使用oneinstack搭建，且面板是全新搭建。如果需要提供更多信息请随时提出，感谢。

**Comment by AS13379** [comment]
节点没有CDN
现已设置该选项

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月08日 12:00 |
| 收件人 | Anankke/SSPanel-Uim ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [Anankke/SSPanel-Uim] [BUG] 对于2023.5版本，使用xrayR后端进行对接时，会显示"ret":0,"data":"Invalid request IP."}, %!s(<nil> (Issue #2160) |

站点若有CDN，是否设置恢复真实IP？
节点是否双栈？需要正确填写节点IP

也可考虑将 .config.php 中 $_ENV['checkNodeIp'] 设置为 false

**Comment by iampandora** [comment]
感谢各位回复，问题已解决：
$_ENV['enable_rate_limit']    = true;            //是否开启请求限制
$_ENV['checkNodeIp']            = true;                 //是否webapi验证节点ip

将以上两个选项修改为false即可
另外，当时我的网站是没有套CDN的
