### ISSUE TITLE
[Feature Request] 大佬能改改商店系统吗？

### ISSUE THREAD

**Issue by bxoooooo** [Anankke/SSPanel-Uim#2166]
太痛苦  是真不好营销  逻辑我自己都搞懵去
机场每月重置卖的就是用户用不完    比如一年*1t
用户能用完   那如果我营销策略是每月900g  但是只能买一年
用户真用的完吗
还有时间包 感觉没作用  流量包可以

**Comment by bxoooooo** [comment]
能否在原来基础上增加一个每月自动重置流量的功能

**Comment by jacksunhack** [comment]
> 能否在原来基础上增加一个每月自动重置流量的功能 并且流量用完 用户有套餐的话也自动激活

我觉得这个提议不错，套餐流量用完就自动激活下一个
