### ISSUE TITLE
[Feature Request] 建议节点增加动态倍率

### ISSUE THREAD

**Issue by jacksunhack** [Anankke/SSPanel-Uim#2174]
**Feature 功能请求**

Describe the feature you want. 请描述你想要的功能。
建议节点增加动态倍率

**Comment by M1Screw** [comment]
Dynamic rate service has been added at https://github.com/Anankke/SSPanel-Uim/commit/4d31d34356c5c46a3219a9db672203dc83a41427, however, the full implementation is not included in this commit.

The remaining code regarding configuration and frontend display of dynamic rate will be added after proper testing can be conducted.

**Comment by M1Screw** [comment]
Both configuration & WebAPI implementation of dynamic rate service have been added at https://github.com/Anankke/SSPanel-Uim/commit/5b09d2ae98caecf9c986d740eee7138a2f6ebef8 & https://github.com/Anankke/SSPanel-Uim/commit/88a66b86e6fa92f81e1de7a004359bf62428aee2, now this feature request will be considered completed.
