### ISSUE TITLE
[BUG] 在这里填入你所遇到问题的概述

### ISSUE THREAD

**Issue by wuchen4588** [Anankke/SSPanel-Uim#2175]
**Environment 环境**

OS:    CentOS
PHP version:    7.4
DB version:    MySQL5.7.4
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

问一下为什么我的SSpanel无法重置天数了，已经加入了cron计划。但是就是不能重置很奇怪
![image](https://github.com/Anankke/SSPanel-Uim/assets/60568101/db504561-3bde-4877-b509-b9ef5d2b57f7)

![image](https://github.com/Anankke/SSPanel-Uim/assets/60568101/01440e72-1292-437f-b9da-ef3336898d91)

**Comment by M1Screw** [comment]
This is not a standard SSPanel-UIM installation.

**Comment by jacksunhack** [comment]
6
这也不是2023.5啊

**Comment by wuchen4588** [comment]
> 6 这也不是2023.5啊

老版本sspanel-uim，装的metron主题。莫名奇妙不能重置天数
