### ISSUE TITLE
第二次购买订阅套餐不会重置流量和账户等级时间

### ISSUE THREAD

**Issue by Simonaorg** [Anankke/SSPanel-Uim#2182]
**Environment 环境**

OS:   ubuntu 
PHP version:    8.2
DB version:    10.11
Commit:    2023.4 2023.5

**Bug Info**
第二次购买订阅不会重置流量和账户等级时间，第三次可能会重置，随缘

**Comment by Simonaorg** [comment]
第一次购买商品成功重置流量和账户时间，第二次套餐期间购买未能重置，重复多次购买，出现流量归零

**Comment by bxoooooo** [comment]
不是bug   第二次需要等到第一次时间过期才激活  不是根据流量来的

**Comment by lewuzzx** [comment]
但是，不一样吧
![屏幕截图 2023-10-02 035441](https://github.com/Anankke/SSPanel-Uim/assets/124391916/15fc246a-11e2-483d-aacd-84122cfc2ec4)

**Comment by M1Screw** [comment]
https://wiki.sspanel.org/#/new-shop?id=%e5%8a%9f%e8%83%bd%e5%af%b9%e7%85%a7%e8%a1%a8

**Comment by lewuzzx** [comment]
> https://wiki.sspanel.org/#/new-shop?id=%e5%8a%9f%e8%83%bd%e5%af%b9%e7%85%a7%e8%a1%a8

I understand, thank you for answering my question

**Comment by Simonaorg** [comment]
套餐是时间流量包，实际测试和功能描述不一样

**Comment by Simonaorg** [comment]
再补充一个，后台修改账户等级时间无效，不会同步到用户端，2023.4 2023.5都有这个问题

**Comment by lewuzzx** [comment]
> 再补充一个，后台修改账户等级时间无效，不会同步到用户端，2023.4 2023.5都有这个问题

后台修改账户等级时间无效？不会啊，都是正常的啊，除了时间流量包只支持一次购买其他都是正常的
