### ISSUE TITLE
后台手动延长账户等级时间后不能同步到用户端

### ISSUE THREAD

**Issue by Simonaorg** [Anankke/SSPanel-Uim#2188]
**Environment 环境**

OS:    ubuntu
PHP version:    8.2
DB version:    10.11
Commit:    2023.4 2023.5

**Bug Info**

后台手动延长账户等级时间后不能同步到用户端

**Comment by lewuzzx** [comment]
哥们你哪里出问题了吧？手动延长不能同步？肯定是有问题的。正常搭建下来不可能出现这种问题

**Comment by Simonaorg** [comment]
2022.4貌似是我服务器的原因，修改后数据未保存，没有修改成功的提示，刚测试了几次，修改时间没问题
但是2023.5 修改账户等级时间（修改后在有效期内），用户端没有等级时间显示，提示前往商店购买，导入现有的订阅v2更新结果为无效订阅

**Comment by lewuzzx** [comment]
![屏幕截图 2023-10-02 103624](https://github.com/Anankke/SSPanel-Uim/assets/124391916/f470fc2e-b134-4916-aa6c-14b9ea4de7ff)

**Comment by Simonaorg** [comment]
对，后台显示修改成功，你在前端登录这个账户看看时间是不是一致

**Comment by lewuzzx** [comment]
你自己的问题

**Comment by Simonaorg** [comment]
换了个账号测试了 确实又可以了
