### ISSUE TITLE
[BUG] Sing-Box订阅报错

### ISSUE THREAD

**Issue by chauyuen** [Anankke/SSPanel-Uim#2193]
**Environment 环境**

OS:Debian GNU/Linux 12
PHP version:8.2.2
DB version:MariaDB 10.11
Commit: https://github.com/Anankke/SSPanel-Uim/commit/2ef85d082f765b05f187f8436f0bad36c0538f4f

**Bug Info**
![1696562343637.png](https://s1.locimg.com/2023/10/06/f2d30e84d770c.png)

节点配置
{
  "host": "hostname.local",
  "path": "/path",
  "network": "ws",
  "ws-opts": {
    "path": "/path"
  },
  "alter_id": "0",
  "security": "tls",
  "server_user": "hostname.local",
  "offset_port_node": "nodeserverport",
  "offset_port_user": "443"
}

看起来像是WS的transport下面不能出现host，辛苦看看。

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/d85c4ed0fa357ada498979659206e6a33a3e3abc.

**Comment by chauyuen** [comment]
还是不太行，https://sing-box.sagernet.org/zh/configuration/shared/tls/
tls.server_name应该是个字符串，目前给的是一个数组。
![1696611112788.png](https://s1.locimg.com/2023/10/07/39d432b29062c.png)
