### ISSUE TITLE
[Feature Request] 希望未来文档编辑里可以插入图片

### ISSUE THREAD

**Issue by Chan110011** [Anankke/SSPanel-Uim#2194]
**Feature 功能请求**

希望未来文档编辑里可以插入图片，图文结合的试用教程才有利于客户学习。

**Comment by M1Screw** [comment]
This feature has been added at https://github.com/Anankke/SSPanel-Uim/commit/01fbc53036b74c7c3cb01bb03d41a40cb57fac51.

**Comment by ighunk** [comment]
复制、导入订阅按钮能加下吗 谢谢
