### ISSUE TITLE
[BUG] 定时任务设置菜单报错

### ISSUE THREAD

**Issue by miaowuawa** [Anankke/SSPanel-Uim#2195]
**Environment 环境**

OS:    Centos 7
PHP version:    8.2
DB version:    10.6
Commit:    2023.5

**Bug Info**
![image](https://github.com/Anankke/SSPanel-Uim/assets/46997899/47bf2d4e-d1b6-4ee0-a1ee-c2d5e33dd7f2)
![image](https://github.com/Anankke/SSPanel-Uim/assets/46997899/592d3424-0736-4e1f-9ef0-1ca17ded8623)
定时任务可以正常执行，但是每个定时任务设置页面都出现类似的报错，其他功能不受影响，但是看起来挺难受的，也设置不了

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/5e82d1af27cb53b299761fe10ecb09882761450b.
