### ISSUE TITLE
流量包订单——商品内容报错

### ISSUE THREAD

**Issue by ooo0luo** [Anankke/SSPanel-Uim#2201]
流量包订单点击查看后，商品内容部分报错，订单可以正常生效，只是订单详情里面的商品内容部分报错。时间流量包没有问题，时间包未测试。

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/5fbf13c2e86e61e43f060eafc6d3bf6b31cd0523.
