### ISSUE TITLE
[BUG] 对于2023.5版本，使用xrayR后端进行对接时，会显示"ret":0,"data":"Invalid request IP."}, %!s(<nil>

### ISSUE THREAD

**Issue by FaithAluten** [Anankke/SSPanel-Uim#2202]
**Environment 环境**

OS:    ubuntu 22.04 /x86_64
PHP version:    8.2
DB version:    11.1.2-MariaDB-1:11.1.2+maria~ubu2204
Commit:    2023.5

**Bug Info**
使用Xray后端对接时，会有如下错误：
Panel Start fialed: request https://www.my.domain/mod_mu/nodes/1/info failed: {"ret":0,"data":"Invalid request."}, %!s(<nil>)
panic: Panel Start fialed: request https://www.my.domain/mod_mu/nodes/1/info failed: {"ret":0,"data":"Invalid request."}, %!s(<nil>)
goroutine 1 [running]:
log.Panicf({0x358c09d?, 0x39d0340?}, {0xc00092fe20?, 0xc00027d4d0?, 0x2dd6ea0?})
log/log.go:439 +0x65
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0002056c0)
github.com/XrayR-project/XrayR/panel/panel.go:210 +0x5db
main.main()
github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Describe the issue you run into. 请描述你遇到的问题。
nginx 的日志如下：
access.log: "GET /mod_mu/nodes/1/info?key=xxxsdaj&muKey=xxxsdaj HTTP/1.1" 401 46 "-" "go-resty/2.9.1 (https://github.com/go-resty/resty)"
error.log: *305 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "WebAPI" in /my/sspanel/path/src/Middleware/NodeToken.php on line 45" while reading response header from upstream, client: x.x.x.x, server: www.my.domain, request: "GET /mod_mu/nodes/1/info?key=xxxsdaj&muKey=xxxsdaj  HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.2-fpm.sock:", host: "www.my.domain"
.config.php配置：
在默认配置的基础上只修改了$_ENV['key']；$_ENV['baseUrl']；$_ENV['muKey']以及数据库的配置，其余保持默认
后尝试更改下面两个为 false，无效
$_ENV['enable_rate_limit'] = false; //是否开启请求限制
$_ENV['checkNodeIp'] = false; //是否webapi验证节点ip
站点配置：
在本地新开的 ubuntu 虚拟机完全按照wiki里的配置
利用一台公网ip 为a.a.a.a的服务器（已经*.my.domain和my.domain解析到a.a.a.a）进行frp穿透，为http://www.my.domain:11111，再用这台a.a.a.a的服务器将端口11111反代到本机的 443 端口，并加上 ssl 证书，实现https://www.my.domain访问站点
没有使用任何 cdn

**Comment by M1Screw** [comment]
Check you request hostname.

**Comment by FaithAluten** [comment]
> Check you request hostname.

My request hostname is set to 'www.my.domain' in both xrayr's 'config.yaml' and sspanel's '.config.php'. Can you please advise on where specifically I should check? Your assistance would be greatly appreciated.
