### ISSUE TITLE
订阅问题

### ISSUE THREAD

**Issue by lewuzzx** [Anankke/SSPanel-Uim#2203]
**Environment 环境**

OS:    Debian11
PHP version:    8.2
DB version:    10.11
Commit:    2023.5

**Bug Info**

现存IOS的Clash订阅并不支持Shadowrocket使用，可以导入节点可以刷新有延迟，但并不能正常打开网页或者浏览Youtube，我试过其他面板的订阅没有问题，但是sspanel面板重装了好几次都不行！

**Comment by jacksunhack** [comment]
这个确实有问题 我也有用户反馈 概率会

**Comment by M1Screw** [comment]
It's because Shadowrocket can't properly handle empty clash YAML fields, use Stash instead.
