### ISSUE TITLE
[BUG] Sing-Box订阅报错

### ISSUE THREAD

**Issue by FaithAluten** [Anankke/SSPanel-Uim#2205]
**Environment 环境**

OS:   ubuntu22.04
HTTPS enabled:   enabled
PHP version:    8.2
DB version:  10.11
Redis version:    7.0
Commit:    221afb0

**Bug Info**
![600372804](https://github.com/Anankke/SSPanel-Uim/assets/65154243/bc183a91-4d2c-4d0e-82e0-fec62b6c1b0a)

Describe the issue you run into. 请描述你遇到的问题。
```
vmess:unsupported security type:tls
```
- dev加入了 sing-box 客户端，希望更新wiki 相关的配置范例
- 希望更新 v2ray 相关的中转范例，wiki 中只提供了中转端口的范例，没有中转和落地域名/ip 怎么填的范例

**Comment by FaithAluten** [comment]
且`"enable_vless": "1",`无效，配置下发依然是 vmess

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/eedf480d42b5939cb53b894337a5d80a7ba589de.
