### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Arango823** [Anankke/SSPanel-Uim#2215]
请求集成 [epusdt](https://github.com/assimon/epusdt) 支付！

**Comment by M1Screw** [comment]
https://github.com/assimon/epusdt#%E5%A3%B0%E6%98%8E

![fuckfuckcat_06bf1b0b](https://github.com/Anankke/SSPanel-Uim/assets/14369594/b0ab4afe-960f-426c-9601-2928d68f2ff4)
