### ISSUE TITLE
貌似数据库升级失败

### ISSUE THREAD

**Issue by Simonaorg** [Anankke/SSPanel-Uim#2221]
**Environment 环境**

OS:   ubuntu
HTTPS enabled:   yes
PHP version:    最新
DB version:  最新
Redis version:    最新
Commit:   2023.5 2023082000

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
用目前ubuntu教程安装的最新安装包，尝试升级同等级安装包，提示如下（操作几次都是这个提示）：
迁移完成。
正在更新 GeoLite2 数据库...
成功更新 GeoLite2 数据库。
没有任何新数据库设置项需要添加
Current database version 2023020100.

Found migration version 2023071700.
Found migration version 2023031700.
Found migration version 2023082000.
Found migration version 2023061800.
Found migration version 2023060300.
Found migration version 2023071600.
Found migration version 2023071000.
Found migration version 2023072000.
Found migration version 2023020100....skip
Found migration version 2023031701.
Found migration version 2023080900.
Found migration version 2023063000.
Found migration version 2023050800.
Found migration version 2023030500.
Found migration version 2023053000.
Found migration version 2023081800.
Found migration version 2023032600.
Found migration version 2023021600.

Forward to 2023021600
Forward to 2023030500
Forward to 2023031700
Forward to 2023031701
Forward to 2023032600
Forward to 2023050800
Forward to 2023053000
Forward to 2023060300
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'telegram_id' in 'user' in /var/www/v2/db/migrations/2023060300-add_user_locale_and_update_data_type.php:11
Stack trace:
#0 /var/www/v2/db/migrations/2023060300-add_user_locale_and_update_data_type.php(11): PDO->exec()
#1 /var/www/v2/src/Command/Migration.php(103): App\Interfaces\MigrationInterface@anonymous->up()
#2 /var/www/v2/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /var/www/v2/db/migrations/2023060300-add_user_locale_and_update_data_type.php on line 11

**Comment by mpton1986738** [comment]
同样
