### ISSUE TITLE
哪个commit稳定？

### ISSUE THREAD

**Issue by visense** [Anankke/SSPanel-Uim#2222]
最新的[ab10743](https://github.com/Anankke/SSPanel-Uim/commit/ab107438d7b302c5b8ebcfbe50f6da5b22d55910)
搭建完成，后台修改用户等级比如为100，过几分钟自动恢复为了0

2023.5版本，使用php xcat Migration new
提示：
telegram_id 列找不到。。。。

折腾3天了，哪个commit能稳定跑起来

**Comment by M1Screw** [comment]
> 后台修改用户等级比如为100，过几分钟自动恢复为了0

只修改等級不修改到期時間就會觸發付費用戶過期檢查，然後等級和流量被清零，這是預期的表現。

**Comment by visense** [comment]
感谢大佬！
