### ISSUE TITLE
无法建立节点，点击保存500错误。

### ISSUE THREAD

**Issue by 759071793** [Anankke/SSPanel-Uim#2233]
**Environment 环境**

OS:   Ubuntu 22.04.2 LTS aarch64(Py3.7.8)
HTTPS enabled:   YES
PHP version:    8.2
DB version:  MySQL 10.7.3-MariaDB
Redis version:    7
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
<img width="669" alt="image" src="https://github.com/Anankke/SSPanel-Uim/assets/23308600/f940650f-c658-496d-bff2-06581aff28d0">

节点创建界面无法保存，下面有很多报错。

**Comment by 759071793** [comment]
请问一下大佬为什么直接给我关了你，是我哪里没有描述好吗，我这边导入数据库啥的没有一点报错，就是进网页后台创建节点500错误，storage文件夹下面生成的临时文件报错，折腾了一个通宵了，不停重装删除，仔细看文档。
可是真的搭建部署过程中一点错误没有。伪静态也是设置了的，php相关函数也禁用了，数据库结构也全都导入没有一点问题，只是node这张表一开始肯定是空的。

望管理能提点一下。。。

**Comment by M1Screw** [comment]
Fixed at https://github.com/Anankke/SSPanel-Uim/commit/4d26ebf7448ce0facff97df394210c5e34a80513.
