### ISSUE TITLE
[BUG] mod_mu/users  返回用户数组为空

### ISSUE THREAD

**Issue by ckbkdj** [Anankke/SSPanel-Uim#2234]
**Environment 环境**

OS: ubuntu 22   
HTTPS enabled:  true 
PHP version:    8.2
DB version:  MariaDB11.1
Redis version:    
Commit:    
sspanel版本：2023.06

**Bug Info**
获取节点用户返回空。
Describe the issue you run into. 请描述你遇到的问题。
根据官方wiki安装完以后，配置完成节点，配置完用户，用户组跟等级都正常， 但是根据api测试了mod_mu/users用户数据总是返回空集合。

**Comment by M1Screw** [comment]
A more clear WebAPI return msg has been added at https://github.com/Anankke/SSPanel-Uim/commit/5f57aa2c9c19a8d9c71ff31d3ec4382714ed4bc5.
