### ISSUE TITLE
2023.6 无法签到。余额购买产品后卡在等待中

### ISSUE THREAD

**Issue by ckbkdj** [Anankke/SSPanel-Uim#2236]
**Environment 环境**

OS:   ubuntu22
HTTPS enabled:   yes
PHP version:    8.2
DB version:  11.1
Redis version:    7
Commit:    [2023.6](https://github.com/Anankke/SSPanel-Uim/releases/tag/2023.6)

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

1. 版本2023.6 部署完成后，发现无法签到。点击无响应，
2. 创建节点确定后也没有提示，创建完成后，需要手动返回节点列表确认是否创建成功，

**Comment by wyUshio** [comment]
问下创建节点的时候咋保存的?我拉取的修复版本,还是创建不了

**Comment by ckbkdj** [comment]
> 问下创建节点的时候咋保存的?我拉取的修复版本,还是创建不了

能保存啊。我直接下载的是2023.6版本。

**Comment by ighunk** [comment]
签到
<img width="579" alt="Screen Shot 2023-11-11 at 10 42 58" src="https://github.com/Anankke/SSPanel-Uim/assets/80145128/50126ee9-2d8f-42df-bbc3-9b1fd7b8f25e">

**Comment by wyUshio** [comment]
> > 问下创建节点的时候咋保存的?我拉取的修复版本,还是创建不了
> 
> 能保存啊。我直接下载的是2023.6版本。

emm 难道体质不一样吗...

**Comment by wyUshio** [comment]
> > 问下创建节点的时候咋保存的?我拉取的修复版本,还是创建不了
> 
> 能保存啊。我直接下载的是2023.6版本。

你装的开发版还是普通的啊?

**Comment by ckbkdj** [comment]
> > > 问下创建节点的时候咋保存的?我拉取的修复版本,还是创建不了
> > 
> > 
> > 能保存啊。我直接下载的是2023.6版本。
> 
> 你装的开发版还是普通的啊?

肯定是正式版，不是开发板
