### ISSUE TITLE
php xcat Migration new 无法连接数据库

### ISSUE THREAD

**Issue by monsterchick** [Anankke/SSPanel-Uim#2300]
**Environment 环境**

OS:   Ubuntu 22.04 LTS
HTTPS enabled:   False
PHP version:    PHP 8.2.12 (cli)
DB version:  11.1.3-MariaDB-1:11.1.3+maria~ubu2204
Redis version:    7.2.3
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
当输入php xcat Migration new后，
报错：Could not connect to main database: SQLSTATE[HY000] [2002] No such file or directoryroot@sspanel:~/chocola.world#

**Comment by jack338c** [comment]
@linhtieusai do you mean correct the my.cnf?
Could you tell me how to do that?
I got same issue according to the offical tutorial[https://wiki.sspanel.org/#/install-using-ubuntu]( https://wiki.sspanel.org/#/install-using-ubuntu)

thanks
