### ISSUE TITLE
正在從舊SSP版本更新到最新版，有個問題

### ISSUE THREAD

**Issue by hsly109** [Anankke/SSPanel-Uim#2305]
OS:   debian12
HTTPS enabled:   HSTS
PHP version:    8.2
DB version:  10.11
Redis version:    
Commit:    

因為我是從3年前的ssp版本進行更新，我發現目前最新版本的ssp的password加密方法上似乎不存在sha256了，請問是被移除了嗎

**Comment by M1Screw** [comment]
You can check https://github.com/Anankke/SSPanel-Uim/blob/dev/src/Utils/Hash.php for the supported hash method.
