### ISSUE TITLE
[BUG] 在这里填入你所遇到问题的概述

### ISSUE THREAD

**Issue by linhtieusai** [Anankke/SSPanel-Uim#2309]
**Environment 环境**
Ubuntu

OS:   22.04
HTTPS enabled:   Yes
PHP version:    8
DB version:  
Redis version:    
Commit:    

**Bug Info**
```

Forward to 2023020100
Forward to 2023021600
Forward to 2023030500
Forward to 2023031700
Forward to 2023031701
Forward to 2023032600
Forward to 2023050800
Forward to 2023053000
Forward to 2023060300
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'telegram_id' in 'user' in /home/5g/db/migrations/2023060300-add_user_locale_and_update_data_type.php:11
Stack trace:
#0 /home/5g/db/migrations/2023060300-add_user_locale_and_update_data_type.php(11): PDO->exec()
#1 /home/5g/src/Command/Migration.php(103): App\Interfaces\MigrationInterface@anonymous->up()
#2 /home/5g/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /home/5g/db/migrations/2023060300-add_user_locale_and_update_data_type.php on line 11
```

Describe the issue you run into. 请描述你遇到的问题。

I follow all step and trouble at this step:
php xcat Migration new
=> causing the error

i pointed my domain to VPS IP, and the UI show OK. but click on Register / Login then nothing happen. i am stuck at Register / Login screen
you can check my site (still a fresh install of SSpanel)
http://5g.viecthom.com/auth/login

**Comment by shyding** [comment]
![image](https://github.com/Anankke/SSPanel-Uim/assets/24986567/cbc6133e-30bf-4b74-a109-683116007887)

**Comment by shyding** [comment]
界面已经添加了用户 ,可是XrayR后端一直提示无用户, 订阅也显示没有节点 ,可是节点列表却有节点, 使用的是dev最新版
![image](https://github.com/Anankke/SSPanel-Uim/assets/24986567/cd98e60b-8182-4f6d-8a12-845dec41607a)
