### ISSUE TITLE
[BUG] 访问订阅链接时报REDIS错误

### ISSUE THREAD

**Issue by lowprofileusername** [Anankke/SSPanel-Uim#2335]
**Environment 环境**

OS:   
HTTPS enabled:   
PHP version:    8.2
DB version:  
Redis version:    7
Commit:    

**Bug Info**

Slim Application Error

The application could not run because of the following error:
Details
Type: ArgumentCountError
Code: 0
Message: Redis::__construct() expects exactly 0 arguments, 1 given
File:  SSPanel-Uim/src/Services/Cache.php
Line: 13
Trace

最新COMMIT
请问是哪里设置问题？

**Comment by M1Screw** [comment]
PHP Redis extension version must be higher than 6.0.0.

**Comment by iWATCHDOG** [comment]
> PHP Redis extension version must be higher than 6.0.0.

The php redis version is the latest version and still looks like this.

**Comment by Anankke** [comment]
> > PHP Redis extension version must be higher than 6.0.0.
> 
> The php redis version is the latest version and still looks like this.

What's your current commit ver?
