### ISSUE TITLE
如何接入没有SMTP授权码的邮箱服务商

### ISSUE THREAD

**Issue by Xmu2022** [Anankke/SSPanel-Uim#2339]
**Environment 环境**

OS:   
HTTPS enabled:   
PHP version:    
DB version:  
Redis version:    
Commit:    

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
如何接入没有SMTP授权码的邮箱服务商，或者自建的邮箱服务，只有账号与密码，如果接入？？？

**Comment by Anankke** [comment]
1. 换一家有的 SMTP 的；
2. 没有的话就不是给你发 SMTP 的，你可以说说是啥服务商，大概率只是没找到而已；
3. 自己写 HTTP API，抄代码里面的例子。

**Comment by Xmu2022** [comment]
主要是自建的SMTP没有办法提供，比如宝塔的邮局管理器，docker-mailserver,这些都提供不了SMTP授权码，

我也想过自己写HTTP API，但没有方向，能给个思路吗？

**Comment by M1Screw** [comment]
Skill issue.

**Comment by Anankke** [comment]
> 主要是自建的SMTP没有办法提供，比如宝塔的邮局管理器，docker-mailserver,这些都提供不了SMTP授权码，

据我所知这俩都有，太菜导致的不能用。

**Comment by Xmu2022** [comment]
> > 主要是自建的SMTP没有办法提供，比如宝塔的邮局管理器，docker-mailserver,这些都提供不了SMTP授权码，
> 
> 据我所知这俩都有，太菜导致的不能用。

你的意思是，这两个服务商都能提供SMTP授权码？不会的吧，宝塔的，我到官网论坛找过，是明确说没有的，docker-mailserver，刚建了，找遍了配置文件，也没找到关于SMTP密码的相关参数，只有账号密码

**Comment by Xmu2022** [comment]
> > 主要是自建的SMTP没有办法提供，比如宝塔的邮局管理器，docker-mailserver,这些都提供不了SMTP授权码，
> 
> 据我所知这俩都有，太菜导致的不能用。

能提供一下找SMTP密码的思路吗？如何去搜索，这问题困了我一周了，不胜感激
