### ISSUE TITLE
[Feature Request] 流量时间产品包用户自己选择是否直接生效

### ISSUE THREAD

**Issue by SHIINMASHIRO** [Anankke/SSPanel-Uim#2340]
**Feature 功能请求**

当前:
目前的流量时间产品是根据时间来判断重复购买的产品是否直接生效的.
又一个问题就是当用户的时间流量产品中的流量到期后,想直接购买新相同的流量时间产品.因为他们不想购买单独的流量包.
此时如果原先的套餐没有到期后,则会一直等待生效.

改进:
希望能做一个按钮,用户可以直接手动选择覆盖当前的流量时间套餐. 并且时间依据是当前的时间来生效产品.

例如:
用户流量时间: 2024年3月1日到期 剩余流量0GB 
当前时间: 2024年1月22日.
购买 时间流量产品 时长1个月 流量 300G
手动执行生效后:

2024年2月22日到期, 剩余流量 300G

Thanks.

**Comment by M1Screw** [comment]
Or allow the user to pay to reset their tabp. Overwrite tabp directly could result in Cron problems.

**Comment by SHIINMASHIRO** [comment]
> Or allow the user to pay to reset their tabp. Overwrite tabp directly could result in Cron problems.

请问这个在哪里重置呢,好像没有找到
