### ISSUE TITLE
2023.7 版本问题

### ISSUE THREAD

**Issue by jack338c** [Anankke/SSPanel-Uim#2358]
大神好！
全新安装到这一步：php xcat Migration new，出现下面错误。2023.6没有这个问题
请问这是什么原因，如何解决？
谢谢！
祝新年一切都好！
`Forward to 2023060300
Forward to 2023061800
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.user_hourly_usage' doesn't exist in /var/www/xx.xxx.com/db/migrations/2023061800-update_new_shop_data_type.php:11
Stack trace:
#0 /var/www/xx.xxx.com/db/migrations/2023061800-update_new_shop_data_type.php(11): PDO->exec()
#1 /var/www/xx.xxx.com/src/Command/Migration.php(110): App\Interfaces\MigrationInterface@anonymous->up()
#2 /var/www/xx.xxx.com/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /var/www/xx.xxx.com/db/migrations/2023061800-update_new_shop_data_type.php on line 11`

**Comment by M1Screw** [comment]
This is a repeated problem every time a table is renamed/dropped in the newer version of the database, to fix this issue once and for all, a patch will be added to the main repo to disable any intermedial db migrations for new installation.

**Comment by jack338c** [comment]
@M1Screw 
thank you very much for your help !

**Comment by M1Screw** [comment]
This issue should be fixed at https://github.com/Anankke/SSPanel-Uim/commit/17b1f85da01d3e2b22ddeffa408bfdff850c3066.

**Comment by jack338c** [comment]
understood
thanks again !
