### ISSUE TITLE
[Feature Request] 邮件验证发送设置限时

### ISSUE THREAD

**Issue by IngressPrime** [Anankke/SSPanel-Uim#2363]
**Feature 功能请求**

用户注册在发送邮箱验证码时，请求发送成功后设置发送按钮禁用或者显示已发送并设置重发倒计时。
用户在重置密码时，发送邮件也希望如上设置。

其他问题：重置密码的连接在设置密码时请求更改时显示连接无效，无法重置密码。

**Comment by M1Screw** [comment]
> 请求发送成功后设置发送按钮禁用或者显示已发送并设置重发倒计时

I will consider this feature.

> 重置密码的连接在设置密码时请求更改时显示连接无效，无法重置密码

Check your Redis connection, and the link will expire after one visit/page load, make sure there is no link preview or link scan feature enabled in your email provider.

**Comment by iefnuy** [comment]
>and the link will expire after one visit/page load, make sure there is no link preview or link scan feature enabled in your email provider.

能否在用户请求修改密码成功后再使链接失效而不是访问一次就失效。

**Comment by M1Screw** [comment]
> 能否在用户请求修改密码成功后再使链接失效而不是访问一次就失效。

No, this is a safety feature.

**Comment by M1Screw** [comment]
Added at https://github.com/Anankke/SSPanel-Uim/commit/9d668ace636a72f1d80ee9307d430fb4f1f8b6d0.
