### ISSUE TITLE
按WIKI安装 更新配套数据库版本问题

### ISSUE THREAD

**Issue by HsiaoweiYuen** [Anankke/SSPanel-Uim#2374]
报错如下：

 PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.user_hourly_usage' doesn't exist in /www/sspanel/域名/db/migrations/2023061800-update_new_shop_data_type.php:11
Stack trace:
#0 /www/sspanel/域名/db/migrations/2023061800-update_new_shop_data_type.php(11): PDO->exec()
#1 /www/sspanel/域名/src/Command/Migration.php(110): App\Interfaces\MigrationInterface@anonymous->up()
#2 /www/sspanel/域名/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /www/sspanel/域名/db/migrations/2023061800-update_new_shop_data_type.php on line 11

重装安装了数次，一直卡在2023061800这

**Comment by HsiaoweiYuen** [comment]
![Screenshot_20240227_042038.jpg](https://github.com/Anankke/SSPanel-Uim/assets/76433131/f2c6add1-96ca-4c06-9a4d-b784d1ce609c)

**Comment by hanmaier** [comment]
?  这不是写了 表不存在么

**Comment by HsiaoweiYuen** [comment]
> ?  这不是写了 表不存在么

搭建了几次，有一次也不知道怎么成功了，然后我比较好奇，我重装了服务器，后面再也不行了😅
