### ISSUE TITLE
[BUG] Check-In without captcha enabled will fail and User can't open the ticket

### ISSUE THREAD

**Issue by adpeng** [Anankke/SSPanel-Uim#2384]
**Environment 环境**

OS:   ubuntu 22.04.4
HTTPS enabled:   Nginx 1.22.1
PHP version:    8.2,8.3
DB version:  10.11.6-MariaDB
Redis version:    7.2,7.0,6.2

第一，注册与找回密码发送不了邮件报错如下：
![photo_2024-03-03_00-10-58](https://github.com/Anankke/SSPanel-Uim/assets/131513002/9820e595-7fc4-4481-90c9-3cb1b53d1486)

第二，签到不开启后台cloudflare验证的话签到不了提示如下：
![photo_2024-03-03_00-12-20](https://github.com/Anankke/SSPanel-Uim/assets/131513002/4515f6e6-797e-4f59-8db8-22f5f5e184af)

第三，前台用户工单提交报错提交不了
![image](https://github.com/Anankke/SSPanel-Uim/assets/131513002/a78dae94-1b3f-4718-8549-9f6e9583b7d5)

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

**Comment by M1Screw** [comment]
1. Use php redis extension version 6.0+
2. Fixed in the dev branch.
3. Fixed in the dev branch.

**Comment by adpeng** [comment]
php redis 扩展版本 6.0.2  已经更新为这个版本了
Redis版本： 7.2,7.0,6.2
版本下载的目前最新版，前台创建工单还是报
![image](https://github.com/Anankke/SSPanel-Uim/assets/131513002/e53440a9-d198-4735-ad4a-10f2e04a417b)

签到不开启 Turnstile 签到还是报错
![image](https://github.com/Anankke/SSPanel-Uim/assets/131513002/35b7f4ec-06de-4bb1-be49-c9f6f9e90b23)

注册发送邮箱验证OK了
