### ISSUE TITLE
[BUG] 返利逻辑里潜在的bug

### ISSUE THREAD

**Issue by leokke** [Anankke/SSPanel-Uim#2388]
**Environment 环境**

OS:   无关
HTTPS enabled:   无关
PHP version:    无关
DB version:  无关
Redis version:    无关
Commit:    6136289

**Bug Info**

当支付平台对同一个支付订单重复多次调用notify接口后，邀请人可能会获得多次返利。我目前的解决方法是在payback表中增加trade_no字段，以此达到对多次notify的去重。
因为本地的代码改的太乱了，所以原谅我不能提贡献，以及期待你们有更漂亮的解决方式～

**Comment by M1Screw** [comment]
What?
