### ISSUE TITLE
[BUG] 好像是易支付回调的问题

### ISSUE THREAD

**Issue by zesai** [Anankke/SSPanel-UIM#2402]
**Environment 环境**

项目版本：2023.4

**Bug Info**

2024/03/24 03:16:25 [error] 431443#0: *3401198 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "money" in /www/sspanel/src/Services/Gateway/Epay.php on line 144" while reading response header from upstream, client: 106.00.00.255, server: xxxxx.xyz, request: "GET /user/payment/return/epay HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.xxxx.xyz", referrer: "https://xxxxxx.com/"

偶尔会有这样的日志

**Comment by M1Screw** [comment]
Web server connectivity issue.
