### ISSUE TITLE
[BUG] Rate Limit功能异常

### ISSUE THREAD

**Issue by xinyang0326** [Anankke/SSPanel-UIM#2418]
**Environment 环境**
OS:   CentOS 7.6
HTTPS enabled: Yes
PHP version: 8.2.16
DB version: mariadb 11.3.2
Redis version: 7.2.4
Commit:    

**Bug Info**
如果开启 Rate Limit 和 checkNodeIp 所有 WebApi接口 将无法返回数据并抛出 服务器500
以下是详细日志，具体问题定位大概在 rate_limit_webapi 和 rate_limit_webapi_ip 上
![屏幕截图 2024-04-21 184812](https://github.com/Anankke/SSPanel-UIM/assets/69512631/df35313d-c313-45f7-987e-591fa36c358b)

**Comment by M1Screw** [comment]
Install php-redis extension v6.0+.
