### ISSUE TITLE
[BUG] 在这里填入你所遇到问题的概述

### ISSUE THREAD

**Issue by chibinyong** [Anankke/SSPanel-UIM#2419]
**Environment 环境**

OS:   debian12
HTTPS enabled:   
PHP version:    8.3
DB version:  10.11.6-MariaDB
Redis version:    7.2.4
Commit:    
从2023.7 2024012700升级到2024.1 2024040500时，软件版本成功升级但是数据库版本升级失败，以下是报错代码，希望能指导下怎么解决
**Bug Info**
Current database version 2024012700

Found migration version 2023060300...skip
Found migration version 2023111801...skip
Found migration version 2024012700...skip
Found migration version 2023031701...skip
Found migration version 2023071600...skip
Found migration version 2024012300...skip
Found migration version 2023063000...skip
Found migration version 2023050800...skip
Found migration version 2023072000...skip
Found migration version 2023053000...skip
Found migration version 2023082000...skip
Found migration version 2024040500
Found migration version 2023081800...skip
Found migration version 2023120700...skip
Found migration version 2024031700
Found migration version 2024012000...skip
Found migration version 2023021600...skip
Found migration version 2023102200...skip
Found migration version 2023061800...skip
Found migration version 2024030300
Found migration version 2023111800...skip
Found migration version 2024031000
Found migration version 2023080900...skip
Found migration version 2023032600...skip
Found migration version 2023071700...skip
Found migration version 2023031700...skip
Found migration version 2024021900
Found migration version 2023030500...skip
Found migration version 2023111700...skip
Found migration version 2023071000...skip
Found migration version 2023020100...skip

Latest database version 2024040500

Forward to 2024021900
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'b5137eadbbb3a7d4b2ea1507517ca7d8' for key 'password' in /www/wwwroot/www.1.xyz/db/migrations/2024021900-add_missing_indexes.php:11
Stack trace:
#0 /www/wwwroot/www.1.xyz/db/migrations/2024021900-add_missing_indexes.php(11): PDO->exec()
#1 /www/wwwroot/www.1.xyz/src/Command/Migration.php(123): App\Interfaces\MigrationInterface@anonymous->up()
#2 /www/wwwroot/www.1.xyz/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /www/wwwroot/www.1.xyz/db/migrations/2024021900-add_missing_indexes.php on line 11

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'b5137eadbbb3a7d4b2ea1507517ca7d8' for key 'password' in /www/wwwroot/www.1.xyz/db/migrations/2024021900-add_missing_indexes.php:11
Stack trace:
#0 /www/wwwroot/www.1.xyz/db/migrations/2024021900-add_missing_indexes.php(11): PDO->exec()
#1 /www/wwwroot/www.1.xyz/src/Command/Migration.php(123): App\Interfaces\MigrationInterface@anonymous->up()
#2 /www/wwwroot/www.1.xyz/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /www/wwwroot/www.1.xyz/db/migrations/2024021900-add_missing_indexes.php on line 11

Describe the issue you run into. 请描述你遇到的问题。

**Comment by M1Screw** [comment]
Change your node password value to a non-duplicate one.
