### ISSUE TITLE
SSPanel-UIM 版本2024.1，数据库版本2024040500，Stripe无法支付

### ISSUE THREAD

**Issue by wans10** [Anankke/SSPanel-UIM#2421]
大佬，SSPanel更新到2024.1正式版以后Stripe无法跳转到支付页面，之前用的2024.1Dev可以正常支付，希望大佬帮忙看看，谢谢。
<img width="1103" alt="image" src="https://github.com/Anankke/SSPanel-UIM/assets/51012039/73ccb48c-8726-4913-84f3-e509826b863e">
<img width="1279" alt="image" src="https://github.com/Anankke/SSPanel-UIM/assets/51012039/3c12f822-b708-4db3-bcf1-b479e89056b2">
<img width="995" alt="image" src="https://github.com/Anankke/SSPanel-UIM/assets/51012039/7e8a4dc7-577b-4267-a40c-a1fe49a632f7">

**Comment by mmfdsfsd** [comment]
我也遇到了这个问题，请问你还有2024.1Dev这个版本的源代码么？

**Comment by Anankke** [comment]
Fixed in ad0b2ae3085dc95bc8a3fcaf04fc8d4346ad604a.
