### ISSUE TITLE
[BUG] .config.php的db_host配置为localhost时，db_port自定义配置似乎不生效

### ISSUE THREAD

**Issue by Applesoil** [Anankke/SSPanel-UIM#2473]
**Environment 环境**

OS:   Ubuntu 22.04.1 LTS
HTTPS enabled:   false
PHP version:   8.2.24 
DB version:  11.5.2

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。
.config.php的db_port自定义配置似乎不生效，系统总会使用默认的3306端口

**Comment by Anankke** [comment]
这显然是不太可能的，是不是有什么奇妙缓存？

**Comment by Applesoil** [comment]
> 这显然是不太可能的，是不是有什么奇妙缓存？

在本地拉了新的sspanel并配置了不存在的端口号，重启系统后仍能正常访问，但修改host，username，password中任一个都会立刻生效

**Comment by Applesoil** [comment]
> > 这显然是不太可能的，是不是有什么奇妙缓存？
> 
> 在本地拉了新的sspanel并配置了不存在的端口号，重启系统后仍能正常访问，但修改host，username，password中任一个都会立刻生效

![image](https://github.com/user-attachments/assets/3ce26189-e74b-49a5-bf35-f60ceb104921)
变量名是db_port，是不是名字有问题

**Comment by Applesoil** [comment]
> 这显然是不太可能的，是不是有什么奇妙缓存？

啊对不起，我把db_host从localhost改为127.0.0.1后，端口号配置生效

**Comment by Applesoil** [comment]
> 这显然是不太可能的，是不是有什么奇妙缓存？

啊对不起，好像是配localhost的问题，我把db_host从localhost改为127.0.0.1后，端口号配置生效，但我在远程新的Ubuntu服务器上也有这种情况

**Comment by Applesoil** [comment]
> 这显然是不太可能的，是不是有什么奇妙缓存？

啊对不起，好像是配localhost的问题，在把localhost改为127.0.0.1后，db_port配置生效，但在新的服务器上配了localhost也会有这样的问题

**Comment by Anankke** [comment]
我的建议是先用 127，指不定你这个 localhost 登录的是 unix socket

**Comment by Applesoil** [comment]
> 我的建议是先用 127，指不定你这个 localhost 登录的是 unix socket

非常感谢，应该是的，我宿主机安装了maraidb且起了docker跑另外版本数据库时出现了这个问题
