### ISSUE TITLE
尝试在demo站点切到dev，节点无法显示

### ISSUE THREAD

**Issue by ghost** [Anankke/SSPanel-UIM#383]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
commit 6f3e409a22448ec3bc5e7ddcfcd283482dfb4e9b
Author: laurier <14360417+laurieryayoi@users.noreply.github.com>
Date:   Sat Nov 17 00:07:35 2018 +0800

    修改clash链接&newpasswdreset

    fix nodeinfo
2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

从master 切到 dev后， 节点列表页面不显示节点，但切回master后显示正常。

**Comment by rico93** [comment]
谢谢，因为看到有clash的功能，想切过来看看，打扰。谢啦
