### ISSUE TITLE
关于在商店中添加群组的设想

### ISSUE THREAD

**Issue by Supersharks** [Anankke/SSPanel-UIM#393]
您好，在现有的版本中，管理面板中的用户管理、节点添加和添加商品中的 等级功能已实现功能的对接，是重要的规则。可否能在管理面板中的 商品添加 增加 群组 的功能？这样在区分商品时就会有群组和等级两个规则。如果这算定制功能，我愿有偿求助。再次感谢大神辛苦工作，如有可能，望回复。

**Comment by uubxs** [comment]
大佬辛苦了，不知还要多久呢？~

**Comment by NimaQu** [comment]
@uubxs

**Comment by SuicidalCat** [comment]
@uubxs 鈷咕菇沽
