### ISSUE TITLE
申请增加后台添加用户功能

### ISSUE THREAD

**Issue by lenovoy450** [Anankke/SSPanel-Uim#486]
**我正在申请**  (使用 "x" 选择)
- [ ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**
看到肥羊有管理员后台快速添加用户的功能, 感觉还不错。有没有大佬完善一下呢。永远喜欢Anankke.
https://github.com/mmmwhy/mod/commit/d6bb2ffcf05b133b8b1ddba2df0c355f9a5794c6
https://github.com/mmmwhy/mod/commit/8bff9529a582d865b11e3f0ff57075be0cfd3e15

**Comment by Anankke** [comment]
咕

**Comment by uubxs** [comment]
支持添加哈

**Comment by PengCaiPC** [comment]
啥时候落实啊

**Comment by Anankke** [comment]
等一个 pr

**Comment by akqzx** [comment]
后台数据库就可以操作啦

**Comment by zhenlinhgs** [comment]
⑴管理员后台快速创建用户的功能
⑵管理员后台快速添加用户套餐（快速续费功能）
最好2个都能一起加上去，这样就比肥羊的肥羊的自创建用户功能又升级了一步

**Comment by JusufUs** [comment]
> ⑴管理员后台快速创建用户的功能
> ⑵管理员后台快速添加用户套餐（快速续费功能）
> 最好2个都能一起加上去，这样就比肥羊的肥羊的自创建用户功能又升级了一步

这个想法不错，方便给想买又不想注册觉得麻烦的人快速弄好。

**Comment by regendsoh** [comment]
飘过 有点兴趣想玩
迟些试试看

**Comment by Anankke** [comment]
目前版本已经有了
