### ISSUE TITLE
关于新 Git Worflow 的讨论

### ISSUE THREAD

**Issue by SukkaW** [Anankke/SSPanel-Uim#540]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**申请添加新的特性或功能或者好的想法**

- `dev` 分支不再发布预构建版本。
- `dev` 分支的每一条 commit 由 Travis CI 进行构建，并将包含了预构建版本的 repo 推送到分支 `canary`
- 当一个阶段的开发完成以后，将包含了预构建的 `canary` 合并进 `master`；`dev` 不再合并进 `master`。

即

```
(git commit) => [branch: dev] (doesn't contains prebuilt verison of index. DO NOT USE DIRECTLY)
                      |
                 (Travis CI) => [branch: canary] (contains prebuilt verison of index, used for testing environment)
                                       |
                                    (merge)
                                       |
                                [branch: master] (contains stable verison of index, used for production environment)      
```

**Comment by SuicidalCat** [comment]
爲何要參照Chrome命名方式？我認爲直接使用beta或者β來表示開發測試分支是一個更好的選擇。

**Comment by SukkaW** [comment]
@SuicidalCat canary 是金丝雀的意思。在以前没有瓦斯监测器的年代，煤矿工人在下井以前会放入一只金丝雀，如果金丝雀活着说明井下瓦斯水平安全、如果金丝雀死了说明井下瓦斯水平存在危险。所以 canary 指代的是愿意亲身进行测试的体验者。

**Comment by SuicidalCat** [comment]
@SukkaW 我認爲不方便部分用戶理解就是不合適的

**Comment by CGDF-Github** [comment]
那prebuilt更契合。。。

> 爲何要參照Chrome命名方式？我認爲直接使用beta或者β來表示開發測試分支是一個更好的選擇。

**Comment by Colinwood11** [comment]
那么。。为什么不直接中文   叫   敢死队？

**Comment by Anankke** [comment]
我突然觉得苏卡卡说得对（

**Comment by SukkaW** [comment]
Change of the plan.

**Comment by AS137443** [comment]
@SukkaW 是可耐的苏卡卡，拖走了。

**Comment by Anankke** [comment]
@SukkaW 是可耐的苏卡卡，拖走了。

**Comment by SukkaW** [comment]
We should make `uim-index-dev` become a single alone repository (for instance `sspanel-uim/uim-index-dev`) that only contains the front-end related code. This repository should have at least two branches, `master` and `prebuilt` (@laurieryayoi can have his own `dev` branch if he likes).
The `master` branch only contains the `uim-index-dev` source code (tons of `.vue` files) and the `prebuilt` branch should only contains the contents of `dist` dir (`.html` and `.js` files).
The `prebuilt` branch should be locked and only access push from CI. The CI should be configured to built from every commit of `master` branch. `prebuilt` branch should use git tag (just publish a new github release that targets `prebuilt` branch) to mark version of the front-end.

**Comment by SukkaW** [comment]
```
[ New single repository : uim-index-dev ]

(git commit) => [branch: dev] (*only* contains .vue)
     |
(Travis CI) — build .html and .js from .vue => ./dist dir
                                                    |
                                            (CI : git push)
                                                    |
                         [branch: prebuilt] (*only* contains .html and .js)
                                                    ||
                                                    ||
                         (Publish a new GitHub release at prebuilt branch) => "airports" update front-end from specific git tag of prebuilt branch
```
