### ISSUE TITLE
普通节点和单端口节点同时存在时的节点订阅问题

### ISSUE THREAD

**Issue by mohlee** [Anankke/SSPanel-UIM#59]
当订阅地址是 {$baseUrl}/link/{$ssr_sub_token}?mu=1 时可获得单端口节点的更新，而当订阅地址是 {$baseUrl}/link/{$ssr_sub_token}?mu=0 时则获得普通节点的更新。
但如果站点同时存在两种类型的节点，并将这两个地址同时放入订阅列表并尝试更新时，其中后更新的就会冲掉先更新的。在 Windows、MacOS 和 Android 客户端均存在这个问题，而如果用 Shadowrocket 则不存在该问题，不同的订阅地址即使站点名字相同也会分别列出和分别更新。
有没有可能，做出一个单一的订阅地址可以同时更新两种不同类型的节点，或者即使用不同的订阅地址，但不会互相冲突？
感谢。

**Comment by NimaQu** [comment]
我记得不会冲掉啊，普通更新普通的，单端口更新单端口的

**Comment by mohlee** [comment]
大佬你好
感谢回复
我给你开个账号你帮我看下嘛~

**Comment by NimaQu** [comment]
可以，发我邮箱吧

**Comment by NimaQu** [comment]
您好，感谢反馈已经修复，请更新版本或者参照最新的 commit 记录进行修复

**Comment by mohlee** [comment]
您好
感谢关注并更新代码

我在自己的站点上更新了代码并清空了缓存后
在 Android 客户端和 Windows 客户端上进行了反复测试
现在情况是这样

安卓客户端上没有任何改变
Windows 客户端是这样
1. 清空所有节点和订阅地址后，重新添加两个地址，更新订阅后，可获得全部节点。
2. 在1的基础上再次更新订阅，则先更新的那部分节点会被冲掉。
3. 如果清空所有节点，但不清空订阅地址，此时更新订阅，先更新的那部分节点会被冲掉。

另
因本人对 php 实在不太了解，如果下面说错还望不要见笑。
从更新的代码看，意思是多加一个判断，如果mu不为0，则在"group"这个字段里加上单端口的字样。
但从运行的结果来看，即使在首次添加订阅地址并成功更新所有节点后，从客户端里看，单端口的节点中"Group"这个字段中也并没有预期中“单端口”的字样。
同时，在 Windows 客户端文件夹内的 gui-config.json 文件中
`		{
			"URL" : "https://www.test.site/link/abcd0123456789ef?mu=0",
			"Group" : "测试站点",
			"LastUpdateTime" : 1525382642
		},
		{
			"URL" : "https://test,site/link/abcd0123456789ef?mu=1",
			"Group" : "测试站点",
			"LastUpdateTime" : 1525382643
		}`
这个部分的"Group"之中也并没有“单端口”的字样。

测试账号没变，可随时复现上面所述的问题。
感谢

**Comment by mohlee** [comment]
再次更新后好像可以了。
感谢各位大佬。
