### ISSUE TITLE
V2节点等级分组问题

### ISSUE THREAD

**Issue by DreamChanSS** [Anankke/SSPanel-Uim#607]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [x ] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容
commit d3d84c1a00ea05d12149d14441f0d93e98cbce31
Author: Anankke <anankke@protonmail.com>
Date:   Thu Apr 4 00:39:55 2019 -0400

    <E6><B7><BB><E5><8A><A0><E5><8D><87><E7><BA><A7><E6><97><B6><E9><BB><98><E8>

diff --git a/app/Controllers/AuthController.php b/app/Controllers/AuthController.pindex a1469e0..52c9adb 100644
--- a/app/Controllers/AuthController.php
+++ b/app/Controllers/AuthController.php
@@ -31,14 +31,13 @@ class AuthController extends BaseController
     {
         $GtSdk = null;
         $recaptcha_sitekey = null;
-        if (Config::get('enable_login_captcha') == 'true'){
-            switch(Config::get('captcha_provider'))
-            {
+        if (Config::get('enable_login_captcha') == 'true') {
+            switch (Config::get('captcha_provider')) {
                 case 'recaptcha':
                     $recaptcha_sitekey = Config::get('recaptcha_sitekey');
                     break;
                 case 'geetest':
-                    $uid = time().rand(1, 10000) ;
+                    $uid = time() . rand(1, 10000);
                     $GtSdk = Geetest::get($uid);
                     break;
             }
@@ -64,18 +63,18 @@ class AuthController extends BaseController
             ->display('auth/login.tpl');
     }
 
-    public function getCaptcha($request, $response, $args) {
+    public function getCaptcha($request, $response, $args)
+    {
         $GtSdk = null;
         $recaptcha_sitekey = null;
-        if (Config::get('captcha_provider') != ''){
-            switch(Config::get('captcha_provider'))
-            {

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

添加等级为3，分组为2的v2节点后，等级2分组1的用户在节点列表无法查看节点信息（到这里是正常的）。但用客户端可以正常订阅更新到该节点，且可以正常连接。

**申请添加新的特性或功能或者好的想法**

**Comment by DreamChanSS** [comment]
添加等级为3，分组为2的v2节点后，等级2分组1的用户在节点列表无法查看节点信息（到这里是正常的）。但用客户端可以正常订阅更新到该节点，且可以正常连接。

**Comment by Anankke** [comment]
V2 部分是谁写的来着

**Comment by wewall** [comment]
> 用客户端可以正常订阅更新到该节点，且可以正常

https://github.com/Anankke/SSPanel-Uim/blob/dev/app/Utils/URL.php#L306
https://github.com/Anankke/SSPanel-Uim/blob/dev/app/Controllers/Mod_Mu/UserController.php#L17

**Comment by SakuraSa233** [comment]
Closed for inactivity.
