### ISSUE TITLE
能否增加自定义服务器功能?

### ISSUE THREAD

**Issue by KleinerSource** [Anankke/SSPanel-Uim#615]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki)
- [ x] [项目其他 issue](https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/NimaQu/ss-panel-v3-mod_Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

1.请在面板路径下运行`git show HEAD`，然后贴出输出内容

2.如果是页面问题（500 或 Slim Application Error )，请在 config 开启 debug 模式后截图或贴出输出内容，如果是某个按钮点击没反应，请打开浏览器开发者控制台（通常为 F12 ) ，贴出 console 输出内容

**申请添加新的特性或功能或者好的想法**
希望能添加那些 固定端口 协议 密码的设置.
有些服务器装的标准端(非多用户) 拥有固定端口协议密码的. 不受后台管理的后端

**Comment by SukkaW** [comment]
已经在 Todo 上了，但是咕了

**Comment by Anankke** [comment]
在咕了.gugu

**Comment by wewall** [comment]
这个需求需要改面板还不够 部署节点的后端也要改呀，

**Comment by chauyuen** [comment]
> 这个需求需要改面板还不够 部署节点的后端也要改呀，

不需要，其实他的需求是添加一个普通单用户节点（e.x.SSR，非SSRMU）。节点信息不随登录用户改变，节点也不反馈任何信息给到面版。

**Comment by SakuraSa233** [comment]
Close for inactive.
