### ISSUE TITLE
新的提交请使用 PSR-12 格式

### ISSUE THREAD

**Issue by Anankke** [Anankke/SSPanel-Uim#664]
新的 Commit、Pull request 请使用 PSR-12
保护头发从代码格式做起
 爱您

**Comment by NimaQu** [comment]
@Anankke 保护 Anankke 从代码格式做起

**Comment by SukkaW** [comment]
Pin Issue，请

**Comment by safepayment** [comment]
👍 我提交了SSP史上最后一个不符合规范的PR。

**Comment by GeekQu** [comment]
看来我应该先看 issue

**Comment by Colinwood11** [comment]
得去学习一下PSR - 12是什么才能PR了  嘤嘤嘤

**Comment by safepayment** [comment]
PSR-12格式 可以参考下面的工具

1) easyCodingStandard
https://github.com/symplify/easyCodingStandard/

2) PHP-CS-Fixer
https://github.com/friendsofphp/php-cs-fixer

**Comment by hatwis** [comment]
20190709 新版本中修改的edit.tpl 导致版面混淆协议无法修改

**Comment by Anankke** [comment]
> 20190709 新版本中修改的edit.tpl 导致版面混淆协议无法修改

这里不是开 issue 的地方
