### ISSUE TITLE
普通用户节点bug

### ISSUE THREAD

**Issue by heitu001** [Anankke/SSPanel-Uim#670]
节点权限为0的时候最近出现，节点服务器cpu异常爆满，脚本文件占用100%，导致节点无法使用，一直上线下线！切换成v1后正常！

**Comment by heitu001** [comment]
![1](https://user-images.githubusercontent.com/50029572/58753093-b37d6a80-84ec-11e9-8075-6a4409bfb479.JPG)

**Comment by Anankke** [comment]
机器太差，加钱，请

**Comment by Anankke** [comment]
而且 log 都没有也敢来开 issue？
