### ISSUE TITLE
报告问题

### ISSUE THREAD

**Issue by JusufUs** [Anankke/SSPanel-Uim#673]
resources/views/material/user/header_info.tpl
中
<link href="https://fonts.loli.net/css?family=Roboto:300,300italic,400,400italic,500,500italic|Material+Icons" rel="stylesheet">

本行失效，好像是fonts.loli.net被墙

**Comment by SukkaW** [comment]
@JusufUs 请检查你自己所在的网络环境。据我所知， fonts.loli.net 并没有被墙。

**Comment by ranwen** [comment]
@SukkaW https://t.me/sbfans/235021

**Comment by JusufUs** [comment]
我已经在国内的其他好几个服务器直接访问该地址，都是网页无法显示，才来报告的。

**Comment by AS137443** [comment]
@JusufUs 确实挂了  谢谢告知

**Comment by Anankke** [comment]
实测已经恢复

**Comment by SukkaW** [comment]
@Anankke 我们可以考虑剥离 Google Fonts，将 Material Design Icons 交给 jsDelivr，并且去掉 Roboto 字体。

**Comment by Anankke** [comment]
支持，请立即这么做
