### ISSUE TITLE
path_search not working

### ISSUE THREAD

**Issue by Anankke** [Anankke/SSPanel-Uim#674]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

https://github.com/Anankke/SSPanel-Uim/blob/05224fc1ad3c79b37d478a5a8446a6f865822efc/app/Controllers/Admin/RelayController.php#L263

path_search returns nothing and not working

是个上古问题

我好忙啊来个人修一修

**Comment by pang-w** [comment]
不懂里面的业务逻辑，不然顺手改了  :(
