### ISSUE TITLE
节点流量上限重置日无效

### ISSUE THREAD

**Issue by zs910208565** [Anankke/SSPanel-Uim#676]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug

<!-- 

**反馈BUG**

大佬们好，已经设置流量上限清空日，还是不起作用。到期不重置。
请问改怎么修改，纯小白问题勿介意！

**Comment by zs910208565** [comment]
已设置节点流量重置日，但是没有效果！ 最新版本

**Comment by regendsoh** [comment]
@zs910208565 php /路径/xcat dailyjob
