### ISSUE TITLE
单端口节点等级BUG

### ISSUE THREAD

**Issue by 643822883** [Anankke/SSPanel-Uim#682]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

当用户等级大于某单端口节点等级时，该单端口节点在小于或等于用户等级的节点都会显示

**Comment by Anankke** [comment]
没听懂
单端口就应该是这样的啊

**Comment by 643822883** [comment]
等级1的单端口节点同时在等级2的节点上生效

**Comment by 643822883** [comment]
比如美国节点等级为1，80单端口节点等级为1，但是我香港节点为2，也有80单端口
