### ISSUE TITLE
f2f支付回调BUG

### ISSUE THREAD

**Issue by wzw1997007** [Anankke/SSPanel-Uim#683]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

dev分支最新版本，在`.config.php`中`f2fNotifyUrl`此项留空后会出现充值不到账的现象，但是此项填入`https://站点域名/payment/notify`后却可以正常到账，于是本人猜想是此项为空时没有正确获取回调链接，但是经查`/app/Services/Gateway/AopF2F.php`这个文件中有` $notifyUrl = Config::get('f2fNotifyUrl') ?? (Config::get('baseUrl') . '/payment/notify');`这句代码，不知出于什么原因导致此项为空时无法获取正确的回调链接。
站点域名确定没有被墙

**Comment by Anankke** [comment]
PHP Version?

**Comment by wzw1997007** [comment]
PHP版本为7.2.6

**Comment by wzw1997007** [comment]
经测试将
`$notifyUrl = Config::get('f2fNotifyUrl') ?? (Config::get('baseUrl') . '/payment/notify');`
替换为
`if (Config::get('f2fNotifyUrl') == '') {`
`$notifyUrl = Config::get('baseUrl') . '/payment/notify';`
`} else {`
`$notifyUrl = Config::get('f2fNotifyUrl');`
`}`
后即可解决问题

**Comment by qmqroot** [comment]
> 经测试将 替换
> `$notifyUrl = Config::get('f2fNotifyUrl') ?? (Config::get('baseUrl') . '/payment/notify');`
> 为
> `if (Config::get('f2fNotifyUrl') == '') {`
> `$notifyUrl = Config::get('baseUrl') . '/payment/notify';`
> `} else {`
> `$notifyUrl = Config::get('f2fNotifyUrl');`
> `}`
> 后即可解决问题

为什么我这样改完付款显示失败

**Comment by Anankke** [comment]
早就已经修复的 bug，不需要更改。

**Comment by du5** [comment]
> 经测试将
> `$notifyUrl = Config::get('f2fNotifyUrl') ?? (Config::get('baseUrl') . '/payment/notify');`
> 替换为
> `if (Config::get('f2fNotifyUrl') == '') {`
> `$notifyUrl = Config::get('baseUrl') . '/payment/notify';`
> `} else {`
> `$notifyUrl = Config::get('f2fNotifyUrl');`
> `}`
> 后即可解决问题

你硬是把一行的三元写成了五行！！！！

**Comment by qmqroot** [comment]
> 早就已经修复的bug，不需要更改。

为什么我没改也是不回调，付完网页还是二维码界面，刷新余额也没变，但是支付宝能到账
