### ISSUE TITLE
搭建 v2ray 做后端的问题

### ISSUE THREAD

**Issue by m01i0ng** [Anankke/SSPanel-Uim#685]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

用Rico 版的后端、看了 wiki 里的每个字、但还是运行不成功、报错：

```
[Error] SSPanelPlugin: SSPanelPlugin: Can't get data from server or the  data is not as expected current url ... current md5 528b92eff5f2468fea7670bde23c62ed
```

使用 docker-compose 方式，WS+TLS Caddy

**Comment by Anankke** [comment]
@ricobb

**Comment by rico93** [comment]
因为收费版本，请付费

**Comment by m01i0ng** [comment]
=。=了解了、thx
