### ISSUE TITLE
使用第三方支付系统时邀请返利系统收不到返利。。

### ISSUE THREAD

**Issue by chuwu-hu** [Anankke/SSPanel-Uim#689]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

如题，项目演示站无法打开所以就没法复现问题了。
邀请人等级>0，而邀请机会>0，支付系统f2f支付宝当面付、码支付、trimepay、番茄云支付都一样。
另外要提的是，使用这些支付系统支付时，管理后台支付记录也没有记录订单，当使用充值码充值时就没有这些问题。

**Comment by Anankke** [comment]
@chuwu-hu 在？看看回调？

**Comment by chuwu-hu** [comment]
回调？回调应该没问题，因为用户的余额增加了

**Comment by Anankke** [comment]
@chuwu-hu 无法复现
