### ISSUE TITLE
节点开启单端口多用户后，前端节点不显示节点

### ISSUE THREAD

**Issue by Gejiafeng** [Anankke/SSPanel-Uim#691]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**Comment by lostinfever** [comment]
我也遇到这个问题，都是按照教程配置的，但是前端确实没有显示

**Comment by jm0477** [comment]
我这边也复现这个问题，而且单端口订阅没有单端口节点出现。

**Comment by aiastia** [comment]
@jm0477

**Comment by aipeach** [comment]
@jm0477 注意承载节点承载用户的等级，问题应该是在这(确信)

**Comment by jm0477** [comment]
@aipeach  感谢！ 的确是这样。 
调整承载用户等级大于所有用户等级，承载节点等级改为0
前端可以正常显示节点细节，单端口订阅正常。感谢！
