### ISSUE TITLE
[Feature Request] Add link to www.ipip.net at admin area

### ISSUE THREAD

**Issue by SukkaW** [Anankke/SSPanel-Uim#693]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

Add links to `www.ipip.net` for IP address shown at admin area.

The url format `https://www.ipip.net/ip/${ip}.html`

**Comment by Anankke** [comment]
构想：做成按钮，点击查询 ipip api 然后返回内容替代显示
ipip 的免费 api 是有 rate limit 所以不能完全代替本地库

**Comment by SukkaW** [comment]
@Anankke IPIP 的免费 API 是一个 IP 每天 1000 次，但是没法跨域。
纯真 IP 库基本够用，只有部分 IP 需要前往 IPIP 查询。

**Comment by Anankke** [comment]
这个我觉得
应该做一个什么别的按钮点一下 xhr 请求然后显示

**Comment by SukkaW** [comment]
@Anankke 做个按钮直接新标签页访问 IPIP 就好了。。一般情况下面板显示的纯真 IP 库够用了。

**Comment by Anankke** [comment]
那就把显示的那个地方 herf 到 ipip

**Comment by Anankke** [comment]
算了算了你康康现在这个情况

**Comment by Colinwood11** [comment]
Polaris去哪了233333
