### ISSUE TITLE
管理员无法在用户中心 node 页面看到所有分组节点

### ISSUE THREAD

**Issue by jmireles7** [Anankke/SSPanel-Uim#694]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题 
      注.  演示站打不开了

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [  ] 申请添加新的特性或功能或者好的想法

**反馈BUG**

管理员无法在用户中心 node 页面看到所有分组节点，已经升级最新dev分支，
只能把管理员换到相应分组才能看到节点，
另外建议分组的节点另外分组显示（例如Vip1 Vip2 那样）

**Comment by Anankke** [comment]
我记得是可以的但是我也不确定（
这个部分没动过
需要更多报告

**Comment by jmireles7** [comment]
> 我记得是可以的但是我也不确定（
> 这个部分没动过
> 需要更多报告

git reset --hard
HEAD is now at b5429b5d fix: lost functions

问题依旧存在

**Comment by adawdawdawdfsef** [comment]
https://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/loginhttps://www.pornhub.com/login

**Comment by wewall** [comment]
分组！！！超级机场

**Comment by Anankke** [comment]
已确认，会修复

**Comment by yangyzp** [comment]
我怎么记得以前可以看到不同组的节点呀，现在版本看不到了吗？   
改出bug了？

**Comment by wikicc** [comment]
刚试了下，真有这个bug。。。

**Comment by JohnFreeman9** [comment]
#762 已在此处解决
