### ISSUE TITLE
执行php xcat dailyjob   重置流量报错

### ISSUE THREAD

**Issue by zs910208565** [Anankke/SSPanel-Uim#698]
-->

**我确认我已经阅读了** (使用 "x" 选择)

- [ X] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ X] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ X] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

rm: cannot remove ‘/www/wwwroot/xxx.xx/storage/*.png’: No such file or directory
PHP Warning:  file_get_contents(http://update.cz88.net/ip/copywrite.rar): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway
 in /www/wwwroot/xxx.xx/app/Command/Job.php on line 232

Warning: file_get_contents(http://update.cz88.net/ip/copywrite.rar): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway
 in /www/wwwroot/xxx.xx/app/Command/Job.php on line 232
PHP Warning:  file_get_contents(/www/wwwroot/xxx.xx/storage/qqwry.md5): failed to open stream: No such file or directory in /www/wwwroot/xxx.xx/app/Command/Job.php on line 237

Warning: file_get_contents(/www/wwwroot/xxx.xx/storage/qqwry.md5): failed to open stream: No such file or directory in /www/wwwroot/xxx.xx/app/Command/Job.php on line 237
PHP Warning:  file_get_contents(http://update.cz88.net/ip/qqwry.rar): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway
 in /www/wwwroot/xxx.xx/app/Command/Job.php on line 241

Warning: file_get_contents(http://update.cz88.net/ip/qqwry.rar): failed to open stream: HTTP request failed! HTTP/1.1 502 Bad Gateway
 in /www/wwwroot/xxx.xx/app/Command/Job.php on line 241
From https://github.com/xcxnig/ssr-download
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.

**Comment by Anankke** [comment]
@zs910208565 纯真数据库因为蓝视云申必操作不可用力

**Comment by zs910208565** [comment]
每个字都认识，合一起不认识了-。-

**Comment by Anankke** [comment]
按说是不影响重置的，这个到时候会处理一下

**Comment by zs910208565** [comment]
设置的节点每月1日清空流量上限，今天看了下没清空。来反馈下。
感谢大佬维护这么好的项目~~

**Comment by SukkaW** [comment]
> @zs910208565 纯真数据库因为蓝视云申必操作不可用力

讲道理 114514 年之前我就把 SSPanel 的纯真 IP 库搞成从我的 SLA 三个 9 的 https://qqwry.mirror.noc.one 了。
