### ISSUE TITLE
语法错误 auth/login.tpl line.171双逗号

### ISSUE THREAD

**Issue by topjohncian** [Anankke/SSPanel-Uim#701]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

语法错误 auth/login.tpl line171 js  双逗号 请大佬们提个pr

**Comment by SukkaW** [comment]
@topjohncian PR welcome

**Comment by topjohncian** [comment]
@SukkaW I'm using phone. Goodbye
