### ISSUE TITLE
更新最新版dev分支，有用户反映用原来的账号密码，提示密码错误。

### ISSUE THREAD

**Issue by sanboukarasu** [Anankke/SSPanel-Uim#703]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

https://github.com/Anankke/SSPanel-Uim/commit/aa7f93e02bba808cbfb3d75a6947a6c2dc67afd9
已更新最新版dev分支，有用户反映用原来的账号密码登录，提示密码错误。
是否和此项改动有关？

**Comment by Anankke** [comment]
重新复制粘贴 config example 重新按照旧的填写

**Comment by wewall** [comment]
注意加盐

**Comment by Anankke** [comment]
草，是围墙

**Comment by Hitiko** [comment]
@Anankke 草

**Comment by AS137443** [comment]
@Anankke 注意salt以及是md5还是sha1

**Comment by wewall** [comment]
草

**Comment by Hitiko** [comment]
@wewall 草

**Comment by Anankke** [comment]
@Hitiko 草

**Comment by wewall** [comment]
@Hitiko 草

**Comment by Hitiko** [comment]
@wewall 草

**Comment by wewall** [comment]
@Hitiko 草
