### ISSUE TITLE
购买shop列表中商品无法按照商品id序号顺序显示? 

### ISSUE THREAD

**Issue by samac08** [Anankke/SSPanel-Uim#705]
如题 发现都是按照名称上升排序显示, 感觉显示好乱不统一  ,如何改为按照id序号显示商品?

**Comment by Anankke** [comment]
https://github.com/Anankke/SSPanel-Uim/blob/dev/app/Controllers/UserController.php#L962 ，请

**Comment by Anankke** [comment]
@samac08 这个问题值 50

**Comment by samac08** [comment]
@Anankke  搞定 感谢大佬 !

**Comment by siemenstutorials** [comment]
请问如何搞定的？
