### ISSUE TITLE
dev分支chenpay报错无法打开充值页面

### ISSUE THREAD

**Issue by liwenjie119** [Anankke/SSPanel-Uim#707]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

![批注 2019-07-07 152002_LI](https://user-images.githubusercontent.com/25956275/60765316-549ea880-a0cb-11e9-9265-5980cffab95a.jpg)

**Comment by liwenjie119** [comment]
演示站无法打开，没有复现

**Comment by Anankke** [comment]
@liwenjie119 检查下是否修复

**Comment by liwenjie119** [comment]
@Anankke 大佬，今天试了试有新的报错
![批注 2019-07-09 192104](https://user-images.githubusercontent.com/25956275/60884380-4beed380-a27f-11e9-89ae-26aeea35098e.jpg)

**Comment by lKingl** [comment]
@liwenjie119 220行后面更换为"<span>" + (m >= 10 ? m : '0' + m) + "</span>:<span>" + (s >= 10 ? s : '0' + s) + "</span>"

**Comment by lKingl** [comment]
span被markdown安排了。。`"<span>" + (m >= 10 ? m : '0' + m) + "</span>:<span>" + (s >= 10 ? s : '0' + s) + "</span>"`
