### ISSUE TITLE
申请添加：重置订阅地址、邀请链接、端口和设置两步验证时弹窗提醒

### ISSUE THREAD

**Issue by AldrinBrown** [Anankke/SSPanel-Uim#710]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

申请添加新的特性或功能或者好的想法
希望能添加：重置订阅地址、邀请链接、端口和设置两步验证时弹窗提醒
希望大佬能添加弹窗提醒功能，以避免新手和移动端用户会手滑无意间点到

**Comment by Toxic-Cat** [comment]
@AldrinBrown pr welcome

**Comment by ccwy** [comment]
<div aria-hidden="true" class="modal modal-va-middle fade" id="invite_reset_modal" role="dialog" tabindex="-1">
					<div class="modal-dialog modal-xs">
						<div class="modal-content">
							<div class="modal-heading">
								<a class="modal-close" data-dismiss="modal">×</a>
								<h2 class="modal-title">确认要重置邀请链接？</h2>
							</div>
							<div class="modal-inner">
								<p>请您确认。</p>
							</div>
							<div class="modal-footer">
								<p class="text-right"><button class="btn btn-flat btn-brand-accent waves-attach waves-effect" data-dismiss="modal" type="button">取消</button><button class="btn btn-flat btn-brand-accent" data-dismiss="modal" id="invite_reset_link" type="button">确定</button></p>
							</div>
						</div>
					</div>
				</div>


<script>
$(".reset-link").click(function () {
 $("#invite_reset_modal").modal();
});
	
$("#invite_reset_link").click(function () {
	$("#result").modal();
	$("#msg").html("已重置您的邀请链接，复制您的邀请链接发送给其他人！");
	window.setTimeout("location.href='/user/inviteurl_reset'", {$config['jump_delay']});
});
</script>
