### ISSUE TITLE
在线IP 报DataTables warning: table id=table_1 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

### ISSUE THREAD

**Issue by lj407269507** [Anankke/SSPanel-Uim#716]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

在线IP会报错DataTables warning: table id=table_1 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by wewall** [comment]
已复现
```DataTables warning: table id=table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7```
![微信截图_20190712012003.png](https://i.loli.net/2019/07/12/5d2770012233274607.png)

**Comment by Anankke** [comment]
@wewall 那就康康 f12 啊！

**Comment by Anankke** [comment]
@wewall commit log 规范化，请

**Comment by wewall** [comment]
@Anankke 
```cf-railgun: direct (waiting for pending WAN connection)
cf-ray: 4f4c76951edc2e25-NRT
content-length: 237
content-type: application/json
date: Thu, 11 Jul 2019 17:23:05 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
status: 500```

**Comment by Anankke** [comment]
@wewall 在？自己 500 为什么不开 debug 看返回？

**Comment by wewall** [comment]
@Anankke 在的呢, 开 debug return 200, 还是提示 `DataTables warning: table id=table_1 - Ajax error. For more information about this error, please see http://datatables.net/tn/7
` 呢

**Comment by lj407269507** [comment]
![QQ截图20190712012331](https://user-images.githubusercontent.com/43335960/61071587-0fb8a000-a444-11e9-8ff8-7b343b1ed073.png)
我是这样，和你的不一样

**Comment by Anankke** [comment]
只看返回头不看内容？

**Comment by aiastia** [comment]
```
1.点击PHP设置，将PHP运行模式改成静态
2.接着点击配置修改栏目，找到display_errors，将On改成Off
```

**Comment by lj407269507** [comment]
@aiastia  还是报这个DataTables warning: table id=table_1 - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1   而且封禁IP和已封禁IP也开始报了！

**Comment by Anankke** [comment]
我寻思等了一天了也没人贴返回内容
那就不管了罢

**Comment by wewall** [comment]
这个开debug 返回 200 除了提示窗没有输出的 不开 debug 返回 500 无输出

**Comment by Anankke** [comment]
@wewall 必不可能

**Comment by wewall** [comment]
这是真的呀,  不过不是代码的问题

**Comment by lj407269507** [comment]
content.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ content.js:1
n @ content.js:1
(anonymous) @ content.js:1
n @ content.js:1
(anonymous) @ content.js:1
(anonymous) @ content.js:1
jquery@3.2.1:4 [Violation] 'load' handler took 17161ms

**Comment by SukkaW** [comment]
@lj407269507 怎么尽回复些没用的 WARNING 信息

**Comment by xcxnig** [comment]
@SukkaW 宝塔 装的 mysql 8.0 ?

**Comment by wewall** [comment]
@lj407269507  测试了下demo, 有两个解决方案
> 1. `php /htmlhome/xcat initQQWry`
> 2. display_errors，将 On 改成 Off

**Comment by lj407269507** [comment]
= 3=~~第二个可以解决了，谢谢 @wewall

**Comment by imjonat** [comment]
完了。。我的也开始报了 而且是商品界面。之前遇到过 用lnmp装就ok，现在merge了master 商品报错 还不显示 尴尬了

**Comment by TBQin** [comment]
我的好像是用户列表 搜搜打中文就会报这个错误

**Comment by KagamigawaMeguri** [comment]
> 我的好像是用户列表 搜搜打中文就会报这个错误

+1

**Comment by DrawLi** [comment]
> 我的好像是用户列表 搜搜打中文就会报这个错误

+1

**Comment by dongfangmu** [comment]
按照楼上那个改静态跟off保存等一会儿就可以了，我的好了

**Comment by yuiviber** [comment]
研究了好久了还是没解决（以下两个方法都用了）
1.点击PHP设置，将PHP运行模式改成静态
2.接着点击配置修改栏目，找到display_errors，将On改成Off

**Comment by maker2002** [comment]
> 研究了好久了还是没解决（以下两个方法都用了）
> 1.点击PHP设置，将PHP运行模式改成静态
> 2.接着点击配置修改栏目，找到display_errors，将On改成Off

你们是不是都套了cloudflare？我的也报这个错误，但不是每次都报。

**Comment by tanpengsccd** [comment]
> 完了。。我的也开始报了 而且是商品界面。之前遇到过 用lnmp装就ok，现在merge了master 商品报错 还不显示 尴尬了

这个我发现是  只要数据shop表的字段content 中 含有 "reset":"30" 就会出错,去表里把字段删除就正常.

**Comment by tanpengsccd** [comment]
还有class 也是.
