### ISSUE TITLE
演示站sspanel.host无法访问?

### ISSUE THREAD

**Issue by Excalibur-osu** [Anankke/SSPanel-Uim#719]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

访问跳转到阿里云的备案提醒页面 无法正常访问
是我的姿势不对? 请指教!

**Comment by topjohncian** [comment]
我们是sspanel.host哦

**Comment by wewall** [comment]
> 访问跳转到阿里云的备案提醒页面 无法正常访问
> 是我的姿势不对? 请指教!

是你电脑没申请翻墙网络备案, 所以无法访问哦, 去工信局备案就行啦

**Comment by topjohncian** [comment]
@wewall dns污染管我们什么事 请自行番强访问

**Comment by Passipur** [comment]
@wewall 需要申请备案的 建议您现在去补一个备案 不然被查到访问日志就麻烦了（（（

**Comment by wewall** [comment]
@Excalibur-osu 需要申请备案的 建议您现在去补一个备案 不然被查到访问日志就麻烦啦（（（

**Comment by Excalibur-osu** [comment]
标题输错了 是sspanel.host 你们都正常是吧?
那可能是DNS问题吧 我再试试
