### ISSUE TITLE
关于商品重置流量逻辑问题

### ISSUE THREAD

**Issue by cjiasu** [Anankke/SSPanel-Uim#721]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

目前版本:
$System_Config['enable_bought_reset']='false'; 设置关闭续费时重置流量
商品设置不管设置 续费时重置流量 或者不重置流量 都无法重置流量

$System_Config['enable_bought_reset']='true'; 设置开启续费时重置流量
商品设置不管设置 续费时重置流量 或者不重置流量 都重置流量

好像商品设置那个开关成了摆设？

这个是不是有点不合理?我记得去年版本是：
$System_Config['enable_bought_reset']='false'; 设置关闭续费时重置流量
商品设置续费时重置流量  用户购买时商品重置流量  
商品设置续费时不重置流量  用户购买时商品不重置流量  
$System_Config['enable_bought_reset']='true'; 设置开启续费时重置流量
商品设置续费时重置流量  用户购买时商品重置流量  
商品设置续费时不重置流量  用户购买时商品不重置流量

**Comment by KagamigawaMeguri** [comment]
重置流量不重置流量到底重不重置流量，我懵了
对逻辑问题不满意可以自行去Shop.php修改←我是直接无视config的这个设定自己改的

**Comment by lw960105** [comment]
> 重置流量不重置流量到底重不重置流量，懵我了
> 对逻辑问题不满意可以自行去Shop.php修改←我是直接无视配置的这个设定自己改的

大佬能贴下代码吗

**Comment by wewall** [comment]
> 重置流量不重置流量到底重不重置流量，我懵了
> 对逻辑问题不满意可以自行去Shop.php修改←我是直接无视config的这个设定自己改的

大佬能贴下代码吗

**Comment by wewall** [comment]
Show me the code

**Comment by KagamigawaMeguri** [comment]
我寻思着还是自己写吧，想要的逻辑自己最清楚，照猫画虎又不难。

**Comment by JohnnyRandy** [comment]
这个问题看得我怀疑人生

**Comment by wewall** [comment]
> 这个问题看得我怀疑人生

一共八种情况，只列举了四种就怀疑人生了， 这可咋整啊

**Comment by Anankke** [comment]
@wewall 那咋办嘛

**Comment by NimaQu** [comment]
@Anankke 那咋办嘛

**Comment by WooMai** [comment]
@NimaQu 那咋办嘛

**Comment by Passipur** [comment]
@WooMai 那咋办嘛

**Comment by wewall** [comment]
@Passipur 那咋办嘛

**Comment by dendinuo** [comment]
大佬们有遇到过，等级过期后，vip等级不重置 的情况吗

**Comment by KagamigawaMeguri** [comment]
> 大佬们有遇到过，等级过期后，vip等级不重置 的情况吗

泥嚎
有的

**Comment by dendinuo** [comment]
> > 大佬们有遇到过，等级过期后，vip等级不重置 的情况吗
> 
> 泥嚎
> 有的

你解决了吗，我准备重装，，好麻烦

**Comment by wewall** [comment]
> 你解决了吗，我准备重装，，好麻烦

手动同步用户数据看看报错吗? 
```bash 
*/1 * * * * php /网站目录/xcat checkjob
```

**Comment by dendinuo** [comment]
> > 你解决了吗，我准备重装，，好麻烦
> 
> 手动同步用户数据看看报错吗?
> 
> ```shell
> php /网站目录/xcat checkjob
> ```
报错了。。。咋办。
PHP Parse error:  syntax error, unexpected '?' in /www/wwwroot/sspanel.cn/app/Command/Job.php on line 288

Parse error: syntax error, unexpected '?' in /www/wwwroot/sspanel.cn/app/Command/Job.php on line 288

vi  /www/wwwroot/sspanel.cn/app/Command/Job.php on line 288--->
 foreach ($users as $user) {
            $alive_ips = ($alive_ipset[$user->id] ?? new ArrayObject());
            $ips = array();

            $disconnected_ips = explode(',', $user->disconnect_ip);

            foreach ($alive_ips as $alive_ip) {
                if (!isset($ips[$alive_ip->ip]) && !in_array($alive_ip->ip, $disconnected_ips)) {
                    $ips[$alive_ip->ip] = 1;
                    if ($user->node_connector < count($ips)) {
                       
                        $isDisconnect = Disconnect::where('id', '=', $alive_ip->ip)->where('userid', '=', $user->id)->first();

**Comment by dendinuo** [comment]
> > 你解决了吗，我准备重装，，好麻烦
> 
> 手动同步用户数据看看报错吗?
> 
> ```shell
> php /网站目录/xcat checkjob
> ```

谢谢你的指点，我解决了 是php环境问题。。

**Comment by wewall** [comment]
> 谢谢你的指点，我解决了 是php环境问题。。

没事,

**Comment by Anankke** [comment]
这是个永久性的难题，解决要等重写 shop 了
