### ISSUE TITLE
关于 单端口限速 问题咨询

### ISSUE THREAD

**Issue by KagamigawaMeguri** [Anankke/SSPanel-Uim#722]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

情况：【节点限速】<【套餐限速】
翻issus 看到 后端限速node_speedlimit 是取最小值
在下照着这个修改，解决了不知道什么时候出现的节点限速失效问题，但仅限【普通端口】
https://github.com/Anankke/shadowsocks-mod/pull/1/files
将节点切换成【单端口多用户】，限速失效

询问了几个dalao都说限速没问题。

很疑惑，后端限速应该是针对端口，不知道单端口+没修改过后端 的情况下，其他人是如何正常限速
求解，感谢。

-------------更新1----------------------
经测试最新master单端口限速失效
-------------更新2----------------------
付费求解决

**Comment by wewall** [comment]
速度超过限制就 ban 号, 人工限速

**Comment by KagamigawaMeguri** [comment]
> 速度超过限制就 ban 号, 人工限速

谢谢，但这个办法未免太麻烦了……
