### ISSUE TITLE
申请增加支付接口聚合

### ISSUE THREAD

**Issue by nishuo** [Anankke/SSPanel-Uim#724]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

> 由于多种需要,不仅要使用到信用卡支付,当面付以及码支付的监控接口,导致只能选择一个接口使用
> 
> 能否支持多种支付接口同时使用选择呢？例如whmcs这样的

**Comment by rico93** [comment]
@nishuo 可以看看

**Comment by nishuo** [comment]
> @nishuo 可以看看

看啥看

**Comment by rico93** [comment]
@nishuo 看着 增加这个功能，o(╥﹏╥)o

**Comment by Anankke** [comment]
@nishuo 在重构计划中
