### ISSUE TITLE
Xcat定时任务出错！

### ISSUE THREAD

**Issue by ZeusGamingPlay** [Anankke/SSPanel-Uim#735]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

checkJob Crond命令报错如下：
PHP Parse error:  syntax error, unexpected ',', expecting ']' in /data/mystack/sites/[site_url]/www/app/Command/XCat.php on line 196

**Comment by wewall** [comment]
Please upgrade to php 7.1 and later

**Comment by wewall** [comment]
本来想瞄一眼贵站 PHP 版本, headers 里面居然取消暴露 PHP 版本

**Comment by ZeusGamingPlay** [comment]
> Please upgrade to php 7.1 and later

已经是部署在 PHP 7.2.8 环境下的站点了，另外测试了从PHP7.0-7.2.8几个主流版本都有这样的报错呢？

**Comment by ZeusGamingPlay** [comment]
问题已解决，测试过后没有问题的话稍后提交PR。

**Comment by wewall** [comment]
> 已经是部署在 PHP 7.2.8 环境下的站点了，另外测试了从PHP7.0-7.2.8几个主流版本都有这样的报错呢？

https://cn.piliapp.com/php-syntax-check/ 

测试语法的话 7.1 以下都会有报错, 理论上 7.1 以后都正常
