### ISSUE TITLE
码支付用不了，问码支付说是对接了老网关，请问在哪里可以更改网关？

### ISSUE THREAD

**Issue by qsyssr** [Anankke/SSPanel-Uim#742]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

如题！这个在那里更改？？？好几天都不能用了！

**Comment by wingsrabbit** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/9890f25623c1d956c15f8fe8f8e19b97a975d1c0

**Comment by Anankke** [comment]
@wingsrabbit 你们谁去提交个更新修修

**Comment by SukkaW** [comment]
@Anankke 早就修完了。那个 PR 是我 merge 的。
