### ISSUE TITLE
indexold.tpl 有个网址加载错误

### ISSUE THREAD

**Issue by KagamigawaMeguri** [Anankke/SSPanel-Uim#748]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

	window.addEventListener('load',()=>{
		fetch('https://api.lwl12.com/hitokoto/v1?encode=realjson',{
			method: 'GET',
		}).then((response)=>{
			return response.json();
		}).then((r)=>{
			insertHitokoto(r);
		})
	});
133行 https://api.lwl12.com/hitokoto/v1?encode=realjson 这个网址 似乎ssl错误了很长时间

**Comment by SukkaW** [comment]
SSPanel UIM 由于历史遗留原因错误地使用了一个由个人维护、SLA 不做保证的一言 API 服务。
我们将会尽快去除一言。

**Comment by SukkaW** [comment]
@Anankke The `uim-index-dev` hasn't been fixed. Now I have reopened the issue.

**Comment by reason4love** [comment]
<div id="lwlhitokoto"></div>替换成<p id="hitokoto">:D 获取中...</p>
底部添加一条
<script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>
就可以修复
在一言官网看的。。。

**Comment by reason4love** [comment]
73行
`<div id="lwlhitokoto"></div>`替换成`<p id="hitokoto">:D 获取中...</p>`
最后大概205行增加一条
`<script src="https://v1.hitokoto.cn/?encode=js&select=%23hitokoto" defer></script>`
即可，旧代码可以删除，测试已无问题

**Comment by SukkaW** [comment]
@reason4love 现在的问题不是要更换 Hikoto。现在我们要直接去掉 Hikoto。
SSPanel UIM 最终用户多达 150 万+ 人，在整个项目层级使用任何公共免费的 API 都是不道德的。
