### ISSUE TITLE
最新版本telegram账号绑定时机器人回复3个问号怎么解？大佬

### ISSUE THREAD

**Issue by ivannovs** [Anankke/SSPanel-Uim#749]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

![image](https://user-images.githubusercontent.com/46206221/62625784-84560000-b958-11e9-98b1-fa0a867ab2df.png)
解二维码方式是online.代码是最新git的，wiki都看了一遍了没有找到答案。
请大佬诊断一下，谢谢

**Comment by ivannovs** [comment]
调试了半天代码，找到问题所在了。。zxing_local_decode
$filepath = BASE_PATH . '/storage/' . time() . random_int(1, 100) . '.png';
/storage目录要有写权限。。我擦，建议在WIKI中完善指明。打绕了大佬 们。

**Comment by ivannovs** [comment]
关了

**Comment by Anankke** [comment]
> 调试了半天代码，找到问题所在了。。zxing_local_decode
> $filepath = BASE_PATH . '/storage/' . time() . random_int(1, 100) . '.png';
> /storage目录要有写权限。。我擦，建议在WIKI中完善指明。打绕了大佬 们。

自己不看你怪谁？
