### ISSUE TITLE
已用流量/今日已用 undefined/undefined

### ISSUE THREAD

**Issue by aiastia** [Anankke/SSPanel-Uim#752]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

演示站如图，
![image](https://user-images.githubusercontent.com/19776350/62773336-7dec9300-bad4-11e9-8f05-bc5f5b6e09d3.png)

![image](https://user-images.githubusercontent.com/19776350/62773290-61e8f180-bad4-11e9-9131-f1937651e159.png)

**Comment by SukkaW** [comment]
在演示站未能复现该 Bug，请提供更多信息。

**Comment by aiastia** [comment]
这个图就在演示站上截的。
![image](https://user-images.githubusercontent.com/19776350/62775348-f6a21e00-bad9-11e9-89e5-dda4cf4773d3.png)

不过好像是浏览器缓存的问题,刚刚换了个浏览器就显示 了……/尴尬）
