### ISSUE TITLE
[邀请码] 无法固定

### ISSUE THREAD

**Issue by tanyui** [Anankke/SSPanel-Uim#760]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug

**您好，邀请码现在无法固定使用一个，邀请朋友注册一次就会自动更新，无法固定使用一个

定制了邀请链接，依然会重置。**

**Comment by Anankke** [comment]
？
