### ISSUE TITLE
下载客户端地址全部404

### ISSUE THREAD

**Issue by AndyChuck** [Anankke/SSPanel-Uim#765]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

在master分支中的版本：首页-快速添加节点-点击下载xxx，这些按钮链接到的资源全部404，希望在今后版本中直接把这些按钮链接到对应的Github Release

![PIC](https://user-images.githubusercontent.com/23419265/63224012-b9800f00-c1f0-11e9-9941-e82460179f35.png)

**Comment by lenovoy450** [comment]
看到标题第一感觉，怎么又把issue当新手教程了，本着对你的尊重，我又看了一眼代码，才发现这代码真差啊，怎么不加入眼科医院电话呢

**Comment by SukkaW** [comment]
@lenovoy450 目前我们只有这 `Idiot` 的 `Label`，也许我们需要一个 `Blinded` 的 Label。

**Comment by regendsoh** [comment]
@lenovoy450 建议重新阅读搭建教程 实在不行私聊我交 ` 50￥` 学费 我教你
https://t.me/regendsoh

**Comment by SukkaW** [comment]
@regendsoh 你回错人了

**Comment by regendsoh** [comment]
@SukkaW 改了 跪了 眼睛不好 @lenovoy450 dalao见谅

**Comment by AndyChuck** [comment]
你们的master分支里有这个文件吗？
![PIC2](https://user-images.githubusercontent.com/23419265/63225047-023ec480-c1ff-11e9-9f22-10474cbc342d.png)
![PIC3](https://user-images.githubusercontent.com/23419265/63225052-04a11e80-c1ff-11e9-8313-fe5e1c52dcbb.png)

**Comment by Anankke** [comment]
弱智问题，已ban
