### ISSUE TITLE
用户过期了仍可以使用，显示无期限问题

### ISSUE THREAD

**Issue by 0923** [Anankke/SSPanel-Uim#767]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**Comment by 0923** [comment]
![image](https://user-images.githubusercontent.com/20281864/63399102-0f77d100-c402-11e9-8e5f-ab17aa798ec5.png)

**Comment by Passipur** [comment]
@0923 并没有觉得这有什么问题

**Comment by lenovoy450** [comment]
和上一个说404的一样，看看眼科？ 或者谁给你搭的找谁去

**Comment by aiastia** [comment]
@lenovoy450 这个节点还能用是定时任务没有配置吧。

**Comment by lenovoy450** [comment]
那为什么不配置呢，wiki又不是没有写，所以推荐眼科

**Comment by 0923** [comment]
哪位大佬知道是那一条定时任务么，我试试

**Comment by 0923** [comment]
> @ lenovoy450这个节点还能用是定时任务没有配置吧。

大佬知道是那一条定时任务么，我试试

**Comment by aiastia** [comment]
@0923 看wiki 或者去群里 报价 99（滑稽

**Comment by 0923** [comment]
> @ 0923看wiki或者去群里报价99（滑稽

好啦
