### ISSUE TITLE
能说一下新版本和旧版本配置区别在哪里吗？为什么WIKI的方法也不行，没人更新！！

### ISSUE THREAD

**Issue by 573462273** [Anankke/SSPanel-Uim#773]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**Comment by molissr** [comment]
没区别。代码没合并

发自我的 iPhone

**Comment by 573462273** [comment]
你的意思是wiki方法还能用，对吗？

**Comment by lenovoy450** [comment]
不行就买伟哥

**Comment by molissr** [comment]
我的意思是更个锤子
没区别更什么

发自我的 iPhone

**Comment by molissr** [comment]
不是有记录吗？你可以看看新版本增加了什么

发自我的 iPhone

**Comment by LiuYund** [comment]
哎，之前的Wiki前端教程被删除了，现在的Wiki又打不开，里面的教程也有问题，弄了一天老是报各种错误，我的小破站怕是要关了

**Comment by Passipur** [comment]
@LiuYund 区别commit都写了 您翻看便是

**Comment by mxihan** [comment]
@LiuYund  请使用全局代理访问Wiki，为了规避一些问题Wiki已禁止大陆IP访问

**Comment by LiuYund** [comment]
> @LiuYund 请使用全局代理访问Wiki，为了规避一些问题Wiki已禁止大陆IP访问

感谢解答！之前的Wiki有一个lnmp的一键搭建脚本，现在的Wiki没有了.....

**Comment by molissr** [comment]
现在的站要挂梯子

发自我的 iPhone
