### ISSUE TITLE
[FR] Add PayPal and oversea currency

### ISSUE THREAD

**Issue by Garry050** [Anankke/SSPanel-Uim#775]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

我想把sspanel用于海外用户。
我认为货币可以兑换成美元、欧元、日元等。
但付款方式太差了。我试过用paymentwall。但这是美国的**平台
(似乎需要美国身份证和税号……WTF？)
所以…我想使用原生PayPal在SSPanel。
如果你加上这个，我会捐钱的

> 
> I want use SSPanel for overseas user.
> I think currency can change to USD,EUR,JPY etc etc...
> but payment method so bad. i tried use PaymentWall. but wait. it's american sh*t platform...
> (It's seems require America ID and Tax ID... WTF?)
> So I wanna use [Original] PayPal on the SSPanel...

**Comment by SukkaW** [comment]
SSPanel UIM is mainly designed for users in mainland china.

Currently, we support many payment gateway services, maybe some of them support PayPal.
At this moment we have no plan adding support for direct PayPal. We will look into this feature request then.

**Comment by safepayment** [comment]
这个任务我可以认领。
@Garry050 你自己有Paypal商户账户么，还是想代收。
