### ISSUE TITLE
payjs,QR生成错误修复

### ISSUE THREAD

**Issue by hillghost86** [Anankke/SSPanel-Uim#780]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

第一次用github，不知道这个应该发哪里，就先发这里了！
调试payjs过程中，发现2处需要修改的地方
1.\app\Services\Payment.php
11行 缺少PAYJS
use App\Services\Gateway\{
    AopF2F, Codepay, DoiAMPay, PaymentWall, ChenPay, SPay, TrimePay,PAYJS
};

2. \resources\views\material\user\payjs.tpl
二维码生成js部分

                            var qrcode = new QRCode("qrcode", {
                                correctLevel: 3,  //解决超过200字符的二维码生成问题
                                render: "canvas",
                                width: 200,
                                height: 200,
                                text: data.url      //使用encodeURI()函数报会调低至错误
                            });

**Comment by Anankke** [comment]
非常感谢，已经修复
