### ISSUE TITLE
申请在新版Wiki中添加LNMP一键搭建脚本

### ISSUE THREAD

**Issue by LiuYund** [Anankke/SSPanel-Uim#781]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

旧Wiki有LNMP一键搭建脚本，新Wiki中移除了该脚本。按照新Wiki里面的LNMP搭建教程始终有问题，之前的一键搭建脚本相当方便，能否将之前的脚本添加到新Wiki？

**Comment by Anankke** [comment]
有问题不开 issue 却来要求加脚本？

**Comment by LiuYund** [comment]
> 有问题不开 issue 却来要求加脚本？

在新Wiki站评论了，电报群问了，你的Blog留言了都没有回复才来github的。。。。

**Comment by Anankke** [comment]
> 在新Wiki站评论了，电报群问了，你的Blog留言了都没有回复才来github的。。。。
![image](https://user-images.githubusercontent.com/40639066/64093203-77dd8100-cd25-11e9-8392-7aaf72b4ac64.png)
大家好，我上不了网，始终不成功，求解决

**Comment by LiuYund** [comment]
> > 在新Wiki站评论了，电报群问了，你的Blog留言了都没有回复才来github的。。。。
> 
> ![image](https://user-images.githubusercontent.com/40639066/64093203-77dd8100-cd25-11e9-8392-7aaf72b4ac64.png)
> 
> 大家好，我上不了网，始终不成功，求解决

1.我在搭建过程中遇到的各种问题都有在百度，Google搜索解决方法，但由于对linux并不熟悉，自己尝试几天都始终报错，并不是你认为的什么都不做只想别人给方法的伸手党
2.对小白来说，以前的一键搭建脚本确实很好用，所以希望能再新Wiki上添加，可以帮助更多的小白，也节约了各位dalao回答问题的时间
3.我很感谢你对于这个项目的贡献，也知道各位dalao没有时间去回答所有小白的问题，但是能别嘲讽我吗
4.以前的一键搭建脚本真的很方便

**Comment by crystal-moe** [comment]
@LiuYund 可以非常明确的告诉你，wiki和教程是有区别的。如果想偷懒，请用脑子偷懒。如果帮助你只是无意义地重复Google，那请联系你亲密的人，他们才会无差别解答。

**Comment by Anankke** [comment]
> 1.我在搭建过程中遇到的各种问题都有在百度，Google搜索解决方法，但由于对linux并不熟悉，自己尝试几天都始终报错，并不是你认为的什么都不做只想别人给方法的伸手党

### 大家好，我不是**伸手党**，**伸手党**是我客户
首先教程是正确的，不成功几乎都是自己漏掉执行或者看不懂英语导致的，所以宁当爷新别人也没义务帮助你，包括 wiki 等文档也是完备的。没有基础就不要开机场，先去学习 Linux，就算再菜整不明白，文档里面也有宝塔教程，这都弄不明白的话没救的，**伸手党**。
哦直到现在都不懂贴出报错，宁真不是**伸手党**，宁是**爷新**。

> 2.对小白来说，以前的一键搭建脚本确实很好用，所以希望能再新Wiki上添加，可以帮助更多的小白，也节约了各位dalao回答问题的时间

我们不会向 wiki 里加入任何有误导性或者来源无法控制的内容。小白就不应该开机场，因为个体差异一键脚本只会带来更多麻烦。

> 3.我很感谢你对于这个项目的贡献，也知道各位dalao没有时间去回答所有小白的问题，但是能别嘲讽我吗

### LMAO

> 4.以前的一键搭建脚本真的很方便

非官方，被黑自理，谢谢茄子

**Comment by LiuYund** [comment]
> @LiuYund 可以非常明确的告诉你，wiki和教程是有区别的。如果想偷懒，请用脑子偷懒。如果帮助你只是无意义地重复Google，那请联系你亲密的人，他们才会无差别解答。

了解了，抱歉占用了您的时间和精力来close这个issues，我继续学习Linux尝试搭建吧。

**Comment by SukkaW** [comment]
@Anankke 
不过毕竟他至少懂得 Issue 模板是要填写的，不是拿来删掉的。。
我把这个 issue 锁了吧。
