### ISSUE TITLE
无法收到邮件 已经添加财务报表 自动备份 但发现从没收到过邮件

### ISSUE THREAD

**Issue by pengfeixu7** [Anankke/SSPanel-Uim#785]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

**Comment by pengfeixu7** [comment]
无法收到邮件 已经添加财务报表 自动备份 但发现从没收到过邮件

**Comment by lenovoy450** [comment]
无法收到转账，已经填写了银行卡号，姓名，但发现从没有收到钱

**Comment by lenovoy450** [comment]
你有邮局吗，你告诉邮局给你发信了吗，邮局答应给你发了吗，邮差找到你家了吗，给你放邮箱了吗，你家保洁的阿姨给你把信扔了吗？

**Comment by pengfeixu7** [comment]
> 你有邮局吗，你告诉邮局给你发信了吗，邮局答应给你发了吗，邮差找到你家了吗，给你放邮箱了吗，你家保洁的阿姨给你把信扔了吗？

因为这些我不知道怎么排查  所以来询问

**Comment by regendsoh** [comment]
不知道排查还开什么机场 不如回去睡觉 晚安安

**Comment by wewall** [comment]
> 无法收到转账，已经填写了银行卡号，姓名，但发现从没有收到钱

什么转账

**Comment by pengfeixu7** [comment]
> > 无法收到转账，已经填写了银行卡号，姓名，但发现从没有收到钱
> 


> > 无法收到转账，已经填写了银行卡号，姓名，但发现从没有收到钱
> 
> 什么转账

我的问题换个说法。。。 逻辑一样的。。。。你知道怎么排查吗

**Comment by aiastia** [comment]
@pengfeixu7 这个问题说起来比较复杂。这个要从宇宙开始的时候说起。说来话长。不如你来群里面报价。这个比较简单。

**Comment by pengfeixu7** [comment]
> @ pengfeixu7这个问题说起来比较复杂。这个要从宇宙开始的时候说起。说来话长。不如你来群里面报价。这个比较简单。

群里好像都是50起步耶

**Comment by wewall** [comment]
> 群里好像都是50起步耶

https://www.bilibili.com/video/av32779873/
