### ISSUE TITLE
api相关 

### ISSUE THREAD

**Issue by taojishou** [Anankke/SSPanel-Uim#787]
请问有没有api文档？比如登录 获取节点列表等等的

**Comment by pang-w** [comment]
**请求URL：** 
- ` https://hosts/api/token `
  
**请求方式：**
- POST 

**参数：** 

|参数名|必选|类型|说明|
|:----    |:---|:----- |-----   |
|email |  是  |    string   |    无   |
|passwd |  是  |    string   |    无   |


**返回示例**

``` 
{
  "ret": 1,
  "msg": "ok",
  "data": {
    "token": "wL7WF0fyoFBtzz58AH4hgLM0xNKvIJnqC5WG0UqgYvn5bwip2JIcnIN31I3tOS4z",
    "user_id": 1
  }
}

```


**请求URL：** 
- ` https://hosts/api/token/{token} `
  
**请求方式：**
- GET 



**返回示例**

``` 
{
  "ret": 1,
  "msg": "ok",
  "data": {
    "token": "9IjtrIMgXQsm64CtsEqIXu0gBoGIUDN2kvR4wX1z5UedMDbBmpJb86FGuSTKnvHy",
    "userId": 1,
    "createTime": 1568191997,
    "expireTime": 1568796797
  }
}

```
