### ISSUE TITLE
充值购买问题

### ISSUE THREAD

**Issue by clatme** [Anankke/SSPanel-Uim#797]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

不用先充值，直接购买套餐 比较好

比如发优惠码  用户先要看优惠码减多少钱 再充值等值的金额，然后再购买套餐比较麻烦。 

流程比较繁琐，建议直接购买套餐，而不用先充值后再购买

**Comment by Anankke** [comment]
建议你来重写ｓｈｏｐ，就是你了

**Comment by wewall** [comment]
建议你来重写ｓｈｏｐ，就是你了

**Comment by NimaQu** [comment]
@clatme 中央已经决定了，你来重写 shop

**Comment by Deoncn** [comment]
神仙
