### ISSUE TITLE
备份源站 2G tar 引起的沉思

### ISSUE THREAD

**Issue by wewall** [Anankke/SSPanel-Uim#798]
- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题
- [x] 反馈一个 bug

忽然想需要下载的文件放在本地 源文件 + `.git` 文件夹 随便过 G , 用 github 开源直连是不是会稍微好点, 这样也不需要更新这玩意, 还剩下备份源站代码的时间, 节约了储存

如果不修改是不是可以修改 clone 深度

https://github.com/Anankke/SSPanel-Uim/blob/1811fc0aaa508fa8fedb0984ef05ad6ec693c87c/app/Command/XCat.php#L175-L179

**Comment by SukkaW** [comment]
SSPanel 的 客户端下载大小是 165MB。每天要被同步 450 次。不用 GitHub 独立一个 Repo，流量钱你出？
你备份源站不忽略 `public.ssr-download` 目录和 SSPanel 有什么关系？

**Comment by wewall** [comment]
用 github 开源直连 不收流量费

**Comment by wewall** [comment]
这几个都有 releases 页面

**Comment by Anankke** [comment]
SSPanel 的 客户端下载大小是 165MB。每天要被同步 450 次。不用 GitHub 独立一个 Repo，流量钱你出？
你备份源站不忽略 `public/ssr-download` 目录和 SSPanel 有什么关系？
