### ISSUE TITLE
充值中心空白

### ISSUE THREAD

**Issue by dendinuo** [Anankke/SSPanel-Uim#800]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

新版前端 充值中心 空白，老版页面可以用，怎么回事，你们有遇到过吗

![image](https://user-images.githubusercontent.com/40659261/65047802-a5693200-d995-11e9-90c9-add3f084402b.png)
![image](https://user-images.githubusercontent.com/40659261/65047868-c467c400-d995-11e9-818d-634afce4f8bc.png)

**Comment by SakuraSa233** [comment]
Please ask the author of this payment system to support Vue.
