### ISSUE TITLE
ClientApiController.php mu index error

### ISSUE THREAD

**Issue by pang-w** [Anankke/SSPanel-Uim#801]
https://github.com/Anankke/SSPanel-Uim/blob/f9284e64244258f923b4169cc467bc72513e7332/app/Controllers/Client/ClientApiController.php#L64

        if ($request->getQueryParams()['mu'] != '') {
            $mu = $request->getQueryParams()['mu'];
        }
如果没有传递mu参数，会报错。虽然不知道为什么要这么写，但是我觉得 这样更好一些？
        $accessToken = Helper::getParam($request, 'access_token');
        $mu = Helper::getParam($request, 'mu', '');
        $storage = Factory::createTokenStorage();
        $token = $storage->get($accessToken);
        $user = User::find($token->userId);
        $ssr_sub_token = LinkController::GenerateSSRSubCode($user->id, 0);
        $res['ret'] = 1;
        $res['msg'] = 'ok';
        $res['data'] = Config::get('subUrl') . $ssr_sub_token . '?mu=' . $mu;
        return $this->echoJson($response, $res);

**Comment by Anankke** [comment]
上古 commit，是在 helper 重写之前完成的了。
我觉得差不多，想改的话可以开个 pr

**Comment by pang-w** [comment]
回头全都看过源码之后再说吧， 看你很多变量都带有mu参数， 想问一下是什么意思呢？

**Comment by Anankke** [comment]
@pang-w 。

**Comment by pang-w** [comment]
@Anankke  what? 想问一下例如 mu_only  mu_nodes 这些的mu 不是很理解。

**Comment by SukkaW** [comment]
Muilt User.

**Comment by pang-w** [comment]
@SukkaW  谢谢～
