### ISSUE TITLE
对接rico 的 v2ray 后端，启动成功，无法连接面板，报错信息与配置如下

### ISSUE THREAD

**Issue by blakelu** [Anankke/SSPanel-Uim#805]
![image](https://user-images.githubusercontent.com/13463232/65373486-c214ab00-dcb0-11e9-8345-429a7bf19be4.png)
![image](https://user-images.githubusercontent.com/13463232/65373493-d5c01180-dcb0-11e9-8056-54b09b7a992f.png)

**Comment by SakuraSa233** [comment]
Closed due to didn't obey the issue template.
