### ISSUE TITLE
关于订阅链接的BUG

### ISSUE THREAD

**Issue by NiTian1207** [Anankke/SSPanel-Uim#808]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

更新订阅链接后需要刷新网页才会显示新的链接

**Comment by Anankke** [comment]
那你不刷新怎么显示新的连接啊

**Comment by NiTian1207** [comment]
不是应该自动更新页面上的链接吗。0.0

**Comment by NiTian1207** [comment]
blog.anank.ke 打不开了

**Comment by Anankke** [comment]
> 不是应该自动更新页面上的链接吗。0.0

你来写

**Comment by Anankke** [comment]
> blog.anank.ke 打不开了

机房烧没了，最近会重建

**Comment by NiTian1207** [comment]
> 
> 
> > 不是应该自动更新页面上的链接吗。0.0
> 
> 你来写

我不会写。。。
就是在重置完订阅链接后自动刷新页面。
就像原来面板那样
