### ISSUE TITLE
RuntimeException Unexpected data in output buffer.

### ISSUE THREAD

**Issue by masker9524** [Anankke/SSPanel-Uim#812]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

參考「自豪的使用 LNMP 部署 SSPanel 魔改版」搭建環境之後，最後連線到頁面時顯示RuntimeException Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?
debug 截圖如下，不清楚是不是 Slim\App的問題 或者哪裡手滑設置錯誤

先謝過各位大佬們了！

![Screen Shot 2019-09-24 at 8 01 03 pm](https://user-images.githubusercontent.com/8372547/65502549-5a579d80-df06-11e9-98f7-5c06d0607a54.png)

**Comment by SakuraSa233** [comment]
`git reset --hard`

**Comment by masker9524** [comment]
感謝大老快速回覆，最後發現 php7.3-fpm 沒有關閉 debug
