### ISSUE TITLE
多次购买套餐重置属性问题

### ISSUE THREAD

**Issue by addarmy** [Anankke/SSPanel-Uim#819]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

用户再次购买套餐或多次购买套餐,重置属性会叠加
例如:
套餐A 为等级1 每月重置50GB
套餐B 为等级2 每月重置100GB
用户在1号购买了套餐A，无论是这个套餐已经到期或者是升级购买了套餐B，此时用户重置属性就出现问题，在1号时依然会按照套餐A进行流量重置为50GB，到15号再次重置为100GB。（这仅仅是两个套餐的举例，如果在用户购买多个套餐时，他的重置属性就产生多个，即使旧套餐已经到期，再次购买新套餐，他的旧套餐属性就会开始继续生效。）

**Comment by Anankke** [comment]
每月重置本来来就不是让你覆盖的
