### ISSUE TITLE
sspanel v3 搬家后升级，怎么会用户密码全部都是错的？

### ISSUE THREAD

**Issue by uubxs** [Anankke/SSPanel-Uim#820]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [  ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

其他测试没有问题，就是用户登录的时候都提示密码错误，求告知，谢谢！

**Comment by LifeVictory** [comment]
@uubxs 100

**Comment by Anankke** [comment]
@uubxs 自己搜 issue

**Comment by uubxs** [comment]
> @uubxs 自己搜 issue
@Anankke
感谢！是我看漏了，打扰了。
