### ISSUE TITLE
反馈一个节点连接密码重置的BUG

### ISSUE THREAD

**Issue by jianpanxia666** [Anankke/SSPanel-Uim#821]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题（**演示站无法登录**）

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

1.重置节点连接密码后，点击拷贝复制的是原密码，而不是重置后的新密码。
2.而且重置第二次时，密码不会变动，需要刷新页面再重置才行。
3.貌似重置后新的密码不是即时生效，实测重置后一分钟内原密码还能连接。

**Comment by Anankke** [comment]
1. 需要刷新，这个可以通过重置任意内容之后强制自动刷新做到
2. 同上
3. 节点一分钟同步一次，并非 bug。除非重写为 websocket 链接或者 RPC 链接。

**Comment by Anankke** [comment]
https://github.com/Anankke/SSPanel-Uim/issues/710 一个道理
