### ISSUE TITLE
php xcat setTelegram 出错

### ISSUE THREAD

**Issue by 573462273** [Anankke/SSPanel-Uim#825]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

PHP Fatal error:  Uncaught TelegramBot\Api\HttpException: Bad Request: bad webhook: HTTPS url must be provided for webhook in /var/www/ss.com/vendor/telegram-bot/api/src/BotApi.php:281
Stack trace:
#0 /var/www/ss.com/vendor/telegram-bot/api/src/BotApi.php(258): TelegramBot\Api\BotApi::curlValidate(Resource id #106, '{"ok":false,"er...')
#1 /var/www/ss.com/vendor/telegram-bot/api/src/BotApi.php(227): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /var/www/ss.com/vendor/telegram-bot/api/src/BotApi.php(437): TelegramBot\Api\BotApi->call('setWebhook', Array)
#3 /var/www/ss.com/app/Command/XCat.php(267): TelegramBot\Api\BotApi->setWebhook('http://ss.c...')
#4 /var/www/ss.com/app/Command/XCat.php(45): App\Command\XCat->setTelegram()
#5 /var/www/ssv.com/xcat(11): App\Command\XCat->boot()
#6 {main}
  thrown in /var/www/ss.com/vendor/telegram-bot/api/src/BotApi.php on line 281

**Comment by galaxychuck** [comment]
@573462273 HTTPS

**Comment by 573462273** [comment]
Thanks.

**Comment by jacksunhack** [comment]
webhook 那一项怎么填/
