### ISSUE TITLE
大佬是否可以在sspanel对接1台vps绑定10ip这种骚操作？

### ISSUE THREAD

**Issue by OJBKSS-dev** [Anankke/SSPanel-Uim#831]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x ] 申请添加新的特性或功能或者好的想法

也就是想明白，后台一个node ID一台服务器，如果这台服务器有10个ipv4如何填写添加节点这个位置呢，后端又是如何部署呢，希望可以了解sspanel mod这个神奇的功能，实现一台vps多个IP，一人一个IP玩游戏！

**Comment by KunagisaYuki** [comment]
@OJBKSS-dev @Talocan 出来烂拳

**Comment by OJBKSS-dev** [comment]
> @OJBKSS-dev @talocan 出来烂拳

大佬高明，请问如何可以达到这个想要的效果呢

**Comment by crystal-moe** [comment]
@OJBKSS-dev 老老实实给用户提供服务而不是滥竽充数，OK？

**Comment by SukkaW** [comment]
SSPanel UIM 不支持为一个节点分配多个 IP 的设置。

如果你的机器有 10 个 IP，请自行添加 10 个节点并对节点进行分组。

**Comment by OJBKSS-dev** [comment]
> @OJBKSS-dev 老老实实给用户提供服务而不是滥竽充数，OK？

不不不，用户想要多个IP 数量如果比较大，购买服务器成本会比较高，当然会想用这个折中的办法处理！

**Comment by regendsoh** [comment]
@OJBKSS-dev 给钱定制 就可以

**Comment by topjohncian** [comment]
@OJBKSS-dev 找anankke定制啊 t.me/Talocan

**Comment by zackvv** [comment]
> > @ OJBKSS-dev老老实实给用户提供服务而不是滥竽充数，好吗？
> 
> 不不不，用户想要多个IP数量如果比较大，购买服务器成本会比较高，当然会想用这个折中的方法处理！

你搞定了没，我也想弄这个

**Comment by OJBKSS-dev** [comment]
我已经搞定了，有需要我可以免费告诉你如何操作，我的邮箱rockssr@163.com





------------------ 原始邮件 ------------------
发件人: zackvv <notifications@github.com&gt;
发送时间: 2020年1月8日 11:48
收件人: Anankke/SSPanel-Uim <SSPanel-Uim@noreply.github.com&gt;
抄送: 奥奥-OJBKSS <741500926@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[Anankke/SSPanel-Uim] 大佬是否可以在sspanel对接1台vps绑定10ip这种骚操作？ (#831)



  
@ OJBKSS-dev老老实实给用户提供服务而不是滥竽充数，好吗？
  
不不不，用户想要多个IP数量如果比较大，购买服务器成本会比较高，当然会想用这个折中的方法处理！
  
你搞定了没，我也想弄这个

**Comment by dylan198911** [comment]
发你邮件没回复呢  着急~
