### ISSUE TITLE
支付网关报524(CDN)

### ISSUE THREAD

**Issue by Excalibur-osu** [Anankke/SSPanel-Uim#837]
源站IP被墙 使用了cloudflare 网站服务并未受到影响
但发现充值时一直显示正在连接支付网关 等待大约1分钟左右后报错"[object Object] 发生错误了"
开启debug控制台无输出
调试工具网络列表内显示https://www.域名.com/user/payment/purchase这个页面报cloudflare的524错误
请教一下 是否因源站IP被墙导致? 理论上cloudflare连接源站服务器应该没问题 cloudflare并不在墙内 不解

**Comment by Anankke** [comment]
那你家支付宝网关也带 cloudflare了？

动动脑子
