### ISSUE TITLE
反馈一个BUG

### ISSUE THREAD

**Issue by hnhhzy** [Anankke/SSPanel-Uim#841]
我用的最新的分支。单端口服务器无法正常使用。
有来自2个地方的BUG。

1.如果服务器使用的是域名而不是IP。
那么/app/Middleware/Mod_Mu.php的34行，永远为null。因为使用域名的单端口节点。数据库的node_ip字段为空
2.前端节点列表报：Warning:  Creating default object from empty value in /www/wwwroot/tubevpn666.com/app/Controllers/UserController.php on line 472
我检查472行，问题出在471行
`$mu_user = User::where('port', '=', $node->server)->first();`
打印出来的node->server为域名，他在用户表的port搜域名，永远都是空？

**Comment by Anankke** [comment]
@hnhhzy 麻烦看 wiki，行？
虽然这部分也是屎山遗留的原因

**Comment by hnhhzy** [comment]
额。难道目前的版本是不支持单端口多用户的吗？还是有啥分支是能解决这问题的？
