### ISSUE TITLE
节点分组后，不显示单端口

### ISSUE THREAD

**Issue by jianpanxia666** [Anankke/SSPanel-Uim#842]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

节点分组后不显示单端口，订阅地址能订阅到单端口但是无法使用。普通端口正常。

**Comment by Anankke** [comment]
历史遗留 bug 暂时没有修复计划

**Comment by ssrlive** [comment]
安装到 [这里](https://blog.anank.ke/w/SSPanel_with_LNMP#menu_index_23) 时, 报告找不到 autoload.php 文件, 出错在下面一行. 怎么解决? 删掉就好?

https://github.com/Anankke/SSPanel-Uim/blob/dev/bootstrap.php#L17

**Comment by regendsoh** [comment]
分组后 单端口承载用户需要和该节点同一个分组 才能达到单端口可使用。

**Comment by regendsoh** [comment]
@jianpanxia666 ?
