### ISSUE TITLE
管理界面、充值码管理，系统中金额流转记录在php7.2和7.3环境下均报错

### ISSUE THREAD

**Issue by Baiyuetribe** [Anankke/SSPanel-Uim#854]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

后台管理、充值码管理，系统中金额流转记录在php7.2和7.3环境下均报错，Warning: Use of undefined constant number - assumed 'number' (this will throw an Error in a future version of PHP) in /www/wwwroot/latte.com/app/Models/User.php on line 391。只有php7.1环境下正常使用。
请求修复该bug
![Snipaste_2019-11-02_12-58-36.png](https://i.loli.net/2019/11/02/Dn7qdf8ivIasNuS.png)

**Comment by Anankke** [comment]
是 warning 报了个锤子错自己先关了不就行了事挺多还

**Comment by Baiyuetribe** [comment]
明白了，php里display erro关闭了就正常了，还有这种操作，没想到啊

**Comment by Anankke** [comment]
@regendsoh 出来修你的 bug

**Comment by regendsoh** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/d217000ca296e76aebb86733196e582b509fb150

这几个有变动的 public function 在你的 app/models/user.php 替换一下

**Comment by topjohncian** [comment]
@Baiyuetribe 你是佰阅站长吗？在？为什么抄袭

**Comment by Baiyuetribe** [comment]
> @Baiyuetribe 你是佰阅站长吗？在？为什么抄袭

啥叫抄袭？我抄袭了什么？

**Comment by Baiyuetribe** [comment]
感谢@regendsoh 已修复该问题
