### ISSUE TITLE
注册时候联系方式如何关闭，config里面找了没有找到

### ISSUE THREAD

**Issue by chen63536** [Anankke/SSPanel-Uim#861]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**Comment by Anankke** [comment]
无法关闭

**Comment by chen63536** [comment]
因为样式css有冲突，造成没有办法选择联系方式，这样就不能注册了，有没有办法帮忙解决下，谢谢！头疼啊，谢谢！

**Comment by chen63536** [comment]
因为样式css有冲突，造成没有办法选择联系方式，这样就不能注册了，有没有办法帮忙解决下，谢谢！头疼啊，谢谢！

Anankke <notifications@github.com> 于2019年11月6日周三 下午2:56写道：
