### ISSUE TITLE
注册时，选择联系方式能否有默认值，就是点击注册页面时，联系方式默认是QQ

### ISSUE THREAD

**Issue by chen63536** [Anankke/SSPanel-Uim#862]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

**Comment by regendsoh** [comment]
@chen63536 请自行更改代码。

**Comment by chen63536** [comment]
能不能帮忙修改？

<div class="rowtocol">
<div class="auth-row">
<div class="form-group form-group-label dropdown">
<label class="floating-label" for="imtype">选择您的联络方式</label>
<button class="form-control maxwidth-auth" id="imtype" data-toggle="input">

</button>
<input class="form-control maxwidth-auth" id="imtype" type="imtype">
<ul class="dropdown-menu" aria-labelledby="imtype">
<li><a href="#" class="dropdown-option" onclick="return false;" val="1"
data="imtype">微信</a></li>
<li><a href="#" class="dropdown-option" onclick="return false;" val="2"
data="imtype">QQ</a></li>
<li><a href="#" class="dropdown-option" onclick="return false;" val="3"
data="imtype">Facebook</a></li>
<li><a href="#" class="dropdown-option" onclick="return false;" val="4"
data="imtype">Telegram</a></li>
</ul>
</div>
</div>
</div>

修改后发给我，你发收款二维码，这边给你付款10元，谢谢！

>

**Comment by Anankke** [comment]
脑瘫麻烦别开机场
