### ISSUE TITLE
建议将充值码与充值记录区分开来，不混在一起显示

### ISSUE THREAD

**Issue by miniaoe** [Anankke/SSPanel-Uim#863]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ x] 申请添加新的特性或功能或者好的想法

建议，将未使用的充值码与在线支付区分开，不放到一个页面里。
单独充值码页面展示全部充值码，不论有没有使用或者过期，可以进行筛选。
已使用的充值码记录到充值记录里，计算到当月流水中。

**Comment by topjohncian** [comment]
@miniaoe 在？Welcome PR
