### ISSUE TITLE
支付宝当面付订单详情无用户的邮箱只有一串码

### ISSUE THREAD

**Issue by a212059302** [Anankke/SSPanel-Uim#864]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

我已经升级了最新版本

支付宝当面付订单详情无用户的邮箱只有一串码

**Comment by Anankke** [comment]
麻烦脑瘫不要开机场

**Comment by Jcyt-R** [comment]
@Anankke 哈哈哈哈

**Comment by a212059302** [comment]
所有教程都打不开 网站关了 你才脑瘫

**Comment by laogao123** [comment]
@a212059302 太秀了

**Comment by aipeach** [comment]
@a212059302 阁下是想出道了

**Comment by a212059302** [comment]
我把他的wiki翻遍了 都没找到 然后就来请问下  上来就骂

**Comment by laogao123** [comment]
@a212059302 换我我也照骂

**Comment by JohnFreeman9** [comment]
@a212059302 建议阁下脑力升级

**Comment by aipeach** [comment]
@a212059302 wiki并没有这些，如果要回滚版本请到群里报价，跟安安可对线可不是明智的选择

**Comment by a212059302** [comment]
> @a212059302 wiki并没有这些，如果要回滚版本请到群里报价，跟安安可对线可不是明智的选择

好多 非常感谢

**Comment by a212059302** [comment]
@aipeach 好多 非常感谢
