### ISSUE TITLE
现在wiki和演示站都提示备案呢

### ISSUE THREAD

**Issue by youxiage** [Anankke/SSPanel-Uim#865]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

现在wiki和演示站都提示备案呢
https://wiki.sspanel.host/

**Comment by aipeach** [comment]
@youxiage 代理访问

**Comment by PYniang** [comment]
@youxiage 建議在PAC裡面添加走代理呢

**Comment by regendsoh** [comment]
@youxiage 不会用代理 你开🔨机场呢

**Comment by topjohncian** [comment]
@youxiage 不会用代理 你开🔨机场呢

**Comment by Anankke** [comment]
@topjohncian 不会用代理 你开🔨机场呢

**Comment by narakuzi** [comment]
@youxiage   不会用代理 你开🔨机场呢
