### ISSUE TITLE
开启“合并订阅链接”后，客户端（Win和Android都测试过）订阅到的节点数量变少

### ISSUE THREAD

**Issue by pplulee** [Anankke/SSPanel-Uim#866]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

开启“合并订阅链接”后，客户端（Win和Android都测试过）订阅到的节点数量变少

**Comment by xeye666** [comment]
已经遇到同样的类似问题，节点配置为只启用单端口或普通端口 二选一，config开启订阅合并后只能更新普通端口，并不能合并，但是管理员账户却可以。

**Comment by aipeach** [comment]
@xeye666 你说管理员可以，初步怀疑是你承载节点或承载用户的等级没设置对

**Comment by xeye666** [comment]
> @xeye666 你说管理员可以，初步怀疑是你承载节点或承载用户的等级没设置对

这种低级错误不会犯的，可能我表述不准确，是普通端口可以刷新出来，单端口节点刷新不出，管理员没有这个问题，我已经更换多种加密测试。

**Comment by wskydfcu** [comment]
遇到差不多的问题
订阅合并模式，无法单端口节点(是否显示) 中隐藏某个节点。管理员订阅地址可以隐藏节点。普通订阅用户却更新出隐藏节点

**Comment by JusufUs** [comment]
修改URL那个文件亲测可用

**Comment by xiaoyiya** [comment]
> 已经遇到同样的类似问题，节点配置为启用单端口与多端口，config开启订阅合并后只能更新普通端口，单端口刷新不出节点，但是管理员账户却无此问题。安卓/ios均测试。

这个问题我遇到的是因为承载用户权限问题，建议仔细检查

**Comment by wskydfcu** [comment]
> 修改URL那个文件亲测可用

怎么修改。可以报价帮我修改一下吗？TG +1 8705696568

**Comment by wskydfcu** [comment]
> > 已经遇到同样的类似问题，例程配置为启用单端口与多端口，配置打开订阅合并后只能更新普通端口，单端口刷新不出计数器，但是管理员账户却无此问题。安卓/ ios均测试。
> 
> 这个问题我遇到的是因为承载用户权限问题，建议仔细检查
您好。我仔细检测过。承载用户，承载节点，用户全权都是为1
