### ISSUE TITLE
添加管理员账号和ip解析库 的时候 提示 缺少 vendor 目录？

### ISSUE THREAD

**Issue by tysonair** [Anankke/SSPanel-Uim#871]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

---

添加管理员账号和ip解析库
php xcat initQQWry    //下载ip解析库
php xcat createAdmin  //创建管理员账号，除非提示创建成功，否则说明你上一步的数据库填写有误

提示：

PHP Warning:  require(/www/wwwroot/xxx.xxx/vendor/autoload.php): failed to open stream: No such file or directory in /www/wwwroot/xxx.xxx/bootstrap.php on line 17
PHP Fatal error:  require(): Failed opening required '/www/wwwroot/xxx.xxxvendor/autoload.php' (include_path='.:/www/server/php/72/lib/php') in /www/wwwroot/xxx.xxx/bootstrap.php on line 17

**Comment by wuabuhuan** [comment]
我也有此问题

**Comment by yry0008** [comment]
@wuabuhuan 你的composer安装了吗

**Comment by wuabuhuan** [comment]
> @wuabuhuan 你的composer安装了吗

是的 安装了
