### ISSUE TITLE
已用流量每天重置

### ISSUE THREAD

**Issue by Allenprox** [Anankke/SSPanel-Uim#873]
请问已用流量每天重置,这个该如何配置啊。或者是和那个重置日一起重置已用流量！要怎么写？因为主要是我想弄成每天重置流量为1G，但是如果重置流量无法一起重置已用流量的话，会把已用流量从1G中减去，变成实际重置的流量只有1G减去已用流量，剩余值。
如果不重置已用流量也可以，只要我重置总流量的时候，已用流量不要从这部分减去就可以

**Comment by regendsoh** [comment]
@Allenprox 自 己 写 #prwelcome
