### ISSUE TITLE
网站将您重定向的次数过多

### ISSUE THREAD

**Issue by Redbeanw44602** [Anankke/SSPanel-Uim#874]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

问题：重定向次数过多 500
**唔...F12控制台屁内容没有啊，那就贴Debug吧...**
SmartyException thrown with message "unable to write file /www/sites/plane-wodf/storage/framework/smarty/compile/wrt5dcf99070df7c5_55851253"

Stacktrace:
#24 SmartyException in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_internal_runtime_writefile.php:60
#23 Smarty_Internal_Runtime_WriteFile:writeFile in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:209
#22 Smarty_Template_Compiled:write in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:184
#21 Smarty_Template_Compiled:compileTemplateSource in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:141
#20 Smarty_Template_Compiled:process in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php:105
#19 Smarty_Template_Compiled:render in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:216
#18 Smarty_Internal_Template:render in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:232
#17 Smarty_Internal_TemplateBase:_execute in /www/sites/plane-wodf/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php:134
#16 Smarty_Internal_TemplateBase:display in /www/sites/plane-wodf/app/Controllers/HomeController.php:58
#15 App\Controllers\HomeController:indexold in /www/sites/plane-wodf/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:40
#14 call_user_func in /www/sites/plane-wodf/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php:40
#13 Slim\Handlers\Strategies\RequestResponse:__invoke in /www/sites/plane-wodf/vendor/slim/slim/Slim/Route.php:281
#12 Slim\Route:__invoke in /www/sites/plane-wodf/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#11 Slim\Route:callMiddlewareStack in /www/sites/plane-wodf/vendor/slim/slim/Slim/Route.php:268
#10 Slim\Route:run in /www/sites/plane-wodf/vendor/slim/slim/Slim/App.php:503
#9 Slim\App:__invoke in /www/sites/plane-wodf/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php:70
#8 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in /www/sites/plane-wodf/vendor/slim/slim/Slim/DeferredCallable.php:57
#7 call_user_func_array in /www/sites/plane-wodf/vendor/slim/slim/Slim/DeferredCallable.php:57
#6 Slim\DeferredCallable:__invoke in /www/sites/plane-wodf/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#5 call_user_func in /www/sites/plane-wodf/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:70
#4 Slim\App:Slim\{closure} in /www/sites/plane-wodf/vendor/slim/slim/Slim/MiddlewareAwareTrait.php:117
#3 Slim\App:callMiddlewareStack in /www/sites/plane-wodf/vendor/slim/slim/Slim/App.php:392
#2 Slim\App:process in /www/sites/plane-wodf/vendor/slim/slim/Slim/App.php:297
#1 Slim\App:run in /www/sites/plane-wodf/config/routes.php:389
#0 require in /www/sites/plane-wodf/public/index.php:11
网站:npl.wodfuck.me（Debug模式）麻烦dalao去康康
还有我想问一下这是啥Debug啊这么牛逼好高大上

**Comment by NimaQu** [comment]
检查权限

**Comment by Redbeanw44602** [comment]
原来如此！忘了设置权限了！谢谢dalao给Star了
