### ISSUE TITLE
建议:在完成验证后才允许发送验证邮件

### ISSUE THREAD

**Issue by Redbeanw44602** [Anankke/SSPanel-Uim#877]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ ] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

如图
![捕获](https://user-images.githubusercontent.com/29711228/68994129-72bab780-08ba-11ea-8e2b-10f4dacfd4d1.PNG)
感觉会有人写个软件，叫***Mail Bombing Tool Powered By Every SSPanel Site's E-mail verification code***呢.........

**Comment by Anankke** [comment]
我也这么认为，so... pr welcome

**Comment by SakuraSa233** [comment]
人机验证模块重写预定，请等待后续更新。

**Comment by Redbeanw44602** [comment]
既然这样............我再提一下（希望支持 Recaptcha v3）#滑稽
