### ISSUE TITLE
dev版管理员无法编辑修改保存用户信息

### ISSUE THREAD

**Issue by liwenjie119** [Anankke/SSPanel-Uim#880]
**我确认我已经阅读了** (使用 "x" 选择)

- [x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [x] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

如修改用户的余额，在我的上面报错500，在sspanel.host报错误0.

**Comment by bbs3223474** [comment]
更新和迁移的时候，最好重新对比表里的差异。因为网站程序升级，数据库里各个表的内容有可能会发生变化。
我这次也出现相同情况，在编辑用户时出现500。所以根据https://blog.csdn.net/qq_36641456/article/details/89044100，打开php的错误信息，还有网站程序的debug模式，发现是数据表里少了一列“detected_last_ban_time”，所以引发这个故障。
建议是创建新数据库，重新导入glzjin_all.sql，然后复制原来的数据过去（我只复制了user、node和announcement三个表）。复制的时候选择“仅数据”而不是“数据和结构”，这样就能无缝整合。
故障处理完毕后关闭php里的display_errors和display_startup_errors，关闭网站debug，才能恢复正常访问。
