### ISSUE TITLE
新功能建议:充值金额与到账金额倍率可修改

### ISSUE THREAD

**Issue by splendidwrx** [Anankke/SSPanel-Uim#882]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
The feature you want.

**Solution**
If you have some solution about this issue, type it here.

**Addition**
Additional context here.
提一个小建议，实际充值金额与到账金额比率可修改，这样子感觉方便做活动。。就像充100可设置到账120，感觉比优惠券方便。

**Comment by NimaQu** [comment]
@splendidwrx 数据库加 trigger

**Comment by nick0425** [comment]
這跟打折又什麼不一樣嗎?

**Comment by daihao18** [comment]
@nick0425 当然不一样了，如果有人设置余额提现，还可以拿来褥羊毛

**Comment by nick0425** [comment]
@daihao18  應該沒有這麼笨的老闆吧!!

**Comment by daihao18** [comment]
@nick0425 哈哈哈，说说而已。优惠券好控制，灵活。充值比例可控性低一些。

**Comment by splendidwrx** [comment]
但是全站优惠的时候真的是充值比率可修改比较方便，（主要我机场不支持提现哈哈哈）
