### ISSUE TITLE
问一个问题

### ISSUE THREAD

**Issue by Redbeanw44602** [Anankke/SSPanel-Uim#883]
抱歉破坏了格式，但这三个项我真的猜不透什么意思。
![1](https://user-images.githubusercontent.com/29711228/69903119-990b4780-13d0-11ea-91d9-c7f56902c896.png)
这个是用来重置用户流量的吗？如果**用户购买该套餐，30天后他的流量重置为0**。该如何配置呢？谢谢大佬！

**Comment by Jie1998** [comment]
那你就不要配置，傻屌

**Comment by Anankke** [comment]
Closed
