### ISSUE TITLE
git full升级到master最新出现的问题

### ISSUE THREAD

**Issue by JusufUs** [Anankke/SSPanel-Uim#887]
检查file: /www/wwwroot/XXX/composer.phar该文件存在，是最新的

开始升级composer依赖...
Could not open input file: /www/wwwroot/XXX/composer.phar
Could not open input file: /www/wwwroot/XXX/composer.phar
升级composer依赖结束，请自行根据上方输出确认是否升级成功

然后手动执行
php composer.phar selfupdate
依然报错
Could not open input file: composer.phar

**Comment by du5** [comment]
@JusufUs 50
