### ISSUE TITLE
[BUG] “今日已用”似乎无法归到“过去已用”

### ISSUE THREAD

**Issue by Redbeanw44602** [Anankke/SSPanel-Uim#888]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub.

**Environment 环境**
php7.2 debian9.9 bt

**Commit**
当然是最新

**Bug**
![2](https://user-images.githubusercontent.com/29711228/70371211-a3b36880-190b-11ea-8f2c-ffc076a4c80f.png)
如图所示，今日已用的流量永远是今日已用。零点后依然是这个数值，不能被归到“过去已用”

**Reproduce**
添加xGB流量，然后正常用，“今日已用”正常计数。零点后不归到“过去已用”中

**Comment by PYniang** [comment]
@Redbeanw44602 恁 自 己 定 時 任 務 加 了 ?

**Comment by Redbeanw44602** [comment]
啊！好像少了个dailyjob！感谢提醒
