### ISSUE TITLE
[BUG]邀请人账户不记录被邀请者信息，也不到账返利

### ISSUE THREAD

**Issue by Redbeanw44602** [Anankke/SSPanel-Uim#889]
我又来提Bug了，这次一定是真Bug
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。

**Environment 环境**
Debian9 php7.3 nginx1.17

**Commit**
newest

**Bug**
邀请链接使用后不给邀请人计数，其他邀请赠送机制均正常。（计划任务都有，php配置都正确，伪静态也配置正确）
![1](https://user-images.githubusercontent.com/29711228/70371447-2d643580-190e-11ea-8184-b3b42166c422.png)
同时，被邀请人获赠的金额和流量也全部正常

**Reproduce**
1.进入邀请链接...https://x.xx.xxx/auth/register?code=xxxx
2.链接自动变为https://x.xx.xxx/auth/register
3.填信息，注册成功
4.到账邀请赠送的金额和流量
5.返回邀请人账户，邀请链接可用次数减少，其他不变

演示站爆了

**Comment by regendsoh** [comment]
@Redbeanw44602 要是我说就你这个问题呢。

**Comment by regendsoh** [comment]
@Redbeanw44602 就你有*

**Comment by Vincent-Chau** [comment]
@Redbeanw44602 给👴整笑了

**Comment by regendsoh** [comment]
@Redbeanw44602 @anankke 有人说你演示站爆了 你要不要爆了他

**Comment by Redbeanw44602** [comment]
> 
> 
> @Redbeanw44602 @Anankke 有人说你演示站爆了 你要不要爆了他

![3](https://user-images.githubusercontent.com/29711228/70371610-36560680-1910-11ea-9dc1-7c634f04d0f5.png)
楼上这位*请您睁大眼睛，难道这是我的问题咯？
欢迎来爆我的站

**Comment by du5** [comment]
@Redbeanw44602 这是问题？

**Comment by JusufUs** [comment]
目前我观察的现象是，邀请后=邀请成功，如果被邀请人不购买就不会有邀请记录。其实应该是显示XXX被邀请才对。。

**Comment by SakuraSa233** [comment]
返利记录只会在被邀请者实际购买时才会被添加，目前逻辑上并没有问题。

**Comment by SakuraSa233** [comment]
@regendsoh @Vincent-Chau @Redbeanw44602 
请勿在 issue 中发送于本 issue 无关的内容。(Warn: 1/1)

**Comment by Redbeanw44602** [comment]
> 返利记录只会在被邀请者实际购买时才会被添加，目前逻辑上并没有问题。

原来是这样！谢谢!
