### ISSUE TITLE
Demo站似乎挂了

### ISSUE THREAD

**Issue by ChickenSeller** [Anankke/SSPanel-Uim#890]
访问[](https://sspanel.host/)显示如下页面

![image](https://user-images.githubusercontent.com/5331336/70378752-8ca26400-1967-11ea-822c-22042fb566f0.png)

**Comment by NimaQu** [comment]
@ChickenSeller 断电迁移 db nginx 挂了

**Comment by NimaQu** [comment]
有时间再修
