### ISSUE TITLE
单端口用iptables转发没法获取真实ip。。导致IP连接数限制失效

### ISSUE THREAD

**Issue by splendidwrx** [Anankke/SSPanel-Uim#891]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
单端口用iptables转发没法获取真实ip。。导致IP连接数限制失效
**Solution**
希望以后能支持面板层面的单端口中转

**Addition**
Additional context here.

**Comment by PYniang** [comment]
@splendidwrx 建議radius重構

**Comment by du5** [comment]
@splendidwrx 建议多多学习 iptables 与 route 怎么获取源IP

**Comment by Anankke** [comment]
Closed
