### ISSUE TITLE
[BUG] php 7.4 issue

### ISSUE THREAD

**Issue by NimaQu** [Anankke/SSPanel-Uim#892]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

`nginx version: nginx/1.17.6`

`mysql  Ver 8.0.18 for Linux on x86_64 (MySQL Community Server - GPL)`

```
PHP 7.4.0 (cli) (built: Nov 28 2019 07:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies
```

**Commit**
commit f9284e64244258f923b4169cc467bc72513e7332

**Bug**

无法运行

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
装上 php7.4

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
let it works
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
```
2019/12/08 04:08:50 [error] 28465#28465: *4688 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  date_default_timezone_set(): Timezone ID '' is invalid in /var/www/sspanel.host/app/Services/Boot.php on line 23PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/sspanel.host/app/Services/Config.php on line 10PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Unsupported driver [] in /var/www/sspanel.host/vendor/illuminate/database/Connectors/ConnectionFactory.php:226
Stack trace:
#0 /var/www/sspanel.host/vendor/illuminate/database/Connectors/ConnectionFactory.php(64): Illuminate\Database\Connectors\ConnectionFactory->
```
**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by SakuraSa233** [comment]
Close for it works with 22ff439.
