### ISSUE TITLE
[BUG] 配置 单端口多用户 失败

### ISSUE THREAD

**Issue by ssrlive** [Anankke/SSPanel-Uim#894]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
- Debian 4.19.67
- PHP 7.3.11-1
- mysql  Ver 8.0.17-8

**Commit**

https://github.com/Anankke/SSPanel-Uim/commit/f9284e64244258f923b4169cc467bc72513e7332

**Bug**
配置 单端口多用户 失败。新建一个用户，充了很多钱，然后设置。 新建一个节点，然后设置。从管理模式切换到用户模式查看节点。哦豁——
但是，但是。失败、失败、一直失败。

请检查。如果这个问题解决了。我会将 [ssrot](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki) 集成进 SSPanel-Uim 的后端。

![image](https://user-images.githubusercontent.com/30760636/70797739-0dd27e80-1de0-11ea-9c48-a0155224774a.png)

![image](https://user-images.githubusercontent.com/30760636/70797326-3efe7f00-1ddf-11ea-8231-a9d6c93faab2.png)

**Comment by regendsoh** [comment]
@ssrlive 请将节点类型设为 只启用单端口多用户。

**Comment by ssrlive** [comment]
在 “编辑节点” 页面，“单端口多用户启用” 选择 “只启用单端口多用户” 并不改变结果，问题依旧。

**Comment by Anankke** [comment]
请勿集成，谢谢
Closed

**Comment by aipeach** [comment]
@ssrlive 是不是你承载用户低于普通节点等级导致看不到节点

**Comment by ssrlive** [comment]
在哪里设置？

**Comment by imiaoo** [comment]
> 在哪里设置？

用户编辑-用户等级99

**Comment by ssrlive** [comment]
将用户等级该成99，并将用户设置成管理员后。问题依旧。且 用户等级保留不住。下次打开还是 0.

![image](https://user-images.githubusercontent.com/30760636/70798544-2cd21000-1de2-11ea-881f-7b9f8fb50052.png)
