### ISSUE TITLE
[BUG]这个BUG上个月反馈过，今天测试了一下还是有问题，系统centos7

### ISSUE THREAD

**Issue by maxwellhouse102** [Anankke/SSPanel-Uim#896]
Invalid catalog name: 1046 No database selected in /www/wwwroot/111/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /www/wwwroot/111/vendor/illuminate/database/Connection.php(333): PDO->prepare('select * from `...')
#1 /www/wwwroot/111/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 /www/wwwroot/111/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 /www/wwwroot/111/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#4 /www/wwwroot/111/vendor/illuminate/database/Query/Builder.php(1610): Illuminate\Database\Connection->select('select * from `...', Array, true)
#5 /www/wwwroot/111/vendor/illuminate/database/Query/Builder.php(1596): Illuminate\D in /www/wwwroot/111/vendor/illuminate/database/Connection.php on line 729

Fatal error: Uncaught PDOException: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected in /www/wwwroot/111/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /www/wwwroot/111/vendor/illuminate/database/Connection.php(333): PDO->prepare('select * from `...')
#1 /www/wwwroot/111/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 /www/wwwroot/111/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 /www/wwwroot/111/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#4 /www/wwwroot/111/vendor/illuminate/database/Query/Builder.php(1610): Illuminate\Database\Connection->select('select * from `...', Array, true)
#5 /www/wwwroot/111/vendor/illuminate/database/Query/Builder.php(1596): Illuminate\D in /www/wwwroot/111/vendor/illuminate/database/Connection.php on line 729

**Comment by JusufUs** [comment]
我今天竟然也碰到这个问题了。楼主怎么解决的？。。
