### ISSUE TITLE
[BUG] ’func/ping?‘路由有BUG，跟fanvinga/docker-ssrmu后端对接不上

### ISSUE THREAD

**Issue by Bill0412** [Anankke/SSPanel-Uim#898]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
与Docker版本后端fanvinga/docker-ssrmu搭配使用

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
1 parent 22ff439 commit 2e973442fa650245148738bb3088e8dfcba92ccf

**Bug**
The bug information. 请描述你遇到的 Bug。
前端用https://blog.anank.ke/w/SSPanel_with_LNMP教程，后端用fanvinga/docker-ssrmu，在docker运行的log里会出现，应该是最近的一次route.php更改后出现的问题。
目前的版本里面的http请求的参数里少了一个问号（❓）

2019-12-30 04:34:33 ERROR    web_transfer.py:672 Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 23, in getApi
    timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '<my_server_ip>/mod_mu/func/ping': No schema supplied. Perhaps you meant http://<my_server_ip>/mod_mu/func/ping?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 660, in thread_db
    ping = webapi.getApi('func/ping')
  File "/root/shadowsocks/webapi_utils.py", line 39, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
如上述，用HyperApp的Docker后端

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
http请求应当变为
http://<my_server_ip>/mod_mu/func/ping?key=xxx

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。
关于ping的接口：
1. https://blog.fly2x.cn/archives/36/

**Comment by du5** [comment]
@Bill0412 100

**Comment by Incisakura** [comment]
这是你Docker所运行服务端的问题，并且你也应该注意到了服务端的报错`Invalid URL`。

Close for off-topic.

**Comment by Bill0412** [comment]
我1个月前是行的，那应该是这里的接口变了对吧

**Comment by Bill0412** [comment]
> 这是你Docker所运行服务端的问题，并且你也应该注意到了服务端的报错`Invalid URL`。
> 
> Close for off-topic.

我1个月前是行的，那应该是这里的接口变了对吧

**Comment by Incisakura** [comment]
就算 Panel 的接口变化，服务端也不会给出类似提示。
请细读服务端错误提示自行处理。

以上，本 issue 不再受理。

**Comment by Anankke** [comment]
@Bill0412 非官方，不提供任何支持

**Comment by topjohncian** [comment]
自己make的镜像
topjohncian/cian-ssrmu
