### ISSUE TITLE
[Feature Request]申请添加自助修改邮箱、用户名，为用户中心返利记录添加返利时间

### ISSUE THREAD

**Issue by jianpanxia666** [Anankke/SSPanel-Uim#902]
![嘤嘤嘤](https://user-images.githubusercontent.com/55895771/72042097-6108f580-32e8-11ea-9267-3ba8381cf6b6.png)

------------

![嘤嘤嘤嘤](https://user-images.githubusercontent.com/55895771/72042099-636b4f80-32e8-11ea-85bd-8cf23ca1ca76.png)

**Comment by Scholar-m** [comment]
@Anankke 定制功能，请联系anankke加钱

**Comment by Anankke** [comment]
8接

**Comment by Scholar-m** [comment]
哦吼。那就没法了

**Comment by M1Screw** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/c1e71397f5e9b0a9417cbdfab10a161f0a4c8fda

**Comment by M1Screw** [comment]
自助修改用戶名
https://github.com/Anankke/SSPanel-Uim/commit/3ee25a2255c9ecd45eab46e549cc34e2969ee3a7

**Comment by M1Screw** [comment]
用户中心返利记录添加返利时间
https://github.com/Anankke/SSPanel-Uim/commit/16ed4076ae77786fcb19f2aeab2b9e82fb619d39
