### ISSUE TITLE
[Feature Request] 9012年，注册还会通过邮箱么？

### ISSUE THREAD

**Issue by safepayment** [Anankke/SSPanel-Uim#903]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x ] I certify that I have read project Wiki and other issue may related to this one.

1969年世界上第一封邮件，随着50年的科技进步，邮件作为一个入口方式以及略显沉重。为了获取验证码，需要点开登录邮箱，甚至需要翻阅垃圾箱。而通过FB/Twitter/微信等一键登录已经越来越普及。这些产品的优化都可使用户进入的门槛更低。

而且邮箱和密码的方式稍有不慎，很容易泄露用户的隐私。

**Feature**
一键通过TG注册以及登录。

目前的操作，对于TG用户很繁琐。用户通过邮箱注册后，绑定TG然后以及输入验证码。而这几个步骤应该可以一键完成。

**Solution**
如果用户有TG，点击网站一个连接，直接登录并且跳转进入用户面板。

对于所有TG用户来说，仅一个“登录”按钮即可，没有必要刻意区分注册和登录。如果没有注册，点击帮他注册一个新账户即可。

**Addition**
不知道是否有什么系统依赖与用户邮箱，除了邮箱群发消息。
（邮件群发消息可以通过消息渠道发送）

**Comment by daihao18** [comment]
@safepayment welcome pr

**Comment by Anankke** [comment]
早就有，建议 pr 改进

**Comment by safepayment** [comment]
https://github.com/Anankke/SSPanel-Uim/pull/920
