### ISSUE TITLE
[BUG]用户在套餐有效期内购买2个季度套餐，套餐的流量重置会错乱。

### ISSUE THREAD

**Issue by yangyzp** [Anankke/SSPanel-Uim#907]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
centos 7.5
php 7.1
mysql 5.7

**Commit**
Commits on Jan 10, 2020

**Bug**
面板的设置：“$System_Config['enable_bought_extend']='false';	        //购买时是否延长等级期限（同等级配套）”

举例说明这个bug会更好：
用户A在1月1日购买季度套餐A（套餐内容：等级有效期90天，每30天重置流量为40G）；然后用户又在2月10日购买了季度套餐B（套餐内容：等级有效期90天，每30天重置流量为50G）。
此时用户的等级有效期到5月10日，按理应该只按套餐B的重置计划来重置每月的流量。
但是，到了3月1日的时候，用户的流量会重置为40G（套餐A的重置计划还在生效。）

bug：既然设置了购买套餐不延长等级时间，套餐的重置计划应该取后者，不应该2个套餐的重置计划混淆在一起。

（抱歉，修改一下，前面反馈举例子的时候，时间弄错了~~）
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by regendsoh** [comment]
@yangyzp 改一下，A和B等级时长120天
1. 用户1月1买套餐A，等级期限到4月1(假设)
2. 用户2月1流量重置为40G
3. 用户2月10买套餐B，等级期限到8月1(假设)
问题：用户3月1和10，4月10，5月10流量将会重置 (5月10后不重置)

问题逻辑出在如果你让用户购买低级配套再买高级配套叠加后，重置只要等级期限还没到就跟着高级配套重置？这会是另外一个bug。

正常情况：A配套和B配套就不应该在同一个等级。这个叠加的功能也不推荐在有设置固定时间重置流量的情况下开启(会出现你说的bug，一部分)。

**Comment by regendsoh** [comment]
突然发现你是说 $System_Config['enable_bought_extend']='false';
那这情况是上古bug 不是我之前的PR （走了走了 我的错

**Comment by yangyzp** [comment]
@regendsoh   对的，这个bug好像存在很久了，我用很早之前的版本也是这情况。

**Comment by laurieryayoi** [comment]
这个周期重置失效的情况只有删除对应ID的商品，但是在数据库强行删除商品会有不可预估的问题
所以现在就是无法覆盖的

**Comment by du5** [comment]
@laurieryayoi 一个月两次呗

**Comment by zwx1231** [comment]
> @yangyzp 改一下，A和B等级时长120天
> 
> 1. 用户1月1买套餐A，等级期限到4月1(假设)
> 2. 用户2月1流量重置为40G
> 3. 用户2月10买套餐B，等级期限到8月1(假设)
>    问题：用户3月1和10，4月10，5月10流量将会重置 (5月10后不重置)
> 
> 问题逻辑出在如果你让用户购买低级配套再买高级配套叠加后，重置只要等级期限还没到就跟着高级配套重置？这会是另外一个bug。
> 
> 正常情况：A配套和B配套就不应该在同一个等级。这个叠加的功能也不推荐在有设置固定时间重置流量的情况下开启(会出现你说的bug，一部分)。

这是因为套餐叠加购买仅延长等级时间。但实际重置计划直接重新按照后购买的套餐来了。所以第一次购买的套餐的等级时间实际等于没有流量的无效时间了。所以不要套餐未到期就重复购买。

针对这个BUG我设想过一个骚操作：
A套餐等级1，月付10，流量50G。
B套餐等级2，年付200，流量每月300G。

操作：购买N次A套餐，增加等级有效期。然后购买套餐B重置流量计划。
那么接下来12+N个月，前12个月每个月300G，后面的N个月是套餐A延长的等级时间，可以使用套餐B最后一个月余下的流量。。。是不是很骚

**Comment by regendsoh** [comment]
@zwx1231 发现特别便宜的机场 小心机场物价局。

**Comment by zwx1231** [comment]
> @zwx1231 发现特别便宜的机场 小心机场物价局。

只是举例子啦。
不过我发现我的$System_Config['enable_bought_extend']
是true。。。 会延长等级时间。
我刚刚的例子里A和B是不同等级，所以不能延长
按理说你开false应该不会延长等级时间了啊

**Comment by zwx1231** [comment]
刚刚测试了一下，开false的情况，同VIP账号级套餐叠加购买已经不延长等级有效期了。
