### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by clatteringmarion** [Anankke/SSPanel-Uim#908]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
系统：CentOS Linux 7.7.1908
PHP：7.3.13
MySQL：5.5.5-10.3.21-MariaDB
面板：Plesk Obsidian 18.0.21

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
f9284e6 / 2019Sep

**Bug**
The bug information. 请描述你遇到的 Bug。
无法设置伪静态 （Plesk Nginx）
访问/auth/login或/auth/register会跳回主界面

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
1. 尝试执行https://blog.anank.ke/w/SSPanel_with_LNMP  0x42并修改Plesk Nginx设置报错 (Duplicate Location)
2. 尝试修改配置为： 
```
if (!-e $request_filename) {
	set $test P;
}
if ($uri !~ ^/(plesk-stat|webstat|webstat-ssl|ftpstat|anon_ftpstat|awstats-icon|internal-nginx-static-location)) {
	set $test "${test}C";
}
if ($test = PC) {
	rewrite ^/(.*)$ /index.php$is_args$args;
}
```
参考Plesk官方提供的WordPress Nginx方法， 导致所有子页面都会跳回主页面... 

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
访问/auth/login或/auth/register应显示相应登录/注册界面

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

其他的下面几步都没问题... 就是伪静态没好进不去登录页面

**Comment by NimaQu** [comment]
@clatteringmarion Plesk 我记得是放弃 apache 代理只用 nginx 弄的

**Comment by clatteringmarion** [comment]
其实总觉得应该是Need Documentation...

**Comment by clatteringmarion** [comment]
@NimaQu Plesk主用的是Apache， 你是说放弃该域名的Nginx代理吗？
（如果是的话请问.htaccess 要咋改捏）

**Comment by du5** [comment]
@clatteringmarion 捏

**Comment by NimaQu** [comment]
![Screenshot_20200111-201340](https://user-images.githubusercontent.com/26685881/72212706-e6d69d80-34ae-11ea-8801-6595afa332b2.jpg)
我是这么弄的

**Comment by clatteringmarion** [comment]
@NimaQu 好的谢谢，我试一下

**Comment by clatteringmarion** [comment]
@NimaQu @du5 关掉Nginx反代果然就好了， 谢谢两位
