### ISSUE TITLE
Sendgrid邮件发件人名称为空

### ISSUE THREAD

**Issue by clatteringmarion** [Anankke/SSPanel-Uim#910]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
目前Sendgrid邮件发件时不会写发件人名称…直接是邮箱地址 。 我看之前issue说是因为某些服务商不支持UTF-8， 但请问是否可以给支持UTF-8的Sendgrid设置发件人名称呢？
同时Sendgrid PHP API使用的是V5版本， 最新版本为V7.4.1， 请问是否可以使用新版本？

**Solution**

**Addition**

**Comment by clatteringmarion** [comment]
@Incisakura 我按template走了吖…（只是回头改代码了…）
@Anankke 麻烦看下我交的那个PR… 刚在手机上改的可能不太对😂

**Comment by du5** [comment]
#881

**Comment by du5** [comment]
#881  已经修正并 pr 但被关闭了

**Comment by clatteringmarion** [comment]
@du5 的确是，但是那个只更改了纯SMTP啊😂
除非Sendgrid.php也走Smtp.php
