### ISSUE TITLE
[Feature Request] 使用AWS SES发送邮件

### ISSUE THREAD

**Issue by clatteringmarion** [Anankke/SSPanel-Uim#912]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
用AWS SES发邮件？

**Solution**
当前文件目录下已经有SES的文件了，不知道能不能用… 想试试看能不能改到能用😂

**Addition**

**Comment by Tai7sy** [comment]
SES有smtp的配置, 可以直接用的啊

**Comment by clatteringmarion** [comment]
@Tai7sy  Sendgrid也可以直接用SMTP啊... 但是用API相对好一点？
