### ISSUE TITLE
很重要的

### ISSUE THREAD

**Issue by 821251775** [Anankke/SSPanel-Uim#914]
无法找到订阅链接，也无法一键订阅，ssr 还有mac上的软件也无法更新订阅地址，很烦，网站上根本找不到订阅地址在哪里，也就意味着如果我之前的不能用了，我虽然交钱但是还是不能用vpn，找不到订阅链接在哪里，而且看见了也点不开。

**Comment by regendsoh** [comment]
@821251775 请你找你机场主 不是来这里。

**Comment by Anankke** [comment]
Closed

**Comment by aipeach** [comment]
@821251775 ？迷惑行为

**Comment by regendsoh** [comment]
@821251775 如果有需要 请提供你机场链接 我们帮你找

**Comment by du5** [comment]
@regendsoh 刺激奥
