### ISSUE TITLE
 [error] 9796#9796: *12582 FastCGI sent in stderr: "PHP message: PHP Notice: Undefined variable: debug

### ISSUE THREAD

**Issue by Bill0412** [Anankke/SSPanel-Uim#915]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
OS: Debain 9
PHP: 7.3
MySQL: Ver 8.0.18-9 for debian-linux-gnu on x86_64 (Percona Server (GPL), Release '9', Revision '53e606f')
Nginx:  nginx/1.17.5

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
f9284e6

**Bug**
The bug information. 请描述你遇到的 Bug。
打开 <网站地址>/user时会遇到 502 bad gateway，排查之后发现好像时PHP CGI创建线程数过多，导致一些请求无法处理，查看/var/log/nginx/error.log 后发现有很多很多如下的错误：
2020/01/13 04:24:38 [error] 9796#9796: *12582 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: debug in /var/www/<site_name>/config/routes.php on line 39" while reading response header from upstream, client: <node_name>, server: <server_name>, request: "GET /mod_mu/func/relay_rules?node_id=xxx&key=xxxxxx HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "<site_name>"

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
按照https://blog.anank.ke/w/SSPanel_with_LNMP 部署后添加节点，然后查看/var/log/nginx/error.log

**Expected behavior**
What you expected to happen. 请描述你预期的行为。
declare $debug before using.

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
建议升级 dev 尝试

**Comment by Anankke** [comment]
@Incisakura 在？背锅

**Comment by Bill0412** [comment]
我在routes.php文件的上面声明了一下$debug就解决问题了。
config/routes.php:
`$debug = false;`

**Comment by Anankke** [comment]
@Anankke

**Comment by Anankke** [comment]
妹有解决根本问题

**Comment by xcxnig** [comment]
其实还有
Undefined index: mu
Undefined index: date_unix

**Comment by Incisakura** [comment]
Issues in `master`. Please try to update to 2e97344 to fix.
