### ISSUE TITLE
[BUG]续费失败等通知邮件无限发送

### ISSUE THREAD

**Issue by xcxnig** [Anankke/SSPanel-Uim#917]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

nginx/1.14.2
mysql  Ver 8.0.18-9 for debian
PHP 7.3.13-1

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

commit 4b3985a170365c5710de0a74a141b45a106bb6a8

**Bug**
The bug information. 请描述你遇到的 Bug。

Job.php 中
有关于checkjob任务会导致无限发送邮件轰炸用户的bug

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

php xcat checkjob

![image.png](https://i.loli.net/2020/01/14/IN1jJ4TMotHFGRQ.png)
只要续费失败就发送一封邮件，但是这是在checkjob里面，1分钟发一次，100%会被邮件轰炸的

![image.png](https://i.loli.net/2020/01/14/KPnpbtHeaS74wDd.png)
还有这个过期检测文件，由于改为数据库字段方式存储，不会再生成此文件，只要用户过期就会无限轰炸，，同理 一分钟一次，，

总结：一个套餐过期+续费失败 的用户 每分钟至少收到两封邮件

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

需要增加邮件已通知的字段或更改邮件通知的判断方式

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by Anankke** [comment]
草，你写的是个🔨，，， @Incisakura 
带 bug

**Comment by Incisakura** [comment]
Import sql/job_clean.sql and run utils/job_clean.php.

**Comment by Anankke** [comment]
你得写文档啊

**Comment by xcxnig** [comment]
尚未解决checkjob中  续费失败的邮件发送判断逻辑

![image.png](https://i.loli.net/2020/01/15/qwixsYZGb76Odmt.png)

方案一 简单但是不文明 标记为已经续费
```
            elseif ($bought->is_renewed == false) {
                $subject = Config::get('appName') . '-续费失败';
                $to = $user->email;
                $text = '您好，系统为您自动续费商品名：' . $shop->name . ',金额:' . $shop->price . ' 元 时，发现您余额不足，请及时充值。充值后请稍等系统便会自动为您续费。';
                try {
                    Mail::send($to, $subject, 'news/warn.tpl', [
                        'user' => $user,
                        'text' => $text
                    ]);
                } catch (Exception $e) {
                    echo $e->getMessage();
                }
                $bought->is_renewed = true;
                $bought->save();
            }
```
方案二 增加一个字段 ( 反正 bought字段不多
例如说 is_renew_noticed

**Comment by lzmfor** [comment]
2020.02.21 最新dev版

存在类似问题：节点上线邮件无限发送至管理员

**Comment by laurieryayoi** [comment]
> 2020.02.21 最新dev版
> 
> 存在类似问题：节点上线邮件无限发送至管理员

请确认你已经按照 [#918](https://github.com/Anankke/SSPanel-Uim/issues/918) 操作
