### ISSUE TITLE
[BUG]泡芙云无法重置订阅连接！

### ISSUE THREAD

**Issue by Caijialinxx** [Anankke/SSPanel-Uim#922]
1. 打开 paofuyun.vip 后，左边个人设置下拉列表点击无反应。
2. 在检查元素后找到下拉列表的网址终于进到 https://www.paofuyun.vip/user/edit ，但是重置订阅链接的那个红按钮点了又没反应，那么我想请问一下你们公告中⬇️说的要更新订阅使用应该如何去更新？我在客户端里更新也还是不能顺利爬梯子..

> 重要公告
> 1月24日所有节点加密方式变更，所有用户都需要更新订阅使用，旧订阅信息以及不再有效

跪求解答谢谢！

**Comment by aipeach** [comment]
@Caijialinxx ？？？

**Comment by Colinwood11** [comment]
@Caijialinxx ？？？  你是来推广的还是另有目的？？    这里只是这个公共项目的源代码存放。
