### ISSUE TITLE
如何重新启用 crisp ？ 新版本：（使用 mylivechat 取代 crisp ） 

### ISSUE THREAD

**Issue by Wl56650550** [Anankke/SSPanel-Uim#927]
配置文件.config.php 我已添加：

$_ENV['enable_crisp'] = true;		
$_ENV['crisp_id'] = 'xxxxxxxxxxxxx';		

/resources/views/material 目录增加文件：crisp.tpl
crisp.tpl内容为：

<literal><script type="text/javascript"> window.$crisp=[];window.CRISP_WEBSITE_ID="{$config["crisp_id"]}";$crisp.push(["set", "user:email", "{$user->email}"]);(function(){ d=document;s=d.createElement("script"); s.src="https://client.crisp.chat/l.js"; s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})(); </script></literal>

/resources/views/material/user 目录修改了 main.tpl 文件
增加：

{if $config["enable_crisp"] == 'true'}{include file='crisp.tpl'}{/if}

测试结果：无法显示crisp
现用sspanel版本为目前最新版本

**Comment by aiastia** [comment]
![C5600CC8-1673-4F2D-B461-66D238D67F54](https://user-images.githubusercontent.com/19776350/74085974-9f492e80-4ab9-11ea-9782-0dd6797ea8a1.jpeg)
 可能需要修改这些文件（ 开倒车🚗

**Comment by aipeach** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/248d6078378a38e4cb86159ada5ad62b0046ab7d

**Comment by Wl56650550** [comment]
谢谢你们，已经解决！！！
