### ISSUE TITLE
[Feature Request]希望能够添加clash的快速配置方式

### ISSUE THREAD

**Issue by PandaTAT** [Anankke/SSPanel-Uim#929]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
希望能够添加clash的快速配置方式，好像现在很多都开始用Clash了

[![1IawX8.md.png](https://s2.ax1x.com/2020/02/10/1IawX8.md.png)](https://imgchr.com/i/1IawX8)

**Comment by topjohncian** [comment]
GeekQu仓库有类似功能

在 2020年2月11日星期二，PandaTAT <notifications@github.com> 写道：

**Comment by narakuzi** [comment]
@topjohncian 这个功能可以自己手动修改面板添加，具体教程建议谷歌一下

**Comment by YPandaTAT** [comment]
@narakuzi 目前关于clash的教程好像还比较少，我当时也想自己改来着

**Comment by narakuzi** [comment]
@YPandaTAT 指路一个比较详细的教程https://golby.cc/index.php/262

**Comment by YPandaTAT** [comment]
似乎只能v2？

**Comment by topjohncian** [comment]
@narakuzi 会合并到Anankke上游 等

**Comment by v2rayv3** [comment]
已经添加，可以关闭issue
