### ISSUE TITLE
[BUG]买了心阶套餐，订阅链接链接不上啊为！

### ISSUE THREAD

**Issue by lizy0329** [Anankke/SSPanel-Uim#934]
订阅链接：https://api.xinjie.eu.org/link/6gk69qxjqbEKoSeI?sub=3

工单没人理啊为！

![WeChat Work Screenshot_20200221115633.png](https://i.loli.net/2020/02/21/vXsNd5J3761EaWh.png)

**Comment by du5** [comment]
@lizy0329 6666666
