### ISSUE TITLE
你好，我的前后端都对接好了，显示绿色白云图标，但是连接客户端就是上不去

### ISSUE THREAD

**Issue by yecsama** [Anankke/SSPanel-Uim#935]
你好，我的前后端都对接好了，显示绿色白云图标，但是连接客户端就是上不去；

打开windows 客户端连接测试 一直是超时的，但是在前端里面查看就是绿色的图标，一切显示正常，但就是上不去网。想问问 这是前端没配置好，还是后端有问题？
![image](https://user-images.githubusercontent.com/33511450/75008043-eec42d00-54b1-11ea-9235-29b8260925d7.png)

**Comment by Anankke** [comment]
防 火 墙
Closed

**Comment by yecsama** [comment]
如果是防火墙的话，我之前可以用，突然就不能用了。
然后我重新搭建再也不能用了。
防火墙的话是后端防火墙问题对吧？ 我也关闭防火墙了啊。
大佬还有别的可能吗？




    


在2020年02月21日 13:57，Anankke 写道： Closed #935.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Anankke/SSPanel-Uim/issues/935?email_source=notifications\u0026email_token=AH7VQGSEDICHZ377HH6ILILRD5UMLA5CNFSM4KY4Y6EKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWZM434Y#event-3059338739",
"url": "https://github.com/Anankke/SSPanel-Uim/issues/935?email_source=notifications\u0026email_token=AH7VQGSEDICHZ377HH6ILILRD5UMLA5CNFSM4KY4Y6EKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOWZM434Y#event-3059338739",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Anankke** [comment]
被墙了，下一个

**Comment by yecsama** [comment]
ping的通的，




    


在2020年02月21日 14:08，Anankke 写道： 被墙了，下一个

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Anankke/SSPanel-Uim/issues/935?email_source=notifications\u0026email_token=AH7VQGTDAYYM4QXWHAPMBODRD5VT7A5CNFSM4KY4Y6EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMRUDXI#issuecomment-589513181",
"url": "https://github.com/Anankke/SSPanel-Uim/issues/935?email_source=notifications\u0026email_token=AH7VQGTDAYYM4QXWHAPMBODRD5VT7A5CNFSM4KY4Y6EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMRUDXI#issuecomment-589513181",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by du5** [comment]
https://check-host.net/check-udp
https://torch.njs.app/
