### ISSUE TITLE
[BUG]GFW 检测功能失效

### ISSUE THREAD

**Issue by befantasy** [Anankke/SSPanel-Uim#936]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [ ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [ ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
The bug information. 请描述你遇到的 Bug。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

.config.php文件当中的以下API url已失效。是否有替代方案？
$System_Config['detect_gfw_url']='https://cn-qz-tcping.torch.njs.app/{ip}/{port}';	//检测节点是否被gfw墙了的API的URL

**Comment by KLDGodY** [comment]
三个要求（好像不是这么叫，叫前提）都不看就来issues？

**Comment by regendsoh** [comment]
https://ping.regend.xyz/{ip}/{port}

**Comment by befantasy** [comment]
> 三个要求（好像不是这么叫，叫前提）都不看就来issues？

你这样的回复，无聊不无聊？比法无效的issues还浪费资源。

**Comment by befantasy** [comment]
> [https://ping.regend.xyz/{ip}/{port}](https://ping.regend.xyz/%7Bip%7D/%7Bport%7D)

十分感谢！ 测试可用。

**Comment by KLDGodY** [comment]
> > 三个要求（好像不是这么叫，叫前提）都不看就来issues？
> 
> 你这样的回复，无聊不无聊？比法无效的issues还浪费资源。

没有issues怎么有回复，，，

**Comment by befantasy** [comment]
> > > 三个要求（好像不是这么叫，叫前提）都不看就来issues？
> > 
> > 
> > 你这样的回复，无聊不无聊？比法无效的issues还浪费资源。
> 
> 没有issues怎么有回复，，，

你要认为没有那就少在这废话浪费带宽和计算资源，吃饱了撑的。

实际情况就是当前dev和master里面的gfw检测api url失效。open issues里没有相关问题，我怎么就不能发issue？
closed issues我确实漏搜了，惯性思维只查了open issue。没想到closed issue有，但作者没合并PR。

**Comment by Anankke** [comment]
别打力别打力
![IMG_20200218_095025_637](https://user-images.githubusercontent.com/40639066/75229525-16501980-5780-11ea-8079-c7a030208407.jpg)

**Comment by regendsoh** [comment]
> > > > 三个要求（好像不是这么叫，叫前提）都不看就来issues？
> > > 
> > > 
> > > 你这样的回复，无聊不无聊？比法无效的issues还浪费资源。
> > 
> > 
> > 没有issues怎么有回复，，，
> 
> 你要认为没有那就少在这废话浪费带宽和计算资源，吃饱了撑的。
> 
> 实际情况就是当前dev和master里面的gfw检测api url失效。open issues里没有相关问题，我怎么就不能发issue？
> closed issues我确实漏搜了，惯性思维只查了open issue。没想到closed issue有，但作者没合并PR。

我不能保证SLA 所以作者没让合并

**Comment by befantasy** [comment]
> > > > > 三个要求（好像不是这么叫，叫前提）都不看就来issues？
> > > > 
> > > > 
> > > > 你这样的回复，无聊不无聊？比法无效的issues还浪费资源。
> > > 
> > > 
> > > 没有issues怎么有回复，，，
> > 
> > 
> > 你要认为没有那就少在这废话浪费带宽和计算资源，吃饱了撑的。
> > 实际情况就是当前dev和master里面的gfw检测api url失效。open issues里没有相关问题，我怎么就不能发issue？
> > closed issues我确实漏搜了，惯性思维只查了open issue。没想到closed issue有，但作者没合并PR。
> 
> 我不能保证SLA 所以作者没让合并

嗯，我刚才搜索看到了。 是我的惯性思维导致疏忽。我的问题。

**Comment by Colinwood11** [comment]
@Anankke ananke也太可爱了叭

**Comment by KLDGodY** [comment]
> > > > 三个要求（好像不是这么叫，叫前提）都不看就来issues？
> > > 
> > > 
> > > 你这样的回复，无聊不无聊？比法无效的issues还浪费资源。
> > 
> > 
> > 没有issues怎么有回复，，，
> 
> 你要认为没有那就少在这废话浪费带宽和计算资源，吃饱了撑的。
> 
> 实际情况就是当前dev和master里面的gfw检测api url失效。open issues里没有相关问题，我怎么就不能发issue？
> closed issues我确实漏搜了，惯性思维只查了open issue。没想到closed issue有，但作者没合并PR。

https://ae01.alicdn.com/kf/U8c1e2d6dd44643d4affd986f5b0a2344j.jpg
都不同意恁提恁🐴的问题

**Comment by KLDGodY** [comment]
> > > > 三个要求（好像不是这么叫，叫前提）都不看就来issues？
> > > 
> > > 
> > > 你这样的回复，无聊不无聊？比法无效的issues还浪费资源。
> > 
> > 
> > 没有issues怎么有回复，，，
> 
> 你要认为没有那就少在这废话浪费带宽和计算资源，吃饱了撑的。
> 
> 实际情况就是当前dev和master里面的gfw检测api url失效。open issues里没有相关问题，我怎么就不能发issue？
> closed issues我确实漏搜了，惯性思维只查了open issue。没想到closed issue有，但作者没合并PR。

![IMG_20200218_095025_637](https://ae01.alicdn.com/kf/U8c1e2d6dd44643d4affd986f5b0a2344j.jpg)
都不同意恁提恁🐴的问题

**Comment by befantasy** [comment]
你这sb真是吃饱了撑的没事做。你他马的回尼玛的回？ 怎么会有你这种沙雕。

**Comment by Anankke** [comment]
Blocked.
