### ISSUE TITLE
[BUG]财务报表功能报错

### ISSUE THREAD

**Issue by befantasy** [Anankke/SSPanel-Uim#937]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [ x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [ x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

OS: Centos 7
MySQL: 5.6
PHP: 7.3

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

master

**Bug**
The bug information. 请描述你遇到的 Bug。
更新财务报表是有以下报错。根据报错信息放狗搜了一下说是PHP 7.x对取值的验证更加严格。。。但不懂代码，没有找到解决方案。
> [root]# php xcat sendFinanceMail_day
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /www/wwwroot/xxx/vendor/esdeathlove/datatables/src/Datatables.php on line 213
Send offline mail to user: 1[root@vultr linz.ltd]# php xcat sendFinanceMail_week
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /www/wwwroot/xxx/vendor/esdeathlove/datatables/src/Datatables.php on line 213
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /www/wwwroot/xxx/vendor/esdeathlove/datatables/src/Datatables.php on line 213

根据提示看了一下Datatables.php

if (count($this->edit) > 0)是213行。

```
    public function generate($json = true)
    {
        $this->execute();
        $formatted_data = [];

        foreach ($this->data as $key => $row)
        {
            // editing columns..
            if (count($this->edit) > 0)
            {
                foreach ($this->edit as $edit_column => $closure)
                {
                    $row[ $edit_column ] = $this->exec_replace($closure, $row);
                }
            }

            $formatted_data[] = $row;
        }

        $response['draw'] = $this->input('draw');
        $response['recordsTotal'] = $this->recordstotal;
        $response['recordsFiltered'] = $this->recordsfiltered;
        $response['data'] = $formatted_data;

        return $this->response($response, $json);
    }
```

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by befantasy** [comment]
不懂代码，顺藤摸瓜摸索了一下，好像解决了。
在这里没找到报错的文件Datatables.php。根据路径名搜了搜，似乎是用了这个php库，https://github.com/n1crack/datatables
跟着去那里查看了Datatables.php的history，在某个commit comment里找到了add php 7.2 support的注释。看了一下，改动了以下代码

> if (count($this->add) > 0) 
> 替换成
> if (null !== $this->add && count($this->add) > 0)

再次运行 php xcat sendFinanceMail_day，报错消失。

**Comment by befantasy** [comment]
更新一下，这样修改后会造成管理界面的节点显示异常。。。
还得继续寻求解决方案。

**Comment by DANVEZ** [comment]
我也有同样的问题，不过不是很影响使用

**Comment by pplulee** [comment]
可以将213行改为
`if (count((array)$this->edit) > 0)`
报错消失，可正常执行

**Comment by befantasy** [comment]
> 可以将213行改为
> `if (count((array)$this->edit) > 0)`
> 报错消失，可正常执行

谢谢，搞定。
