### ISSUE TITLE
[TG机器人配置里开启每日统计报表]

### ISSUE THREAD

**Issue by ANHR0** [Anankke/SSPanel-Uim#940]
这两个tg机器人汇报没法在配置文件里开启,主要是我也不懂怎么手动开启，希望也能先给出手动开启的方法，谢谢大佬

小哥哥小姐姐，数据库被清理了，感觉身体被掏空了呢~

各位老爷少奶奶，我来为大家报告一下系统今天的运行状况哈~
今日签到人数:
今日使用总流量:
晚安~

**Comment by KLDGodY** [comment]
~~似乎配置就能开启了？~~反正我是这样：）

**Comment by laurieryayoi** [comment]
dev请参考 [#918](https://github.com/Anankke/SSPanel-Uim/issues/918)

**Comment by ANHR0** [comment]
> ~~似乎配置能够开启了？~~反正我是这样：）

没有吧，只有这两个主动配置吧？难道在别的地方开启？求解
$_ENV['finance_public'] = true;			//财务报告是否向群公开
$_ENV['enable_welcome_message'] = true;	//机器人发送欢迎消息

**Comment by KLDGodY** [comment]
> > ~~似乎配置能够开启了？~~反正我是这样：）
> 
> 没有吧，只有这两个主动配置吧？难道在别的地方开启？求解
> $_ENV['finance_public'] = true; //财务报告是否向群公开
> $_ENV['enable_welcome_message'] = true; //机器人发送欢迎消息

两个我都事开的

**Comment by ANHR0** [comment]
> > > ~~似乎配置能够开启了？~~反正我是这样：）
> > 
> > 
> > 没有吧，只有这两个主动配置吧？难道在别的地方开启？取得
> > $ _ENV ['finance_public'] = true //财务报告是否向群公开
> > $ _ENV ['enable_welcome_message'] = true；//机器人发送欢迎消息
> 
> 两个我都事开的

$System_Config['telegram_group_quiet']='false';		//Telegram 机器人在群组中不回应

这里呢？这边我一直是关闭状态，除了这几个之外没有bot的功能开关了吧

**Comment by KLDGodY** [comment]
> > > > ~~似乎配置能够开启了？~~反正我是这样：）
> > > 
> > > 
> > > 没有吧，只有这两个主动配置吧？难道在别的地方开启？取得
> > > $ _ENV ['finance_public'] = true //财务报告是否向群公开
> > > $ _ENV ['enable_welcome_message'] = true；//机器人发送欢迎消息
> > 
> > 
> > 两个我都事开的
> 
> $System_Config['telegram_group_quiet']='false'; //Telegram 机器人在群组中不回应
> 
> 这里呢？这边我一直是关闭状态，除了这几个之外没有bot的功能开关了吧

这个我事关，其他好像没有了，，，

**Comment by befantasy** [comment]
如果config里开了却没报，看是不是crontab里没加那个每日统计的任务。

**Comment by chauyuen** [comment]
一个是计划任务，另一个是后台，似乎有些配置移进了后台。
