### ISSUE TITLE
[Feature request]增加一个管理员报平安打卡功能

### ISSUE THREAD

**Issue by splendidwrx** [Anankke/SSPanel-Uim#946]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
就是一个在管理中心多一个按钮，管理员可以设置多长时间报平安打卡，如果发生不测，到了设定时间未打卡，系统在设定时间到时将数据库删除，并上传一份备份到国外网盘防止仅仅忘了打卡误删数据这种情况

**Solution**
If you have some solution about this issue, type it here.

**Addition**
管理员甚至可以用telegrambot来打卡

**Comment by du5** [comment]
有趣

**Comment by NimaQu** [comment]
@splendidwrx 草.jpg

**Comment by taizi-tp** [comment]
@splendidwrx 建再加个报平安需要输入密码，设置真假两个密码，真密码正常通过，假密码用于防止有人胁迫，可以做到无声避险，依然显示报平安成功但是还是会执行逃难进程

**Comment by DaylightMonet** [comment]
@splendidwrx 建议联动，同一个TG绑定的在任何一个魔改都能启动危机预案

**Comment by du5** [comment]
@splendidwrx 签到建议同时定位判断

**Comment by splendidwrx** [comment]
> @splendidwrx 签到建议同时定位判断



> @splendidwrx 签到建议同时定位判断

是不是还得维护一个全国派出所/看守所地址仓库

**Comment by narakuzi** [comment]
@splendidwrx 建议加一个全国机场主在线ip查询，方便大家知晓谁虚无了，，

**Comment by taizi-tp** [comment]
@narakuzi 建议创立联动机制，每人都是烽火，谁被抓了立刻警告其他机场主

**Comment by narakuzi** [comment]
@taizi-tp 然后上演烽火戏诸侯，，历史的车轮滚滚向前，，

**Comment by taizi-tp** [comment]
@narakuzi ，，，，，你说得对

**Comment by Anankke** [comment]
建议自建机器人 tg 打卡没打卡直接 dd 磁盘这个不建议面板做你觉得是不是呢嘻嘻
