### ISSUE TITLE
[Feature discussion] shopitem types

### ISSUE THREAD

**Issue by laurieryayoi** [Anankke/SSPanel-Uim#949]
**Feature**
- 增加几种商店商品类型
  1. 流量包
  2. 买同时在线设备数
  3.  买速率上限 （虽然我觉得这个好像没什么必要，姑且写一下）
解决目前存在的一些商店问题

**Solution**
太简单了，都不想码示例

**Addition**
关于升降套餐，我觉得升降是不可能升降的，一辈子都不可能升降的

**Comment by Passipur** [comment]
@laurieryayoi 太简单的话
pr welcome?
本代码白嫖怪在此先谢谢大佬了
ヽ(✿ﾟ▽ﾟ)ノ

**Comment by aipeach** [comment]
@laurieryayoi 升降套餐我觉得可以学运营商那样，运营商是下一个月生效，魔改可以套餐结束后生效下一套餐

**Comment by laurieryayoi** [comment]
> @laurieryayoi 升降套餐我觉得可以学运营商那样，运营商是下一个月生效，魔改可以套餐结束后生效下一套餐

这个不错，不过要数据库多加一个字段和加Job，存用户已经购买但是未生效的套餐，等上一个套餐到期后再执行shop的buy函数

**Comment by Anankke** [comment]
这是好的喵
