### ISSUE TITLE
[BUG]升级到最新DEV源码后报500错误无法打开

### ISSUE THREAD

**Issue by chauyuen** [Anankke/SSPanel-Uim#957]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
CentOS7+MYSQL5.6+PHP7.4+Nginx

**Commit**
Merge pull request #955 from v2rayv3/dev a62bc63

**Bug**
自动更新到最新源码后站点报500错误无法打开。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
恢复正常。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
演示站https://sspanel.host/目前也是报500，无法打开。

**Comment by laurieryayoi** [comment]
#918 
如果还是不行打开php的debug

**Comment by chauyuen** [comment]
导入gconfig.sql后恢复

**Comment by chauyuen** [comment]
#963

**Comment by mkgtnull** [comment]
导入gconfig.sql后仍然是报错500

**Comment by chauyuen** [comment]
> 导入gconfig.sql后仍然是报错500

php xcat update试试，不行的话，如果还是不行打开php的debug以及config里面的debug，截图来看看。
