### ISSUE TITLE
[BUG] TG机器人功能问题

### ISSUE THREAD

**Issue by 1orz** [Anankke/SSPanel-Uim#961]
Mysql 5.7 
PHP 7.3
commit a62bc6305d2a2bf4a0dafa2a8af4c809816e8982
最新dev分支 新版tg机器人功能问题

Bug复现：
   如图，正确的将tg绑定后，点击/menu菜单功能下的四个功能按钮，均被跳转到为注册用户访客模式。

![8mb37j.png](https://s1.ax1x.com/2020/03/12/8mb37j.png)

已经检查并导入所有需要的sql
旧版机器人正常(.咕咕咕)

**Comment by chauyuen** [comment]
刚刚试了下，似乎没什么问题

**Comment by 1orz** [comment]
只有签到功能是正常的，可正常执行签到动作并且获得流量= =很奇怪

**Comment by GeekQuerxy** [comment]
fix #986
