### ISSUE TITLE
[BUG] php xcat update 报错

### ISSUE THREAD

**Issue by xcxnig** [Anankke/SSPanel-Uim#964]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

Linux Debian-101-buster-64-minimal 4.19.0-6-amd64
PHP 7.3.15-4+0~20200224.55+debian10~1.gbpbea824

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

d25794be0ceacf47032411b9d608fc1b5d44c823

```
root@localhost /var/www/demo # git reflog
d25794be (HEAD -> dev, origin/dev, origin/HEAD) HEAD@{0}: clone: from https://github.com/Anankke/SSPanel-Uim

```

**Bug**
The bug information. 请描述你遇到的 Bug。

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
```
root@localhost  /var/www/demo # php xcat update
备份成功

开始检查新增的配置项...
以上是新增的配置项...
开始升级客户端...
客户端升级结束
开始升级 QQWry...
开始下载纯真 IP 数据库....纯真 IP 数据库下载成功！升级 QQWry结束

创建 appprofile 文件.
0PHP Fatal error:  Uncaught Error: Call to a member function getAttributes() on null in /var/www/demo/src/Command/Update.php:260
Stack trace:
#0 /var/www/demo/src/Command/Update.php(42): App\Command\Update::old_to_new('1')
#1 /var/www/demo/src/Command/XCat.php(95): App\Command\Update::update(Object(App\Command\XCat))
#2 /var/www/demo/xcat(18): App\Command\XCat->boot()
#3 {main}
  thrown in /var/www/demo/src/Command/Update.php on line 260
```
**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by GeekQu** [comment]
@xcxnig ......？遇到没有审计记录的情况了，我去修

**Comment by GeekQuerxy** [comment]
#967 已修复
