### ISSUE TITLE
[BUG] 商店不显示商品

### ISSUE THREAD

**Issue by Garfield** [Anankke/SSPanel-Uim#970]
> 请将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .
> 
> * [x]  我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
> * [x]  我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
> * [x]  我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
> 
> **Environment 环境**
> Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
> 
> Linux centos7
> PHP 7.2
> 
> **Commit**
> The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
> 
> [f55b718](https://github.com/Anankke/SSPanel-Uim/commit/f55b718c07c9542fa14c04dc469d1c9f4409f03d)
> 
> ```
> 
> **Bug**
> The bug information. 请描述你遇到的 Bug。
> 
> **Reproduce**
> Steps to reproduce the bug. 请逐步描述如何复现 Bug。
> 
![image](https://user-images.githubusercontent.com/48400702/76702891-629bd300-6708-11ea-864c-88c0a88c0683.png)
console
![image](https://user-images.githubusercontent.com/48400702/76702907-78a99380-6708-11ea-8d77-920869bbdac5.png)

> **Expected behavior**
> What you expected to happen. 请描述你预期的行为。
> 
> **Logs**
> If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
> 
> ```
> 
> **Addition**
> Additional context here. 如有可能，请提供更多相关资料。

**Comment by Garfield** [comment]
收到 刚刚清了就没有 现在有了 可能是缓存同步太慢了

**Comment by jameqq** [comment]
我遇到跟你一样的错误，是节点列表不显示了，请问怎么解决

**Comment by Garfield** [comment]
刷新缓存更新





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Carter"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 下午3:29
收件人: "Anankke/SSPanel-Uim"<SSPanel-Uim@noreply.github.com&gt;; 
抄送: "Antake"<2284128416@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [Anankke/SSPanel-Uim] [BUG] 商店不显示商品 (#970)





 
我遇到跟你一样的错误，是节点列表不显示了，请问怎么解决
