### ISSUE TITLE
编辑用户资料时出现错误 slim application error

### ISSUE THREAD

**Issue by kkbbzjh** [Anankke/SSPanel-Uim#979]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Centos7，mysql5.7，php7.3，nginx1.17.9

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

**Bug**
用户编辑出现错误，并无法编辑

**Reproduce**
在管理面板，找到任意用户，点：编辑

**Logs**

Slim Application Error

The application could not run because of the following error:

Details
Type: TypeError
Message: Return value of App\Models\User::last_detect_ban_time() must be of the type string, null returned
File: /www/wwwroot/xxxxxxx.com/src/Models/User.php
Line: 507

Trace
#0 /www/wwwroot/xxxxxxx.com/storage/framework/smarty/compile/be8d8e7768a830fd6728631b02bd18409f0835dc_0.file.edit.tpl.php(131): App\Models\User->last_detect_ban_time()
#1 /www/wwwroot/xxxxxxx.com/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5e715a0c55c090_84383820(Object(Smarty_Internal_Template))
#2 /www/wwwroot/xxxxxxx.com/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#3 /www/wwwroot/xxxxxxx.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#4 /www/wwwroot/xxxxxxx.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#5 /www/wwwroot/xxxxxxx.com/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#6 /www/wwwroot/xxxxxxx.com/src/Controllers/Admin/UserController.php(309): Smarty_Internal_TemplateBase->display('admin/user/edit...')
#7 [internal function]: App\Controllers\Admin\UserController->edit(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#8 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /www/wwwroot/xxxxxxx.com/src/Middleware/Admin.php(25): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 [internal function]: App\Middleware\Admin->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(App\Middleware\Admin), Array)
#13 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#14 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /www/wwwroot/xxxxxxx.com/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#20 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware), Array)
#21 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#22 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#24 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 /www/wwwroot/xxxxxxx.com/public/index.php(34): Slim\App->run()
#27 {main}

**Comment by Anankke** [comment]
@GeekQu

**Comment by GeekQu** [comment]
php xcat update

@kkbbzjh <https://wiki.sspanel.host/#/update>

**Comment by GeekQuerxy** [comment]
@kkbbzjh 说明您在 `php xcat update` 中发生了异常

### 您可查看
 
- **user** 表结构是否有 **last_detect_ban_time** 以及 **all_detect_number** 字段
- 并且是否存在 **[detect_ban_log](https://github.com/Anankke/SSPanel-Uim/blob/dev/sql/detect_ban_log.sql)**、**[gconfig](https://github.com/Anankke/SSPanel-Uim/blob/dev/sql/gconfig.sql)**、**[telegram_tasks](https://github.com/Anankke/SSPanel-Uim/blob/dev/sql/telegram_tasks.sql)**、**[user_subscribe_log](https://github.com/Anankke/SSPanel-Uim/blob/dev/sql/user_subscribe_log.sql)** 表
- 并且 **detect_log** 表结构中是否存在 **[status](https://github.com/Anankke/SSPanel-Uim/blob/dev/sql/glzjin_all.sql#L776)** 字段
- 是否进行过 #918 

不存在的请前往 sql 目录下手动导入对应

**Comment by ROCKBUND** [comment]
tg bot关掉试试

**Comment by kkbbzjh** [comment]
该问题已经解决了，一直是外挂数据库，没有留意数据库增添了很多内容，结构同步之后，问题已经解决了，谢谢2位大佬的帮忙~~
@GeekQu @Anankke
