### ISSUE TITLE
[BUG]Bot鉴权无效，任意用户可通过管理命令更改任意用户数据

### ISSUE THREAD

**Issue by xcxnig** [Anankke/SSPanel-Uim#980]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
d25794be0ceacf47032411b9d608fc1b5d44c823
**Bug**
The bug information. 请描述你遇到的 Bug。

1 `.$_ENV['userCenterClient']  = []` 如果出现某项未填写时，会出现Undefined 类型错误
![image.png](https://i.loli.net/2020/03/19/qEbikLUcV6p7WDY.png)

2. `$_ENV['use_new_telegram_bot'] =true;   ` 时，bot无法正确鉴权。

如果说：

**非管理员用户可以使用任意管理员命令修改任意成员的数据**
![image.png](https://i.loli.net/2020/03/19/K7O1NdpI2QP5j84.png)

**可以查看并操作非本人帐号的账户资料**
![image.png](https://i.loli.net/2020/03/15/U9WnYrtQxJNboZk.gif)

3. 已绑定用户重复绑定时提示绑定码过期而不是已绑定

4. 订阅记录 页面 点击数字会跳转回首页

5. 网站bot在加群时不验证是否该群为白名单群

**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

开启 new_bot 人人都是管理员

**Expected behavior**
What you expected to happen. 请描述你预期的行为。

**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by v2rayv3** [comment]
#981

**Comment by GeekQuerxy** [comment]
fix #986
