### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by basicfu** [Anankke/SSPanel-Uim#985]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
linux  umi是dev最新分支版本
**Commit**
cef0c3989ce46e799046f0b2e3b54b1db48d3203
**Bug**
通过邀请码注册时，如果资料填写正确可以完成注册且有邀请关系，当我在填写资料过程中出现联系方式重复的时候，系统后台会提示我，修改完联系方式二次发起注册成功，但是第二次注册时已经不携带邀请码的cookie了，所以如果出现资料填写错误继续注册的情况下，邀请码信息会丢失

**Comment by narakuzi** [comment]
@basicfu 理论上，联系方式重复了不就是恶意注册叻吗，，，

**Comment by basicfu** [comment]
这个是故意设定的功能吗？我只是在测试的时候填错重了联系方式，这种情况在实际中确实是很少发生，如果是已有的功能那我就知道了哈哈
