### ISSUE TITLE
tgbot 和邮箱 每隔一分钟就提示一次节点恢复上线

### ISSUE THREAD

**Issue by amfiyong** [Anankke/SSPanel-Uim#989]
tgbot 每隔一分钟就在群组里发送消息提示节点恢复上线。邮件也是一样，每隔一分钟管理员账户邮件 就收到 节点恢复上线的提醒。
 请教下各位大佬，这是什么原因造成的 。

**Comment by Colinwood11** [comment]
@amfiyong 加钱上好的机器，不然关闭检测或者删库跑路

**Comment by amfiyong** [comment]
我用的，4c8g的机器怎么会配置低

**Comment by guanmengkai** [comment]
把网站目录下sql文件夹里的clean_job.sql，导入数据库即可恢复正常

**Comment by amfiyong** [comment]
@guanmengkai 老哥，你说的方法，确实有效。请问下，机器人现在在群组里 推送了，“VPN统一流量结算和统一验证登录 ”的掉线信息 。而且，在网页 telegram配置里 有很多重复的配置。 该如何处理。
