### ISSUE TITLE
[Feature Request] 添加IPv6地址数据库

### ISSUE THREAD

**Issue by clatteringmarion** [Anankke/SSPanel-Uim#993]
- [x] I acknowledge if I don't follow the format below or I don't check these box, my issue could be closed without any notice.
- [x] I certify that I have read project Wiki and other issue may related to this one.

**Feature**
添加对IPv6地址的信息查询
当前数据库对IPv6均显示为 IANA保留地址， 现在IPv6已经开始使用了... 应该也可以支持查询IPv6信息了吧... （要不然异地登陆邮件“系统发现您的账号在 IANA 有异常登录"有点尴尬）

**Solution**
Maxmind GeoLite2 数据库已经支持IPv6查询： https://support.maxmind.com/ipv6-data-faq/
可以通过https://dev.maxmind.com/geoip/geoipupdate/#Direct_Downloads + 免费授权key获取GeoLite2数据库

另外https://github.com/Rhilip/ipv6wry.db 这个貌似也是国内的IPv6数据库获取程序？

**Addition**

**Comment by du5** [comment]
GEOIP 不是 Enterprise 库查询的信息很少，归属地大都没有中文吧！

**Comment by NimaQu** [comment]
https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr?ip=fe80::ed2d:f974:c728:c294 (不是

**Comment by du5** [comment]
> https://api.live.bilibili.com/ip_service/v1/ip_service/get_ip_addr?ip=fe80::ed2d:f974:c728:c294 (不是

白嫖 yes！

**Comment by M1Screw** [comment]
這個功能，可以直接使用内嵌的“IP 归属地查询（Powered by Sukka）”，支持IPv6
