### ISSUE TITLE
[BUG] php执行安装的时候会报错

### ISSUE THREAD

**Issue by NGXTDN** [Anankke/SSPanel-Uim#994]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [x ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
centos7.3 php7.2  mysql5.6  nginx1.15
**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
master
**Bug**
The bug information. 请描述你遇到的 Bug。
执行“php composer.phar install”进行依赖安装的时候，出现“charlottedunois/yasmin”缺失
**Reproduce**
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
使用宝塔6.9进行安装，环境（centos7.3 php7.2  mysql5.6  nginx1.15），进行php composer.phar install 安装依赖会复现bug
**Expected behavior**
What you expected to happen. 请描述你预期的行为。
进行sspanel搭建
**Logs**
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。
**php composer.phar install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package charlottedunois/yasmin could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.**

**Addition**
Additional context here. 如有可能，请提供更多相关资料。

**Comment by FirstLightMK** [comment]
遇到同样的问题。尝试手动下载charlottedunois/yasmin解决。

**Comment by NGXTDN** [comment]
> 遇到手动的问题。尝试手动下载charlottedunois / yasmin解决。

不是这个库被删了

**Comment by Fatasss** [comment]
自行删除composer.json里charlottedunois / yasmin可以解决

**Comment by NGXTDN** [comment]
> 自行删除composer.json里charlottedunois / yasmin可以解决

删除之后会出现什么错误？

**Comment by Fatasss** [comment]
> > 自行删除composer.json里charlottedunois / yasmin可以解决
> 
> 删除之后会出现什么错误？

不会出现错误的，删除后composer将不会加载这个库。这个库是为了支持discord，你可以不使用这个功能

**Comment by chauyuen** [comment]
DEV版本早就取消了这个库，不知道为什么没有Merge进Master。https://github.com/Anankke/SSPanel-Uim/commit/051ffc57f9f25f61e996cea0aab6f05e1e7b390c

**Comment by stardock** [comment]
感谢指导   [赞]

**Comment by Anankke** [comment]
请使用 dev 版本

**Comment by xsxx09** [comment]
> 自行删除composer.json里charlottedunois / yasmin可以解决

能询问一下怎么删除吗。。

**Comment by KLDGodY** [comment]
@xsxx09 vim 脑袋.txt  i 退格键 :wq

**Comment by SukkaW** [comment]
~~谁tm 给这个 issue 加上 `bug` label 的~~ 哪个脑子进水的人允许开 issue 的人给自己 issue 接 label 的？

**Comment by AidenOfficial** [comment]
@SukkaW 我也不知道，我也不敢问

**Comment by sigle0724** [comment]
@xsxx09 谷歌是个好东西

**Comment by Anankke** [comment]
> ~谁tm 给这个 issue 加上 `bug` label 的~ 哪个脑子进水的项目 owner 允许开 issue 的人给自己 issue 接 label 的？

我记得是你写的来着？（

**Comment by djx2726889** [comment]
> composer.json

确实可以解决
